### PR TITLE
Fix coordinator queryID tooltip and query string truncation

### LINKED ISSUE #17744: Coordinator UI Enhancement
- Tooltip won't disappear as expected after clicking the query link.
- Queries with too many lines don’t get truncated.

image

### PR DESCRIPTION
**Pull request by erick576**
### Change Query ID tooltip trigger to disappear after clicking
- Change trigger to hover only

### Truncate query strings that are considered not long enough to be truncated but go over the max amount of box lines
- Cover query strings that may not be long enough to be truncated but cover more lines then the box holds which should end off with .. to show truncation
- This change will only work on lines that aren't too long (Ex : a sixth line thats 3 lines long wont be covered)
- Please Note : To avoid adjusting the functionality that cuts queries at 300 characters, only cases under 300 characters have been considered for this case

Resolves #17744 

### Test plan - (Please fill in how you tested your changes)

1. Run The Presto Server
2. Visit the UI Page
3. Connect to the CLI
4. Create a table
 > CREATE TABLE ds_customer WITH (format='dwrf', partitioned_by=array['ds']) AS SELECT *, '2021-07-11' as ds FROM customer LIMIT 1000;
5. Insert into table
> INSERT INTO ds_customer SELECT *, '2021-07-12' as ds FROM customer LIMIT 1000;
6. Run each of the queries below and see if the output is truncated properly on the min and max screen size
Queries

- 7+ lines without having any line cover over a single line
> SELECT name,
name,
name, 
name, 
name, 
name,
name
FROM ds_customer;

Max Window Size
Screen Shot 2022-05-13 at 2 47 02 PM

Min Window Size
Screen Shot 2022-05-13 at 2 47 36 PM

- Multiple lines but with over 300 chars so it cuts off
> SELECT name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name,
name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name FROM ds_customer;

Max Window Size
Screen Shot 2022-05-13 at 2 48 41 PM

Min Window Size
Screen Shot 2022-05-13 at 2 48 17 PM

- A single line longer than 300 chars so it cuts off
> SELECT name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name FROM ds_customer;

Max Window Size
Screen Shot 2022-05-13 at 2 49 13 PM

Min Window Size
Screen Shot 2022-05-13 at 2 49 35 PM

- A single line under 300 character but over 95 followed by small lines that go over 7 but don’t go over 300 characters
> SELECT name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name,
name,
name,
name,
name,
name,
name
FROM ds_customer;

Max Window Size
Screen Shot 2022-05-13 at 2 50 20 PM

Min Window Size
Screen Shot 2022-05-13 at 2 50 01 PM

- The last line is what makes it go over 7 lines and it is the seventh line (Example of an exceptional case that still exist)
> SELECT name,
name,
name,
name,
name,
name,
name, name, name, name, name, name, name, name, name, name, name, name, name from ds_customer;

Max Window Size
Screen Shot 2022-05-13 at 3 48 49 PM

Min Window Size
Screen Shot 2022-05-13 at 3 49 13 PM

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

File: presto-main/src/main/resources/webapp/src/components/QueryList.jsx [hunk 1]
```diff
@@ -63,12 +63,34 @@ export class QueryListItem extends React.Component {
...
         let formattedQueryText = "";
+        let currentLine = 0;
 
         for (let i = 0; i < lines.length; i++) {
             const trimmedLine = lines[i].substring(minLeadingWhitespace).replace(/\s+$/g, '');
+            currentLine += Math.ceil(trimmedLine.length / 75);
 
             if (trimmedLine.length > 0) {
-                formattedQueryText += trimmedLine;
+                 formattedQueryText += trimmedLine;
```
Comment (zacw7) [inline presto-main/src/main/resources/webapp/src/components/QueryList.jsx:73]: nit: a blank space needs to be removed.

Comment (zacw7) [inline presto-main/src/main/resources/webapp/src/components/QueryList.jsx:73]: nit: a blank space needs to be removed.

**Review by zacw7 — CHANGES_REQUESTED** [review]
Thanks for making the change and writing up this very detailed test plan. I think there are too many magic numbers like 3, 7, 72, 75 and gonna make the code hard to maintain. Maybe let us keep it simple - cut off at the 7th line.

**Comment by erick576** [comment]
> Thanks for making the change and writing up this very detailed test plan. I think there are too many magic numbers like 3, 7, 72, 75 and gonna make the code hard to maintain. Maybe let us keep it simple - cut off at the 7th line.

That is fine as well, I can remove the line break code though the case where the 6th line lets say covers 3 lines, it wont be cut off to make sure it ends on 7 since theres no line break to cut off on (thus the calculations I made). All cases where the line are short though will still be covered

File: presto-main/src/main/resources/webapp/src/components/QueryList.jsx (hunk 1 above)
Comment (erick576) [reply presto-main/src/main/resources/webapp/src/components/QueryList.jsx:73]: done

**Comment by erick576** [comment]
> Thanks for making the change and writing up this very detailed test plan. I think there are too many magic numbers like 3, 7, 72, 75 and gonna make the code hard to maintain. Maybe let us keep it simple - cut off at the 7th line.

Changes have been added

File: presto-main/src/main/resources/webapp/src/components/QueryList.jsx [hunk 2]
```diff
@@ -63,13 +63,23 @@ export class QueryListItem extends React.Component {
...
+            currentLine += Math.ceil(trimmedLine.length / 75);
 
             if (trimmedLine.length > 0) {
                 formattedQueryText += trimmedLine;
 
+                if (formattedQueryText.length >= 300) {
+                    break;
+                }
+
+                if (currentLine >= 7) {
```
Comment (zacw7) [inline presto-main/src/main/resources/webapp/src/components/QueryList.jsx:79]: Same for 7, let's make it `maxLines`.

File: presto-main/src/main/resources/webapp/src/components/QueryList.jsx [hunk 3]
```diff
@@ -63,13 +63,23 @@ export class QueryListItem extends React.Component {
         }
 
         let formattedQueryText = "";
+        let currentLine = 0;
 
         for (let i = 0; i < lines.length; i++) {
             const trimmedLine = lines[i].substring(minLeadingWhitespace).replace(/\s+$/g, '');
+            currentLine += Math.ceil(trimmedLine.length / 75);
```
Comment (zacw7) [inline presto-main/src/main/resources/webapp/src/components/QueryList.jsx:70]: Is 75 the max width per line? If so, let's create a constant `const maxWidthPerLine = 75` and replace the hard-coded `75` with it.

**Comment by erick576** [comment]
@zacw7 If you want it to be even simpler I can just count line breaks though any line thats covers more than a single line wont be accounted for anymore. Let me know

File: presto-main/src/main/resources/webapp/src/components/QueryList.jsx [hunk 4]
```diff
@@ -63,13 +63,23 @@ export class QueryListItem extends React.Component {
         }
 
         let formattedQueryText = "";
+        let currentLine = 0;
```
Comment (zacw7) [inline presto-main/src/main/resources/webapp/src/components/QueryList.jsx:66]: Let's rename it into something like `currentLineCount`.

**Review by zacw7 — CHANGES_REQUESTED** [review]

File: presto-main/src/main/resources/webapp/src/components/QueryList.jsx (hunk 2 above)
Comment (erick576) [reply presto-main/src/main/resources/webapp/src/components/QueryList.jsx:79]: done

File: presto-main/src/main/resources/webapp/src/components/QueryList.jsx (hunk 3 above)
Comment (erick576) [reply presto-main/src/main/resources/webapp/src/components/QueryList.jsx:70]: done

File: presto-main/src/main/resources/webapp/src/components/QueryList.jsx (hunk 4 above)
Comment (erick576) [reply presto-main/src/main/resources/webapp/src/components/QueryList.jsx:66]: done

File: presto-main/src/main/resources/webapp/src/components/QueryList.jsx [hunk 5]
```diff
@@ -63,13 +63,25 @@ export class QueryListItem extends React.Component {
         }
 
         let formattedQueryText = "";
+        let currentLineCount = 0;
 
         for (let i = 0; i < lines.length; i++) {
             const trimmedLine = lines[i].substring(minLeadingWhitespace).replace(/\s+$/g, '');
+            const maxWidthPerLine = 75;
```
Comment (zacw7) [inline presto-main/src/main/resources/webapp/src/components/QueryList.jsx:70]: nit - This should be outside of the for-loop given that the value doesn't change.

File: presto-main/src/main/resources/webapp/src/components/QueryList.jsx [hunk 6]
```diff
@@ -63,13 +63,25 @@ export class QueryListItem extends React.Component {
         }
 
         let formattedQueryText = "";
+        let currentLineCount = 0;
```
Comment (zacw7) [inline presto-main/src/main/resources/webapp/src/components/QueryList.jsx:66]: `lineCount` might look slightly better? Wdyt?

**Review by zacw7 — CHANGES_REQUESTED** [review]

File: presto-main/src/main/resources/webapp/src/components/QueryList.jsx (hunk 6 above)
Comment (erick576) [reply presto-main/src/main/resources/webapp/src/components/QueryList.jsx:66]: yeah as long as it says "**count**" in it, it implies that its current so we could make it shorter

File: presto-main/src/main/resources/webapp/src/components/QueryList.jsx (hunk 5 above)
Comment (erick576) [reply presto-main/src/main/resources/webapp/src/components/QueryList.jsx:70]: same as maxLines which exists in the for loop?

Comment (erick576) [reply presto-main/src/main/resources/webapp/src/components/QueryList.jsx]: moved

**Review by zacw7 — APPROVED** [review]
LGTM. Please make sure the `index.js` is updated accordinly. Will leave it to @yuanzhanhku for the final review.

**Comment by erick576** [comment]
> LGTM. Please make sure the `index.js` is updated accordinly. Will leave it to @yuanzhanhku for the final review.

Can confirm the `index.js` is up to date upon rebuilding
> yarn --cwd presto-main/src/main/resources/webapp/src install

File: presto-main/src/main/resources/webapp/src/components/QueryList.jsx [hunk 7]
```diff
@@ -62,14 +62,26 @@ export class QueryListItem extends React.Component {
...
         let formattedQueryText = "";
 
         for (let i = 0; i < lines.length; i++) {
             const trimmedLine = lines[i].substring(minLeadingWhitespace).replace(/\s+$/g, '');
+            lineCount += Math.ceil(trimmedLine.length / maxWidthPerLine);
 
             if (trimmedLine.length > 0) {
                 formattedQueryText += trimmedLine;
 
+                if (formattedQueryText.length >= 300) {
```
Comment (yuanzhanhku) [inline presto-main/src/main/resources/webapp/src/components/QueryList.jsx:77]: This magic number is used twice(here and line 91). Let's define a const variable for this.

Comment (yuanzhanhku) [inline presto-main/src/main/resources/webapp/src/components/QueryList.jsx:77]: This needs to be > 300 instead of >= 300.
Otherwise, when formattedQueryText.length == 300, truncateString in line 91 will return formattedQueryText without the '...' which is not correct as there could be more line which are appended to formattedQueryText yet.

Comment (erick576) [reply presto-main/src/main/resources/webapp/src/components/QueryList.jsx]: done

Comment (erick576) [reply presto-main/src/main/resources/webapp/src/components/QueryList.jsx]: done

**Comment by erick576** [comment]
Have changed the trigger element to data-trigger since the former dosent work on chrome browsers

**Review by yuanzhanhku — APPROVED** [review]

**Review by highker — APPROVED** [review]
