### PR TITLE
Make testQueryHeartbeat deterministic

### LINKED ISSUE #23235: testQueryHeartbeat is flaky
Another test that looks fundamentally probabilistic and flaky. We really should stop writing and including these.

```
2024-07-17T00:52:18.1917691Z [ERROR] Tests run: 8391, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 1,346.493 s <<< FAILURE! - in TestSuite
2024-07-17T00:52:18.1920380Z [ERROR] com.facebook.presto.resourcemanager.TestResourceManagerClusterStatusSender.testQueryHeartbeat  Time elapsed: 1.008 s  <<< FAILURE!
2024-07-17T00:52:18.1923186Z java.lang.AssertionError: Expect number of heartbeats to fall within target range (10), +/- 50%.  Was: 4 expected [true] but found [false]
2024-07-17T00:52:18.1942673Z 	at org.testng.Assert.fail(Assert.java:110)
2024-07-17T00:52:18.1943656Z 	at org.testng.Assert.failNotEquals(Assert.java:1413)
2024-07-17T00:52:18.1944462Z 	at org.testng.Assert.assertTrue(Assert.java:56)
2024-07-17T00:52:18.2040828Z 	at 
```

### PR DESCRIPTION
**Pull request by tdcmeehan**
## Description
We only need to check that the heartbeats are being regularly sent.

## Motivation and Context
Fixes #23235

## Impact
Less flaky tests

## Test Plan
Green CI

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by hantangwangd — APPROVED** [review]
Thanks for the fix, lgtm!

File: presto-main/src/test/java/com/facebook/presto/resourcemanager/TestResourceManagerClusterStatusSender.java [hunk 1]
```diff
@@ -112,7 +112,7 @@ public void testNodeStatus()
                 format("Expect number of heartbeats to fall within target range (%s), +/- 50%%.  Was: %s", TARGET_HEARTBEATS, nodeHeartbeats));
```
Comment (aditi-pandit) [inline presto-main/src/test/java/com/facebook/presto/resourcemanager/TestResourceManagerClusterStatusSender.java:112]: @tdcmeehan : Do you feel this check should be changed as well to avoid the comparisons using TARGET_HEARTBEATS to make the code more robust ?

**Review by yingsu00 — APPROVED** [review]
I have similar question as @aditi-pandit . But for this testQueryHeartbeat test it seems good.
