### PR TITLE
Optimize ST_Envelope

### LINKED ISSUE #9814: ST_Envelope fails with NPE on geometry collections
```
presto:di> select ST_Envelope(ST_GeometryFromText('GEOMETRYCOLLECTION (POINT (5 1), LINESTRING (3 4, 4 4))'));
Query 20180124_195738_50768_xv2yh failed: null
java.lang.NullPointerException
        at com.facebook.presto.plugin.geospatial.GeoFunctions.getEnvelope(GeoFunctions.java:590)
        at com.facebook.presto.plugin.geospatial.GeoFunctions.stEnvelope(GeoFunctions.java:396)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:649)
        at com.facebook.presto.sql.FunctionInvoker.invoke(FunctionInvoker.java:88)
        at com.facebook.presto.sql.planner.ExpressionInterpreter$Visitor.visitFunctionCall(ExpressionInterpreter.java:971)
        at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:119)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.planner.ExpressionInterpreter.optimize(ExpressionInterpreter.java:283)
        at com.facebook.presto.sql.planner.iterative.rule.SimplifyExpressions.rewrite(SimplifyExpressions.java:55)
        at com.facebook.presto.sql.planner.iterative.rule.SimplifyExpressions.lambda$createRewrite$0(SimplifyExpressions.java:79)
        at com.facebook.presto.sql.planner.iterative.rule.ExpressionRewriteRuleSet$ProjectExpressionRewrite.lambda$apply$0(ExpressionRewriteRuleSet.java:129)
        at com.facebook.presto.sql.planner.plan.Assignments.lambda$rewrite$1(Assignments.java:107)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.facebook.presto.sql.planner.plan.Assignments.rewrite(Assignments.java:108)
        at com.facebook.presto.sql.planner.iterative.rule.ExpressionRewriteRuleSet$ProjectExpressionRewrite.apply(ExpressionRewriteRuleSet.java:129)
        at com.facebook.presto.sql.planner.iterative.rule.ExpressionRewriteRuleSet$ProjectExpressionRewrite.apply(ExpressionRewriteRuleSet.java:110)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:157)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:130)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:93)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:182)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:95)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:182)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:95)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:182)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:95)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:182)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:95)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:84)
        at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:133)
        at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:122)
        at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:368)
        at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:347)
        at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:279)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

CC: @nezihyigitbasi

### PR DESCRIPTION
**Pull request by mbasmanova**
Similar to #9798, ST_Envelope spent most of the time deserializing geometry from Slice. This PR updates ST_Envelope to limit deserialization to just the envelope.

Benchmark results before the change:

```
Benchmark                                      Mode  Cnt       Score       Error  Units
BenchmarkSTEnvelope.complexGeometry  avgt   20  173054.303 ± 24902.172  ns/op
BenchmarkSTEnvelope.simpleGeometry   avgt   20    1866.689 ±   388.987  ns/op
```

and after:

```
Benchmark                                      Mode  Cnt     Score    Error  Units
BenchmarkSTEnvelope.complexGeometry  avgt   20   977.294 ± 55.636  ns/op
BenchmarkSTEnvelope.simpleGeometry   avgt   20  1016.174 ± 57.284  ns/op
```

Also, fixes #9814

### CODE REVIEW

File: presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/GeoFunctions.java [hunk 1]
```diff
@@ -392,10 +393,11 @@ public static Slice stBoundary(@SqlType(GEOMETRY_TYPE_NAME) Slice input)
...
     {
-        OGCGeometry geometry = deserialize(input);
-        SpatialReference reference = geometry.getEsriSpatialReference();
-        Envelope envelope = getEnvelope(geometry);
-        return serialize(createFromEsriGeometry(envelope, reference));
+        Envelope envelope = deserializeEnvelope(input);
+        if (envelope == null) {
+            return EMPTY_POLYGON;
+        }
+        return serialize(createFromEsriGeometry(envelope, null));
```
Comment (nezihyigitbasi) [inline presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/GeoFunctions.java]: Previously, you were passing the spatial reference of `geometry` to `createFromEsriGeometry()`, but now you pass `null`. Why is that change needed?

File: presto-geospatial/src/test/java/com/facebook/presto/plugin/geospatial/BenchmarkSTEnvelope.java [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+import org.openjdk.jmh.runner.options.VerboseMode;
+
+import java.io.IOException;
+import java.util.concurrent.TimeUnit;
+
+import static com.facebook.presto.plugin.geospatial.GeometryBenchmarkUtils.loadLargePolygon;
+
+@State(Scope.Thread)
+@Fork(2)
+@Warmup(iterations = 10, time = 500, timeUnit = TimeUnit.MILLISECONDS)
```
Comment (nezihyigitbasi) [inline presto-geospatial/src/test/java/com/facebook/presto/plugin/geospatial/BenchmarkSTEnvelope.java]: static import `TimeUnit.MILLISECONDS`

File: presto-geospatial/src/test/java/com/facebook/presto/plugin/geospatial/BenchmarkSTEnvelope.java [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+@Measurement(iterations = 10, time = 500, timeUnit = TimeUnit.MILLISECONDS)
+@OutputTimeUnit(TimeUnit.NANOSECONDS)
```
Comment (nezihyigitbasi) [inline presto-geospatial/src/test/java/com/facebook/presto/plugin/geospatial/BenchmarkSTEnvelope.java]: static import `TimeUnit.NANOSECONDS`

File: presto-geospatial/src/test/java/com/facebook/presto/plugin/geospatial/GeometryBenchmarkUtils.java [hunk 4]
```diff
@@ -0,0 +1,35 @@
+/*
```
Comment (nezihyigitbasi) [inline presto-geospatial/src/test/java/com/facebook/presto/plugin/geospatial/GeometryBenchmarkUtils.java]: Please add this refactoring as a separate commit.

File: presto-geospatial/src/test/java/com/facebook/presto/plugin/geospatial/BenchmarkSTEnvelope.java [hunk 5]
```diff
@@ -0,0 +1,83 @@
...
+@BenchmarkMode(Mode.AverageTime)
+public class BenchmarkSTEnvelope
+{
+    @Benchmark
+    public Object stEnvelopeSimpleGeometry(BenchmarkData data)
```
Comment (nezihyigitbasi) [inline presto-geospatial/src/test/java/com/facebook/presto/plugin/geospatial/BenchmarkSTEnvelope.java]: The name of this class already contains `STEnvelope` so you can simplify the names of the benchmark methods by removing that (`simpleGeometry`/`complexGeometry`).

File: presto-geospatial/src/test/java/com/facebook/presto/plugin/geospatial/BenchmarkSTEnvelope.java [hunk 6]
```diff
@@ -0,0 +1,83 @@
...
+    {
+        return GeoFunctions.stEnvelope(data.simpleGeometry);
+    }
+
+    @Benchmark
+    public Object stEnvelopeComplexGeometry(BenchmarkData data)
```
Comment (nezihyigitbasi) [inline presto-geospatial/src/test/java/com/facebook/presto/plugin/geospatial/BenchmarkSTEnvelope.java]: You can return `Slice` from these two benchmark methods.

File: presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/GeoFunctions.java (hunk 1 above)
Comment (mbasmanova) [reply presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/GeoFunctions.java]: I no longer have the spatial reference of `geometry`, hence, cannot pass it. However, we don't use spatial reference anywhere and all geometries have `null` spatial reference because of `geometry.setSpatialReference(null);` in `geometryFromText`.

**Comment by mbasmanova** [comment]
@nezihyigitbasi Nezih, thank you for review. I updated the PR to incorporate your comments.

File: presto-geospatial/src/test/java/com/facebook/presto/plugin/geospatial/GeometryBenchmarkUtils.java [hunk 7]
```diff
@@ -0,0 +1,35 @@
...
+import java.nio.file.Files;
+import java.nio.file.Path;
+import java.nio.file.Paths;
+import java.util.List;
+
+public class GeometryBenchmarkUtils
+{
+    private GeometryBenchmarkUtils() {}
+
+    public static String loadLargePolygon()
```
Comment (nezihyigitbasi) [inline presto-geospatial/src/test/java/com/facebook/presto/plugin/geospatial/GeometryBenchmarkUtils.java]: nit: We can update the signature of the method as `loadPolygon(String fileName)` instead of tying it to a certain file.

**Comment by nezihyigitbasi** [comment]
The failing test seems unrelated, and it was previously reported as flaky.

**Comment by mbasmanova** [comment]
@nezihyigitbasi Thank you, Nezih. I addressed the comments and updated the PR. For some reason I don't see the Travis job kicking in. Do you happen to know why? I'd like to wait for the test results before merging.

**Comment by nezihyigitbasi** [comment]
There is a release going on right now, please talk to @raghavsethi before merging if this needs to be merged.
