### PR TITLE
Align output to buffer size in rcfile writer

### LINKED ISSUE #8993: Consider lowering MALLOC_ARENA_MAX to prevent native memory OOM
## Yes, we leak native memory
When compressing/decompressing gziped tables with _rcfile writers_, we use java native zlib inflaters and deflaters which allocate system native memory. There is an ongoing effort (#8531, #8879, #8455, #8529) to ensure the gzip input and output streams are properly closed to prevent native memory leak. However, even with all these fixes, we are **still leaking memory**. The following figure shows the native memory usage with 4 current queries with shape `insert into A select * from B`. The cluster OOMed several times.
screen shot 2017-09-17 at 11 20 04 am

## But there is no leaking object!
To understand what objects are not freed, we use [jemalloc](http://www.evanjones.ca/java-native-leak-bug.html). However, the jemalloc profiling result shows **0 memory leak**. What's interesting is that the machines with jemalloc turned on didn't show a sign of memory leak. The following figure shows a comparison of a node with jemalloc and a node with the default allocator (glibc) in the same cluster with the same queries ran as above.
screen shot 2017-09-17 at 11 20 31 am

## Why memory allocators make a difference?
glibc is the default native memory allocator of Java. The objects allocated by glibc may **NOT** be returned to the OS once it's freed for performance improvement. The downside of this is memory fragmentation. **The fragmentation can grow unboundedly and finally triggers a OOM**. This [blog](https://www.ibm.com/developerworks/community/blogs/kevgrig/entry/linux_native_memory_fragmentation_and_process_size_growth?lang=en) describes the details. On the other side, jemalloc is designed to [minimize memory fragmentation](http://jemalloc.net/), which avoids this problem from the beginning.

## Tuning glibc
[MALLOC_ARENA_MAX](https://devcenter.heroku.com/articles/tuning-glibc-memory-behavior) is an environment variable to control how many memory pools can be created for glibc. By default, it is 8 X #CPU cores. With MALLOC_ARENA_MAX set to 2, the OOM issue has completely gone. The following figure demonstrates the native memory usage with different MALLOC_ARENA_MAX values vs jemalloc. Notice that the drop is not a OOM; I just killed the query. When MALLOC_ARENA_MAX is 2 or 4, the memory save is even better than jemalloc. But of course, this is a trade of between memory and performance.
screen shot 2017-09-17 at 12 41 55 am

## What we can do to prevent this?
- Use a memory pool like what Hadoop does
- Switch to jemalloc
- Tune down MALLOC_ARENA_MAX

The first point may not work well given the memory pool can hold onto a codec for a long time without releasing it. This can lead to memory waste. That is also the reason we  switch to JDK gzip library from the Hadoop one (#8481). Switching to jemalloc could be an option but may bring some uncertainties to the existing system. So maybe just to tune down MALLOC_ARENA_MAX?

## Pick a number for MALLOC_ARENA_MAX
The goal is to find out what value for MALLOC_ARENA_MAX is proper. Of course, this can variable from different types of machines/clusters. The test environment is a cluster with 95 nodes with each node has 200GB of heap memory and 50GB of native memory.

**_1. To what extend we may OOM_**
Setting: a script to repetitively run 4 concurrent queries reading the same table with 256 billion rows and inserting into another 4 tables. This benchmark runs for hours to determine if there is (a trend or fact) of OOM.
```
MALLOC_ARENA_MAX=4:	not OOM
MALLOC_ARENA_MAX=8:	not OOM
MALLOC_ARENA_MAX=16:	OOM
```
Somehow, this benchmark may not be representative since it really depends on what queries we are running and how we assign heap/non-heap memory.

_**2.  CPU performance**_
Setting: a single query reads a table with 111 billion rows/26 columns and writes into another table.  The task concurrency and number of writers are all set to 64 to simulate the production environment and give pressure on memory. 
```
Original Hadoop writer:				43.60 CPU days
default MALLOC_ARENA_MAX with rcfile writer:	38.41 CPU days
MALLOC_ARENA_MAX=8 with rcfile writer:		38.57 CPU days
MALLOC_ARENA_MAX=4 with rcfile writer:		38.61 CPU days
MALLOC_ARENA_MAX=2 with rcfile writer:		38.69 CPU days
```
The rcfile writer is designed to run faster than the Hadoop one. Among different values of MALLOC_ARENA_MAX, there is subtle difference. I bet most of the CPU is used in compressing/decompressing/writing/reading data instead of allocating/deallocating memory.

## Conclusion
When memory is leaking, it may not be a problem of our code. It could just be an improper tuning.

### PR DESCRIPTION
**Pull request by highker**
Flushing data in arbitrary sizes can be a problem for memory
fragmentation. This is generally fine unless the output stream can
allocate native memory (e.g., gzip streams). Native memory allocator may
not be able to compact fragmentation, which can cause native memory OOM.

Resolves #8993

### CODE REVIEW

File: presto-rcfile/src/main/java/com/facebook/presto/rcfile/BufferedOutputStreamSliceOutput.java [hunk 1]
```diff
@@ -195,17 +205,29 @@ public void writeBytes(byte[] source)
...
+                // fill up the current buffer
+                int flushLength = getFreeBufferLength();
+                slice.setBytes(bufferPosition, source, sourceIndex, flushLength);
+                bufferPosition = slice.length();
+                flushBufferToOutputStream();
+                sourceIndex += flushLength;
+                length -= flushLength;
+            }
+
+            // line up the chuck to buffer size and flush directly to OutputStream
```
Comment (electrum) [inline presto-rcfile/src/main/java/com/facebook/presto/rcfile/BufferedOutputStreamSliceOutput.java]: Typo

File: presto-rcfile/src/main/java/com/facebook/presto/rcfile/BufferedOutputStreamSliceOutput.java [hunk 2]
```diff
@@ -173,17 +173,31 @@ public void writeBytes(Slice source)
...
+                slice.setBytes(bufferPosition, source, sourceIndex, flushLength);
+                bufferPosition = slice.length();
+                flushBufferToOutputStream();
+                sourceIndex += flushLength;
+                length -= flushLength;
+            }
+
+            // line up the chunk to chunk size and flush directly to OutputStream
+            int flushLength = length - length % CHUNK_SIZE;
+            for (int i = 0; i < flushLength / CHUNK_SIZE; i++) {
```
Comment (dain) [inline presto-rcfile/src/main/java/com/facebook/presto/rcfile/BufferedOutputStreamSliceOutput.java]: I think it would be simpler to do:
```java
while (length <= CHUNK_SIZE) {
    writeToOutputStream(source, sourceIndex, CHUNK_SIZE);
    sourceIndex += CHUNK_SIZE;
    length -= CHUNK_SIZE;
}
```
then after the loop you don't need to touch length of bufferOffset.

File: presto-rcfile/src/main/java/com/facebook/presto/rcfile/BufferedOutputStreamSliceOutput.java [hunk 3]
```diff
@@ -195,17 +209,31 @@ public void writeBytes(byte[] source)
...
+                int flushLength = getFreeBufferLength();
+                slice.setBytes(bufferPosition, source, sourceIndex, flushLength);
+                bufferPosition = slice.length();
+                flushBufferToOutputStream();
+                sourceIndex += flushLength;
+                length -= flushLength;
+            }
+
+            // line up the chunk to chunk size and flush directly to OutputStream
+            int flushLength = length - length % CHUNK_SIZE;
```
Comment (dain) [inline presto-rcfile/src/main/java/com/facebook/presto/rcfile/BufferedOutputStreamSliceOutput.java]: same here

File: presto-rcfile/src/test/java/com/facebook/presto/rcfile/TestBufferedOutputStreamSliceOutput.java [hunk 4]
```diff
@@ -0,0 +1,64 @@
...
+            inputArray[i] = (byte) (i % 128);
+        }
+
+        // pick some offsets to make the inputs into different chunks
+        int[] offsets = {0, 100, 545, 1024, 2049, 2050, 2051, 2151, 10480, 20042, 20100, 40001, 65536};
+
+        // test some different buffer sizes
+        for (int bufferSize : new int[] {4096, 4345, 65535, 65536, 65537, 100000}) {
+            // check byte array version
+            ByteArrayOutputStream byteOutputStream = new ByteArrayOutputStream(length);
```
Comment (dain) [inline presto-rcfile/src/test/java/com/facebook/presto/rcfile/TestBufferedOutputStreamSliceOutput.java]: Make a subclass that captures the flush sizes and then validate you don't get flushes > 4k

File: presto-rcfile/src/main/java/com/facebook/presto/rcfile/BufferedOutputStreamSliceOutput.java [hunk 5]
```diff
@@ -173,17 +172,30 @@ public void writeBytes(Slice source)
...
+            // line up the chunk to chunk size and flush directly to OutputStream
+            while (length >= CHUNK_SIZE) {
+                writeToOutputStream(source, sourceIndex, CHUNK_SIZE);
+                sourceIndex += CHUNK_SIZE;
+                length -= CHUNK_SIZE;
+                bufferOffset += CHUNK_SIZE;
+            }
         }
+
+        // buffer the remaining data
```
Comment (dain) [inline presto-rcfile/src/main/java/com/facebook/presto/rcfile/BufferedOutputStreamSliceOutput.java]: wrapper this with `if (length != 0)`

File: presto-rcfile/src/main/java/com/facebook/presto/rcfile/BufferedOutputStreamSliceOutput.java [hunk 6]
```diff
@@ -195,17 +207,30 @@ public void writeBytes(byte[] source)
...
```
Comment (dain) [inline presto-rcfile/src/main/java/com/facebook/presto/rcfile/BufferedOutputStreamSliceOutput.java]: same
