### PR TITLE
Fix computation of QueuedQueries JMX metrics

### LINKED ISSUE #19929: Discrepancy between Actual Running Query/Queued Query Count and JMX Metrics
Queued Query and Running Query count on Web UI and JMX metrics are contradicting each other. A few examples of the same snapshot of the cluster from both Web UI and JConsole can be seen below:

Screenshot 2023-06-20 at 7 18 42 PM

JMX Metric: `com.facebook.presto.execution<name=QueryManager><>QueuedQueries`

Screenshot 2023-06-20 at 7 18 53 PM

Screenshot 2023-06-20 at 7 19 28 PM

JMX Metric: `com.facebook.presto.execution<name=QueryManager><>QueuedQueries`

Screenshot 2023-06-20 at 7 19 21 PM

Based on the observations, it looks like the JMX metric computation is not accurate.

### PR DESCRIPTION
**Pull request by imjalpreet**
Fixes #19929

Test plan 

Validated that JMX metrics and Presto Console have the same values for Queued Query post this change.

The motivation behind the change: Due to the discrepancy between the count on UI and JMX metric, this PR tries to modify the way the JMX metric is being computed to make it consistent with the value displayed on Presto UI.  

```
== RELEASE NOTES ==

General Changes
* Fix Queued Query Count JMX Metrics (:issue:`19929`). Expose the QueryManagerStats metrics under the ``com.facebook.presto.dispatcher:name=DispatchManager`` namespace.

```

### CODE REVIEW

**Review by tdcmeehan — CHANGES_REQUESTED** [review]
1. I do not think we should remove the metrics from QueryManagerStats, as these are almost certainly being relied upon by many deployments of Presto.
2. If what we're trying to do is separate out queries which are submitted, but not yet queued in a resource group, let's do that by making the appropriate code changes in `QueryManagerStats` and usages.  Let's move the counter update in that class to happen close to when it's queued inside the resource group, for example.

**Review by yingsu00 — COMMENTED** [review]
As far as I understood, I think the problem was that the stats was not updated at right location:

- DispatchManager.createQueryInternal() creates a LocalDispatchQuery for each submitted query, and keep them in its member queryTracker. 

- Each LocalDispatchQuery has a QueryStateMachine to track the query states (QUEUED, WAITING_FOR_RESOURCES, etc.). The QUEUED state was set when the DispatchManager is trying to queue a query.
- The DispatchManager has a QueryManagerStats object `stats `, and its `queuedQueries` was incremented after the dispatchQuery is added to DispatchManager's queryTracker.

- The coordinator UI gets the #queued queries by enumerating all queries in the **DispatchManager** and check the query state machine to see if it's queued: [ClusterStatsResource.getClusterStats](https://github.com/prestodb/presto/blob/b0cde2e4a2ab9fe2c3576dd50acc330938cff6e3/presto-main/src/main/java/com/facebook/presto/server/ClusterStatsResource.java#LL128C45-L128C45) ,

- SqlQueryManager has a QueryManagerStats object `stats`, but this is another stats object than the one in DispatchManager. SqlQueryManager.stats.queuedQueries got incremented in QueryManager.createQuery(). This is AFTER the min worker requirement is met, and when the query starts execution.

So it seems the QueryManagerStats.queuedQueries was not updated correctly. It should be incremented when the stateMachine for the localDispatchQuery enters the QUEUED state. See the stacks below:
```
			DispatchManager.createQueryInternal(queryId, resourceGroupManager)
				...				
				dispatchQuery = dispatchQueryFactory.createDispatchQuery(…(dq) -> resourceGroupManager.submit(dq, selectionContext, queryExecutor)).  
						
				boolean queryAdded = queryCreated(dispatchQuery);
					queryAdded = queryTracker.addQuery(dispatchQuery);
						queries.putIfAbsent(dispatchQuery.getQueryId(), dispatchQuery)
					If queryAdded
						stats.trackQueryStats(dispatchQuery);    // This is DispatchManager.stats
							submittedQueries.update(1);
							queuedQueries.incrementAndGet();
				clusterStatusSender.registerQuery(dispatchQuery);
				dispatchQuery.startWaitingForPrerequisites();
				prerequisitesFuture = queryPrerequisites.waitForPrerequisites
				LocalDispatchQuery.queueQuery
					stateMachine.transitionToQueued().  // transitioned to QUEUED state. The stats should be updated here
					queryQueuer.accept(this);
						resourceGroupManager.submit(dq, selectionContext, queryExecutor). 
							groups.get(selectionContext.getResourceGroupId()).run(queryExecution);
								InternalResourceGroup.run(ManagedQueryExecution query)
									canQueue &= group.canQueueMore();
									canRun &= group.canRunMore();
									if (canRun && queuedQueries.isEmpty()) {
										startInBackground(query);
											runningQueries.add(query);
											executor.execute(query::startWaitingForResources);  
												query::startWaitingForResources
													if (stateMachine.transitionToWaitingForResources()) {
													            waitForMinimumWorkers();
														// when worker requirement is met, wait for query execution to finish construction and then start the execution
														boolean isDispatching = stateMachine.transitionToDispatching();
														queryExecution -> startExecution(queryExecution, isDispatching)
															LocalDispatchQuery.startExecution(QueryExecution queryExecution, boolean isDispatching)
																querySubmitter.accept(queryExecution);
																	QueryManager::createQuery. 
																		queryTracker.addQuery(queryExecution)
																		stats.trackQueryStats(queryExecution);    // This is SqlQueryManager.stats
																			submittedQueries.update(1);
																			queuedQueries.incrementAndGet();   // queuedQueries incremented here, but the query is not in QUEUED state actually
																		queryExecution::start

```
I think we should not remove the queuedQueries and runningQueries from QueryManagerStats, but instead, just update it at the right location. I didn't check the decrement callsites, but similarly, it should be updated at the same location that the stateMachine shifted from QUEUED to other states.

File: presto-main/src/main/java/com/facebook/presto/execution/QueryManagerStats.java [hunk 1]
```diff
@@ -145,6 +145,8 @@ private class StatisticsListener
         private boolean stopped;
         @GuardedBy("this")
         private boolean started;
+        @GuardedBy("this")
+        private boolean queued = true;
```
Comment (imjalpreet) [inline presto-main/src/main/java/com/facebook/presto/execution/QueryManagerStats.java:149]: The default value is set to true since this listener starts tracking state changes only after query is queued.

File: presto-main/src/main/java/com/facebook/presto/server/CoordinatorModule.java [hunk 2]
```diff
@@ -189,6 +189,7 @@ protected void setup(Binder binder)
 
         // dispatcher
         binder.bind(DispatchManager.class).in(Scopes.SINGLETON);
+        newExporter(binder).export(DispatchManager.class).withGeneratedName();
```
Comment (imjalpreet) [inline presto-main/src/main/java/com/facebook/presto/server/CoordinatorModule.java:192]: For now, I have exposed the DispatchManager QueryManagerStats in a separate namespace. But the stats object exposed via this class has more accurate stats(compared to SqlQueryManager) for all metrics including Queued Query and Running Query count. 

If we decide to expose only one of them, I would recommend we should expose the DispatchManager stats object. To make the change backwards compatible we can expose it under the same namespace as before so it remains transparent to the users.

**Review by imjalpreet — COMMENTED** [review]
@yingsu00 @tdcmeehan thanks for your review, I have made the changes based on your suggestions. 

Can you please have a look and let me know in case of any questions?

File: presto-main/src/main/java/com/facebook/presto/execution/QueryManagerStats.java [hunk 3]
```diff
@@ -28,6 +28,7 @@
 import java.util.concurrent.atomic.AtomicInteger;
 import java.util.function.Supplier;
 
+import static com.facebook.presto.execution.QueryState.QUEUED;
```
Comment (yingsu00) [inline presto-main/src/main/java/com/facebook/presto/execution/QueryManagerStats.java:31]: I actually think `trackQueryStats()` methods in QueryManagerStats should NOT do  `queuedQueries.incrementAndGet();`. Having a query submitted doesn't mean it's already queued.  @tdcmeehan Do you know why they were done this way?

File: presto-main/src/main/java/com/facebook/presto/execution/QueryManagerStats.java [hunk 4]
```diff
@@ -75,7 +76,6 @@ private void queryStarted()
     {
         startedQueries.update(1);
         runningQueries.incrementAndGet();
-        queryDequeued();
     }
 
     private void queryStopped()
```
Comment (yingsu00) [inline presto-main/src/main/java/com/facebook/presto/execution/QueryManagerStats.java:81]: I think we should introduce `queryQueued()` method, similar to these methods.

File: presto-main/src/main/java/com/facebook/presto/execution/QueryManagerStats.java [hunk 5]
```diff
@@ -169,15 +171,25 @@ public void stateChanged(QueryState newValue)
...
                     }
-                    else {
+                    else if (queued) {
                         queryDequeued();
+                        queued = false;
                     }
                     finalQueryInfoSupplier.get()
                             .ifPresent(QueryManagerStats.this::queryFinished);
                 }
+                else if (newValue.ordinal() > QUEUED.ordinal() && newValue.ordinal() < RUNNING.ordinal()) {
```
Comment (yingsu00) [inline presto-main/src/main/java/com/facebook/presto/execution/QueryManagerStats.java:181]: Correct me if I'm wrong, but where is the logic of updating `queuedQueries` when the new state is QUEUED? In such case the newValue.ordinal() is equal to QUEUED.ordinal(), also the newValue.isDone() is false. Which if branch handles this situation?

Comment (yingsu00) [reply presto-main/src/main/java/com/facebook/presto/execution/QueryManagerStats.java:181]: Should we introduce `queryQueued()` method that increment queuedQueries count, and add a branch  in this method if the new state is QUEUED?

**Review by yingsu00 — COMMENTED** [review]
@imjalpreet Will you be able to add tests to make sure the dispatchQueries' stateMachines match with the `QueryManagerStats stats` in both SqlQueryManager and DispatchManager?

File: presto-main/src/main/java/com/facebook/presto/execution/QueryManagerStats.java (hunk 5 above)
Comment (imjalpreet) [reply presto-main/src/main/java/com/facebook/presto/execution/QueryManagerStats.java:181]: > where is the logic of updating queuedQueries when the new state is QUEUED?

In the current implementation, this was not required since every call to trackQueryStats was incrementing queuedQueries. 

> Should we introduce queryQueued() method that increment queuedQueries count, and add a branch in this method if the new state is QUEUED?

But yes, I think this looks better, I just saw that query is queued after trackQueryStats(dispatchQuery). So we should not be incrementing the queuedQueries in trackQueryStats.

File: presto-main/src/main/java/com/facebook/presto/execution/QueryManagerStats.java (hunk 3 above)
Comment (imjalpreet) [reply presto-main/src/main/java/com/facebook/presto/execution/QueryManagerStats.java:31]: > I actually think trackQueryStats() methods in QueryManagerStats should NOT do queuedQueries.incrementAndGet();. Having a query submitted doesn't mean it's already queued. 

I agree, that doesn't look right for both the methods. In the case of DispatchQuery, it is queued after the call to trackQueryStats, and in the case of SqlQueryManager, the query is not even in the queued state when trackQueryStats is called. It is called after waiting for resources finishes and query execution is about to start.

**Comment by yingsu00** [comment]
> In the current implementation, this was not required since every call to trackQueryStats was incrementing queuedQueries.

As far as I can see, trackQueryStats() was only setting up the initial state of the stats. See where it is called. It's only called after `queryCreated()` was successful. Also it should NOT be increasing the queuedQueries as I mentioned above.

**Comment by imjalpreet** [comment]
> As far as I can see, trackQueryStats() was only setting up the initial state of the stats. See where it is called. It's only called after queryCreated() was successful. Also it should NOT be increasing the queuedQueries as I mentioned above.

Yes, I agree. But I was talking about the current implementation in master. Since in that implementation it was already incrementing queuedQueries in trackQueryStats, I am assuming that was the reason there were no checks for Queued State after that. 

I am currently working on making the corrections including not incrementing queuedQueries in trackQueryStats as I mentioned earlier.

**Comment by imjalpreet** [comment]
Key observations and changes:

1. We observed that queued query count was being incremented in the `com.facebook.presto.execution.QueryManagerStats.trackQueryStats` method. Queued Query Count should not be incremented at this stage since the Query is not in Queued State when this method is called. In the case of `DispatchQuery`, the query is yet to be queued and in the case of `QueryExecution` query has already passed Queued state. This PR stops incrementing the queued query count in this method call.
2. This PR introduces tracking of Queued QueryState in `com.facebook.presto.execution.QueryManagerStats.StatisticsListener` to increment Queued Query Count based on state change. This ensures that the `QueryManagerStats` Query Count metric is consistent with `QueryStateMachine` changes. 
3. This PR also exposes the `QueryManagerStats` under the namespace of `com.facebook.presto.dispatcher:name=DispatchManager`. This change has been done because only `DispatchManager`query stats account for all the QueryState changes. The stats object part of the `SqlQueryManager` class cannot account for all `QueryState` changes including Queued State since these stats only start tracking once the Query is about to begin execution (`com.facebook.presto.dispatcher.LocalDispatchQuery#startExecution` --> `com.facebook.presto.execution.SqlQueryManager#createQuery`)

@yingsu00 @tdcmeehan I have updated the PR taking into account all concerns and recommendations. Can you please have a look and let me know in case of any questions.

File: presto-main/src/main/java/com/facebook/presto/execution/QueryManagerStats.java (hunk 4 above)
Comment (imjalpreet) [reply presto-main/src/main/java/com/facebook/presto/execution/QueryManagerStats.java:79]: Done.

File: presto-tests/src/test/java/com/facebook/presto/tests/TestQueryManager.java [hunk 6]
```diff
@@ -226,4 +227,37 @@ public void testQueryOutputSizeExceeded()
...
+    public void testQueuedQueryCount()
+            throws Exception
+    {
+        DispatchManager dispatchManager = queryRunner.getCoordinator().getDispatchManager();
+        // Create 5 queries to guarantee queueing
+        createQueries(dispatchManager, 5);
+
+        assertNotEquals(dispatchManager.getStats().getQueuedQueries(), 0L);
+
+        assertEquals(
```
Comment (yingsu00) [inline presto-tests/src/test/java/com/facebook/presto/tests/TestQueryManager.java:241]: This test only tests the stats at one snapshot. Can we enhance it to multiple checks before all queries finish such that all the states match? Something like
```
while (stats.queuedQueries + stats.runningQueries != 0) {
    assert queuedQueries match;
    assert runningQueries match;
    sleep(x);
}
```

**Review by yingsu00 — COMMENTED** [review]
Mostly look good, some nits in addition to the test comment:

Could you please make the commit titles in 50 chars, and commit message lines within 72 chars?

**Comment by imjalpreet** [comment]
@yingsu00 I have updated the PR, please have a look and let me know in case anything is missed.

File: presto-tests/src/test/java/com/facebook/presto/tests/TestQueryManager.java [hunk 7]
```diff
@@ -226,4 +227,45 @@ public void testQueryOutputSizeExceeded()
...
+    public void testQueryCountMetrics()
+            throws Exception
+    {
+        DispatchManager dispatchManager = queryRunner.getCoordinator().getDispatchManager();
+        // Create a total of 4 queries to test concurrency limit and ensure Queued Queries
+        createQueries(dispatchManager, 3);
+
+        // This is to ensure the 4th Query we want to monitor is Queued
+        while (dispatchManager.getStats().getRunningQueries() != 3) {
+            Thread.sleep(25);
```
Comment (yingsu00) [inline presto-tests/src/test/java/com/facebook/presto/tests/TestQueryManager.java:241]: How was 25 chosen? Is it possible the query runs faster than 25msec and this loop never ends?

File: presto-tests/src/test/java/com/facebook/presto/tests/TestQueryManager.java [hunk 8]
```diff
@@ -226,4 +227,45 @@ public void testQueryOutputSizeExceeded()
...
+        }
+
+        QueryId queryId = dispatchManager.createQueryId();
```
Comment (yingsu00) [inline presto-tests/src/test/java/com/facebook/presto/tests/TestQueryManager.java:244]: Thanks for updating the test. But this only tests 1 queued query. Do you think creating a few more of them would make the tests more meaningful? Something like
```
create r(=3) queries;
wait until all r queries are running;

create q queries;
assert q queries are queued;
while (dispatchManager.getStats().getQueuedQueries() + dispatchManager.getStats().getRunningQueries() > 0
                && stopwatch.elapsed().toMillis() < 60000) {
    numQueued = count queuedQueries from dispatchManager;
    assert numQueued == stats.queuedQueries;
    assert numQueued <= numQueued of last round 
 
    numRunning = count runningQueries from dispatchManager;
    assert numRunning == stats.runningQueries;
    assert numRunning <= numRunning from last round
    assert numRunning <= r;

    sleep(x); // x be a small number
}
```

File: presto-tests/src/test/java/com/facebook/presto/tests/TestQueryManager.java [hunk 9]
```diff
@@ -226,4 +227,45 @@ public void testQueryOutputSizeExceeded()
...
         }
     }
+
+    @Test
+    public void testQueryCountMetrics()
+            throws Exception
+    {
+        DispatchManager dispatchManager = queryRunner.getCoordinator().getDispatchManager();
+        // Create a total of 4 queries to test concurrency limit and ensure Queued Queries
+        createQueries(dispatchManager, 3);
```
[the remark this answers is not in the document]
Comment (imjalpreet) [reply presto-tests/src/test/java/com/facebook/presto/tests/TestQueryManager.java]: I have updated the comment and the reason queueing is guaranteed with > 3 queries is because max concurrent queries are set to 3 via resource groups.

File: presto-tests/src/test/java/com/facebook/presto/tests/TestQueryManager.java (hunk 8 above)
Comment (imjalpreet) [reply presto-tests/src/test/java/com/facebook/presto/tests/TestQueryManager.java]: As discussed offline, I have updated the tests accordingly.

**Comment by imjalpreet** [comment]
@yingsu00 I have updated the test as we discussed offline. 

The reason we are only asserting the exact count of queued queries and running queries outside the loop is that flakiness was observed while asserting them over some time in the loop. Flakiness was because queries were changing states while we were trying to assert the counts. 

Now within the loop, we are trying to assert that the count of queued queries is decreasing over time and running queries are always <= 3

File: presto-main/src/main/java/com/facebook/presto/execution/QueryManagerStats.java [hunk 10]
```diff
@@ -167,15 +174,31 @@ public void stateChanged(QueryState newValue)
...
                         queryStopped();
                     }
-                    else {
+                    else if (queued) {
                         queryDequeued();
                     }
                     finalQueryInfoSupplier.get()
                             .ifPresent(QueryManagerStats.this::queryFinished);
                 }
+                else if (newValue.ordinal() == QUEUED.ordinal()) {
```
Comment (tdcmeehan) [inline presto-main/src/main/java/com/facebook/presto/execution/QueryManagerStats.java:183]: I find the following easier to read:

```java
        @Override
        public void stateChanged(QueryState newValue)
        {
            synchronized (this) {
                if (stopped) {
                    return;
                }

                if (newValue.isDone()) {
                    stopped = true;
                    if (started) {
                        queryStopped();
                    }
                    else if (queued) {
                        queryDequeued();
                    }
                    finalQueryInfoSupplier.get()
                            .ifPresent(QueryManagerStats.this::queryFinished);
                    return;
                }

                if (newValue.ordinal() == QUEUED.ordinal()) {
                    if (!queued) {
                        queued = true;
                        queryQueued();
                    }
                }
                else if (newValue.ordinal() > QUEUED.ordinal()) {
                    if (queued) {
                        queryDequeued();
                        queued = false;
                    }
                    if (newValue.ordinal() >= RUNNING.ordinal()) {
                        if (!started) {
                            started = true;
                            queryStarted();
                        }
                    }
                }
            }
        }
    }
    ```

**Review by tdcmeehan — COMMENTED** [review]
LGTM % the suggested simplification to the `stateChanged` method

File: presto-main/src/main/java/com/facebook/presto/execution/QueryManagerStats.java (hunk 10 above)
Comment (imjalpreet) [reply presto-main/src/main/java/com/facebook/presto/execution/QueryManagerStats.java]: @tdcmeehan Thanks for the review, I have made the change.

**Review by yingsu00 — APPROVED** [review]

**Review by tdcmeehan — APPROVED** [review]
