### PR TITLE
Fix dupe expression error in orderings

### LINKED ISSUE #15320: Crash with dupe expression error
The following query gives error with dupe expression.

  SELECT
      CAST(
          ARRAY_AGG(
              method_rank --prediction_method_id
              ORDER BY
                  method_rank ASC,
                  conf_score DESC,
                  method_subrank ASC
          )
          AS ARRAY<BIGINT>
      ) AS all_predictions_with_method_rank
      FROM (select 1 ) cross join
( SELECT 1 as conf_score, 0 AS method_id, 0 AS method_rank, 0 AS method_subrank LIMIT 0)
;

### PR DESCRIPTION
**Pull request by pranjalssh**
Fix dupe expression error in orderings

Fix duplicate expressions in orderings that may be revealed after we unalias references.

Fixes #15320

== NO RELEASE NOTE ==

### CODE REVIEW

File: presto-tests/src/test/java/com/facebook/presto/tests/TestLocalQueries.java [hunk 1]
```diff
@@ -144,4 +144,10 @@ public void testIOExplain()
                 jsonCodec(IOPlan.class).fromJson((String) getOnlyElement(result.getOnlyColumnAsSet())),
                 new IOPlan(ImmutableSet.of(input), Optional.empty()));
     }
+
+    @Test
```
Comment (rongrong) [inline presto-tests/src/test/java/com/facebook/presto/tests/TestLocalQueries.java:148]: Move this test to `AbstractTestQueries`, which will be run in different configurations rather than just with `LocalQueryRunner`.

**Review by rongrong — COMMENTED** [review]
Looks good. Just one nits. Thanks!

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SymbolMapper.java [hunk 2]
```diff
@@ -135,14 +136,16 @@ public OrderingScheme map(OrderingScheme orderingScheme)
...
         // SymbolMapper inlines symbol with multiple level reference (SymbolInliner only inline single level).
         ImmutableList.Builder<VariableReferenceExpression> orderBy = ImmutableList.builder();
-        ImmutableMap.Builder<VariableReferenceExpression, SortOrder> ordering = ImmutableMap.builder();
+        HashMap<VariableReferenceExpression, SortOrder> orderingMap = new HashMap<VariableReferenceExpression, SortOrder>();
         for (VariableReferenceExpression variable : orderingScheme.getOrderByVariables()) {
             VariableReferenceExpression translated = map(variable);
-            orderBy.add(translated);
-            ordering.put(translated, orderingScheme.getOrdering(variable));
+            // Some variables may become duplicates after canonicalization, so we put them only once.
+            if (!orderingMap.containsKey(translated)) {
```
Comment (kaikalur) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SymbolMapper.java:143]: When you are at it, maybe warn if someone does 

ORDER BY x DESC, x ASC

because currently we just take the first one. But since you are checking here, you can warn.

**Review by kaikalur — CHANGES_REQUESTED** [review]

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SymbolMapper.java (hunk 2 above)
Comment (rongrong) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SymbolMapper.java:143]: Should that be a separate PR?

Comment (rongrong) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SymbolMapper.java:143]: Actually let's do it in this PR as well, cause otherwise by deduping we might hide the error.

Comment (kaikalur) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SymbolMapper.java:143]: Actually, I say give a warning anyway if you see a repetition and also a second warning if they are mismatched sort direction.

Comment (pranjalssh) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SymbolMapper.java:143]: I checked this information is already lost when OrderingScheme is created. We can only add a warning here if we have 

ORDER BY x DESC, y ASC

where x and y are same canonical variables, but different variables in input.

To put a warning for all cases of same variable, we need to have a different PR which touches different points where OrderingScheme is created

**Comment by pranjalssh** [comment]
Addressed comments

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SymbolMapper.java (hunk 2 above)
Comment (kaikalur) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SymbolMapper.java:149]: OK. Create an issue so we can track it.

Comment (pranjalssh) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SymbolMapper.java:149]: https://github.com/prestodb/presto/issues/16327

**Review by kaikalur — APPROVED** [review]

**Comment by pranjalssh** [comment]
@rongrong can we merge this?

**Comment by pedromealves** [comment]
Hi, can someone review #17011

**Comment by pedroafonsoalves** [comment]
Hi, can someone review #17011
