### PR TITLE
Fix getBlockView to use positionCount instead of outputPositionCount

### LINKED ISSUE #14470: Length of the field blocks differ in Structs field resulting in a java.lang.IllegalArgumentException
```
com.facebook.presto.spi.PrestoException: Failed to read ORC file:
	at com.facebook.presto.hive.orc.OrcSelectivePageSource.getNextPage(OrcSelectivePageSource.java:100)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:272)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:237)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)

Caused by: java.lang.IllegalArgumentException: length of field blocks differ: field 0: 232, block 1: 34
	at com.facebook.presto.spi.block.RowBlock.validateConstructorArguments(RowBlock.java:93)
	at com.facebook.presto.spi.block.RowBlock.fromFieldBlocks(RowBlock.java:52)
	at com.facebook.presto.orc.reader.StructSelectiveStreamReader.getBlockView(StructSelectiveStreamReader.java:545)
	at com.facebook.presto.orc.reader.StructSelectiveStreamReader.getBlockView(StructSelectiveStreamReader.java:540)
	at com.facebook.presto.orc.reader.StructSelectiveStreamReader.getBlockView(StructSelectiveStreamReader.java:540)
```

### PR DESCRIPTION
**Pull request by bhhari**
Fix the block view to return right number of positions incase of all Nulls using the positionCount
Fixes #14470 
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

File: presto-hive/src/test/java/com/facebook/presto/hive/TestHivePushdownFilterQueries.java [hunk 1]
```diff
@@ -670,7 +670,7 @@ public void testAllNullsInStruct()
     {
         List<String> types = ImmutableList.of(BOOLEAN, TINYINT, SMALLINT, INTEGER, BIGINT, DOUBLE, REAL, VARCHAR, DATE);
 
-        String query = String.format("SELECT orderkey, CAST(ROW(%s, 1) AS ROW(%s, a INTEGER)) as struct FROM orders",
+        String query = String.format("SELECT orderkey, CAST(ROW(%s, orderkey) AS ROW(%s, a INTEGER)) as struct FROM orders",
```
Comment (mbasmanova) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestHivePushdownFilterQueries.java:673]: nit: a -> orderkey
