### PR TITLE
Fix race in TestTaskExecutor.testTaskHandle

### LINKED ISSUE #5116: Race in TestTaskExecutor.testTaskHandle
This test fails non-deterministically with:
```
java.lang.AssertionError: expected [1] but found [0]
Expected :1
Actual   :0
 <Click to see difference>


	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at com.facebook.presto.execution.TestTaskExecutor.testTaskHandle(TestTaskExecutor.java:141)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:74)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

It's pretty easy to repro if you set the invocation count to 10k

### PR DESCRIPTION
**Pull request by geraint0923**
Fix #5116

### CODE REVIEW

File: presto-main/src/test/java/com/facebook/presto/execution/TestTaskExecutor.java [hunk 1]
```diff
@@ -115,7 +115,7 @@ public void test()
         }
     }
 
-    @Test
+    @Test(invocationCount = 10000)
```
Comment (cberner) [inline presto-main/src/test/java/com/facebook/presto/execution/TestTaskExecutor.java]: remove this

File: presto-main/src/test/java/com/facebook/presto/execution/TestTaskExecutor.java [hunk 2]
```diff
@@ -130,6 +130,8 @@ public void testTaskHandle()
             beginPhase.register();
             Phaser verificationComplete = new Phaser();
             verificationComplete.register();
+            // register once more to make splits could not be finished
+            verificationComplete.register();
```
Comment (cberner) [inline presto-main/src/test/java/com/facebook/presto/execution/TestTaskExecutor.java]: I think it would be better to fix this by constructing two `TestingJob` objects. I'm not sure why this test is written calling `enqueueSplit` twice with the same `driver`, but that's not the right way to use it.

**Comment by cberner** [comment]
Also, explain in the commit message what this is fixing and why it was broken

File: presto-main/src/test/java/com/facebook/presto/execution/TestTaskExecutor.java (hunk 1 above)
Comment (geraint0923) [inline presto-main/src/test/java/com/facebook/presto/execution/TestTaskExecutor.java]: I think multiple runs are necessary for this test so that we could catch the race issue.

File: presto-main/src/test/java/com/facebook/presto/execution/TestTaskExecutor.java (hunk 2 above)
Comment (geraint0923) [inline presto-main/src/test/java/com/facebook/presto/execution/TestTaskExecutor.java]: Nice, I will fix it.

File: presto-main/src/test/java/com/facebook/presto/execution/TestTaskExecutor.java (hunk 1 above)
Comment (cberner) [inline presto-main/src/test/java/com/facebook/presto/execution/TestTaskExecutor.java]: The race is due to the test being written incorrectly though, not a race in the Presto code. I would remove it, since our tests are already taking too long :)

Comment (geraint0923) [inline presto-main/src/test/java/com/facebook/presto/execution/TestTaskExecutor.java]: Ok, I will do it.

**Comment by geraint0923** [comment]
Address the comments.

**Comment by cberner** [comment]
Looks good
