### PR TITLE
Report meaningful exception when no spill paths configured

### LINKED ISSUE #9197: Incorrect Error Message When Spill Path is not specified
HI ,

When spill to disk experimental feature is enabled and spill path on disk is not specified, it's throwing the below error which is confusing, instead the error message should ideally be ""No spill paths defined" which is more actionable 

"No free space available for spill"

### PR DESCRIPTION
**Pull request by findepi**
Fixes #9197

### CODE REVIEW

File: presto-main/src/main/java/com/facebook/presto/spiller/FileSingleStreamSpillerFactory.java [hunk 1]
```diff
@@ -154,6 +154,9 @@ private synchronized Path getNextSpillPath()
                 return path;
             }
         }
+        if (spillPaths.isEmpty()) {
```
Comment (losipiuk) [inline presto-main/src/main/java/com/facebook/presto/spiller/FileSingleStreamSpillerFactory.java]: I was actually thinking about adding this check on Presto startup. So we check if spill paths are configured if spill is enabled. I am not sure if there is natural place for such config cross validation. If there is no better place you could pass `spill.enabled` flag to `FileSingleStreamSpillerFactory` and put validation in `@PostConstruct` method.
What do you think?

Comment (findepi) [reply presto-main/src/main/java/com/facebook/presto/spiller/FileSingleStreamSpillerFactory.java]: That would work. However, you can enable/disable spill on session level too. Indeed, Presto can refuse to start when spill is enabled and no paths configured, but it still must fail reasonably when no paths configured and users enables spill with a session's switch.

Comment (losipiuk) [reply presto-main/src/main/java/com/facebook/presto/spiller/FileSingleStreamSpillerFactory.java]: Actually there is no session property to change spill paths.
And there is already code which validates if spill paths list is non-empty if we enable spilling via session property 

```
                new PropertyMetadata<>(
                        SPILL_ENABLED,
                        "Experimental: Enable spilling",
                        BOOLEAN,
                        Boolean.class,
                        featuresConfig.isSpillEnabled(),
                        false,
                        value -> {
                            boolean spillEnabled = (Boolean) value;
                            if (spillEnabled && featuresConfig.getSpillerSpillPaths().isEmpty()) {
                                throw new PrestoException(
                                        StandardErrorCode.INVALID_SESSION_PROPERTY,
                                        format("%s cannot be set to true; no spill paths configured", SPILL_ENABLED));
                            }
                            return spillEnabled;
                        },
                        value -> value),
```

Hmm this is awful to have it in two places. 

Maybe instead adding special validation for `spill-paths` config property we should validate if default session is valid on Presto startup?

Comment (electrum) [reply presto-main/src/main/java/com/facebook/presto/spiller/FileSingleStreamSpillerFactory.java]: Default session validation would produce the wrong error message, since the problem is the spill config property, not the session property. I think we need the check in both places. But I agree we should do it on startup if spilling is enabled by default.

**Comment by findepi** [comment]
I added config validation using annotations in `FeatureConfig`. I retained the run-time check in `FileSingleStreamSpillerFactory`, as spill can be enabled on session level too.

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/FeaturesConfig.java [hunk 2]
```diff
@@ -407,6 +408,12 @@ public FeaturesConfig setSpillerSpillPaths(String spillPaths)
         return this;
     }
 
+    @AssertTrue(message = "experimental.spiller-spill-path must be configured when experimental.spill-enabled is set to true")
```
Comment (losipiuk) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/FeaturesConfig.java]: Somewhat hacky. Is this approach used in other places?

Test?

Comment (findepi) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/FeaturesConfig.java]: No, it's not used elsewhere. Do you have a better idea?

We don't have tests that validation in `FeaturesConfig` works. I added such a test nonetheless.

File: presto-main/src/test/java/com/facebook/presto/sql/analyzer/TestFeaturesConfig.java [hunk 3]
```diff
@@ -166,4 +172,19 @@ public void testExplicitPropertyMappings()
 
         assertFullMapping(properties, expected);
     }
+
+    @Test
```
Comment (losipiuk) [inline presto-main/src/test/java/com/facebook/presto/sql/analyzer/TestFeaturesConfig.java]: Why not @Test with expectedExceptons?
