### PR TITLE
fix(native): Fix TRY expression handling in NativeExpressionOptimizer

### LINKED ISSUE #27317: native(sidecar): Fix `TRY` expression handling in NativeExpressionOptimizer
## Expected Behavior
When a TRY expression wraps a fail(...) call or a cast-wrapped fail statement (e.g., `TRY(fail(...))` or `TRY(CAST(fail(...) AS INTEGER))`), the native expression optimizer should:
1. Detect the TRY-wrapped fail pattern during expression optimization
2. Replace it with a NULL constant of the appropriate type
3. Recursively handle nested occurrences in child expressions (SpecialFormExpressions and CallExpressions)
4. Correctly map the internal Velox `try` function to the Presto `internal$try` name during conversion

## Current Behavior
TRY expressions that wrap fail() calls are not properly handled during native expression optimization in the sidecar execution path, resulting in:
1. Incorrect or missing NULL constants where TRY(fail(...)) should be optimized
2. Malformed expressions when SpecialFormExpressions (e.g., COALESCE) contain TRY-wrapped fail calls as children
3. Function handle resolution failures for the internal `try` function, preventing correct Velox-to-Presto conversion
4. Nested TRY(fail(...)) patterns remaining unoptimized after iterative optimization passes

This bug only manifests with sidecar expression optimization enabled, as it's the code path that calls the native expression optimizer iteratively.

## Possible Solution
The fix involves three components:

1. **NativeExpressionOptimizer enhancements** (Java):
   - Add helper methods to detect fail expressions and TRY-wrapped fail patterns
   - Implement recursive sanitization (`sanitizeTryFailInChildren`) to walk CallExpression and SpecialFormExpression trees
   - Replace any child TRY(fail(...)) pattern with a NULL constant during post-processing of the optimization replacement map

2. **Function handle mapping** (C++):
   - Define a mapping between Velox's internal `try` function name and Presto's fully qualified `internal$try` name
   - Update `getFunctionHandle` to return a NativeFunctionHandle for internal function mappings
   - Rewrite Velox function names via the mapping before constructing Presto call expressions

3. **Test coverage**:
   - Add regression tests for COALESCE(TRY(CAST(...) AS INTEGER)) and TRY(CAST('a' AS BIGINT)) patterns
   - Validate that these expressions optimize to 0 and NULL respectively

## Steps to Reproduce
1. Enable native sidecar expression optimization
2. Execute a query with a TRY expression wrapping a fail() or CAST(fail()) pattern:
   ```sql
   SELECT COALESCE(TRY(CAST(CONCAT(...) AS INTEGER)), 0) FROM table;

### PR DESCRIPTION
**Pull request by pramodsatya**
## Description

Resolves #27317.

Fixes TRY expression handling in the native sidecar expression optimizer and Velox-to-Presto expression conversion path. When TRY expressions wrap fail() calls or cast-wrapped fail statements, they are not properly converted back to Presto's expected shape after optimization, causing function resolution failures.

## Motivation and Context

In the sidecar execution path with native expression optimization enabled, there are a couple of bugs in the way TRY expressions are handled:

1. TRY is an internal function in Presto but it is a special form expression in Velox that is not registered as a function, and therefore is not registered with the function namespace prefix. The Velox to Presto TRY expression conversion must be mindful of this corner case. from  

2. Presto TRY expressions are converted to Velox equivalent for optimization i.e `$internal$try(lambda)` → Velox `try(body)`, optimized in Velox, then converted back to Presto expression. In this codepath, the Velox to Presto expression conversion was not re-wrapping the optimized body into a lambda, resulting in a Presto `try(body)` shape that Presto's function registry cannot resolve.

The issue manifests specifically because:
- Presto's `$internal$try` function expects a 0-argument lambda: `$internal$try(() -> body)`
- The native converter intentionally unwraps lambdas during Presto→Velox conversion to allow Velox's native optimizer to run
- The converter must rebuild the lambda structure on the way back so Presto can resolve the internal function by its proper signature
Without this, queries like `COALESCE(TRY(CAST(...) AS INTEGER), 0)` fail with "presto.default.$internal$try(T):T not found".

The `NativeExpressionOptimizer` in sidecar plugin should rewrite try wrapping fail sub-expressions in the optimized expressions to NULL. The sidecar cannot do it because it leverages the Velox `ExprOptimizer` for optimizing sub-trees and Velox cannot identify such expression shapes, since TRY is not a distinct expression type or a registered function in Velox.

## Impact

- Enables safe optimization of TRY expressions with the sidecar's native expression optimizer
- Allows queries with TRY-wrapped fail patterns and casts to execute correctly
- Fixes correctness bug in the code path by handling TRY shape mismatch

## Test Plan

Verified with sidecar integration tests that TRY expressions are correctly optimized by the native expression optimizer.

## Release Notes

```
== NO RELEASE NOTE ==
```

## Summary by Sourcery

Improve native expression optimization and function mapping for TRY/fail patterns across Java and C++ components.

Bug Fixes:
- Correctly detect and replace TRY-wrapped fail expressions (including casted variants) with NULL in the native expression optimizer.
- Ensure SpecialFormExpression arguments containing TRY-wrapped fail are normalized to NULL results.
- Fix function handle resolution for internal TRY by treating it as a native internal function and mapping it correctly from Velox to Presto.

Enhancements:
- Add recursive sanitization of child expressions to normalize nested TRY(fail(...)) patterns in the native expression optimizer.

Tests:
- Extend native sidecar plugin tests to cover COALESCE/TRY with cast failures and TRY(cast) returning NULL behavior.

## Summary by Sourcery

Fix handling of TRY expressions in native optimization and Velox-to-Presto conversion so they preserve Presto’s expected internal function shape and semantics.

Bug Fixes:
- Rewrite TRY-wrapped FAIL (and casted FAIL) sub-expressions to NULL in the native expression optimizer so sidecar queries behave correctly.
- Ensure Velox TRY expressions are converted back to Presto’s $internal$try with a zero-argument lambda and correct function handle resolution.
- Prevent incorrect reuse of partially optimized replacement trees by recursively visiting replacements during expression rebuilding.

Enhancements:
- Extend Velox-to-Presto type signature serialization to support lambda/function types for internal functions like TRY.
- Add internal function name mapping from Velox TRY to Presto’s $internal$try during expression conversion.

Tests:
- Add sidecar plugin integration tests covering TRY with failing casts, TRY(fail(...)) patterns, COALESCE with TRY, and general TRY(CAST(...)) behavior.

## Summary by Sourcery

Fix TRY expression handling in native sidecar optimization and Velox-to-Presto conversion to ensure correct mapping of TRY/fail patterns and internal function resolution.

Bug Fixes:
- Normalize TRY-wrapped fail and cast-fail sub-expressions to NULL during native expression replacement so optimized trees remain semantically correct.
- Prevent repeated or stale replacements in the native expression optimizer by recursively re-visiting replacement subtrees.
- Correct Velox-to-Presto conversion of TRY expressions by mapping Velox try to Presto's $internal$try with the expected 0-argument lambda signature and function handle type.
- Expose isTryFunction and isFailFunction checks via StandardFunctionResolution to reliably detect TRY and FAIL calls during optimization.

Enhancements:
- Extend Velox type-to-Presto TypeSignature serialization to support function (lambda) types used by internal TRY.
- Improve native-to-Presto function handle construction and internal function mapping infrastructure for native execution.

Tests:
- Expand native sidecar plugin tests to cover TRY with failing casts, fail() calls, nested TRY(fail) patterns, COALESCE/TRY interactions, and general TRY CAST usage.

### CODE REVIEW

**Comment by pramodsatya** [comment]
@sourcery-ai review.

File: presto-native-sidecar-plugin/src/test/java/com/facebook/presto/sidecar/TestNativeSidecarPlugin.java [hunk 1]
```diff
@@ -700,6 +700,15 @@ public void testNativeExpressionOptimizer()
         // Test dereference expression with SQL invoked function, array_least_frequent.
         assertQuerySucceeds(session, "SELECT array_least_frequent(array_agg(orderkey)) from orders");
         assertQuerySucceeds(session, "SELECT array_least_frequent(array_agg(nationkey)) from nation");
+
+        // Verify try(failing_function()) returns NULL.
+        assertQueryWithSameQueryRunner(session, "SELECT TRY(CAST(abs(-1234567890) AS TINYINT))", "SELECT NULL");
+        assertQueryWithSameQueryRunner(session, "SELECT COALESCE(TRY(CAST(abs(-1234567890) AS TINYINT)), 0)", "SELECT 0");
```
[the remark this answers is not in the document]
Comment (pramodsatya) [reply presto-native-sidecar-plugin/src/test/java/com/facebook/presto/sidecar/TestNativeSidecarPlugin.java]: the overflow will be converted to a fail so this test is more comprehensive.

File: presto-native-sidecar-plugin/src/test/java/com/facebook/presto/sidecar/TestNativeSidecarPlugin.java [hunk 2]
```diff
@@ -700,6 +700,15 @@ public void testNativeExpressionOptimizer()
...
+
+        // Test TRY expression.
+        assertQuerySucceeds(session, "SELECT TRY(CAST(orderkey AS TINYINT)) from orders");
+        assertQuerySucceeds(session, "SELECT TRY(CAST(comment AS BIGINT)) from orders");
+        assertQuerySucceeds(session, "SELECT TRY(CAST(orderkey AS DOUBLE)) from orders");
```
[the remark this answers is not in the document]
Comment (pramodsatya) [reply presto-native-sidecar-plugin/src/test/java/com/facebook/presto/sidecar/TestNativeSidecarPlugin.java]: this is valid but the equivalent SQLs use CASE expressions, which currently has a bug in the `NativeExpressionOptimizer` path; the tests enhancement is pending on https://github.com/prestodb/presto/pull/27031.

**Comment by pramodsatya** [comment]
@sourcery-ai review.

**Comment by pramodsatya** [comment]
@sourcery-ai review.

**Comment by pramodsatya** [comment]
@aditi-pandit, could you help review this fix?

File: presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp [hunk 3]
```diff
@@ -361,10 +378,16 @@ CallExpressionPtr VeloxToPrestoExprConverter::getCallExpression(
   result["@type"] = kCall;
   protocol::Signature signature;
   std::string exprName = expr->name();
+  bool isTryExpression = (exprName == velox::expression::kTry);
```
Comment (aditi-pandit) [inline presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp]: Can move this assignment closer to its usage below.

Comment (pramodsatya) [reply presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp]: `exprName` changes in the following if/else check so I had kept the assignment here to use the Velox expression constant for `try`, is that alright?

Comment (pramodsatya) [reply presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp]: Cleaned up the function to delineate velox/presto expression names and moved the assignment closer to usage now, thanks for the suggestion. Could you please take another look?

File: presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp [hunk 4]
```diff
@@ -33,7 +33,11 @@ namespace {
 
 constexpr char const* kSpecial = "special";
 
-protocol::TypeSignature getTypeSignature(const velox::TypePtr& type) {
+// Serializes Velox type to equivalent Presto TypeSignature. Supports lambda
+// type signatures in the form "function(T)".
+protocol::TypeSignature getTypeSignature(
+    const velox::TypePtr& type,
+    bool isFunction = false) {
```
Comment (aditi-pandit) [inline presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp]: Maybe call parameter asLambda ?

File: presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp [hunk 5]
```diff
@@ -101,6 +109,15 @@ const std::unordered_map<std::string, std::string>& veloxToPrestoOperatorMap() {
   return veloxToPrestoOperatorMap;
 }
 
+const std::unordered_map<std::string, std::string>&
```
Comment (aditi-pandit) [inline presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp:104]: Can you add a comment about what this map represents ? Are there any other functions that could make it here ?

**Review by aditi-pandit — COMMENTED** [review]
Thanks @pramodsatya

**Comment by aditi-pandit** [comment]
@pdabre12 : Please can you review as well.

File: presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp (hunk 5 above)
Comment (pramodsatya) [reply presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp:104]: Thanks for pointing it out, `try_cast` also belongs here and I have updated the list and added e2e tests, added a comment reg this map as well. 
cc: @pdabre12

File: presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp [hunk 6]
```diff
@@ -362,14 +380,27 @@ CallExpressionPtr VeloxToPrestoExprConverter::getCallExpression(
...
+  // Map Velox expression to the right Presto expression name when constructing
+  // the Presto function signature.
   const auto& opMap = veloxToPrestoOperatorMap();
-  auto mapIter = opMap.find(exprName);
+  auto mapIter = opMap.find(veloxExprName);
   if (mapIter != opMap.end()) {
-    exprName = mapIter->second;
+    prestoExprName = mapIter->second;
+  } else {
+    const auto& internalFunctionMap = veloxToPrestoInternalFunctionMap();
```
Comment (pdabre12) [inline presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp:434]: `internalFunctionMap` variable not used.

File: presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp [hunk 7]
```diff
@@ -362,14 +380,27 @@ CallExpressionPtr VeloxToPrestoExprConverter::getCallExpression(
...
+    mapIter = veloxToPrestoInternalFunctionMap().find(veloxExprName);
+    if (mapIter != opMap.end()) {
```
Comment (pdabre12) [inline presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp]: Shouldn't this be `mapIter != internalFunctionMap.end()`

File: presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp [hunk 8]
```diff
@@ -378,17 +409,36 @@ CallExpressionPtr VeloxToPrestoExprConverter::getCallExpression(
...
+  bool isTryExpression = (veloxExprName == velox::expression::kTry);
+  if (isTryExpression) {
+    VELOX_CHECK_EQ(
+        exprInputs.size(),
+        1,
+        "Velox TRY expression should have exactly 1 input, but got {}.",
+        exprInputs.size());
+
+    // Presto '$internal$try' expects a lambda with no arguments: () -> T.
+    argumentTypes.emplace_back(
```
Comment (pdabre12) [inline presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp]: This could be a `try_cast` as well right? Should we handle that case?

File: presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp [hunk 9]
```diff
@@ -378,17 +409,36 @@ CallExpressionPtr VeloxToPrestoExprConverter::getCallExpression(
...
-  result["functionHandle"] = getFunctionHandle(exprName, signature);
+  result["functionHandle"] = getFunctionHandle(prestoExprName, signature);
   result["returnType"] = getTypeSignature(expr->type());
   result["arguments"] = json::array();
-  for (const auto& exprInput : exprInputs) {
-    result["arguments"].push_back(getRowExpression(exprInput));
+  if (isTryExpression) {
+    const auto lambdaExpr = std::make_shared<velox::core::LambdaTypedExpr>(
+        velox::ROW({}), exprInputs.at(0));
+    result["arguments"].push_back(getLambdaExpression(lambdaExpr.get()));
```
Comment (pdabre12) [inline presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp]: Can we use the same logic as here in the above block where in we create a `lambda` with no args?

File: presto-native-sidecar-plugin/src/main/java/com/facebook/presto/sidecar/expressions/NativeExpressionOptimizer.java [hunk 10]
```diff
@@ -315,18 +317,26 @@ public List<RowExpression> getExpressionsToOptimize()
...
             this.resolver = i -> replacements.getOrDefault(i, i);
+            this.resolution = resolution;
         }
 
-        public ReplacingVisitor(Function<VariableReferenceExpression, RowExpression> variableResolver)
+        public ReplacingVisitor(Function<VariableReferenceExpression, RowExpression> variableResolver, StandardFunctionResolution resolution)
         {
             requireNonNull(variableResolver, "variableResolver is null");
+            requireNonNull(resolution, "resolution is null");
+            this.replacements = java.util.Collections.emptyMap();
```
Comment (pdabre12) [inline presto-native-sidecar-plugin/src/main/java/com/facebook/presto/sidecar/expressions/NativeExpressionOptimizer.java]: nit: static import

File: presto-native-sidecar-plugin/src/main/java/com/facebook/presto/sidecar/expressions/NativeExpressionOptimizer.java [hunk 11]
```diff
@@ -315,18 +317,26 @@ public List<RowExpression> getExpressionsToOptimize()
...
             this.resolver = i -> i instanceof VariableReferenceExpression ? variableResolver.apply((VariableReferenceExpression) i) : i;
+            this.resolution = resolution;
```
Comment (pdabre12) [inline presto-native-sidecar-plugin/src/main/java/com/facebook/presto/sidecar/expressions/NativeExpressionOptimizer.java:338]: Can you move this closer to the `requireNonNull(resolution, "resolution is null");`?

File: presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp (hunk 9 above)
Comment (pramodsatya) [reply presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp]: Consolidated the argTypes and args construction, thanks.

File: presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp (hunk 8 above)
Comment (pramodsatya) [reply presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp]: `try_cast` is handled correctly by the existing code path and only the Velox-to-Presto function name mapping needs to be fixed for it.

**Comment by aditi-pandit** [comment]
@pdabre12 : Please can you take a first stab at a review.

File: presto-native-sidecar-plugin/src/main/java/com/facebook/presto/sidecar/expressions/NativeExpressionOptimizer.java [hunk 12]
```diff
@@ -359,9 +370,19 @@ public RowExpression visitLambda(LambdaDefinitionExpression lambda, Void context
...
+
             if (canBeReplaced(call)) {
-                return resolver.apply(call);
+                RowExpression replacement = resolver.apply(call);
+                if (replacements.containsKey(replacement)) {
+                    return replacement;
+                }
+                // Replacement tree can be optimized further, such as rewriting TRY-wrapping-FAIL patterns with NULL.
+                return replacement.accept(this, context);
             }
```
[the remark this answers is not in the document]
Comment (pdabre12) [reply presto-native-sidecar-plugin/src/main/java/com/facebook/presto/sidecar/expressions/NativeExpressionOptimizer.java:384]: @pramodsatya I think this might be a valid comment.
Can we have cases of nested `try_cast/try` calls?

[the remark this answers is not in the document]
Comment (pdabre12) [reply presto-native-sidecar-plugin/src/main/java/com/facebook/presto/sidecar/expressions/NativeExpressionOptimizer.java:384]: Nevermind, I see the test cases with nested calls.

File: presto-native-sidecar-plugin/src/main/java/com/facebook/presto/sidecar/expressions/NativeExpressionOptimizer.java [hunk 13]
```diff
@@ -372,8 +393,14 @@ public RowExpression visitCall(CallExpression call, Void context)
...
         {
             if (canBeReplaced(specialForm)) {
-                return resolver.apply(specialForm);
+                RowExpression replacement = resolver.apply(specialForm);
+                if (replacements.containsKey(replacement)) {
+                    return replacement;
+                }
+                // Replacement tree can be optimized further, such as rewriting TRY-wrapping-FAIL patterns with NULL.
+                return replacement.accept(this, context);
             }
```
[the remark this answers is not in the document]
Comment (pramodsatya) [reply presto-native-sidecar-plugin/src/main/java/com/facebook/presto/sidecar/expressions/NativeExpressionOptimizer.java:402]: Already addressed.

File: presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp [hunk 14]
```diff
@@ -101,6 +102,18 @@ const std::unordered_map<std::string, std::string>& veloxToPrestoOperatorMap() {
...
+const std::unordered_map<std::string, std::string>&
+veloxToPrestoInternalFunctionMap() {
+  // Maps Velox internal function names to Presto internal/native function
+  // names used when constructing function signatures.
+  static const std::unordered_map<std::string, std::string>
+      veloxToPrestoInternalFunctionMap = {
+          {"try", "presto.default.$internal$try"},
+          {"try_cast", "presto.default.try_cast"},
+      };
+  return veloxToPrestoInternalFunctionMap;
```
[the remark this answers is not in the document]
Comment (pramodsatya) [reply presto-native-execution/presto_cpp/main/types/VeloxToPrestoExpr.cpp:113]: `internal/native` already present in code comment.

**Comment by pramodsatya** [comment]
Thanks @pdabre12. @aditi-pandit, could you PTAL?

**Comment by steveburnett** [comment]
Please resolve the file conflict.

**Comment by pramodsatya** [comment]
Done @steveburnett.
