### PR TITLE
Push SemiJoin predicate inferred from filter side to source side (v2)

### LINKED ISSUE #10085: Planning fails for queries with non-deterministic predicate pushdownable to semi-join source
Example query:

```
SELECT * FROM lineitem WHERE orderkey NOT IN (SELECT orderkey FROM orders) AND orderkey = random(5)
```

fails with:

```
java.lang.IllegalArgumentException: Only deterministic expressions may be considered for rewrite

	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.facebook.presto.sql.planner.EqualityInference.rewriteExpression(EqualityInference.java:106)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitSemiJoin(PredicatePushDown.java:811)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitSemiJoin(PredicatePushDown.java:115)
	at com.facebook.presto.sql.planner.plan.SemiJoinNode.accept(SemiJoinNode.java:139)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitFilter(PredicatePushDown.java:275)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitFilter(PredicatePushDown.java:115)
	at com.facebook.presto.sql.planner.plan.FilterNode.accept(FilterNode.java:72)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
...
```

This happens when `PredicatePushDown` tries to push down `orderkey = random(5)` to semi-join source responsible for scanning `lineitem` table.
It seems like a valid pushdown as semi-join does not creates copies of rows from the source side.

### PR DESCRIPTION
**Pull request by losipiuk**
Followup of #10048

Now with guarding that semi-join output is actually used for filtering out rows above semi join.
Still a point change. Could be extended with restructuring PP for SemiJoin to also move predicates from source side to filter side.
And eventually migrated to Iterative optimizer as discussed elsewhere.

Wait till tests pass before rewiew.

cc: @kokosing, @sopel39, @martint, @findepi 

Also fixes #10085

### CODE REVIEW

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PredicatePushDown.java [hunk 1]
```diff
@@ -825,6 +825,19 @@ public PlanNode visitSemiJoin(SemiJoinNode node, RewriteContext<Expression> cont
             postJoinConjuncts.addAll(equalityPartition.getScopeComplementEqualities());
             postJoinConjuncts.addAll(equalityPartition.getScopeStraddlingEqualities());
 
+            if (extractConjuncts(inheritedPredicate).contains(node.getSemiJoinOutput().toSymbolReference())) {
```
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PredicatePushDown.java]: you need to check in what context `semijoin` symbol is used, e.g:
`semijoin and y`
`not semijoin`
`semijoin = func_that_returns_boolean(...)`

File: presto-main/src/test/java/com/facebook/presto/sql/planner/TestPredicatePushdown.java [hunk 2]
```diff
@@ -60,4 +61,35 @@ public void testPushDownToLhsOfSemiJoin()
...
+    }
+
+    @Test
+    public void testPredicateFromFilterSideNotPropagatesToSourceSideOfSemiJoinIfNotIn()
+    {
+        assertPlan("SELECT quantity FROM (SELECT * FROM lineitem WHERE orderkey NOT IN (SELECT orderkey FROM orders where orderkey = 2))",
+                anyTree(
+                        semiJoin("LINE_ORDER_KEY", "ORDERS_ORDER_KEY", "SEMI_JOIN_RESULT",
+                                project(
+                                        tableScan("lineitem", ImmutableMap.of(
```
Comment (findepi) [inline presto-main/src/test/java/com/facebook/presto/sql/planner/TestPredicatePushdown.java]: There could be a filter above TS, w `ORDERS_ORDER_KEY != 2`, right? Add a comment that it's possible, but not implemented yet.

**Comment by losipiuk** [comment]
Added test

File: presto-main/src/test/java/com/facebook/presto/sql/planner/TestPredicatePushdown.java (hunk 2 above)
Comment (findepi) [reply presto-main/src/test/java/com/facebook/presto/sql/planner/TestPredicatePushdown.java]: I'm wrong. There can't be, because the filtering side may come empty. Please add:
```
// There should be no Filter above table scan, because we don't know whether SemiJoin's filtering source is empty.
```

**Comment by losipiuk** [comment]
I will see if I find some time to extend it over weekend to make it a bit more general.

**Comment by losipiuk** [comment]
Here is the more general approach. Much more inferences support. Based on logic of rewrites for inner join for case when we have semi-join and inherited predicated contains semi-join output symbol as a conjunct.

Fixed #10085 on the way. 

Please review.

File: presto-main/src/test/java/com/facebook/presto/sql/planner/TestPredicatePushdown.java [hunk 3]
```diff
@@ -62,7 +62,7 @@ public void testPushDownToLhsOfSemiJoin()
                                 anyTree(tableScan("orders", ImmutableMap.of("ORDERS_ORDER_KEY", "orderkey"))))));
     }
 
-    @Test(enabled = false) // unignore after fixing #10085
```
Comment (findepi) [inline presto-main/src/test/java/com/facebook/presto/sql/planner/TestPredicatePushdown.java]: squash

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PredicatePushDown.java [hunk 4]
```diff
@@ -837,6 +845,93 @@ public PlanNode visitSemiJoin(SemiJoinNode node, RewriteContext<Expression> cont
...
+                }
+                else {
+                    postJoinConjuncts.add(conjunct);
+                }
+            }
+
+            // Push inheritedPredicates down to the filtering source if possible
+            for (Expression conjunct : EqualityInference.nonInferrableConjuncts(deterministicInheritedPredicate)) {
+                Expression rewrittenConjunct = allInference.rewriteExpression(conjunct, in(filteringSourceSymbols));
+                // TODO can we push non-deterministic stuff conjuncts there (not doing it for now)
```
Comment (findepi) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PredicatePushDown.java]: missing `?` What's `stuff`?

File: presto-main/src/test/java/com/facebook/presto/sql/planner/TestPredicatePushdown.java (hunk 3 above)
Comment (findepi) [reply presto-main/src/test/java/com/facebook/presto/sql/planner/TestPredicatePushdown.java]: and sort the commits

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PredicatePushDown.java [hunk 5]
```diff
@@ -837,6 +845,93 @@ public PlanNode visitSemiJoin(SemiJoinNode node, RewriteContext<Expression> cont
             return output;
         }
 
+        private PlanNode visitFilteringSemiJoin(SemiJoinNode node, RewriteContext<Expression> context)
+        {
+            Expression inheritedPredicate = context.get();
```
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PredicatePushDown.java]: I think you can reuse: `PredicatePushDown.Rewriter#processInnerJoin` method. Then any conjuct from: `InnerJoinPushDownResult#getJoinPredicate` can be used as filter in semi join (all should be equivalent).

File: presto-main/src/test/java/com/facebook/presto/sql/planner/TestPredicatePushdown.java [hunk 6]
```diff
@@ -60,4 +61,30 @@ public void testPushDownToLhsOfSemiJoin()
...
+    {
+        assertPlan("SELECT * FROM lineitem WHERE orderkey IN (SELECT orderkey FROM orders) AND orderkey = random(5)",
+                anyTree(
+                        semiJoin("LINE_ORDER_KEY", "ORDERS_ORDER_KEY", "SEMI_JOIN_RESULT",
+                                anyTree(
+                                        filter("LINE_ORDER_KEY = CAST(random(5) AS bigint)",
+                                                        tableScan("lineitem", ImmutableMap.of(
+                                                                "LINE_ORDER_KEY", "orderkey")))),
+                                anyTree(
+                                        project(// NO filter here
```
Comment (kokosing) [inline presto-main/src/test/java/com/facebook/presto/sql/planner/TestPredicatePushdown.java]: how do you know? Filter could be above the project.

See `com.facebook.presto.sql.planner.assertions.PlanMatchPattern#anyNot`, maybe we need something like `anyTreeNot`

File: presto-main/src/test/java/com/facebook/presto/sql/planner/TestPredicatePushdown.java [hunk 7]
```diff
@@ -60,4 +61,30 @@ public void testPushDownToLhsOfSemiJoin()
...
+
+        assertPlan("SELECT * FROM lineitem WHERE orderkey NOT IN (SELECT orderkey FROM orders) AND orderkey = random(5)",
+                anyTree(
+                        semiJoin("LINE_ORDER_KEY", "ORDERS_ORDER_KEY", "SEMI_JOIN_RESULT",
+                                anyTree(
+                                        filter("LINE_ORDER_KEY = CAST(random(5) AS bigint)",
+                                                        tableScan("lineitem", ImmutableMap.of(
+                                                                "LINE_ORDER_KEY", "orderkey")))),
+                                anyTree(
+                                        project(// NO filter here
```
Comment (kokosing) [inline presto-main/src/test/java/com/facebook/presto/sql/planner/TestPredicatePushdown.java]: ditto

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PredicatePushDown.java [hunk 8]
```diff
@@ -797,7 +797,15 @@ private Object nullInputEvaluator(final Collection<Symbol> nullSymbols, Expressi
         public PlanNode visitSemiJoin(SemiJoinNode node, RewriteContext<Expression> context)
         {
             Expression inheritedPredicate = context.get();
+            if (!extractConjuncts(inheritedPredicate).contains(node.getSemiJoinOutput().toSymbolReference())) {
+                return visitNonFilteringSemiJoin(node, context);
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PredicatePushDown.java]: IMO `visitNonFilteringSemiJoin` should be called for both cases, then possibly in `visitFilteringSemiJoin` you might have easier code:

```
Plan rewritten = visitNonFilteringSemiJoin(node, context);
if (extractConjuncts(inheritedPredicate).contains(node.getSemiJoinOutput().toSymbolReference())) {
    rewritten = visitFilteringSemiJoin(node, context);
}
return rewritten;
```

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PredicatePushDown.java (hunk 5 above)
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PredicatePushDown.java]: I do not like `inheritedPredicate`, maybe just `predicate`?

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PredicatePushDown.java (hunk 8 above)
Comment (losipiuk) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PredicatePushDown.java]: It could allow to get rid of  common part:
```java
            // Push inheritedPredicates down to the source if they don't involve the semi join output
            for (Expression conjunct : EqualityInference.nonInferrableConjuncts(inheritedPredicate)) {
                Expression rewrittenConjunct = allInference.rewriteExpressionAllowNonDeterministic(conjunct, in(sourceSymbols));
                // Since each source row is reflected exactly once in the output, ok to push non-deterministic predicates down
                if (rewrittenConjunct != null) {
                    sourceConjuncts.add(rewrittenConjunct);
                }
                else {
                    postJoinConjuncts.add(conjunct);
                }
            }
```

Yet it does not come at the cost.
 Note that `visitNonFilteringSemiJoin` can return either `FilterNode` or `SemiJoinNode`. This then would need to be handled here (or inside `visitFilteringSemiJoin`). Given the fact that common snippet is not that long I am not sure if that is worth an effort. This way at least shape is simple (though I agree there is some duplication).

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PredicatePushDown.java (hunk 5 above)
Comment (losipiuk) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PredicatePushDown.java]: I do not like the `predicate`. There are many "predicates" involved in the method and some designator is nice-to-have. Also what we get from `context.get()` is called `inheritedPredicate` all over the class.

File: presto-main/src/test/java/com/facebook/presto/sql/planner/TestPredicatePushdown.java (hunk 6 above)
Comment (losipiuk) [reply presto-main/src/test/java/com/facebook/presto/sql/planner/TestPredicatePushdown.java]: I change the `anyTree` to explicit `node(ExchangeNode.class`

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PredicatePushDown.java (hunk 5 above)
Comment (losipiuk) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PredicatePushDown.java]: I tried that but it gets awkward:
* you have to pass weird `boolean allowNonDeterministicPushDownToLeftSide` parameter to `processInnerJoin`
* you have to split `InnerJoinPushDownResult.getJoinPredicate` into actual join predicate and post-join predicate to be put within `FilterNode` above `SemiJoinNode`. The `InnerJoinPushDownResult.postJoinPredicate` is always TRUE as InnerJoin handles non-equality filter expressions internally.

IMO it does not get more readable. And you do not save many lines of code.

I captured the work in progress in https://github.com/losipiuk/presto/commit/7c8ffa09d4fe6c19480a210a352421fc56373d92

File: presto-main/src/test/java/com/facebook/presto/sql/planner/TestPredicatePushdown.java (hunk 2 above)
Comment (losipiuk) [reply presto-main/src/test/java/com/facebook/presto/sql/planner/TestPredicatePushdown.java]: Extended a bit.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PredicatePushDown.java [hunk 9]
```diff
@@ -837,6 +845,93 @@ public PlanNode visitSemiJoin(SemiJoinNode node, RewriteContext<Expression> cont
...
+                }
+                else {
+                    postJoinConjuncts.add(conjunct);
+                }
+            }
+
+            // Push inheritedPredicates down to the filtering source if possible
+            for (Expression conjunct : EqualityInference.nonInferrableConjuncts(deterministicInheritedPredicate)) {
+                Expression rewrittenConjunct = allInference.rewriteExpression(conjunct, in(filteringSourceSymbols));
+                // TODO can we push non-deterministic conjuncts there (not doing it for now)
```
Comment (findepi) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PredicatePushDown.java]: `can we ..` -- if this is supposed to be question, put `?` or `¿` somewhere

Comment (sopel39) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PredicatePushDown.java]: most likely we can't

File: presto-main/src/test/java/com/facebook/presto/sql/planner/TestPredicatePushdown.java [hunk 10]
```diff
@@ -60,4 +63,142 @@ public void testPushDownToLhsOfSemiJoin()
...
+                                                        "LINE_QUANTITY", "quantity")))),
+                                node(ExchangeNode.class, // NO filter here
+                                        project(
+                                                tableScan("orders", ImmutableMap.of("ORDERS_ORDER_KEY", "orderkey")))))));
+    }
+
+    @Test
+    public void testPredicateFromFilterSideNotPropagatesToSourceSideOfSemiJoinUsedInProjection()
+    {
+        assertPlan("SELECT orderkey IN (SELECT orderkey FROM orders WHERE orderkey > 2) FROM lineitem",
```
Comment (sopel39) [inline presto-main/src/test/java/com/facebook/presto/sql/planner/TestPredicatePushdown.java]: add test with `...IN (SELECT orderkey FROM orders WHERE orderkey = 2)...`
and also maybe with:
```
`...IN (SELECT orderkey FROM orders WHERE orderkey = random(5)...`
```

Comment (losipiuk) [reply presto-main/src/test/java/com/facebook/presto/sql/planner/TestPredicatePushdown.java]: > add test with `...IN (SELECT orderkey FROM orders WHERE orderkey = 2)...`

There is test like this: `testEqualsPredicateFromFilterSidePropagatesToSourceSideOfSemiJoin`
It uses `SELECT quantity FROM (SELECT * FROM lineitem WHERE orderkey IN (SELECT orderkey FROM orders WHERE orderkey = 2))` query

> `...IN (SELECT orderkey FROM orders WHERE orderkey = random(5)...`

added

**Comment by losipiuk** [comment]
> would be interesting to benchmark perf difference

Between what and what ? :)

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PredicatePushDown.java (hunk 9 above)
Comment (kokosing) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PredicatePushDown.java]: So if we aren't sure about this, lets not leave this fuzzy TODO in the code to not to confuse people. Lets create an issue about that instead.

Comment (losipiuk) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PredicatePushDown.java]: No longer there https://github.com/prestodb/presto/commit/a85a9768b450a481e65a5c3bb7b3ab551719498b

Comment (losipiuk) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PredicatePushDown.java]: No longer there https://github.com/prestodb/presto/commit/a85a9768b450a481e65a5c3bb7b3ab551719498b

**Comment by sopel39** [comment]
> Between what and what ? :)

TPCH/TPCDS (or just queries with IN) with/without this change. This will change baseline for our CBO benchmarks.

There are also TPCH/TPCDS queries with `NOT IN`. Would be great to support that too. However it seems much harder. Probably we could use dynamic filter for that:
```
NOT dynamic_filter(source_sym, dynamic_filter_sym) OR source_sym is null
```

**Comment by kokosing** [comment]
We could leverage the tool of comparing join ordering, to compare plans and see how many plans of TPCH/TPCDS have changed with this change. I checked the join ordering and nothing changed ;/

**Comment by losipiuk** [comment]
> I checked the join ordering and nothing changed ;/

It does not mean it did not change any of the plans (but I do not know if it did) :)

**Comment by losipiuk** [comment]
> TPCH/TPCDS (or just queries with IN) with/without this change. This will change baseline for our CBO benchmarks.

I do not see it as a blocker for merging this. We can do benchmarks as followup.

> There are also TPCH/TPCDS queries with NOT IN. Would be great to support that too. However it seems much harder. Probably we could use dynamic filter for that and pushdown: `NOT dynamic_filter(source_sym, dynamic_filter_sym) OR source_sym IS NULL`

Possibly - I would need more clarification on your thought here. Could you capture it as a ticket?
