### PR TITLE
Prune unreferenced outputs before correlated IN

### LINKED ISSUE #8165: Test failure due to correlated subquery in IN predicate
TestRedisDistributedHash.testCorrelatedInPredicateSubqueries fails with the following error:

```
java.lang.AssertionError: Execution of 'actual' query failed: SELECT orderkey, clerk IN (SELECT clerk FROM orders s WHERE s.custkey = o.custkey AND s.orderkey < o.orderkey) FROM orders o

	at org.testng.Assert.fail(Assert.java:83)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:86)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:117)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:112)
	at com.facebook.presto.tests.AbstractTestQueries.testCorrelatedInPredicateSubqueries(AbstractTestQueries.java:7166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
Caused by: java.lang.IllegalStateException: No mapping for column handle RedisColumnHandle{connectorId=redis, ordinalPosition=0, name=redis_key, type=varchar(64), mapping=null, dataFormat=null, formatHint=null, keyDecoder=true, hidden=true, internal=false}!
	at com.google.common.base.Preconditions.checkState(Preconditions.java:518)
	at com.facebook.presto.redis.decoder.hash.HashRedisRowDecoder.decodeRow(HashRedisRowDecoder.java:58)
	at com.facebook.presto.redis.RedisRecordCursor.nextRow(RedisRecordCursor.java:184)
	at com.facebook.presto.redis.RedisRecordCursor.advanceNextPosition(RedisRecordCursor.java:147)
	at com.facebook.presto.spi.RecordPageSource.getNextPage(RecordPageSource.java:99)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:262)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:303)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:537)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:229)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:623)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

This seems to be a regression introduced in 98faf69c110b0f7e51b79924fa06aef9ae345a6e

### PR DESCRIPTION
**Pull request by findepi**
Fixes #8165

### CODE REVIEW

**Comment by martint** [comment]
Some unit tests broke. E.g., TestReorderWindows:


```
- anyTree
    - node(WindowNode)
        WindowMatcher{specification=SpecificationProvider{partitionBy=[SUPPKEY], orderBy=[SHIPDATE], orderings={SHIPDATE=ASC_NULLS_LAST}}}
        bind Optional.empty -> min (TAX) 
        - node(WindowNode)
            WindowMatcher{specification=SpecificationProvider{partitionBy=[SUPPKEY], orderBy=[ORDERKEY], orderings={ORDERKEY=ASC_NULLS_LAST}}}
            bind Optional.empty -> sum (QUANTITY) 
            - anyTree
                - node(WindowNode)
                    WindowMatcher{specification=SpecificationProvider{partitionBy=[PARTKEY], orderBy=[RECEIPTDATE], orderings={RECEIPTDATE=ASC_NULLS_LAST}}}
                    bind Optional.empty -> avg (DISCOUNT) 
                    - anyTree
                        - node(TableScanNode)
                            TableScanMatcher{expectedTableName=lineitem}
                            bind Optional[DISCOUNT] -> Column lineitem:discount
                            bind Optional[ORDERKEY] -> Column lineitem:orderkey
                            bind Optional[QUANTITY] -> Column lineitem:quantity
                            bind Optional[PARTKEY] -> Column lineitem:partkey
                            bind Optional[RECEIPTDATE] -> Column lineitem:receiptdate
                            bind Optional[SHIPDATE] -> Column lineitem:shipdate
                            bind Optional[SUPPKEY] -> Column lineitem:suppkey
                            bind Optional[TAX] -> Column lineitem:tax

] but found [

- Output[sum_quantity_A, avg_discount_B, min_tax_A] => [sum:double, avg:double, min:double]
        Cost: {rows: ?, bytes: ?}
        sum_quantity_A := sum
        avg_discount_B := avg
        min_tax_A := min
    - Project[] => [sum:double, avg:double, min:double]
            Cost: {rows: ?, bytes: ?}
        - Window[partition by (suppkey), order by (shipdate ASC_NULLS_LAST)][$hashvalue_24] => [suppkey:bigint, tax:double, shipdate:date, sum:double, avg:double, $hashvalue_24:bigint, min:double]
                Cost: {rows: ?, bytes: ?}
                min := min("tax") 
            - Project[] => [suppkey:bigint, tax:double, shipdate:date, sum:double, avg:double, $hashvalue_24:bigint]
                    Cost: {rows: ?, bytes: ?}
                    $hashvalue_24 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("suppkey"), 0))
                - Window[partition by (partkey), order by (receiptdate ASC_NULLS_LAST)][$hashvalue_23] => [partkey:bigint, suppkey:bigint, discount:double, tax:double, shipdate:date, receiptdate:date, sum:double, $hashvalue_23:bigint, avg:double]
                        Cost: {rows: ?, bytes: ?}
                        avg := avg("discount") 
                    - Project[] => [partkey:bigint, suppkey:bigint, discount:double, tax:double, shipdate:date, receiptdate:date, sum:double, $hashvalue_23:bigint]
                            Cost: {rows: ?, bytes: ?}
                        - Project[] => [partkey:bigint, suppkey:bigint, discount:double, tax:double, shipdate:date, receiptdate:date, sum:double, $hashvalue:bigint, $hashvalue_23:bigint]
                                Cost: {rows: ?, bytes: ?}
                                $hashvalue_23 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("partkey"), 0))
                            - Window[partition by (suppkey), order by (orderkey ASC_NULLS_LAST)][$hashvalue] => [orderkey:bigint, partkey:bigint, suppkey:bigint, quantity:double, discount:double, tax:double, shipdate:date, receiptdate:date, $hashvalue:bigint, sum:double]
                                    Cost: {rows: ?, bytes: ?}
                                    sum := sum("quantity") 
                                - Project[] => [orderkey:bigint, partkey:bigint, suppkey:bigint, quantity:double, discount:double, tax:double, shipdate:date, receiptdate:date, $hashvalue:bigint]
                                        Cost: {rows: 60000, bytes: ?}
                                    - LocalExchange[SINGLE] () => orderkey:bigint, partkey:bigint, suppkey:bigint, quantity:double, discount:double, tax:double, shipdate:date, receiptdate:date, $hashvalue:bigint, $hashvalue_20:bigint
                                            Cost: {rows: 60000, bytes: ?}
                                        - ScanProject[table = local:tpch:lineitem:sf0.01, originalConstraint = true] => [orderkey:bigint, partkey:bigint, suppkey:bigint, quantity:double, discount:double, tax:double, shipdate:date, receiptdate:date, $hashvalue_21:bigint, $hashvalue_22:bigint]
                                                Cost: {rows: 60000, bytes: ?}/{rows: 60000, bytes: ?}
                                                $hashvalue_21 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("suppkey"), 0))
                                                $hashvalue_22 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("partkey"), 0))
                                                orderkey := tpch:orderkey
                                                partkey := tpch:partkey
                                                suppkey := tpch:suppkey
                                                quantity := tpch:quantity
                                                discount := tpch:discount
                                                tax := tpch:tax
                                                shipdate := tpch:shipdate
                                                receiptdate := tpch:receiptdate

] which resolves to [

- Output[sum_quantity_A, avg_discount_B, min_tax_A] => [sum:double, avg:double, min:double]
        Cost: {rows: ?, bytes: ?}
        sum_quantity_A := sum
        avg_discount_B := avg
        min_tax_A := min
    - Project[] => [sum:double, avg:double, min:double]
            Cost: {rows: ?, bytes: ?}
        - Window[partition by (suppkey), order by (shipdate ASC_NULLS_LAST)][$hashvalue_24] => [suppkey:bigint, tax:double, shipdate:date, sum:double, avg:double, $hashvalue_24:bigint, min:double]
                Cost: {rows: ?, bytes: ?}
                min := min("tax") 
            - Project[] => [suppkey:bigint, tax:double, shipdate:date, sum:double, avg:double, $hashvalue_24:bigint]
                    Cost: {rows: ?, bytes: ?}
                    $hashvalue_24 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("suppkey"), 0))
                - Window[partition by (partkey), order by (receiptdate ASC_NULLS_LAST)][$hashvalue_23] => [partkey:bigint, suppkey:bigint, discount:double, tax:double, shipdate:date, receiptdate:date, sum:double, $hashvalue_23:bigint, avg:double]
                        Cost: {rows: ?, bytes: ?}
                        avg := avg("discount") 
                    - Project[] => [partkey:bigint, suppkey:bigint, discount:double, tax:double, shipdate:date, receiptdate:date, sum:double, $hashvalue_23:bigint]
                            Cost: {rows: ?, bytes: ?}
                        - Project[] => [partkey:bigint, suppkey:bigint, discount:double, tax:double, shipdate:date, receiptdate:date, sum:double, $hashvalue:bigint, $hashvalue_23:bigint]
                                Cost: {rows: ?, bytes: ?}
                                $hashvalue_23 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("partkey"), 0))
                            - Window[partition by (suppkey), order by (orderkey ASC_NULLS_LAST)][$hashvalue] => [orderkey:bigint, partkey:bigint, suppkey:bigint, quantity:double, discount:double, tax:double, shipdate:date, receiptdate:date, $hashvalue:bigint, sum:double]
                                    Cost: {rows: ?, bytes: ?}
                                    sum := sum("quantity") 
                                - Project[] => [orderkey:bigint, partkey:bigint, suppkey:bigint, quantity:double, discount:double, tax:double, shipdate:date, receiptdate:date, $hashvalue:bigint]
                                        Cost: {rows: 60000, bytes: ?}
                                    - LocalExchange[SINGLE] () => orderkey:bigint, partkey:bigint, suppkey:bigint, quantity:double, discount:double, tax:double, shipdate:date, receiptdate:date, $hashvalue:bigint, $hashvalue_20:bigint
                                            Cost: {rows: 60000, bytes: ?}
                                        - ScanProject[table = local:tpch:lineitem:sf0.01, originalConstraint = true] => [orderkey:bigint, partkey:bigint, suppkey:bigint, quantity:double, discount:double, tax:double, shipdate:date, receiptdate:date, $hashvalue_21:bigint, $hashvalue_22:bigint]
                                                Cost: {rows: 60000, bytes: ?}/{rows: 60000, bytes: ?}
                                                $hashvalue_21 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("suppkey"), 0))
                                                $hashvalue_22 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("partkey"), 0))
                                                orderkey := tpch:orderkey
                                                partkey := tpch:partkey
                                                suppkey := tpch:suppkey
                                                quantity := tpch:quantity
                                                discount := tpch:discount
                                                tax := tpch:tax
                                                shipdate := tpch:shipdate
                                                receiptdate := tpch:receiptdate

] <Click to see difference>


	at com.facebook.presto.sql.planner.assertions.PlanAssert.assertPlan(PlanAssert.java:43)
	at com.facebook.presto.sql.planner.assertions.PlanAssert.assertPlan(PlanAssert.java:33)
	at com.facebook.presto.sql.planner.assertions.BasePlanTest.lambda$assertPlan$1(BasePlanTest.java:96)
	at com.facebook.presto.transaction.TransactionBuilder.execute(TransactionBuilder.java:150)
	at com.facebook.presto.testing.LocalQueryRunner.inTransaction(LocalQueryRunner.java:512)
	at com.facebook.presto.testing.LocalQueryRunner.inTransaction(LocalQueryRunner.java:505)
	at com.facebook.presto.sql.planner.assertions.BasePlanTest.assertPlan(BasePlanTest.java:94)
	at com.facebook.presto.sql.planner.assertions.BasePlanTest.assertPlan(BasePlanTest.java:89)
	at com.facebook.presto.sql.planner.optimizations.TestReorderWindows.testNonMergeableABAReordersToAABAllOptimizers(TestReorderWindows.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
```

File: presto-main/src/main/java/com/facebook/presto/sql/planner/PlanOptimizers.java [hunk 1]
```diff
@@ -167,10 +167,7 @@ public PlanOptimizers(Metadata metadata, SqlParser sqlParser, FeaturesConfig fea
                 new UnaliasSymbolReferences(),
                 new IterativeOptimizer(
                         stats,
-                        ImmutableSet.of(
-                                new RemoveRedundantIdentityProjections(),
-                                new TransformCorrelatedInPredicateToJoin(),
-                                new ImplementFilteredAggregations())
+                        ImmutableSet.of(new RemoveRedundantIdentityProjections())
```
Comment (findepi) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/PlanOptimizers.java]: @martint , When i was adding correlated IN, i added my rules to existing `RemoveRedundantIdentityProjections`. You can view this as revert+add the rules in a better place.

**Comment by findepi** [comment]
@martint, I messed with order of optimizers. Now the test is passing
