### PR TITLE
Use Java 8 Time API for sql datetime types

### LINKED ISSUE #5057: Date constructor should handle year 0 correctly
Year zero is converted to January 2nd of 1 AD:

```
presto> select date '0000-12-31';
   _col0    
------------
 0001-01-02 
(1 row)
```

It should be rejected, similar to other invalid dates:
```
presto> select date '2015-02-29';
Query ... failed: Value cannot be cast to date: 2015-02-29

presto> select date '2016-12-32';
Query ... failed: Value cannot be cast to date: 2016-12-32

### PR DESCRIPTION
**Pull request by geraint0923**
Use Java 8 Time APT for SqlDate, SqlTime, SqlTimeWithTimeZone,
SqlTimestamp, and SqlTimestampWithTimeZone.

This will fix #5057

### CODE REVIEW

**Comment by electrum** [comment]
This needs tests which cover the changed behavior for old dates.

**Comment by geraint0923** [comment]
@electrum I will add the tests soon.

File: presto-spi/src/main/java/com/facebook/presto/spi/type/SqlTimestamp.java [hunk 1]
```diff
@@ -66,8 +66,7 @@ public boolean equals(Object obj)
     @Override
     public String toString()
     {
-        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");
-        format.setTimeZone(getTimeZoneForKey(sessionTimeZoneKey));
-        return format.format(new Date(millisUtc));
+        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.SSS");
+        return ZonedDateTime.ofInstant(Instant.ofEpochMilli(millisUtc), ZoneId.of(sessionTimeZoneKey.getId())).format(formatter);
```
Comment (haozhun) [inline presto-spi/src/main/java/com/facebook/presto/spi/type/SqlTimestamp.java]: `Instant.ofEpochMilli(...).atZone(...)` instead of `ZonedDateTime.ofInstant(Instant.ofEpochMilli(...), ...)`

File: presto-spi/src/main/java/com/facebook/presto/spi/type/SqlTimestampWithTimeZone.java [hunk 2]
```diff
@@ -81,8 +82,7 @@ public boolean equals(Object obj)
     @Override
     public String toString()
     {
-        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");
-        format.setTimeZone(getTimeZoneForKey(timeZoneKey));
-        return format.format(new Date(millisUtc)) + " " + timeZoneKey.getId();
+        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.SSS VV");
+        return ZonedDateTime.ofInstant(Instant.ofEpochMilli(millisUtc), ZoneId.of(timeZoneKey.getId())).format(formatter);
```
Comment (haozhun) [inline presto-spi/src/main/java/com/facebook/presto/spi/type/SqlTimestampWithTimeZone.java]: `Instant.ofEpochMilli(...).atZone(...)` instead of `ZonedDateTime.ofInstant(Instant.ofEpochMilli(...), ...)`

File: presto-spi/src/main/java/com/facebook/presto/spi/type/SqlDate.java [hunk 3]
```diff
@@ -60,8 +57,6 @@ public boolean equals(Object obj)
     @Override
     public String toString()
     {
-        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
-        format.setTimeZone(getTimeZoneForKey(UTC_KEY));
-        return format.format(new Date(TimeUnit.DAYS.toMillis(days)));
+        return LocalDate.ofEpochDay(days).format(DateTimeFormatter.ofPattern("YYYY-MM-dd").withZone(ZoneId.of("UTC")));
```
Comment (haozhun) [inline presto-spi/src/main/java/com/facebook/presto/spi/type/SqlDate.java]: Calling `withZone` when formatting a temporal object that does not contain an instant is no-op unless you are printing out the offset. Quote from java doc:

> If the temporal object does not contain an instant, but does contain an offset then an additional check is made. If the normalized override zone is an offset that differs from the offset of the temporal, then a DateTimeException is thrown. In all other cases, the override zone is added to the temporal, replacing any previous zone, but without changing the date/time.

Comment (haozhun) [inline presto-spi/src/main/java/com/facebook/presto/spi/type/SqlDate.java]: `toString` suffices in this case. You don't need a formatter.

File: presto-spi/src/main/java/com/facebook/presto/spi/type/SqlTimestamp.java (hunk 1 above)
Comment (haozhun) [inline presto-spi/src/main/java/com/facebook/presto/spi/type/SqlTimestamp.java]: Initialize the `formatter` statically.

File: presto-spi/src/main/java/com/facebook/presto/spi/type/SqlTimestampWithTimeZone.java (hunk 2 above)
Comment (haozhun) [inline presto-spi/src/main/java/com/facebook/presto/spi/type/SqlTimestampWithTimeZone.java]: Initialize the `formatter` statically.

**Comment by geraint0923** [comment]
@haozhun Addressed your comments and add tests.

Since the existing `assert` methods will convert the results to  Java Sql `Date`, `DateTime` when doing comparison or directly compare the internal millisecond or days which will not invoke the modified `toString` function, I add one method to force to invoke `toString` when comparing the results.

File: presto-main/src/test/java/com/facebook/presto/operator/scalar/TestDateTimeFunctions.java [hunk 4]
```diff
@@ -820,11 +820,51 @@ public void testLocale()
                 toTimestampWithTimeZone(new DateTime(2013, 5, 17, 0, 35, 10, 0, DATE_TIME_ZONE)));
     }
 
+    @Test
+    public void testDateTimeOutputString()
+    {
+        // SqlDate
+        assertFunctionString("date '2012-12-31'", DateType.DATE, "2012-12-31");
```
Comment (haozhun) [inline presto-main/src/test/java/com/facebook/presto/operator/scalar/TestDateTimeFunctions.java]: static import

File: presto-main/src/test/java/com/facebook/presto/operator/scalar/TestDateTimeFunctions.java [hunk 5]
```diff
@@ -820,11 +820,51 @@ public void testLocale()
...
+        assertFunctionString("date '0000-12-31'", DateType.DATE, "0000-12-31");
+        assertFunctionString("date '0000-09-23'", DateType.DATE, "0000-09-23");
+        assertFunctionString("date '0001-10-25'", DateType.DATE, "0001-10-25");
+        assertFunctionString("date '1560-04-29'", DateType.DATE, "1560-04-29");
+
+        // SqlTime
+        assertFunctionString("time '00:00:00'", TimeType.TIME, "00:00:00.000");
```
Comment (haozhun) [inline presto-main/src/test/java/com/facebook/presto/operator/scalar/TestDateTimeFunctions.java]: static import

File: presto-main/src/test/java/com/facebook/presto/operator/scalar/TestDateTimeFunctions.java [hunk 6]
```diff
@@ -820,11 +820,51 @@ public void testLocale()
...
+        assertFunctionString("time '23:59:59.999'", TimeType.TIME, "23:59:59.999");
+
+        // SqlTimeWithTimeZone
+        assertFunctionString("time '00:00:00 UTC'", TIME_WITH_TIME_ZONE, "00:00:00.000 UTC");
+        assertFunctionString("time '01:02:03 Asia/Shanghai'", TIME_WITH_TIME_ZONE, "01:02:03.000 Asia/Shanghai");
+        assertFunctionString("time '23:23:23.233 America/Los_Angeles'", TIME_WITH_TIME_ZONE, "23:23:23.233 America/Los_Angeles");
+        assertFunctionString(WEIRD_TIME_LITERAL, TIME_WITH_TIME_ZONE, "03:04:05.321 +07:09");
+
+        // SqlTimestamp
+        assertFunctionString("timestamp '0000-01-02 01:02:03'", TimestampType.TIMESTAMP, "0000-01-02 01:02:03.000");
```
Comment (haozhun) [inline presto-main/src/test/java/com/facebook/presto/operator/scalar/TestDateTimeFunctions.java]: static import

File: presto-main/src/test/java/com/facebook/presto/operator/scalar/TestDateTimeFunctions.java (hunk 4 above)
Comment (geraint0923) [inline presto-main/src/test/java/com/facebook/presto/operator/scalar/TestDateTimeFunctions.java]: There have been some `static final` variables having the same names as `TIME`, `TIMESTAMP`, and `DATE`.

**Comment by haozhun** [comment]
Commit message should say something like "Fix toString for sql datetime types" instead.

Make sure your tests pass when they are run in a negative time zone as well.

Otherwise looks good.
