### PR TITLE
Fix cte filter pushdown wrong results by splitting SpecialFormExpressions

### LINKED ISSUE #22147: Incorrect results after CteCommonFilterPushdown due to trimmed filters
During our verifier tests, i observed a bug where filters added by the CteProjectionAndFilterPushdownRule got trimmed. In the cte producer tree, we had filter  `"(x = a) OR (x = b) OR (x = c) OR (x = d)"`   pushed down by the `CteProjectionAndFilterPushdownRule` and presto after this rule converted this to `(x = a) OR (x = b) ` dropping `(x = c ) OR (x = d)` 
In our production the filters got dropped in `filterRowExpressionRewriteRule` rule, here in the repro in the `PredicatePushDown` rule

## Your Environment

* Presto version used:
* Storage (HDFS/S3/GCS..):
* Data source and connector used:
* Deployment (Cloud or On-prem):
* [Pastebin](https://pastebin.com/) link to the complete debug logs:

## Possible Solution
This seems to be a major issue in Presto itself maybe predicate pushdown rule and not the ctePushdownRule rule since the ctePushdownRule rule properly applied the filter.

## Steps to Reproduce

Could repro using this test case, 

Unit test in TestCteExecution, it will fail with Results mismatch.

`Expected 1024 rows got 52 rows expected [1024] but found [52]`
```
@Test
    public void testCommonFilterPushdown()
    {
        QueryRunner queryRunner = getQueryRunner();
        String test1 = "WITH order_platform_data AS (\n" +
                "  SELECT\n" +
                "    o.orderkey AS order_key,\n" +
                "    o.orderdate AS datestr,\n" +
                "    o.orderpriority AS event_type\n" +
                "  FROM\n" +
                "    orders o\n" +
                "  WHERE\n" +
                "    o.orderdate BETWEEN DATE '1995-01-01' AND DATE '1995-01-31'\n" +
                "    AND o.orderpriority IN ('1-URGENT', '3-MEDIUM')\n" +
                "  UNION ALL\n" +
                "  SELECT\n" +
                "    l.orderkey AS order_key,\n" +
                "    o.orderdate AS datestr,\n" +
                "    o.orderpriority AS event_type\n" +
                "  FROM\n" +
                "    lineitem l\n" +
                "    JOIN orders o ON l.orderkey = o.orderkey\n" +
                "  WHERE\n" +
                "    o.orderdate BETWEEN DATE '1995-01-01' AND DATE '1995-01-31'\n" +
                "    AND o.orderpriority IN ('2-HIGH', '5-LOW')\n" +
                "),\n" +
                "urgent AS (\n" +
                "    SELECT order_key, datestr\n" +
                "    FROM order_platform_data\n" +
                "    WHERE event_type = '1-URGENT'\n" +
                "),\n" +
                "medium AS (\n" +
                "    SELECT order_key, datestr\n" +
                "    FROM order_platform_data\n" +
                "    WHERE event_type = '3-MEDIUM'\n" +
                "),\n" +
                "high AS (\n" +
                "    SELECT order_key, datestr\n" +
                "    FROM order_platform_data\n" +
                "    WHERE event_type = '2-HIGH'\n" +
                "),\n" +
                "low AS (\n" +
                "    SELECT order_key, datestr\n" +
                "    FROM order_platform_data\n" +
                "    WHERE event_type = '5-LOW'\n" +
                ")\n" +
                "SELECT\n" +
                "    ofin.order_key AS order_key,\n" +
                "    ofin.datestr AS order_date\n" +
                " FROM " +
                "    urgent ofin\n" +
                "    LEFT JOIN medium oproc ON ofin.datestr = oproc.datestr\n" +
                "   LEFT JOIN low on oproc.datestr = low.datestr" +
                "  LEFT JOIN high on low.datestr = high.datestr" +
                " ORDER BY\n" +
                "    ofin.order_key\n";
        ;
        compareResults(queryRunner.execute(Session.builder(super.getSession())
                                .setSystemProperty(PUSHDOWN_SUBFIELDS_ENABLED, "true")
                                .setSystemProperty(CTE_MATERIALIZATION_STRATEGY, "HEURISTIC_COMPLEX_QUERIES_ONLY")
                                .setSystemProperty(CTE_FILTER_AND_PROJECTION_PUSHDOWN_ENABLED, "true")
                                .setSystemProperty(VERBOSE_OPTIMIZER_RESULTS, "ALL")
                                .setSystemProperty(VERBOSE_OPTIMIZER_INFO_ENABLED, "true")
                                .build(),
                        test1),
                queryRunner.execute(getSession(),
                        test1));
    }
```

## Context

The filter  - `Filter[PlanNodeId 2162][filterPredicate = ((expr_32) = (VARCHAR'1-URGENT')) OR ((expr_32) = (VARCHAR'3-MEDIUM')) OR ((expr_32) = (VARCHAR'5-LOW')) OR ((expr_32) = (VARCHAR'2-HIGH'))] => [expr_30:bigint, expr_31:date, expr_32:varchar(15)]` got trimmed.

### PR DESCRIPTION
**Pull request by jaystarshot**
## Description

Fixes #22147. This is needed  due to a bug in SpecialFormExpressions #22698 if > 2 conditions are used.
Also simplified the extra filters so that predicatePushdown optimizer could push down the conditions further 

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* Fix wrong results when queries using materialized CTEs have multiple common filters pushed into the CTE :pr:`22700 `

```

### CODE REVIEW

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/CteProjectionAndPredicatePushDown.java [hunk 1]
```diff
@@ -370,14 +370,21 @@ private PlanNode addFilter(PlanNode node, List<RowExpression> predicates)
...
+                resultPredicate = predicates.get(0);
+                for (int i = 1; i < predicates.size(); i++) {
+                    resultPredicate = new SpecialFormExpression(
+                            SpecialFormExpression.Form.OR,
+                            BOOLEAN,
+                            resultPredicate, predicates.get(i));
+                }
             }
-            return new FilterNode(node.getSourceLocation(), idAllocator.getNextId(), node, predicate);
+            resultPredicate = SimplifyRowExpressions.rewrite(resultPredicate, metadata, session.toConnectorSession());
```
Comment (jaystarshot) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/CteProjectionAndPredicatePushDown.java:386]: Simplifying the **or** conditions is essential and I observed a case in prod where it helped these filters pushed further down in predicatePushdown rule

**Review by feilong-liu — APPROVED** [review]

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/CteProjectionAndPredicatePushDown.java (hunk 1 above)
Comment (feilong-liu) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/CteProjectionAndPredicatePushDown.java:386]: Curious what does this simplify do? Is it to rebalance multiple OR condition?

Comment (jaystarshot) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/CteProjectionAndPredicatePushDown.java:386]: Yeah looks like it breaks down the multiple ors into efficient cnf and dnf forms. In the predicate pushdown optimizer, the current visitJoin method appears to only decompose projects when they are pre broken by this optimizer. 
I've noticed instances where 'or' conditions were not pushed down beneath joins.

**Comment by steveburnett** [comment]
Just a nit, suggest release note entry revision.

```
== RELEASE NOTES ==

General Changes
* Fix a bug in common filter pushdown when using CTE materialization :pr:`22700 `
```

**Comment by rschlussel** [comment]
The release notes should mention that it's a wrong results fix and a bit more user facing.  e.g. maybe something like

* Fix wrong results when queries using materialized CTEs have multiple common filters pushed into the CTE

**Review by rschlussel — APPROVED** [review]

**Comment by rschlussel** [comment]
Can be separate but we should add argument checks when creating special form expressions that they have the right number of arguments.
