### PR TITLE
[native] Fix planning of queries with duplicate output columns

### LINKED ISSUE #19399: [Presto-on-Spark Native] Join query fails with Multiple entries with same key: orderkey=9 and orderkey=0
A join query that returns duplicate column names fails:

```
SELECT * FROM orders o, lineitem l WHERE o.orderkey = l.orderkey;

Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: orderkey=9 and orderkey=0
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215)
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:209)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:147)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:110)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:393)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$CustomPlanTranslator.makeLayoutFromOutputVariables(LocalExecutionPlanner.java:886)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$CustomPlanTranslator.makeLayout(LocalExecutionPlanner.java:875)
	at com.facebook.presto.spark.execution.operator.NativeExecutionOperator$NativeExecutionOperatorTranslator.translate(NativeExecutionOperator.java:408)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitPlan(LocalExecutionPlanner.java:3123)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitPlan(LocalExecutionPlanner.java:900)
```

The "duplicate" column is "orderkey" present in both lineitem and orders.

CC: @rschlussel @miaoever @shrinidhijoshi

### PR DESCRIPTION
**Pull request by mbasmanova**
Fix "Multiple entries with same key: orderkey=9 and orderkey=0" when planning
join query with duplicate output columns:

```
SELECT * FROM orders o, lineitem l WHERE o.orderkey = l.orderkey
```

Fixes #19399

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by rschlussel** [comment]
Won't the result now be missing columns?

**Comment by mbasmanova** [comment]
@rschlussel Rebecca, thank you for review.

> Won't the result now be missing columns?

I don't think so. The output is handled separately by looking at partitioningScheme.

```
        PartitioningScheme partitioningScheme = planFragment.getPartitioningScheme();
        List<VariableReferenceExpression> outputLayout = partitioningScheme.getOutputLayout();
```

Notice that OutputNode is skipped in LocalExecutionPlanner:

```
        @Override
        public PhysicalOperation visitOutput(OutputNode node, LocalExecutionPlanContext context)
        {
            return node.getSource().accept(this, context);
        }
```

**Comment by rschlussel** [comment]
Thanks, I see now.  The output node isn't used for execution on the workers at all.  It's used on the coordinator SqlQueryExecution for setting the column names and that's about it.  I assume it's the same in cpp and prestissimo doesn't really need it either.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/BasePlanFragmenter.java [hunk 1]
```diff
@@ -181,6 +181,27 @@ private SubPlan buildFragment(PlanNode root, FragmentProperties properties, Plan
 
         // Only delegate non-coordinatorOnly plan fragment to native engine
         if (isNativeExecutionEnabled(session) && !properties.getPartitioningHandle().isCoordinatorOnly()) {
+            if (root instanceof OutputNode) {
+                // OutputNode is special in that it can have duplicate output variables. Regular plan nodes,
```
Comment (rschlussel) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/BasePlanFragmenter.java:185]: can you add to this comment that the OutputNode variables aren't really used, to explain why it's okay for correctness.  Also maybe note why OutputNodes are special (as i understand, it's the PhysicalOperations that can't have duplicates, and OutputNode doesn't get translated to a PhysicalOperation, but NativeExecutionNode does).

**Review by rschlussel — COMMENTED** [review]
I wonder if it would be better to add a fix not to produce duplicate output variables closer to where we need it -  i.e. where we do the translation from NativeExecutionNode to physical operation https://github.com/prestodb/presto/blob/master/presto-spark-base/src/main/java/com/facebook/presto/spark/execution/operator/NativeExecutionOperator.java#L408.

**Comment by mbasmanova** [comment]
> I wonder if it would be better to add a fix not to produce duplicate output variables closer to where we need it - i.e. where we do the translation from NativeExecutionNode to physical operation

The original error happen a bit earlier, hence, we'd need to make the change in 2 places. It seems to me that single place is better.

```
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: orderkey=9 and orderkey=0
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215)
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:209)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:147)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:110)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:393)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$CustomPlanTranslator.makeLayoutFromOutputVariables(LocalExecutionPlanner.java:886)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$CustomPlanTranslator.makeLayout(LocalExecutionPlanner.java:875)
	at com.facebook.presto.spark.execution.operator.NativeExecutionOperator$NativeExecutionOperatorTranslator.translate(NativeExecutionOperator.java:408)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitPlan(LocalExecutionPlanner.java:3123)
```

File: presto-main/src/main/java/com/facebook/presto/sql/planner/BasePlanFragmenter.java (hunk 1 above)
Comment (mbasmanova) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/BasePlanFragmenter.java:185]: @rschlussel Rebecca, I tried expanding the comment, but couldn't figure out wording that would make sense. Here is what I have now:

```
                // OutputNode is special in that it can have duplicate output variables. Regular plan nodes,
                // including NativeExecutionNode, must have unique output variables.
                // Check if OutputNode has duplicate output variables and remove these.
```

Any chance you could suggest a specific edit?

Comment (rschlussel) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/BasePlanFragmenter.java:185]: What do you think of the below           
``` 
               // OutputNode is special in that it can have duplicate output variables since it
               // does not get converted to a PhysicalOperation for execution.
               // Regular plan nodes, including NativeExecutionNode, must have unique output variables.
               // Check if OutputNode has duplicate output variables and remove these.
               // This is safe because OutputNode variables will not be used by the workers.

```

**Comment by rschlussel** [comment]
> > I wonder if it would be better to add a fix not to produce duplicate output variables closer to where we need it - i.e. where we do the translation from NativeExecutionNode to physical operation
> 
> The original error happen a bit earlier, hence, we'd need to make the change in 2 places. It seems to me that single place is better.
> 
> ```
> Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: orderkey=9 and orderkey=0
> 	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215)
> 	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:209)
> 	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:147)
> 	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:110)
> 	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:393)
> 	at com.facebook.presto.sql.planner.LocalExecutionPlanner$CustomPlanTranslator.makeLayoutFromOutputVariables(LocalExecutionPlanner.java:886)
> 	at com.facebook.presto.sql.planner.LocalExecutionPlanner$CustomPlanTranslator.makeLayout(LocalExecutionPlanner.java:875)
> 	at com.facebook.presto.spark.execution.operator.NativeExecutionOperator$NativeExecutionOperatorTranslator.translate(NativeExecutionOperator.java:408)
> 	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitPlan(LocalExecutionPlanner.java:3123)
> ```

I think i was suggesting to make the change in NativeExecutionOperatorTranslator.translate(), which is in that stack trace, so I don't think it would need to be changed in two places.  But if you think the change is better here, that's fine too.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/BasePlanFragmenter.java (hunk 1 above)
Comment (mbasmanova) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/BasePlanFragmenter.java:185]: @rschlussel Thank you, Rebecca. Let me use that.

**Comment by mbasmanova** [comment]
@rschlussel 

> I think i was suggesting to make the change in NativeExecutionOperatorTranslator.translate(), which is in that stack trace, so I don't think it would need to be changed in two places. 

I see. I don't have a strong preference, but I feel it is cleaner to ensure that NativeExecutionNode doesn't have duplicate output variables as it does get converted into Physical operator for execution.

**Comment by mbasmanova** [comment]
@rschlussel Updated the comment.

**Review by rschlussel — APPROVED** [review]

**Review by amitkdutta — APPROVED** [review]
Looks good.
