### PR TITLE
Fix flaky testRuntimeOptimizedStagesCorrectness

### LINKED ISSUE #14882: Flaky testRuntimeOptimizedStagesCorrectness
```
[ERROR] Tests run: 2181, Failures: 1, Errors: 0, Skipped: 90, Time elapsed: 3,146.362 s <<< FAILURE! - in TestSuite
[ERROR] testRuntimeOptimizedStagesCorrectness(com.facebook.presto.hive.TestEventListenerWithExchangeMaterialization)  Time elapsed: 1.398 s  <<< FAILURE!
java.lang.AssertionError: expected [1] but found [0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.facebook.presto.hive.TestEventListenerWithExchangeMaterialization.testRuntimeOptimizedStagesCorrectness(TestEventListenerWithExchangeMaterialization.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### PR DESCRIPTION
**Pull request by pguofb**
Fixes #14882

Essentially, this PR let the `setUp()` function wait for up to 3min so that all warmup queries (tpch copying) will finish populating their `QueryCompletedEvent`. This will avoid warm-up query completed events get accidentally captured as that of our testing queries. Further, we add additional checks on the queryId of the testing query and the query id of the captured query completed event, and skip the test when in extreme cases (e.g. warmup query completed event is delayed over 3min) where the two ids do not match.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by pguofb** [comment]
The latest three builds after each push all passed this test suite, which further confirms it as a valid fix. @rschlussel if this fix looks good to you, it would be great if we can get this merged asap to unblock the release process on Monday as @mayankgarg1990 suggested.

File: presto-hive/src/test/java/com/facebook/presto/hive/TestEventListenerWithExchangeMaterialization.java [hunk 1]
```diff
@@ -101,58 +103,67 @@ public void testRuntimeOptimizedStagesCorrectness()
...
         runtimeOptimizedStages = queryRunner.getCoordinator().getQueryManager().getFullQueryInfo(new QueryId(queryCreatedEvent.getMetadata().getQueryId())).getRuntimeOptimizedStages();
 
-        assertEquals(queryMetadata.getRuntimeOptimizedStages().size(), 2);
-        assertEquals(ImmutableSet.copyOf(queryMetadata.getRuntimeOptimizedStages()), ImmutableSet.of("1", "4"));
-        assertTrue(runtimeOptimizedStages.isPresent());
-        assertEquals(runtimeOptimizedStages.get().size(), 2);
-        assertEquals(queryMetadata.getRuntimeOptimizedStages(), runtimeOptimizedStages.get().stream()
-                .map(stageId -> String.valueOf(stageId.getId()))
-                .collect(toImmutableList()));
+        if (queryMetadata.getQueryId().equals(queryId.toString())) {
```
Comment (rschlussel) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestEventListenerWithExchangeMaterialization.java:158]: I worry that this means at some point the test can break and we won't know it because we aren't doing any checks. Is this part necessary for fixing the flakiness?  Is there a way to wait for the correct event instead?

Comment (pguofb) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestEventListenerWithExchangeMaterialization.java:158]: No, this part is not essential, just for the super extreme case where after waiting 180 seconds, the previous queryCompletedEvent still have not reached.

Comment (rschlussel) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestEventListenerWithExchangeMaterialization.java:158]: great, can you remove this then? If there's still test flakiness after this, I'd rather add a loop to wait for the correct query id for a certain amount of time.

Comment (pguofb) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestEventListenerWithExchangeMaterialization.java:158]: But on the other hand, if the queryIds are different then there is no point to further run assertions because essentially we will be comparing two events from two different queries.

Comment (pguofb) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestEventListenerWithExchangeMaterialization.java:158]: Sure. I will remove this part.
