### PR TITLE
Fix flaky test of table registration in Nessie

### LINKED ISSUE #22848: IcebergDistributedSmokeTestBase.testRegisterTable is flaky
Error:  Failures: 
Error:    TestIcebergSmokeNessie>IcebergDistributedSmokeTestBase.testRegisterTable:1378->AbstractTestQueryFramework.assertQuery:164 For query: 
 SELECT * FROM register_new
not equal
Expected rows (1 of 1 missing rows shown, 1 rows in total):
    [1, 1]

Seen here https://github.com/prestodb/presto/actions/runs/9260568635/job/25474586005?pr=22843

### PR DESCRIPTION
**Pull request by hantangwangd**
## Description

Fix #22848 

The Previous logic of `getLocation(schema, table)` in `TestIcebergSmokeNessie` may be affected under concurrent execution of test methods, because it use `contains()` to match the first table name under the given schema. For example, if another test logic concurrently create table `register_insert` or `register_filename` in the same schema, the `getLocation(schemaName, 'register')` in `testRegisterTable()` may get the metadata location for table `register_insert` or `register_filename` rather than `register`.

This PR uses regex matching to avoid such cases, so it should most likely resolve the flaky test issue in #22848.

## Motivation and Context

Fix #22848 

## Impact

N/A

## Test Plan

N/A

## Contributor checklist

- [x] Please make sure your submission complies with our [contributing guide](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md), in particular [code style](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#code-style) and [commit standards](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#commit-standards).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [x] CI passed.

## Release Notes

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

File: presto-iceberg/src/test/java/com/facebook/presto/iceberg/IcebergDistributedSmokeTestBase.java [hunk 1]
```diff
@@ -1588,6 +1588,8 @@ public void testRegisterTable()
     {
         String schemaName = getSession().getSchema().get();
         String tableName = "register";
+        String noiseTableName = "register1";
+        assertUpdate("CREATE TABLE " + noiseTableName + " (id integer, value integer)");
```
Comment (kiersten-stokes) [inline presto-iceberg/src/test/java/com/facebook/presto/iceberg/IcebergDistributedSmokeTestBase.java:1592]: If leaving in, perhaps a comment about what the purpose of the noise table is doing would be good for future understanding

**Review by kiersten-stokes — DISMISSED** [review]
Very nice catch!! Makes it seem so obvious that this was the issue now that you've pointed it out 😄

File: presto-iceberg/src/test/java/com/facebook/presto/iceberg/IcebergDistributedSmokeTestBase.java (hunk 1 above)
Comment (hantangwangd) [reply presto-iceberg/src/test/java/com/facebook/presto/iceberg/IcebergDistributedSmokeTestBase.java:1593]: Sure, done. Please take a look when available, thanks.

**Review by tdcmeehan — APPROVED** [review]
