### PR TITLE
Fix #14693: support TRUNCATE function for DOUBLE and REAL

### LINKED ISSUE #14693: double/real truncation incorrect
Truncation of a decimal number leaves the precision as it was.
image

image

-------

Proposed Solution:
Fix in MathFunctions truncate(num,d) to drop double's precision digits after decimal point based on the value of d

### PR DESCRIPTION
**Pull request by fgwang7w**
== RELEASE NOTES ==
```
General Changes
```
The solution is to fix issue #14693 by adding an enhancement to TRUNCATE function for allowing DOUBLE and REAL types.
Following examples show how user may use this feature:<br>

`truncate(DOUBLE '1234.56', 1)` -> The outcome of the evaluation is `1234.5`<br>

`truncate(REAL '-12.333', -1)` -> The outcome of the evaluation is `-10.0`<br>

<br><br>
NOTE: Neither does this patch change any behaviors of current mathemtical functionalities, nor is the existing workload being impacted. In addition, there is zero impact to data/workload migration.

### CODE REVIEW

File: presto-main/src/test/java/com/facebook/presto/operator/scalar/TestMathFunctions.java [hunk 1]
```diff
@@ -268,6 +268,27 @@ public void testTruncate()
         assertFunction("truncate(DECIMAL '1234567890123456789012.999')", createDecimalType(22, 0), SqlDecimal.of("1234567890123456789012"));
         assertFunction("truncate(DECIMAL '-1234567890123456789012.999')", createDecimalType(22, 0), SqlDecimal.of("-1234567890123456789012"));
 
+        // TRUNCATE DOUBLE -> DOUBLE
```
Comment (tdcmeehan) [inline presto-main/src/test/java/com/facebook/presto/operator/scalar/TestMathFunctions.java:271]: I would put this into a new test case, let's call it `testTruncateWithPrecision`

File: presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java [hunk 2]
```diff
@@ -327,6 +331,69 @@ public static long truncate(@SqlType(StandardTypes.REAL) long num)
...
+            if (decimals < -NUMBER_LENGTH) {
+                decimals = -NUMBER_LENGTH;
+            }
+        }
+        else {
+            if (decimals >= NUMBER_LENGTH) {
+                decimals = NUMBER_LENGTH;
+            }
+        }
+        return floatToRawIntBits(new BigDecimal(Float.toString(numBitsToFloats)).setScale((int) decimals, BigDecimal.ROUND_DOWN).floatValue());
```
Comment (tdcmeehan) [inline presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java:394]:
```suggestion
        return floatToRawIntBits(new BigDecimal(numBitsToFloats).setScale((int) decimals, BigDecimal.ROUND_DOWN).floatValue());
```

Any reason why this had to be converted to a string?  The test cases pass with the above.

File: presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java [hunk 3]
```diff
@@ -66,6 +67,9 @@
 {
     public static final SqlScalarFunction DECIMAL_MOD_FUNCTION = decimalModFunction();
 
+    // double's precision not exceed this limit
+    private static final int NUMBER_LENGTH = 400;
```
Comment (tdcmeehan) [inline presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java:71]: How about `MAX_DECIMAL_PLACES`?

File: presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java [hunk 4]
```diff
@@ -327,6 +331,69 @@ public static long truncate(@SqlType(StandardTypes.REAL) long num)
...
+        if (decimals < 0) {
+            if (decimals < -NUMBER_LENGTH) {
+                decimals = -NUMBER_LENGTH;
+            }
+        }
+        else {
+            if (decimals >= NUMBER_LENGTH) {
+                decimals = NUMBER_LENGTH;
+            }
+        }
```
Comment (tdcmeehan) [inline presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java:393]:
```suggestion
        decimals = Math.max(Math.min(decimals, NUMBER_LENGTH), -NUMBER_LENGTH);
```

File: presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java [hunk 5]
```diff
@@ -327,6 +331,69 @@ public static long truncate(@SqlType(StandardTypes.REAL) long num)
...
```
Comment (tdcmeehan) [inline presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java:361]:
```suggestion
        decimals = Math.max(Math.min(decimals, NUMBER_LENGTH), -NUMBER_LENGTH);
```

File: presto-main/src/test/java/com/facebook/presto/operator/scalar/TestMathFunctions.java [hunk 6]
```diff
@@ -268,6 +268,27 @@ public void testTruncate()
...
+        assertFunction("truncate(DOUBLE '" + -Double.MAX_VALUE / 10 + "', 408)", DOUBLE, -Double.MAX_VALUE / 10);
+        assertFunction("truncate(DOUBLE '" + (double) Long.MAX_VALUE + "', -15)", DOUBLE, 9.223E18);
+
+        // TRUNCATE REAL -> REAL
+        assertFunction("truncate(REAL '12.333', 0)", REAL, 12.0f);
+        assertFunction("truncate(REAL '-12.333', 0)", REAL, -12.0f);
+        assertFunction("truncate(REAL '12.333', -500)", REAL, 0.0f);
+        assertFunction("truncate(REAL '3.40287e37', -35)", REAL, 3.4E37f);
+        assertFunction("truncate(REAL '3.40287e37', -488)", REAL, 0.0f);
+        assertFunction("truncate(REAL '" + (float) Long.MAX_VALUE + "', -15)", REAL, 9.223E18f);
```
Comment (tdcmeehan) [inline presto-main/src/test/java/com/facebook/presto/operator/scalar/TestMathFunctions.java:290]: Let's add some test cases for infinity and NaN.

File: presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java [hunk 7]
```diff
@@ -327,6 +331,69 @@ public static long truncate(@SqlType(StandardTypes.REAL) long num)
         return floatToRawIntBits((float) (Math.signum(numInFloat) * Math.floor(Math.abs(numInFloat))));
     }
 
+    @Description("truncate to double by dropping digits after decimal point")
+    @ScalarFunction
+    @SqlType(StandardTypes.DOUBLE)
+    public static double truncate(@SqlType(StandardTypes.DOUBLE) double num, @SqlType(StandardTypes.BIGINT) long decimals)
```
Comment (tdcmeehan) [inline presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java:337]: We should probably change the type to be `INTEGER` since we're downcasting to int below.  Actually, why not make this `TINYINT` (max range is [-127, 128])?  If that's not sufficient precision, we could make it `SMALLINT` (range > 400) and safely downcast.

File: presto-main/src/test/java/com/facebook/presto/operator/scalar/TestMathFunctions.java (hunk 1 above)
Comment (fgwang7w) [reply presto-main/src/test/java/com/facebook/presto/operator/scalar/TestMathFunctions.java:271]: sure will do, thanks

File: presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java (hunk 2 above)
Comment (fgwang7w) [reply presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java:394]: BigDecimal takes type of DOUBLE not FLOAT so use String as a safe cast value to return.

File: presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java (hunk 3 above)
Comment (fgwang7w) [reply presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java:71]: sure, fixed

File: presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java (hunk 4 above)
Comment (fgwang7w) [reply presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java:393]: sounds good, thanks

File: presto-main/src/test/java/com/facebook/presto/operator/scalar/TestMathFunctions.java (hunk 6 above)
Comment (fgwang7w) [reply presto-main/src/test/java/com/facebook/presto/operator/scalar/TestMathFunctions.java:290]: infinity and NaN cases may land up in DOUBLE case, testcases added

File: presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java (hunk 7 above)
Comment (fgwang7w) [reply presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java:337]: are you referring to the type for decimals?it may not be sufficient to use `TINYINT` because truncate precision could have a long decimal precision. I  switch to`INTEGER` for now

**Comment by kaikalur** [comment]
The one with -1 as the second param are very confusing! Is it similar to any other system like Oracle or Mysql?

**Comment by fgwang7w** [comment]
> [We'll also want to add documentation for it here.](https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/functions/math.rst)

sure will add spec doc accordingly

**Comment by fgwang7w** [comment]
> The one with -1 as the second param are very confusing! Is it similar to any other system like Oracle or Mysql?

Yes this is commonly used in the industry, Oracle has a spec here using -1: https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions200.htm

**Comment by fgwang7w** [comment]
> [We'll also want to add documentation for it here.](https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/functions/math.rst)

@tdcmeehan Thanks for the comment, I have added the doc accordingly for this function. Please help give another review. many thanks!

**Comment by fgwang7w** [comment]
> LGTM. @kaikalur @rongrong do you want to look?

Thanks @tdcmeehan !
@kaikalur @rongrong could you please help review this commit? Thanks!

File: presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java [hunk 8]
```diff
@@ -327,6 +331,51 @@ public static long truncate(@SqlType(StandardTypes.REAL) long num)
         return floatToRawIntBits((float) (Math.signum(numInFloat) * Math.floor(Math.abs(numInFloat))));
     }
 
+    @Description("truncate to double by dropping digits after decimal point")
```
Comment (rongrong) [inline presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java:334]: If there's a limit for decimal point, I think we should be explicit about it and mention in description and in documentation. We should probably also fail the query if an out-of-range number is given, rather than silently changing the behavior.

Comment (rongrong) [reply presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java:334]: Though if the limit is actually limitation of double then this behavior is fine. But in that case I think we also don't have to special handle the max?

Comment (fgwang7w) [reply presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java:334]: Thanks for the review. Are you suggesting to document the max number of precision for double type in alignment with `MAX_DECIMAL_PLACES` value? Yes the limit only handles the double/real type behavior. If the max limit reaches/exceeded, the outcome should be either 0.0 or negative value. I have 2 tests covered that:

`assertFunction("truncate(DOUBLE '" + Double.MAX_VALUE + "', -408)", DOUBLE, 0.0);
assertFunction("truncate(DOUBLE '" + -Double.MAX_VALUE / 10 + "', 408)", DOUBLE, -Double.MAX_VALUE / 10);
`

Is this what you were thinking to cover? @rongrong

**Comment by fgwang7w** [comment]
can someone please help to merge the code or does it need another review?

**Comment by fgwang7w** [comment]
@rongrong assign this pr to you since you left the last comment, if all looks good please help coordinate to merge. many thanks!

File: presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java (hunk 8 above)
Comment (rongrong) [reply presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java:334]: I mean add this to the rst file. Maybe also add it to the function description. So people know the maximum value for decimals should be within 400. Also document the behavior if the provided decimal is larger than 400. Why do we choose 400 as the max digit though? What's the logic behind this?

Comment (fgwang7w) [reply presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java:334]: Actually I double-checked the oracle doc which indicates that the scale of the decimal points ranges from -84 to 127. I will change 400 to 127 to align with oracle's behavior and document it in rst file.

**Review by rongrong — APPROVED** [review]
