### PR TITLE
Fix precision loss in parse_duration for large millisecond values

### LINKED ISSUE #25340: parse_duration: Output imprecision for milliseconds value
Function `parse_duration` is imprecise for millisecond values. In the below examples I cast an integer to a string and concat unit milliseconds to produce an input to said function. The output in Presto mismatches the input for what should be a simple conversion.

## Current Behavior
```
select try(parse_duration(concat(cast(7702741401940153 as VARCHAR), 'ms')));
```
```
         _col0         
-----------------------
 89152099 13:25:40.154 
(1 row)
```
Given our input `7702741401940153` our output should be `...153` but it is `.154` instead.

## Expected Behavior
This is correctly outputted in Prestissimo (Presto C++):
```
presto:di> select try(parse_duration(concat(cast(c0 as VARCHAR), 'ms'))) from (values 7702741401940153) t(c0);
         _col0         
-----------------------
 89152099 13:25:40.153 
(1 row)
```

### PR DESCRIPTION
**Pull request by martinsander00**
Fixes #25340

## Description
Fixes precision loss in `parse_duration` function for large millisecond values.

## Motivation and Context
The `parse_duration` function uses `Duration.valueOf()` which internally uses `Double.parseDouble()`, causing precision loss for large integer values (> 2^53).

Example:
- Input: `parse_duration('7702741401940153ms')`
- Expected: `89152099 13:25:40.153`
- Actual (before fix): `89152099 13:25:40.154`

Solution:
Added special handling for millisecond values that:
1. Detects strings ending with "ms" (with or without space)
2. Attempts to parse the numeric part as a long
3. Falls back to original `Duration.valueOf()` for decimal values 

## Test Plan
Added test cases in `TestDateTimeFunctionsBase.testParseDuration()`:
```
assertFunction("parse_duration('7702741401940153ms')", INTERVAL_DAY_TIME, new SqlIntervalDayTime(89152099, 13, 25, 40, 153));
assertFunction("parse_duration('9117756383778565ms')", INTERVAL_DAY_TIME, new SqlIntervalDayTime(105529587, 18, 36, 18, 565));
```

Test output before fix:

```
[ERROR] com.facebook.presto.operator.scalar.TestDateTimeFunctions.testParseDuration
java.lang.AssertionError: expected [89152099 13:25:40.153] but found [89152099 13:25:40.154]
```

All tests pass after the fix.

## Contributor checklist

- [x] Please make sure your submission complies with our [contributing guide](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md), in particular [code style](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#code-style) and [commit standards](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#commit-standards).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==
General Changes
* Fix precision loss in ``parse_duration`` function for large millisecond values.
```

### CODE REVIEW

File: presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java [hunk 1]
```diff
@@ -1437,8 +1437,32 @@ else if (character == '%') {
     @SqlType(StandardTypes.INTERVAL_DAY_TO_SECOND)
     public static long parseDuration(@SqlType("varchar(x)") Slice duration)
     {
+        String durationStr = duration.toStringUtf8();
```
Comment (hantangwangd) [inline presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java:1444]:
```suggestion
        String durationStr = duration.toStringUtf8().trim();
```

Forgot to handle the trailing spaces. The calculation for something like `parse_duration('7702741401940153   ms  ')` will fall back.

File: presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java [hunk 2]
```diff
@@ -1437,8 +1437,32 @@ else if (character == '%') {
...
+
+        // Special handling for large millisecond values to avoid precision loss
+        if ((durationStr.endsWith("ms") && !durationStr.contains(" ")) ||
+                (durationStr.endsWith(" ms"))) {
```
Comment (hantangwangd) [inline presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java]: Seems we cannot simply do special handling just for values with unit `ms`, for example, the following query meet the same problem:

```
select parse_duration('7702741401940.153 s');
```

Any time unit greater than ms, when used with fractional values, is likely to encounter this problem. Perhaps we should adopt the parsing logic of `Duration.valueOf` and calculate the milliseconds value directly, rather than constructing a `Duration` object to get the milliseconds value. What do you think?

**Review by hantangwangd — CHANGES_REQUESTED** [review]

**Comment by martinsander00** [comment]
@hantangwangd I addressed your comments in a second commit and also sent a slack dm in case there is something else

File: presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java [hunk 3]
```diff
@@ -1437,11 +1440,66 @@ else if (character == '%') {
...
+                case "h":
+                    milliseconds = value.multiply(BigDecimal.valueOf(3_600_000));
+                    break;
+                case "d":
+                    milliseconds = value.multiply(BigDecimal.valueOf(86_400_000));
+                    break;
+                default:
+                    throw new PrestoException(INVALID_FUNCTION_ARGUMENT,
+                            "Unknown time unit: " + unitString);
+            }
```
Comment (hantangwangd) [inline presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java]:
```suggestion
            BigDecimal value = new BigDecimal(matcher.group(1));
            TimeUnit timeUnit = valueOfTimeUnit(matcher.group(2));

            BigDecimal milliseconds = value.multiply(BigDecimal.valueOf(millisPerTimeUnit(timeUnit)));
            try {
                return milliseconds.longValueExact();
            }
            catch (ArithmeticException e) {
                // If exact conversion fails, use rounding
                return milliseconds.setScale(0, RoundingMode.HALF_UP).longValue();
            }
```

Seems we could always use BigDecimal multiplication here -- since it performs better than division -- through extracting a method similar to `millisPerTimeUnit` in `Duration`.

**Comment by martinsander00** [comment]
We did some benchmarking (I added the file to the commit) and here are the results comparing previous approach with the new one.

Each line represents the average time (mode: avgt) for 10 iterations of the parse_duration function, measured in nanoseconds per operation (ns/op). The ± values are the standard deviation (error bars), indicating variability across runs—lower values mean more consistent performance.

`BigDecimal` is slower but acceptable: Across all units, `BigDecimal` takes `~244–357 ns/op`, while double is faster at `~161–192 ns/op`. This makes BigDecimal roughly `1.4x` to `2.2x` slower (e.g., for `ns` unit: `357 / 172 ≈ 2.1x`; for s unit: `244 / 161 ≈ 1.5x`). We think the precision tradeoff is worth the change.

```
BenchmarkForParseDuration.testUseBigDecimal      ns  avgt   10  356.900 ± 80.796  ns/op
BenchmarkForParseDuration.testUseBigDecimal      us  avgt   10  281.825 ± 47.163  ns/op
BenchmarkForParseDuration.testUseBigDecimal      ms  avgt   10  264.527 ± 56.992  ns/op
BenchmarkForParseDuration.testUseBigDecimal       s  avgt   10  244.194 ± 39.542  ns/op
BenchmarkForParseDuration.testUseBigDecimal       m  avgt   10  250.127 ± 15.979  ns/op
BenchmarkForParseDuration.testUseBigDecimal       h  avgt   10  271.032 ±  1.353  ns/op
BenchmarkForParseDuration.testUseBigDecimal       d  avgt   10  261.840 ± 68.725  ns/op
BenchmarkForParseDuration.testUseDouble          ns  avgt   10  172.169 ± 25.494  ns/op
BenchmarkForParseDuration.testUseDouble          us  avgt   10  191.248 ±  8.299  ns/op
BenchmarkForParseDuration.testUseDouble          ms  avgt   10  189.090 ± 12.433  ns/op
BenchmarkForParseDuration.testUseDouble           s  avgt   10  161.473 ±  7.297  ns/op
BenchmarkForParseDuration.testUseDouble           m  avgt   10  170.223 ± 19.301  ns/op
BenchmarkForParseDuration.testUseDouble           h  avgt   10  170.466 ± 17.709  ns/op
BenchmarkForParseDuration.testUseDouble           d  avgt   10  191.937 ± 38.213  ns/op
```

**Review by hantangwangd — DISMISSED** [review]
Thanks for the entire work. Looks good to me!

File: presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java [hunk 4]
```diff
@@ -1437,14 +1440,54 @@ else if (character == '%') {
...
     {
+        String durationStr = duration.toStringUtf8().trim();
+
+        if (durationStr.isEmpty()) {
+            throw new PrestoException(INVALID_FUNCTION_ARGUMENT, "duration is empty");
+        }
+
         try {
-            return Duration.valueOf(duration.toStringUtf8()).toMillis();
+            Pattern pattern = Pattern.compile("^(\\d+(?:\\.\\d+)?)\\s*([a-zA-Z]+)$");
```
Comment (tdcmeehan) [inline presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java]: Wouldn't it be more efficient to extract this as a static member variable?  As it is now, this is evaluated row by row which can be quite expensive.

File: presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java [hunk 5]
```diff
@@ -1437,14 +1440,54 @@ else if (character == '%') {
     @SqlType(StandardTypes.INTERVAL_DAY_TO_SECOND)
     public static long parseDuration(@SqlType("varchar(x)") Slice duration)
     {
+        String durationStr = duration.toStringUtf8().trim();
```
Comment (tdcmeehan) [inline presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java]: It doesn't seem like we need to trim the string.  If not, I'd remove it so we do as little work as possible per row.

File: presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java [hunk 6]
```diff
@@ -1437,14 +1440,54 @@ else if (character == '%') {
...
+
+        if (durationStr.isEmpty()) {
+            throw new PrestoException(INVALID_FUNCTION_ARGUMENT, "duration is empty");
+        }
+
         try {
-            return Duration.valueOf(duration.toStringUtf8()).toMillis();
+            Pattern pattern = Pattern.compile("^(\\d+(?:\\.\\d+)?)\\s*([a-zA-Z]+)$");
+            Matcher matcher = pattern.matcher(durationStr);
```
Comment (tdcmeehan) [inline presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java]: I'm wondering if it would be more efficient to just split the slice into two parts.  Can you help me understand why we didn't just do something along these lines?

```java
    @Description("convert duration string to an interval")
    @ScalarFunction("parse_duration")
    @LiteralParameters("x")
    @SqlType(StandardTypes.INTERVAL_DAY_TO_SECOND)
    public static long parseDuration(@SqlType("varchar(x)") Slice duration)
    {
        try {
            Slice timeSlice = duration.slice(0, duration.length() - 2); // remove suffix
            long time = Long.parseLong(timeSlice.toStringUtf8());
            Slice unitSlice = duration.slice(duration.length() - 2, 2); // get suffix
            TimeUnit unit = Duration.valueOfTimeUnit(unitSlice.toStringUtf8());
            return MILLISECONDS.convert(time, unit);
        }
        catch (NumberFormatException e) {
            throw new PrestoException(INVALID_FUNCTION_ARGUMENT, "Invalid duration format: " + duration.toStringUtf8(), e);
        }
        catch (IllegalArgumentException e) {
            throw new PrestoException(INVALID_FUNCTION_ARGUMENT, "Invalid time unit in duration: " + duration.toStringUtf8(), e);
        }
    }
```

File: presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java (hunk 4 above)
Comment (hantangwangd) [reply presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java]: Oh, nice catch. The above benchmark result were obtained under extracting the pattern as a static member variable in my local, so I overlooked this. When placing it inside the scalar method, the average overhead increases by 200-300ns.

File: presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java (hunk 6 above)
Comment (hantangwangd) [reply presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java]: As I understand, the key point is that the given numerical part can be a decimal, and the calculated original milliseconds may also be a decimal, which requiring a rounded final result. For example, the following inputs are all allowed:

```
parse_duration('12344564564.6123123   us ')
parse_duration('38955347.1335412   s ')
parse_duration('1234.45645646123123   h ')
...
```
We need to preserve the decimal portion, perform calculations, and then apply rounding.

Comment (tdcmeehan) [reply presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java]: Oh, right.  The numeric part may be a decimal.

Comment (martinsander00) [reply presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java]: Since the above input is allowed, we do need `trim()` right? @tdcmeehan @hantangwangd 

So the only missing change is making Pattern a private static final member variable

Comment (hantangwangd) [reply presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java]: The regex handles trailing spaces, so let's remove the `trim()`.

Comment (martinsander00) [reply presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java]: @hantangwangd I ran some tests and that doesn't seem to be the case. I will add the trim back and commit the tests that I ran in case you want to see them.

Comment (hantangwangd) [reply presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java]: Oh sorry, I assumed you were copying the pattern from `Duration` directly. You can copy the pattern from `Duration` directly -- it handles leading/trailing spaces automatically:

```
private static final Pattern PATTERN = Pattern.compile("^\\s*(\\d+(?:\\.\\d+)?)\\s*([a-zA-Z]+)\\s*$");
```

Comment (martinsander00) [reply presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java]: done. Lmk if there is anything else @tdcmeehan @hantangwangd

Comment (hantangwangd) [reply presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java]: Also, please squash the commits into a single one.

Comment (martinsander00) [reply presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java]: done @hantangwangd

**Review by hantangwangd — APPROVED** [review]
Thanks for the fix, lgtm!

File: presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java [hunk 7]
```diff
@@ -1437,14 +1441,53 @@ else if (character == '%') {
...
+        if (durationStr.isEmpty()) {
+            throw new PrestoException(INVALID_FUNCTION_ARGUMENT, "duration is empty");
+        }
+
         try {
-            return Duration.valueOf(duration.toStringUtf8()).toMillis();
+            Matcher matcher = PATTERN.matcher(durationStr);
+
+            if (!matcher.matches()) {
+                throw new PrestoException(INVALID_FUNCTION_ARGUMENT,
```
Comment (beinan) [inline presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java:1454]: I'm a bit hesitant about using regex for date/time functions. While convenient, regular expressions can sometimes have performance implications, especially if this code is in a hot path or deals with many date strings. Have we explored alternative, more optimized date parsing methods?

Comment (martinsander00) [reply presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java:1454]: We haven't explored other methods, however even the original version of the method used a regex internally. Linking Duration.valueOf(): https://github.com/airlift/units/blob/c6629f185a1dd171d6ed2884d7f43ebc167e4bbc/src/main/java/io/airlift/units/Duration.java#L193

I guess we could merge this one and as a follow up I try to come up with a better parsing method and benchmark it against this current one.

Comment (beinan) [reply presto-main-base/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java:1454]: sounds good to me, thanks for the contribution!
