### PR TITLE
Fix invalid array_min/max result of containing NaN

### LINKED ISSUE #8836: Incorrect result for array_min/max of doubles containing NaN
`array_min(array[1, 2, nan()])` => `1`
`array_min(array[nan(), 1, 2])` => `NaN`

This probably occurs because the array_min function interprets `false` when comparing with NaN incorrectly.

The function should return `NaN` if any of the elements is `NaN` (similar to how NULLs are treated).

### PR DESCRIPTION
**Pull request by ebyhr**
Fix #8836

### CODE REVIEW

File: presto-main/src/main/java/com/facebook/presto/operator/scalar/ArrayMinMaxUtils.java [hunk 1]
```diff
@@ -92,7 +93,10 @@ public static Double doubleArrayMinMax(MethodHandle compareMethodHandle, Type el
                     return null;
                 }
                 double value = elementType.getDouble(block, i);
-                if ((boolean) compareMethodHandle.invokeExact(value, selectedValue)) {
+                if (isNaN(value)) {
+                    return value;
```
Comment (findepi) [inline presto-main/src/main/java/com/facebook/presto/operator/scalar/ArrayMinMaxUtils.java]: nit: somehow returning `NaN` looks better to me

Comment (ebyhr) [reply presto-main/src/main/java/com/facebook/presto/operator/scalar/ArrayMinMaxUtils.java]: Oops, I think so. I will update it.

File: presto-main/src/main/java/com/facebook/presto/operator/scalar/ArrayMinMaxUtils.java [hunk 2]
```diff
@@ -92,7 +94,10 @@ public static Double doubleArrayMinMax(MethodHandle compareMethodHandle, Type el
                     return null;
                 }
                 double value = elementType.getDouble(block, i);
-                if ((boolean) compareMethodHandle.invokeExact(value, selectedValue)) {
+                if (isNaN(value)) {
+                    return NaN();
```
Comment (findepi) [inline presto-main/src/main/java/com/facebook/presto/operator/scalar/ArrayMinMaxUtils.java]: why not `Double.NaN` (+ static import)?

File: presto-main/src/main/java/com/facebook/presto/operator/scalar/ArrayMinMaxUtils.java [hunk 3]
```diff
@@ -92,7 +94,10 @@ public static Double doubleArrayMinMax(MethodHandle compareMethodHandle, Type el
                     return null;
                 }
                 double value = elementType.getDouble(block, i);
-                if ((boolean) compareMethodHandle.invokeExact(value, selectedValue)) {
+                if (isNaN(value)) {
```
Comment (findepi) [inline presto-main/src/main/java/com/facebook/presto/operator/scalar/ArrayMinMaxUtils.java]: nit: in fact this could be second `if, else` option, not the first. Thus, for array in decrementing order and w/o NaNs you do less comparisons

File: presto-main/src/test/java/com/facebook/presto/type/TestArrayOperators.java [hunk 4]
```diff
@@ -503,9 +503,13 @@ public void testArrayMin()
     {
         assertFunction("ARRAY_MIN(ARRAY [])", UNKNOWN, null);
         assertFunction("ARRAY_MIN(ARRAY [NULL])", UNKNOWN, null);
+        assertFunction("ARRAY_MIN(ARRAY [NaN()])", DOUBLE, NaN);
         assertFunction("ARRAY_MIN(ARRAY [NULL, NULL, NULL])", UNKNOWN, null);
+        assertFunction("ARRAY_MIN(ARRAY [NaN(), NaN(), NaN()])", DOUBLE, NaN);
         assertFunction("ARRAY_MIN(ARRAY [NULL, 2, 3])", INTEGER, null);
+        assertFunction("ARRAY_MIN(ARRAY [NaN(), 2, 3])", DOUBLE, NaN);
         assertFunction("ARRAY_MIN(ARRAY [1.0, NULL, 3])", DOUBLE, null);
+        assertFunction("ARRAY_MIN(ARRAY [1.0, NaN(), 3])", DOUBLE, NaN);
```
Comment (findepi) [inline presto-main/src/test/java/com/facebook/presto/type/TestArrayOperators.java]: You should also have test for array with NaN after NULL and for NULL after NaN. @martint what should be the result in those cases? Applying "NULL stands for an unknown value" thinking, NaN should "win", right?

**Comment by ebyhr** [comment]
Updated with the logic NaN win Null.
