### PR TITLE
Do not extract range filters for complex types

### LINKED ISSUE #13295: Unsupported type: array(bigint) in TupleDomainFilterUtils
Comparing array column with literal array triggers an error in TupleDomainFilterUtils:

```
CREATE TABLE lineitem_ex AS
SELECT orderkey, ARRAY[orderkey, partkey, suppkey] AS keys FROM lineitem;

SELECT orderkey FROM lineitem_ex WHERE keys = ARRAY[1, 2, 3];
```

```
Caused by: java.lang.UnsupportedOperationException: Unsupported type: array(bigint)
	at com.facebook.presto.orc.TupleDomainFilterUtils.createRangeFilter(TupleDomainFilterUtils.java:173)
	at com.facebook.presto.orc.TupleDomainFilterUtils.toFilter(TupleDomainFilterUtils.java:76)
	at com.google.common.collect.Maps$9.transformEntry(Maps.java:1955)
	at com.google.common.collect.Maps$12.getValue(Maps.java:1996)
	at com.facebook.presto.hive.orc.OrcSelectivePageSourceFactory.toTupleDomainFilters(OrcSelectivePageSourceFactory.java:319)
	at com.facebook.presto.hive.orc.OrcSelectivePageSourceFactory.createOrcPageSource(OrcSelectivePageSourceFactory.java:249)
	... 17 more
```

CC: @prestodb/aria

### PR DESCRIPTION
**Pull request by mbasmanova**
Selective readers cannot handle range filters other than null checks for
complex types (arrays, maps, and structs), e.g. a = ARRAY[1, 2, 3]. This
change extends DomainTranslator.ColumnExtractor to provide values domain
and updates HiveMetadata to provide an implementation of ColumnExtractor
that excludes non-null check filters for complex types.

Fixes #13295

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

File: presto-hive/src/test/java/com/facebook/presto/hive/TestDomainTranslator.java [hunk 1]
```diff
@@ -125,6 +141,16 @@ private RowExpression dereference(RowExpression base, int field)
...
     }
 
+    private RowExpression isNull(RowExpression expression)
+    {
+        return specialForm(IS_NULL, BOOLEAN, expression);
+    }
+
+    private RowExpression not(RowExpression expression)
+    {
+        return call("not", metadata.getFunctionManager().lookupFunction("not", fromTypes(BOOLEAN)), BOOLEAN, expression);
```
Comment (highker) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestDomainTranslator.java]: "not" function is already available in `StandardFunctionResolution`. But I don't mind having it here given it's a test.

Comment (mbasmanova) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestDomainTranslator.java]: @highker Like this?

`return call("not", new FunctionResolution(metadata.getFunctionManager()).notFunction(), BOOLEAN, expression);`

Comment (mbasmanova) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestDomainTranslator.java]: @highker Like this?

`return call("not", new FunctionResolution(metadata.getFunctionManager()).notFunction(), BOOLEAN, expression);`
