### PR TITLE
Fix assertion in tryUpdateUserMemory method

### LINKED ISSUE #12040: "future should be done" assertion in HashBuilderOperator
Some queries are failing with this stack trace:

```
Caused by: com.google.common.base.VerifyException: future should be done
	at com.google.common.base.Verify.verify(Verify.java:123)
	at com.facebook.presto.memory.DefaultQueryContext.tryUpdateUserMemory(DefaultQueryContext.java:199)
	at com.facebook.presto.memory.DefaultQueryContext$QueryMemoryReservationHandler.tryReserveMemory(DefaultQueryContext.java:314)
	at com.facebook.presto.memory.context.RootAggregatedMemoryContext.tryUpdateBytes(RootAggregatedMemoryContext.java:49)
	at com.facebook.presto.memory.context.ChildAggregatedMemoryContext.tryUpdateBytes(ChildAggregatedMemoryContext.java:46)
	at com.facebook.presto.memory.context.ChildAggregatedMemoryContext.tryUpdateBytes(ChildAggregatedMemoryContext.java:46)
	at com.facebook.presto.memory.context.ChildAggregatedMemoryContext.tryUpdateBytes(ChildAggregatedMemoryContext.java:46)
	at com.facebook.presto.memory.context.ChildAggregatedMemoryContext.tryUpdateBytes(ChildAggregatedMemoryContext.java:46)
	at com.facebook.presto.memory.context.SimpleLocalMemoryContext.trySetBytes(SimpleLocalMemoryContext.java:77)
	at com.facebook.presto.operator.OperatorContext$InternalLocalMemoryContext.trySetBytes(OperatorContext.java:599)
	at com.facebook.presto.operator.HashBuilderOperator.updateIndex(HashBuilderOperator.java:344)
	at com.facebook.presto.operator.HashBuilderOperator.addInput(HashBuilderOperator.java:333)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:384)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1065)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at com.facebook.presto.$gen.Presto_0_214_84_gad05dcb____20181206_001801_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
When DefaultQueryContext::tryUpdateUserMemory() is called with a delta
of 0 and when the general pool is full, the updateUserMemory call will
return a future that's not done. However, tryUpdateUserMemory was simply
assuming that for that case the future must be done and asserting on
that, which causes query failures. This change fixes that.

It makes sense for updateUserMemory to return a future that's not done
when we reserve 0 bytes and the pool is full, so that the caller knows
that the pool is full and waits on that future to make the next
reservation. Therefore, for the delta == 0 case it's not correct to
simply assume that future returned from updateUserMemory is done.

Fixes #12040

### CODE REVIEW

**Comment by nezihyigitbasi** [comment]
Fixes #12040.

File: presto-main/src/main/java/com/facebook/presto/memory/DefaultQueryContext.java [hunk 1]
```diff
@@ -196,7 +196,11 @@ private synchronized boolean tryUpdateUserMemory(String allocationTag, long delt
     {
         if (delta <= 0) {
             ListenableFuture<?> future = updateUserMemory(allocationTag, delta);
-            verify(future.isDone(), "future should be done");
+            // When delta == 0 and the pool is full the future can still not be done,
```
Comment (mbasmanova) [inline presto-main/src/main/java/com/facebook/presto/memory/DefaultQueryContext.java]: @nezihyigitbasi What does it mean that the future is not done (for delta = 0)? Is it safe for the caller to proceed? Would you explain why?

Comment (nezihyigitbasi) [reply presto-main/src/main/java/com/facebook/presto/memory/DefaultQueryContext.java]: > What does it mean that the future is not done (for delta = 0)?

This means the pool is full, if you try to allocate a positive delta then it will not be satisfied (return false if `tryUpdateUserMemory` is called, or fail if `updateUserMemory` is called).

> Is it safe for the caller to proceed? Would you explain why?

I think it is safe, because a delta of 0 means don't allocate or release anything (don't change the state of the pools/contexts), so when we return `true` here we just tell the caller that the call succeeded, which is really the case (see the contract in `LocalMemoryContext.trySetBytes) javadoc). If there are subsequent calls to `tryUpdateUserMemory` with delta = 0, they will behave similarly, so no issue with that too. If there is a subsequent call to `tryUpdateUserMemory` with a positive value then we will just catch it with the condition: `if (queryMemoryContext.getUserMemory() + delta > maxUserMemory)` and return false when the pool is full. If there is a subsequent call to other allocations method like `updateUserMemory` with a positive delta, then they will just fail as the pool is full (`EXCEEDED_LOCAL_MEMORY_LIMIT`).

Comment (findepi) [inline presto-main/src/main/java/com/facebook/presto/memory/DefaultQueryContext.java]: why call `updateUserMemory` at all when delta==0?
now, that we (implicitly) special-case delta==0, it makes sense to handle it more properly

File: presto-main/src/main/java/com/facebook/presto/memory/LegacyQueryContext.java [hunk 2]
```diff
@@ -164,7 +164,11 @@ private synchronized boolean tryUpdateUserMemory(String allocationTag, long delt
     {
         if (delta <= 0) {
             ListenableFuture<?> future = updateUserMemory(allocationTag, delta);
-            verify(future.isDone(), "future should be done");
+            // When delta == 0 and the pool is full the future can still not be done,
+            // but, for negative deltas it must always be done.
+            if (delta < 0) {
+                verify(future.isDone(), "future should be done");
```
Comment (findepi) [inline presto-main/src/main/java/com/facebook/presto/memory/LegacyQueryContext.java]:
```
if (delta == 0) {
    // ... some explanation
    return true;
}
if (delta < 0) {
    ...
```

File: presto-main/src/main/java/com/facebook/presto/memory/DefaultQueryContext.java (hunk 1 above)
Comment (nezihyigitbasi) [reply presto-main/src/main/java/com/facebook/presto/memory/DefaultQueryContext.java]: Yes, we need to handle the delta = 0 case more properly, for that I will create a subsequent PR( with that I will also address your comment below).

Comment (nezihyigitbasi) [reply presto-main/src/main/java/com/facebook/presto/memory/DefaultQueryContext.java]: > why call updateUserMemory at all when delta==0?

Looking at the code again, looks like we still need to call `updateUserMemory` otherwise listeners will not be called in the memory pools (see `MemoryPool:onMemoryReserved()`), which will change the behavior of the current implementation.

Comment (findepi) [reply presto-main/src/main/java/com/facebook/presto/memory/DefaultQueryContext.java]: I didn't look into the code, so i might be missing something... Why do we want to call listeners if allocations didn't change?

BTW, if we special case `delta==0`, we can probably do this on lower-level contexts too, to avoid calling synchronized methods.

Comment (nezihyigitbasi) [reply presto-main/src/main/java/com/facebook/presto/memory/DefaultQueryContext.java]: > I didn't look into the code, so i might be missing something... Why do we want to call listeners if allocations didn't change?

`MemoryPool.reserve()` has always been called with `0` bytes, and looking at the git history the listeners are added to the `MemoryPool` is with e83c05cf7b0c4c70ed0e423d77d4f08f510efe1c, so we started calling those listeners for `delta = 0` starting with that change. Currently, I see that only `MemoryRevokingScheduler` relies on these listeners. Since you know that class better than me, if you think it's safe to not call listeners for 0 bytes, then I think we can special case `delta==0` at the lower-level contexts yes.

Comment (findepi) [reply presto-main/src/main/java/com/facebook/presto/memory/DefaultQueryContext.java]: @nezihyigitbasi thanks for looking in this.
Yes, from `MemoryRevokingScheduler` / e83c05cf7b0c4c70ed0e423d77d4f08f510efe1c perspective, no change in memory allocation (`delta==0`), is not an interesting event.
And, I think it is a generally reasonable and future-safe assumption that `MemoryPoolListener#onMemoryReserved` does not need to  (even: should not) be called when no new memory is reserved.
