### PR TITLE
Don't push limit through full outer joins

### LINKED ISSUE #12638: Limit incorrectly pushed down for full outer join
https://github.com/prestodb/presto/commit/28cc38b0766e6b938a1e22fa09589f2f875458e9 incorrectly pushes a limit through a full outer join.  You can't push down the limit because you will end up losing matches and outputting nulls.

Example:
```
SELECT * FROM 
        (VALUES (1),(2),(3)
    ) AS a(id)
FULL OUTER JOIN (
        VALUES (2),(3), (1)
    ) AS b(id)
    ON a.id = b.id
LIMIT
    1;
```

### PR DESCRIPTION
**Pull request by rschlussel**
Fixes a wrong results issue with limits and full outer joins.
Because full outer joins return all rows from both tables, if you push
down a limit you can get incorrect nulls in your output.

Example:
SELECT * FROM
        (VALUES (1),(2),(3)
    ) AS a(id)
FULL OUTER JOIN (
        VALUES (2),(3), (1)
    ) AS b(id)
    ON a.id = b.id
LIMIT
    1;

Fixes #12638

### CODE REVIEW

File: presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushLimitThroughOuterJoin.java [hunk 1]
```diff
@@ -101,13 +100,13 @@ private static boolean isLimited(PlanNode node, Lookup lookup, long limit)
         return cardinality.hasUpperBound() && cardinality.upperEndpoint() <= limit;
     }
 
-    private static boolean isLeftOrFullOuter(Type type)
+    private static boolean isLeftOuter(Type type)
```
Comment (arhimondr) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushLimitThroughOuterJoin.java]: nit: it can be inlined

File: presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushLimitThroughOuterJoin.java [hunk 2]
```diff
@@ -101,13 +100,13 @@ private static boolean isLimited(PlanNode node, Lookup lookup, long limit)
...
     {
-        return type == LEFT || type == FULL;
+        return type == LEFT;
     }
 
-    private static boolean isRightOrFullOuter(Type type)
+    private static boolean isRightOuter(Type type)
```
Comment (arhimondr) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushLimitThroughOuterJoin.java]: nit: it can be inlined

File: presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushLimitThroughOuterJoin.java [hunk 3]
```diff
@@ -78,11 +77,11 @@ public Result apply(LimitNode parent, Captures captures, Context context)
         PlanNode left = joinNode.getLeft();
         PlanNode right = joinNode.getRight();
 
-        if (isLeftOrFullOuter(joinNode.getType()) && !isLimited(left, context.getLookup(), parent.getCount())) {
+        if (isLeftOuter(joinNode.getType()) && !isLimited(left, context.getLookup(), parent.getCount())) {
             left = new LimitNode(context.getIdAllocator().getNextId(), left, parent.getCount(), true);
         }
 
-        if (isRightOrFullOuter(joinNode.getType()) && !isLimited(right, context.getLookup(), parent.getCount())) {
+        if (isRightOuter(joinNode.getType()) && !isLimited(right, context.getLookup(), parent.getCount())) {
```
Comment (arhimondr) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushLimitThroughOuterJoin.java]: Potentially it may result into a performance regression. If the key selected on the right doesn't match any row on the left - the entire right side will have to be streamed before Join outputs any rows. I don't feel strong about it, but I would try to be safe, and add a session property that can be used to disable this optimization in case of emergency.
