### PR TITLE
Fix accidental removal nested type only cast

### LINKED ISSUE #13116: TypeOnly optimization in RowExpression can cause wrong result in nested cast
Following queries:
```
select cast(varchar_value as varchar(3)) || ' sfd' from (values ('9898.122')) t(varchar_value) ;
select cast(cast(varchar_value as varchar(3)) as varchar(5)) from (values ('9898.122')) t(varchar_value);
```

will return:
```
9898. sfd
and 
9898.
```
instead of the expected:
```
989 sfd
989
```
Since the outside cast is typeOnly, the optimization inside `SqlToRowExpressionTranslator` will remove the outside cast and change the inside cast into cast as VARCHAR(5). 

This is likely a long term bug got triggered by recent code path changes.

### PR DESCRIPTION
**Pull request by hellium01**
This is a short term fix for #13116. 
We should rethink how we handle type only cast(which will be tracked on #12891)

### CODE REVIEW

**Comment by hellium01** [comment]
Given this never actually was executed previously, we should try to remove this completely and fix the tests that depends on it.  In general, change the type of part of expression is not a good idea.

File: presto-main/src/main/java/com/facebook/presto/sql/relational/SqlToRowExpressionTranslator.java [hunk 1]
```diff
@@ -502,6 +503,23 @@ private static RowExpression changeType(RowExpression value, Type targetType)
...
+        {
+            // TODO this is a hack to prevent accidentally change children type if children of a cast is not type only cast
+            ImmutableList.Builder<Boolean> casts = ImmutableList.builder();
+            new DefaultExpressionTraversalVisitor<Void, ImmutableList.Builder<Boolean>>()
+            {
+                @Override
+                protected Void visitCast(Cast node, ImmutableList.Builder<Boolean> context)
+                {
+                    super.visitCast(node, context);
+                    context.add(node.isTypeOnly());
```
Comment (rongrong) [inline presto-main/src/main/java/com/facebook/presto/sql/relational/SqlToRowExpressionTranslator.java]: You don't really need a list here. You can just update it as `context = context && node.isTypeOnly()` assuming context is `Boolean`.

File: presto-main/src/main/java/com/facebook/presto/sql/relational/SqlToRowExpressionTranslator.java [hunk 2]
```diff
@@ -502,6 +503,23 @@ private static RowExpression changeType(RowExpression value, Type targetType)
             return value.accept(visitor, null);
         }
 
+        private static boolean allChildrenTypeOnly(Cast node)
+        {
+            // TODO this is a hack to prevent accidentally change children type if children of a cast is not type only cast
```
Comment (rongrong) [inline presto-main/src/main/java/com/facebook/presto/sql/relational/SqlToRowExpressionTranslator.java]: The `TODO` would be more useful if it describes what's the right thing to do.

File: presto-main/src/main/java/com/facebook/presto/sql/relational/SqlToRowExpressionTranslator.java (hunk 1 above)
Comment (hellium01) [reply presto-main/src/main/java/com/facebook/presto/sql/relational/SqlToRowExpressionTranslator.java]: Ah, I was thinking what will happen when the list is empty but yes, we can use an settable boolean.

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java [hunk 3]
```diff
@@ -4090,6 +4090,13 @@ public void testCast()
         assertQuery("SELECT try_cast(x AS BIGINT) FROM (VALUES 1, 2, 3, NULL) t (x)", "VALUES 1, 2, 3, NULL");
     }
 
+    @Test
+    public void testNestedCast()
```
Comment (rongrong) [inline presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java]: It's easier to read if expected values are provided.
