### PR TITLE
Fix confusion matrix computation for classification function

### LINKED ISSUE #14731: Result is wrong for function classification_fall_out for version 0.237 and earlier
The numerator of formula should be false positive for classification aggregate function https://prestodb.io/docs/current/functions/aggregate.html

### LINKED ISSUE #14750: Result is wrong for function classification_miss_rate for version 0.237 and earlier
Due to wrong arguments passed to constructor method of `BucketResult`,  the result from aggregation function `classification_miss_rate` is wrong in version 0.237 and earlier.

Fixed in https://github.com/prestodb/presto/pull/14740

### PR DESCRIPTION
**Pull request by fornaix**
Fixes #14731 and fixes #14750
1. fix document mistake for `classification_fall_out`
2. fix confusion matrix computation.

Definition: https://en.wikipedia.org/wiki/Precision_and_recall#Definition_(classification_context)

|  | predicated positive | predicated negative |
| --- | --- | --- |
| condition positive | True Positive(TP) | False Negative(FN) |
| condition negative | False Positive(FP) | True Negative(TN) |

there are some variables in code.
```
totalTrueWeight = {sum of condition positive}
totalFalseWeight = {sum of condition negative}
runningTrueWeight = {sum of predicated negative in {condition positive}}
runningFalseWeight = {sum of predicated negative in {condition negative}}
```

So we got

|  | predicated positive | predicated negative | |
| --- | --- | --- | --- |
| condition positive | totalTrueWeight - runningTrueWeight | runningTrueWeight | totalTrueWeight |
| condition negative | totalFalseWeight - runningFalseWeight | runningFalseWeight | totalFalseWeight |

```
== RELEASE NOTES ==

General Changes
* Fix  :func:`classification_miss_rate` and :func:`classification_fall_out` functions (:pr:`14740`)

### CODE REVIEW

**Comment by mbasmanova** [comment]
CC: @atavory

File: presto-main/src/test/java/com/facebook/presto/operator/TestClassificationMissRateAggregation.java [hunk 1]
```diff
@@ -34,7 +34,7 @@ public TestClassificationMissRateAggregation()
         final ArrayList<Double> expected = new ArrayList<>();
         while (iterator.hasNext()) {
             final BucketResult result = iterator.next();
-            final double missRate = result.remainingFalseWeight / result.totalTrueWeight;
+            final double missRate = (result.totalTrueWeight - result.remainingTrueWeight) / result.totalTrueWeight;
```
Comment (viczhang861) [inline presto-main/src/test/java/com/facebook/presto/operator/TestClassificationMissRateAggregation.java:37]: Could you also define falseNegative before calculating miss rate,  to be consistent with that in `TestClassificationPrecisionAggregation.java`

File: presto-main/src/test/java/com/facebook/presto/operator/TestClassificationMissRateAggregation.java [hunk 2]
```diff
@@ -34,7 +34,7 @@ public TestClassificationMissRateAggregation()
...
             expected.add(missRate);
         }
         return expected;
```
Comment (viczhang861) [inline presto-main/src/test/java/com/facebook/presto/operator/TestClassificationMissRateAggregation.java:40]: Did we only test execution path rather than real expected value? Ideally, unit test should exist to catch this error.

Comment (fornaix) [reply presto-main/src/test/java/com/facebook/presto/operator/TestClassificationMissRateAggregation.java:40]: I think it did test the expected value. But expected values are calculated at runtime, so the computation in unit test and function must keep consistent. Once the basic definition is wrong, we can't catch the error.

File: presto-main/src/test/java/com/facebook/presto/operator/TestClassificationMissRateAggregation.java (hunk 1 above)
Comment (fornaix) [reply presto-main/src/test/java/com/facebook/presto/operator/TestClassificationMissRateAggregation.java]: done.

**Comment by fornaix** [comment]
> Thank you for the fix. Could you change release note to `Fix incorrect results from function classification_miss_rate and classification_fall_out due to wrong definitions`.

@viczhang861  Thanks for your comment. It looks better now.

**Comment by mbasmanova** [comment]
@fornaix Thank you for the contribution. @viczhang861 Thanks for reviewing.
