### PR TITLE
Make ST_Centroid try-friendly

### LINKED ISSUE #12404: We need a TRY_ALL() operator that can catch all exceptions
In Presto, we have the TRY() operator, which can wrap some operations and convert certain Exceptions to null -- notably they convert INVALID_FUNCTION_ARGUMENT to null.

The TRY() operator does not convert all Exceptions to null.
In particular, if a UDF hits a bug, the UDF is likely to throw an Exception that will not be handled by TRY().

I am working with some newly written geometric functions which sometimes have hard-to-find bugs.
I'm worried about a situation where one of the rows in my table triggers a hard-to-find bug.
If this happens, it would take months to get a fix released, and the UDF would be unusable until then.

We need a TRY_ALL() operator that would work like TRY() but would convert all Exceptions into nulls.

### PR DESCRIPTION
**Pull request by mbasmanova**
Fixes #12404

### CODE REVIEW

File: presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/GeoFunctions.java [hunk 1]
```diff
@@ -385,22 +385,30 @@ public static Slice stCentroid(@SqlType(GEOMETRY_TYPE_NAME) Slice input)
...
+                    centroid = computePolygonCentroid((Polygon) geometry.getEsriGeometry());
+                    break;
+                case MULTI_POLYGON:
+                    centroid = computeMultiPolygonCentroid((OGCMultiPolygon) geometry);
+                    break;
+                default:
+                    throw new PrestoException(INVALID_FUNCTION_ARGUMENT, "Unexpected geometry type: " + geometryType);
+            }
+        }
+        catch (Exception e) {
```
Comment (arhimondr) [inline presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/GeoFunctions.java]: `RuntimeException`

File: presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/GeoFunctions.java [hunk 2]
```diff
@@ -385,22 +385,30 @@ public static Slice stCentroid(@SqlType(GEOMETRY_TYPE_NAME) Slice input)
...
+            if (e instanceof PrestoException && ((PrestoException) e).getErrorCode() == INVALID_FUNCTION_ARGUMENT.toErrorCode()) {
+                throw e;
+            }
+            throw new PrestoException(INVALID_FUNCTION_ARGUMENT, format("Cannot compute centroid: %s Use ST_IsValid to confirm that input geometry is valid or compute centroid for a bounding box using ST_Envelope.", e.getMessage()));
```
Comment (arhimondr) [inline presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/GeoFunctions.java]: Add original exception as a cause.

**Comment by mbasmanova** [comment]
@arhimondr Andrii, thank you for review. Comments addressed. I'll merge once Travis is green.
