### PR TITLE
Make TestQueryManager#testFailQueryPrerun more reliable

### LINKED ISSUE #15215: Flaky test TestQueryManager.testFailQueryPrerun
Example failure log from travis

```
[ERROR] Tests run: 1036, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,008.992 s <<< FAILURE! - in TestSuite
[ERROR] testFailQueryPrerun(com.facebook.presto.tests.TestQueryManager)  Time elapsed: 0.126 s  <<< FAILURE!
java.lang.AssertionError: unexpected query state: RUNNING
	at org.testng.Assert.fail(Assert.java:94)
	at com.facebook.presto.tests.TestQueryManager.testFailQueryPrerun(TestQueryManager.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-09-23T12:50:10.334-0500	INFO	Thread-4884	com.facebook.airlift.bootstrap.LifeCycleManager	Life cycle stopping...
2020-09-23T12:50:10.335-0500	INFO	Thread-4885	com.facebook.airlift.bootstrap.LifeCycleManager	Life cycle stopping...
2020-09-23T12:50:10.338-0500	INFO	Thread-4889	com.facebook.airlift.bootstrap.LifeCycleManager	Life cycle stopping...
2020-09-23T12:50:10.340-0500	INFO	Thread-4883	com.facebook.airlift.bootstrap.LifeCycleManager	Life cycle stopping...
2020-09-23T12:50:10.341-0500	INFO	Thread-4882	com.facebook.airlift.bootstrap.LifeCycleManager	Life cycle stopping...
2020-09-23T12:50:10.341-0500	INFO	Thread-4890	com.facebook.airlift.bootstrap.LifeCycleManager	Life cycle stopping...
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestQueryManager.testFailQueryPrerun:118 unexpected query state: RUNNING
[INFO] 
[ERROR] Tests run: 1036, Failures: 1, Errors: 0, Skipped: 0
```

### PR DESCRIPTION
**Pull request by tdcmeehan**
Fixes #15215

Test plan - unit test runs

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

File: presto-tests/src/test/java/com/facebook/presto/tests/TestQueryManager.java [hunk 1]
```diff
@@ -111,26 +130,41 @@ public void testFailQueryPrerun()
                 "SELECT * FROM lineitem")
                 .get();
 
+        assertNotEquals(dispatchManager.getStats().getQueuedQueries(), 0L);
```
Comment (jeremy-degroot) [inline presto-tests/src/test/java/com/facebook/presto/tests/TestQueryManager.java:133]: This seems like a weird test assertion; I think you're trying to cause a failure if the dispatchManager behaves differently than expected. If you could use the version of assertNotEquals that takes a message to annotate that, I think it would be helpful.

**Review by jeremy-degroot — CHANGES_REQUESTED** [review]
Mostly looks good to me; I think using this kind of resource manager is a good improvement for this test. Just one change I'd make to make test output clearer.

**Review by jeremy-degroot — APPROVED** [review]
Looks good to me

**Review by caithagoras — APPROVED** [review]
