### PR TITLE
[GeoSpatial] Add xxHash64 operator to Bing Tiles

### LINKED ISSUE #12822: approx_distinct(BingTile) fails because BingTile isn't hashable
```
SELECT approx_distinct(bing_tile(1, 1, 2))
Error: (OPERATOR_NOT_FOUND) 'XX HASH 64' cannot be applied to BingTile
```

Since a bing tile is just 64 bits and can be converted into a long, this should be hashable.

### PR DESCRIPTION
**Pull request by jagill**
In particular, this enables operators like approx_distinct which
requires the object to be xxHashable.

Fixes #12822

### CODE REVIEW

**Comment by jagill** [comment]
The check failed due to "The job exceeded the maximum time limit for jobs, and has been terminated.", which seems unrelated to this PR.

File: presto-geospatial/src/test/java/com/facebook/presto/plugin/geospatial/TestBingTileOperators.java [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+import com.facebook.presto.operator.scalar.AbstractTestFunctions;
+import org.testng.annotations.Test;
+
+import static com.facebook.presto.spi.type.BigintType.BIGINT;
+
+public class TestBingTileOperators
+        extends AbstractTestFunctions
+{
+    @Test
+    public void testApproxDistinct()
```
Comment (mbasmanova) [inline presto-geospatial/src/test/java/com/facebook/presto/plugin/geospatial/TestBingTileOperators.java]: The other operators, distinct-from and equals, are tested in TestBingTileFunctions (see testDistinctFrom and testEquals). For consistency, consider moving this test there or moving existing tests here.
