### PR TITLE
Fix integer overflow when creating a BigIntValues Filter

### LINKED ISSUE #14469: Integer overflow exception when creating a BigIntValue Filter
For an "IN" expression like `IN(Long.MIN_VALUE, 1, 10)`, since the max - min falls in out of range of int we will not be able to use BigintValuesUsingBitmask as the number of bits is max - min + 1.
The check for an valid integer was incomplete where we are not checking if its less than the Integer.MIN_VALUE which can happen because of long wrap around

```
Caused by: java.lang.ArithmeticException: integer overflow
	at java.base/java.lang.Math.toIntExact(Math.java:1071)
	at com.facebook.presto.orc.TupleDomainFilter$BigintValuesUsingBitmask.<init>(TupleDomainFilter.java:636)
	at com.facebook.presto.orc.TupleDomainFilter$BigintValuesUsingBitmask.of(TupleDomainFilter.java:645)
	at com.facebook.presto.orc.TupleDomainFilterUtils.toBigintValues(TupleDomainFilterUtils.java:354)
	at com.facebook.presto.orc.TupleDomainFilterUtils.toFilter(TupleDomainFilterUtils.java:112)
	at com.facebook.presto.hive.orc.TupleDomainFilterCache.lambda$new$0(TupleDomainFilterCache.java:35)
```

### PR DESCRIPTION
**Pull request by bhhari**
Fix Int overflow exception which is caused when calculating (max - min + 1 ) because of long wrap around. 

Fixes #14469 
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

File: presto-orc/src/main/java/com/facebook/presto/orc/TupleDomainFilterUtils.java [hunk 1]
```diff
@@ -347,7 +347,8 @@ public static TupleDomainFilter toBigintValues(long[] values, boolean nullAllowe
         // slots in a hash table), e.g. up to 192 bits per value.
         // Filter based on a bitmap uses (max - min) / num-values bits per value.
         // Choose the filter that uses less bits per value.
-        if ((max - min + 1) > Integer.MAX_VALUE || ((max - min + 1) / values.length) > 192) {
+        long range = max - min + 1;
+        if (range > Integer.MAX_VALUE || range < Integer.MIN_VALUE || (range / values.length) > 192) {
```
Comment (mbasmanova) [inline presto-orc/src/main/java/com/facebook/presto/orc/TupleDomainFilterUtils.java:351]: Since max >= min, range must be > 0. Hence, `range < Integer.MIN_VALUE` check is not needed. Let's remove.

Comment (bhhari) [reply presto-orc/src/main/java/com/facebook/presto/orc/TupleDomainFilterUtils.java:351]: -Long.MIN_VALUE is Long.MIN value, that is why we need the check for < Integer.MIN_VALUE, thats the fix

consider max 10,  min -Long.MIN_VALUE
`10 - Long.MIN_VALUE - 1 = -9223372036854775799`

Comment (bhhari) [reply presto-orc/src/main/java/com/facebook/presto/orc/TupleDomainFilterUtils.java]: There are other corner cases like Long.MAX - Long.MIN + 1 = 0
For such kind of corner cases using a BigInteger gives us accurate results

File: presto-orc/src/main/java/com/facebook/presto/orc/TupleDomainFilterUtils.java [hunk 2]
```diff
@@ -347,7 +348,8 @@ public static TupleDomainFilter toBigintValues(long[] values, boolean nullAllowe
         // slots in a hash table), e.g. up to 192 bits per value.
         // Filter based on a bitmap uses (max - min) / num-values bits per value.
         // Choose the filter that uses less bits per value.
-        if ((max - min + 1) > Integer.MAX_VALUE || ((max - min + 1) / values.length) > 192) {
+        BigInteger range = BigInteger.valueOf(max).subtract(BigInteger.valueOf(min)).add(BigInteger.valueOf(1));
```
Comment (mbasmanova) [inline presto-orc/src/main/java/com/facebook/presto/orc/TupleDomainFilterUtils.java:351]: @bhhari nit: perhaps, put each statement on a separate line for readability and consider using intValueExact instead of longValue

```
        BigInteger range = BigInteger.valueOf(max)
                .subtract(BigInteger.valueOf(min))
                .add(BigInteger.valueOf(1));
       if (range.compareTo(BigInteger.valueOf(Integer.MAX_VALUE)) == 1 || (range.intValueExact() / values.length) > 192) {
            return BigintValuesUsingHashTable.of(min, max, values, nullAllowed);
        }
```
