### PR TITLE
Move LDAP authentication to password authenticator plugin

### LINKED ISSUE #7632: Create authentication plugin for basic auth and move out LDAP
The current [LDAP](https://prestodb.io/docs/current/security/ldap.html) support has two parts:

1. Infrastructure in `LdapFilter` to support basic authentication using user/password.
2. LDAP-specific logic to authenticate a user/password.

We should split this up so that second part is in a plugin, allowing other types of authenticators, such as a list of usernames and passwords stored in a file (using PBKDF2 or similar). The LDAP code would be moved into a plugin.

The new plugin can be modeled after `SystemAccessControl`. We'll have a `BasicAuthenticatorFactory` that creates a `BasicAuthenticator` and allow a single instance configured using `etc/basic-authenticator.properties`. 

The interface only needs one method (for now):
```java
public interface BasicAuthenticator
{
    /**
     * Authenticate the provided user and password.
     *
     * @return the authenticated entity
     * @throws AccessDeniedException if not allowed
     */
    Principal createAuthenticatedPrincipal(String user, String password);
}
```

### PR DESCRIPTION
**Pull request by electrum**
Fixes #7632

### CODE REVIEW

File: presto-main/src/main/java/com/facebook/presto/server/security/PasswordAuthenticatorManager.java [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+import static com.google.common.base.Preconditions.checkState;
+import static com.google.common.base.Strings.isNullOrEmpty;
+import static java.util.Objects.requireNonNull;
+
+public class PasswordAuthenticatorManager
+{
+    private static final Logger log = Logger.get(PasswordAuthenticatorManager.class);
+
+    private static final File CONFIG_FILE = new File("etc/password-authenticator.properties");
+    private static final String PROPERTY_NAME = "password-authenticator.name";
```
Comment (losipiuk) [inline presto-main/src/main/java/com/facebook/presto/server/security/PasswordAuthenticatorManager.java]: `NAME_PROPERTY` will capture intention better.

File: presto-main/src/main/java/com/facebook/presto/server/security/PasswordAuthenticator.java [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+import java.security.Principal;
+import java.util.Base64;
+import java.util.List;
+
+import static com.google.common.base.Strings.nullToEmpty;
+import static com.google.common.net.HttpHeaders.AUTHORIZATION;
+import static java.nio.charset.StandardCharsets.ISO_8859_1;
+import static java.util.Objects.requireNonNull;
+
+public class PasswordAuthenticator
```
Comment (losipiuk) [inline presto-main/src/main/java/com/facebook/presto/server/security/PasswordAuthenticator.java]: I am not huge fan of the name of this class give that:
 * SPI contains interface with the same name
 * that interface is used by this class.

File: presto-main/src/main/java/com/facebook/presto/server/security/PasswordAuthenticator.java [hunk 3]
```diff
@@ -0,0 +1,87 @@
...
+    private final PasswordAuthenticatorManager authenticatorManager;
+
+    @Inject
+    public PasswordAuthenticator(PasswordAuthenticatorManager authenticatorManager)
+    {
+        this.authenticatorManager = requireNonNull(authenticatorManager, "authenticatorManager is null");
+    }
+
+    @Override
+    public Principal authenticate(HttpServletRequest request)
```
Comment (losipiuk) [inline presto-main/src/main/java/com/facebook/presto/server/security/PasswordAuthenticator.java]: Please provide short comment what is the shape of header you are parsing here.

**Comment by losipiuk** [comment]
And please fix the travis failure. It is related to the PR.

File: presto-main/src/main/java/com/facebook/presto/server/PrestoServer.java [hunk 4]
```diff
@@ -129,6 +133,12 @@ public void run()
             injector.getInstance(AccessControlManager.class).loadSystemAccessControl();
             injector.getInstance(EventListenerManager.class).loadConfiguredEventListener();
 
+            Optional<PasswordAuthenticatorManager> passwordAuthenticator = injector.getInstance(
```
[the remark this answers is not in the document]
Comment (electrum) [reply presto-main/src/main/java/com/facebook/presto/server/PrestoServer.java]: I intentionally kept it shorter since it's unambiguous here and the line is already long.

File: presto-main/src/main/java/com/facebook/presto/server/security/PasswordAuthenticator.java (hunk 2 above)
Comment (electrum) [reply presto-main/src/main/java/com/facebook/presto/server/security/PasswordAuthenticator.java]: I agree, though I couldn't think of a better name. Fortunately, the SPI interface is used implicitly in this class, so it doesn't require a fully qualified name. I was thinking of `DelegatingPasswordAuthenticator`, though I'm not sure that's an improvement.

Comment (losipiuk) [reply presto-main/src/main/java/com/facebook/presto/server/security/PasswordAuthenticator.java]: I don't have better name neither. :/ It does not seem `DPA` would be better as suffix is still a bit confusing. Not a big issue. Leave it please as we do not see alternative.

**Comment by electrum** [comment]
Thanks for the fast review! Updated to address comments and fix tests (hopefully).

**Comment by losipiuk** [comment]
> Updated to address comments and fix tests (hopefully).

Thanks!

/lgtm but tests still fail. 
It seems you have to add `ServerSecurityModule` to list of modules used for creating injector in `TestingPrestoServer`.
Or just some bindings from it if adding it as a whole would be problematic.

File: presto-main/src/main/java/com/facebook/presto/server/security/PasswordAuthenticator.java (hunk 2 above)
Comment (dain) [reply presto-main/src/main/java/com/facebook/presto/server/security/PasswordAuthenticator.java]: How about `SystemPasswordAuthenticator`?

Comment (dain) [reply presto-main/src/main/java/com/facebook/presto/server/security/PasswordAuthenticator.java]: Or maybe `BasicAuthenticator` since this handles basic auth?

**Comment by electrum** [comment]
@kokosing, the last commit that moves out LDAP updates the `singlenode-ldap` environment to use the `ldap` password authenticator plugin (by necessity as it's no longer built-in to core server).

**Comment by kokosing** [comment]
@electrum I am sorry, I skimmed that too quickly. Awesome you did that already!

**Comment by electrum** [comment]
@losipiuk Sorry for the noise on the failing tests. I should have mentioned that I was relying on Travis to run the tests and I didn't do much testing locally. I didn't expect anyone to look at it so quickly :)
