### PR TITLE
Fix create table if not exists

### LINKED ISSUE #8607: Create table if not exists may fail with 'Table Already Exists'
The actual create table is done in async commit in another thread that doesn't even have the "if not exists" flag.

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
Fixes #8607.

This PR adds a new method to the connector interface that takes a `failIfExists` flag when creating a table, and propagates that all the way down to the connectors. 

Also, for the case where table already exists we added checks to see whether the existing table has the same schema with the new table to minimize the risk of problems later in a transaction (e.g., a tx with a create table and then an insert).

### CODE REVIEW

File: presto-spi/src/main/java/com/facebook/presto/spi/connector/ConnectorMetadata.java [hunk 1]
```diff
@@ -171,6 +171,15 @@ default void createTable(ConnectorSession session, ConnectorTableMetadata tableM
     }
 
     /**
+     * Creates a table using the specified table metadata. If the table already exists and
+     * failIfExists is true this method should throw an exception.
+     */
+    default void createTable(ConnectorSession session, ConnectorTableMetadata tableMetadata, boolean failIfExists)
```
Comment (electrum) [inline presto-spi/src/main/java/com/facebook/presto/spi/connector/ConnectorMetadata.java]: We should add this parameter to the existing method rather than adding a new method. I also think this should be `ignoreExisting`, since the normal behavior is to throw an exception. (saying `IF NOT EXISTS` / `ignoreExisting` is a special case)

Let's also add the same for `dropTable`, so we can make the incompatible changes at the same time.

File: presto-spi/src/main/java/com/facebook/presto/spi/connector/ConnectorMetadata.java [hunk 2]
```diff
@@ -171,6 +171,15 @@ default void createTable(ConnectorSession session, ConnectorTableMetadata tableM
     }
 
     /**
+     * Creates a table using the specified table metadata. If the table already exists and
+     * failIfExists is true this method should throw an exception.
```
Comment (electrum) [inline presto-spi/src/main/java/com/facebook/presto/spi/connector/ConnectorMetadata.java]: Javadoc nit: Use `{@code failIfExists}` to reference parameter names

File: presto-main/src/main/java/com/facebook/presto/execution/CreateTableTask.java [hunk 3]
```diff
@@ -85,16 +85,79 @@ public String explain(CreateTable statement, List<Expression> parameters)
...
+        LinkedHashMap<String, ColumnMetadata> columns = new LinkedHashMap<>();
+        Map<String, Object> inheritedProperties = new HashMap<>();
+        prepareColumnMetadata(statement, metadata, session, tableName, columns, inheritedProperties);
+
         Optional<TableHandle> tableHandle = metadata.getTableHandle(session, tableName);
         if (tableHandle.isPresent()) {
+            TableMetadata tableMetadata = metadata.getTableMetadata(session, tableHandle.get());
             if (!statement.isNotExists()) {
-                throw new SemanticException(TABLE_ALREADY_EXISTS, statement, "Table '%s' already exists", tableName);
+                if (columnsEquals(columns.values(), tableMetadata.getColumns())) {
```
Comment (electrum) [inline presto-main/src/main/java/com/facebook/presto/execution/CreateTableTask.java]: I don't think we should add this check. It changes the semantics of the operation and seems to be arbitrary in how it compares the schema. For example, it ignores properties, which can be a fundamental part of the table definition.

Comment (nezihyigitbasi) [inline presto-main/src/main/java/com/facebook/presto/execution/CreateTableTask.java]: This was a result of a discussion where we decided to be consistent with the checks we do here and in `SemiTransactionalHiveMetastore`, and also to be consistent with the error messages we report back to the client. 

Regarding the properties, I only did the basic check of the column name/type, but you are right this is sort of arbitrary, we can add that here too.

Comment (electrum) [inline presto-main/src/main/java/com/facebook/presto/execution/CreateTableTask.java]: The semantics for `CREATE TABLE IF NOT EXISTS` is that it ignores the error if the table already exists. There are no rules about it having the same schema. Connectors are free to impose their own restrictions, but these are connector specific and shouldn't be part of the engine.

File: presto-main/src/main/java/com/facebook/presto/execution/CreateTableTask.java [hunk 4]
```diff
@@ -85,16 +85,79 @@ public String explain(CreateTable statement, List<Expression> parameters)
...
+        else {
+            metadata.createTable(session, tableName.getCatalogName(), tableMetadata);
+        }
+
+        return immediateFuture(null);
+    }
+
+    private boolean columnsEquals(Collection<ColumnMetadata> createTableColumns, Collection<ColumnMetadata> metadataColumns)
+    {
+        // we only check for the name and type of the columns
```
Comment (electrum) [inline presto-main/src/main/java/com/facebook/presto/execution/CreateTableTask.java]: This comment is a good indication that this check shouldn't be here.

File: presto-main/src/main/java/com/facebook/presto/testing/TestingMetadata.java [hunk 5]
```diff
@@ -173,6 +173,19 @@ public void createTable(ConnectorSession session, ConnectorTableMetadata tableMe
     }
 
     @Override
+    public void createTable(ConnectorSession session, ConnectorTableMetadata tableMetadata, boolean failIfExists)
+    {
+        try {
+            createTable(session, tableMetadata);
+        }
+        catch (IllegalArgumentException e) {
```
Comment (electrum) [inline presto-main/src/main/java/com/facebook/presto/testing/TestingMetadata.java]: This very generic exception often indicates a bug due to invariant violations, so we should avoid catching it. Can we make this a more specific exception?

File: presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java [hunk 6]
```diff
@@ -1739,6 +1758,12 @@ public String getQueryId()
             return queryId;
         }
 
+        @JsonProperty
```
Comment (electrum) [inline presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java]: Note that JSON serialization was removed in 3c8913761176675a4fc85246c64d2369faae811c, so make sure to remove when rebasing

File: presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java [hunk 7]
```diff
@@ -1693,9 +1705,15 @@ private void checkHoldsLock()
         private final T data;
         private final String user;
         private final String queryId;
+        private final Map<ActionParameter, Boolean> actionParameters;
```
Comment (electrum) [inline presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java]: We already have action parameters: the `data` field. This flag is specific to creating a table, so it should go in `TableAndMore`.

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestDistributedQueries.java [hunk 8]
```diff
@@ -133,6 +133,12 @@ public void testCreateTable()
         assertTrue(getQueryRunner().tableExists(getSession(), "test_create"));
         assertTableColumnNames("test_create", "a", "b", "c");
 
+        assertQueryFails("CREATE TABLE test_create (a bigint, b double, c varchar)",
+                "(.*)Table '(\\w+).tpch.test_create' already exists");
```
Comment (electrum) [inline presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestDistributedQueries.java]: I think this is easier to read without wrapping, since it keeps the SQL together

File: presto-raptor/src/main/java/com/facebook/presto/raptor/RaptorMetadata.java [hunk 9]
```diff
@@ -424,7 +424,14 @@ public void createTable(ConnectorSession session, ConnectorTableMetadata tableMe
     @Override
     public void createTable(ConnectorSession session, ConnectorTableMetadata tableMetadata, boolean failIfExists)
     {
-        createTable(session, tableMetadata);
+        try {
```
Comment (electrum) [inline presto-raptor/src/main/java/com/facebook/presto/raptor/RaptorMetadata.java]: We shouldn't need to do anything for Raptor or other non-transactional connectors, since the table creation is done directly in the `createTable()` call and thus the normal handling in the engine will cover it.

**Comment by electrum** [comment]
Thanks for looking into this. I thought it would be much more difficult to fix,

**Comment by nezihyigitbasi** [comment]
@electrum all comments addressed.

**Comment by nezihyigitbasi** [comment]
build broken due to #8983.

File: presto-hive/src/main/java/com/facebook/presto/hive/HiveMetadata.java [hunk 10]
```diff
@@ -1041,7 +1046,7 @@ public void createView(ConnectorSession session, SchemaTableName viewName, Strin
         }
 
         try {
-            metastore.createTable(session, table, principalPrivileges, Optional.empty());
+            metastore.createTable(session, table, principalPrivileges, Optional.empty(), true);
```
Comment (haozhun) [inline presto-hive/src/main/java/com/facebook/presto/hive/HiveMetadata.java]: This should be `false`. Is this a typo?

File: presto-hive/src/main/java/com/facebook/presto/hive/HiveMetadata.java [hunk 11]
```diff
@@ -753,7 +758,7 @@ public HiveOutputTableHandle beginCreateTable(ConnectorSession session, Connecto
             }
         }
 
-        metastore.createTable(session, table, principalPrivileges, Optional.of(writePath));
+        metastore.createTable(session, table, principalPrivileges, Optional.of(writePath), true);
```
Comment (haozhun) [inline presto-hive/src/main/java/com/facebook/presto/hive/HiveMetadata.java]: This should be `false`. Is this a typo?

**Comment by haozhun** [comment]
@electrum 

Recently, you told me that we should try to make the changes backward compatible when making SPI changes whenever possible. By that suggestion, 

```
void createTable(Session session, String catalogName, ConnectorTableMetadata tableMetadata);
```

should be changed to

```
@Deprecated
void createTable(Session session, String catalogName, ConnectorTableMetadata tableMetadata);

default void createTable(Session session, String catalogName, ConnectorTableMetadata tableMetadata, boolean ignoreExisting) {
    if (ignoreExisting) {
        throw new UnsupportedOperationException();
    }
    createTable(session, catalog, tableMetadata);
}
```

But it looks like you were giving the opposite suggestion in this pull request?

**Comment by haozhun** [comment]
@electrum 

I disagree to the changes you requested for "dropTable". Introducing dead code to avoid an SPI change that may or may not be needed in the future doesn't sound right.

File: presto-main/src/test/java/com/facebook/presto/execution/TestCreateTableTask.java [hunk 12]
```diff
@@ -143,10 +143,17 @@ public MockMetadata(
         }
 
         @Override
-        public void createTable(Session session, String catalogName, ConnectorTableMetadata tableMetadata)
+        public void createTable(Session session, String catalogName, ConnectorTableMetadata tableMetadata, boolean ignoreExisting)
+        {
+            doCreateTable(session, catalogName, tableMetadata, ignoreExisting);
+        }
+
+        private void doCreateTable(Session session, String catalogName, ConnectorTableMetadata tableMetadata, boolean ignoreExisting)
```
Comment (haozhun) [inline presto-main/src/test/java/com/facebook/presto/execution/TestCreateTableTask.java]: inline this?

File: presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java [hunk 13]
```diff
@@ -2031,55 +2051,100 @@ public void run()
...
-                    if (remoteTable.isPresent() && getPrestoQueryId(remoteTable.get()).equals(getPrestoQueryId(table))) {
+                handleException(metastore, e);
+            }
+        }
+
+        private void handleException(ExtendedHiveMetastore metastore, RuntimeException exception)
+        {
+            try {
+                Optional<Table> existingTable = metastore.getTable(newTable.getDatabaseName(), newTable.getTableName());
+                existingTable.ifPresent(table -> {
```
Comment (haozhun) [inline presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java]: Can you change this back to `if (remoteTable.isPresent() {` please? When you have a multiple-line lambda like this, using `ifPresent` makes code harder to read.

File: presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java [hunk 14]
```diff
@@ -2031,55 +2051,100 @@ public void run()
...
+                    else {
+                        // if the table definition in the metastore is different than what this tx wants to create
+                        // then there is a conflict, e.g., current tx wants to create T(a: bigint),
+                        // but another tx already created T(a: varchar)
+                        // this may be a problem if there is an insert after this step, so we fail early.
+                        if (!hasTheSameSchema(newTable, table)) {
+                            throw new TableAlreadyExistsException(
+                                    new SchemaTableName(newTable.getDatabaseName(), newTable.getTableName()),
+                                    format("Table already exists with a different schema: '%s'", newTable.getTableName()),
+                                    exception);
```
Comment (haozhun) [inline presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java]: I would inline `handleException` and change this line to `e = new TableAlreadyExistsException(...`

File: presto-hive/src/test/java/com/facebook/presto/hive/AbstractTestHiveClient.java [hunk 15]
```diff
@@ -1730,6 +1731,89 @@ public void testTableCreationRollback()
...
+                transaction.getMetastore(schemaName)
+                        .createTable(session, table, new PrincipalPrivileges(ImmutableMultimap.of(), ImmutableMultimap.of()), Optional.empty(), false);
+                transaction.commit();
+                fail("Expected exception");
+            }
+            catch (PrestoException e) {
+                assertInstanceOf(e, TableAlreadyExistsException.class);
+            }
+
+            // try creating it again from another transaction with ignoreExisting = false
```
Comment (haozhun) [inline presto-hive/src/test/java/com/facebook/presto/hive/AbstractTestHiveClient.java]: should say `= true`

**Comment by electrum** [comment]
We should avoid making backwards incompatible changes. But if a change needs to be made, just make it, rather than leaving a weird API and cruft that needs to be cleaned up later.

**Comment by electrum** [comment]
I meant that we should fix drop table at the same time. It has the same problem.

File: presto-main/src/main/java/com/facebook/presto/execution/CreateTableTask.java [hunk 16]
```diff
@@ -163,16 +162,7 @@ else if (element instanceof LikeClause) {
...
-        try {
-            metadata.createTable(session, tableName.getCatalogName(), tableMetadata);
-        }
-        catch (PrestoException e) {
-            if (!e.getErrorCode().equals(ALREADY_EXISTS.toErrorCode()) || !statement.isNotExists()) {
-                throw e;
-            }
-        }
-
+        metadata.createTable(session, tableName.getCatalogName(), tableMetadata, statement.isNotExists());
```
Comment (haozhun) [inline presto-main/src/main/java/com/facebook/presto/execution/CreateTableTask.java]: Based on discussion with @electrum, let's revert this. Add a comment that this is needed when connectors don't handle the ignoreExisting flag, which is optional.

**Comment by nezihyigitbasi** [comment]
@electrum @haozhun comments addressed, thanks for reviewing.

File: presto-main/src/main/java/com/facebook/presto/execution/CreateTableTask.java [hunk 17]
```diff
@@ -163,16 +163,15 @@ else if (element instanceof LikeClause) {
         Map<String, Object> finalProperties = combineProperties(statement.getProperties().keySet(), properties, inheritedProperties);
 
         ConnectorTableMetadata tableMetadata = new ConnectorTableMetadata(tableName.asSchemaTableName(), ImmutableList.copyOf(columns.values()), finalProperties, statement.getComment());
-
+        //try/catch is needed when connectors don't handle the ignoreExisting flag, which is optional.
```
Comment (haozhun) [inline presto-main/src/main/java/com/facebook/presto/execution/CreateTableTask.java]: Add space after `//`. Use `try-catch` instead of `try/catch`

File: presto-hive/src/main/java/com/facebook/presto/hive/HiveMetadata.java [hunk 18]
```diff
@@ -662,9 +662,21 @@ public void dropTable(ConnectorSession session, ConnectorTableHandle tableHandle
 
         Optional<Table> target = metastore.getTable(handle.getSchemaName(), handle.getTableName());
         if (!target.isPresent()) {
```
Comment (haozhun) [inline presto-hive/src/main/java/com/facebook/presto/hive/HiveMetadata.java]: What about skip the `getTable` entirely and remove `if (!target.isPresent())` here? Instead, we could just go issue a drop table regardless, and handle the TableNotFound there.

Comment (nezihyigitbasi) [reply presto-hive/src/main/java/com/facebook/presto/hive/HiveMetadata.java]: I initially did it this way to keep the old behavior as unchanged as possible, but this makes sense, so updated.

File: presto-spi/src/main/java/com/facebook/presto/spi/connector/ConnectorMetadata.java [hunk 19]
```diff
@@ -163,9 +163,10 @@ default void renameSchema(ConnectorSession session, String source, String target
     }
 
     /**
-     * Creates a table using the specified table metadata.
+     * Creates a table using the specified table metadata. If the table already exists and
+     * {@code ignoreExisting} is false this method should throw an exception.
```
Comment (electrum) [inline presto-spi/src/main/java/com/facebook/presto/spi/connector/ConnectorMetadata.java]: How about
```java
/**
 * Creates a table using the specified table metadata.
 *
 * @throws PrestoException with {@code ALREADY_EXISTS} if the table already exists and {@param ignoreExisting} is not set
 */

File: presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java [hunk 20]
```diff
@@ -2031,35 +2042,56 @@ public void run()
...
+                metastore.createTable(newTable, privileges);
                 done = true;
             }
             catch (RuntimeException e) {
                 try {
-                    Optional<Table> remoteTable = metastore.getTable(table.getDatabaseName(), table.getTableName());
-                    // getPrestoQueryId(partition) is guaranteed to be non-empty. It is asserted in the constructor.
-                    if (remoteTable.isPresent() && getPrestoQueryId(remoteTable.get()).equals(getPrestoQueryId(table))) {
-                        done = true;
+                    Optional<Table> existingTable = metastore.getTable(newTable.getDatabaseName(), newTable.getTableName());
```
Comment (electrum) [inline presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java]: See if you can write this like
```java
metastore.getTable(...).ifPresent(table -> {
    ...
}

File: presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java [hunk 21]
```diff
@@ -2031,35 +2042,56 @@ public void run()
...
+                    if (existingTable.isPresent()) {
+                        Table table = existingTable.get();
+                        // getPrestoQueryId(newTable) is guaranteed to be non-empty. It is asserted in the constructor.
```
Comment (electrum) [inline presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java]: This is strange. Why not just store it in the constructor?
```java
this.queryId = getPrestoQueryId(newTable)
        .orElseThrow(() -> new IllegalArgumentException(...));

File: presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java [hunk 22]
```diff
@@ -2031,35 +2042,56 @@ public void run()
...
+                        if (getPrestoQueryId(table).equals(getPrestoQueryId(newTable))) {
+                            done = true;
```
Comment (electrum) [inline presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java]: Add a comment here. I assume it should be something like
```java
// ignore table if it was already created by us due to retry

File: presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java [hunk 23]
```diff
@@ -2031,35 +2042,56 @@ public void run()
...
+                        }
+                        else {
+                            // if the table definition in the metastore is different than what this tx wants to create
```
Comment (electrum) [inline presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java]: Make these sentences: capitalize and end in period

File: presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java [hunk 24]
```diff
@@ -2031,35 +2042,56 @@ public void run()
...
+                            // then there is a conflict, e.g., current tx wants to create T(a: bigint),
+                            // but another tx already created T(a: varchar)
+                            // this may be a problem if there is an insert after this step
+                            if (!hasTheSameSchema(newTable, table)) {
+                                e = new TableAlreadyExistsException(
```
Comment (electrum) [inline presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java]: Hmm, I'm thinking this should throw `TRANSACTION_CONFLICT`. @haozhun thoughts?

File: presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java [hunk 25]
```diff
@@ -2068,18 +2100,38 @@ public void run(ExtendedHiveMetastore metastore)
...
                 }
             }
+            tableCreated = true;
+        }
+
+        private boolean hasTheSameSchema(Table newTable, Table existingTable)
+        {
+            List<Column> newTableColumns = newTable.getDataColumns();
+            List<Column> existingTableColumns = existingTable.getDataColumns();
+            // we only check for the name and type of the columns
```
Comment (electrum) [inline presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java]: This comment is out of place for the Hive connector. Probably just delete it? Or mention why we only validate name and type (it's fine if column comments are different because queries won't fail)?

File: presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java [hunk 26]
```diff
@@ -2068,18 +2100,38 @@ public void run(ExtendedHiveMetastore metastore)
...
+            // as some connectors can fill in the other fields of
+            // columns with arbitrary data (e.g., AccumuloConnector)
+            for (Column existingColumn : existingTableColumns) {
+                Optional<Column> createTableColumnMetadata = newTableColumns.stream()
```
Comment (electrum) [inline presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java]: Use `anyMatch()` since you don't care about the value

File: presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java [hunk 27]
```diff
@@ -2068,18 +2100,38 @@ public void run(ExtendedHiveMetastore metastore)
                     // Not deleting the table may leave garbage behind. The former is much more dangerous than the latter.
                     // Therefore, the table is not considered added.
                 }
+
                 if (!done) {
                     throw e;
                 }
             }
+            tableCreated = true;
```
Comment (electrum) [inline presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java]: Put this at the end of the try block. It's hard to see since the catch block is huge

File: presto-hive/src/test/java/com/facebook/presto/hive/AbstractTestHiveClient.java [hunk 28]
```diff
@@ -1730,6 +1731,89 @@ public void testTableCreationRollback()
...
+        String schemaName = schemaTableName.getSchemaName();
+        String tableName = schemaTableName.getTableName();
+        Path targetPath;
+        try {
+            try (Transaction transaction = newTransaction()) {
+                LocationService locationService = getLocationService(schemaName);
+                LocationHandle locationHandle = locationService.forNewTable(transaction.getMetastore(schemaName), session, schemaName, tableName);
+                targetPath = locationService.targetPathRoot(locationHandle);
+                Table table = createSimpleTable(schemaTableName, columns, session, targetPath, "q1");
+                transaction.getMetastore(schemaName)
```
Comment (electrum) [inline presto-hive/src/test/java/com/facebook/presto/hive/AbstractTestHiveClient.java]: Put the privileges at the top of the method. Will get rid of some repeated noise
```java
PrincipalPrivileges privileges = new PrincipalPrivileges(ImmutableMultimap.of(), ImmutableMultimap.of());

File: presto-hive/src/test/java/com/facebook/presto/hive/AbstractTestHiveClient.java [hunk 29]
```diff
@@ -1730,6 +1731,89 @@ public void testTableCreationRollback()
...
+                        .createTable(session, table, new PrincipalPrivileges(ImmutableMultimap.of(), ImmutableMultimap.of()), Optional.empty(), false);
+                Optional<Table> tableHandle = transaction.getMetastore(schemaName).getTable(schemaName, tableName);
+                assertTrue(tableHandle.isPresent());
+                transaction.commit();
+            }
+
+            // try creating it again from another transaction with ignoreExisting = false
```
Comment (electrum) [inline presto-hive/src/test/java/com/facebook/presto/hive/AbstractTestHiveClient.java]: Nit: I think this is easier to read without spaces (Python style)
```java
// try creating it again from another transaction with ignoreExisting=false

File: presto-hive/src/test/java/com/facebook/presto/hive/AbstractTestHiveClient.java [hunk 30]
```diff
@@ -1730,6 +1731,89 @@ public void testTableCreationRollback()
...
+        Table.Builder tableBuilder = Table.builder()
+                .setDatabaseName(schemaName)
+                .setTableName(tableName)
+                .setOwner(tableOwner)
+                .setTableType(TableType.MANAGED_TABLE.name())
+                .setParameters(ImmutableMap.of(
+                        PRESTO_VERSION_NAME, TEST_SERVER_VERSION,
+                        PRESTO_QUERY_ID_NAME, queryId))
+                .setDataColumns(columns);
+        tableBuilder.getStorageBuilder()
```
Comment (electrum) [inline presto-hive/src/test/java/com/facebook/presto/hive/AbstractTestHiveClient.java]: Add a `withStorage()` method to `Table.Builder` like `Partition.Builder` has, then you can do
```java
return Table.builder()
        ...
        .withStorage(storage -> storage
                .setLocation(targetPath.toString())
                .setStorageFormat(...)
                .setSerdeParameters(ImmutableMap.of()))
        .build();

File: presto-hive/src/test/java/com/facebook/presto/hive/AbstractTestHiveClient.java [hunk 31]
```diff
@@ -1730,6 +1731,89 @@ public void testTableCreationRollback()
...
+                .setLocation(targetPath.toString())
+                .setStorageFormat(StorageFormat.create(ORC.getSerDe(), ORC.getInputFormat(), ORC.getOutputFormat()))
```
Comment (electrum) [inline presto-hive/src/test/java/com/facebook/presto/hive/AbstractTestHiveClient.java]: I think you can use `fromHiveStorageFormat(ORC)`

File: presto-main/src/main/java/com/facebook/presto/metadata/Metadata.java [hunk 32]
```diff
@@ -120,9 +120,10 @@
     void renameSchema(Session session, CatalogSchemaName source, String target);
 
     /**
-     * Creates a table using the specified table metadata.
+     * Creates a table using the specified table metadata. If the table already exists and
```
Comment (electrum) [inline presto-main/src/main/java/com/facebook/presto/metadata/Metadata.java]: See my Javadoc recommendation on the SPI version

File: presto-main/src/main/java/com/facebook/presto/execution/CreateTableTask.java [hunk 33]
```diff
@@ -163,16 +163,15 @@ else if (element instanceof LikeClause) {
         Map<String, Object> finalProperties = combineProperties(statement.getProperties().keySet(), properties, inheritedProperties);
 
         ConnectorTableMetadata tableMetadata = new ConnectorTableMetadata(tableName.asSchemaTableName(), ImmutableList.copyOf(columns.values()), finalProperties, statement.getComment());
-
+        // try/catch is needed when connectors don't handle the ignoreExisting flag, which is optional.
```
Comment (electrum) [inline presto-main/src/main/java/com/facebook/presto/execution/CreateTableTask.java]: Let's move this comment to inside the catch block:
```java
// connectors are not required to handle the ignoreExisting flag

File: presto-main/src/main/java/com/facebook/presto/execution/CreateTableTask.java [hunk 34]
```diff
@@ -163,16 +163,15 @@ else if (element instanceof LikeClause) {
...
         try {
-            metadata.createTable(session, tableName.getCatalogName(), tableMetadata);
+            metadata.createTable(session, tableName.getCatalogName(), tableMetadata, statement.isNotExists());
```
Comment (electrum) [inline presto-main/src/main/java/com/facebook/presto/execution/CreateTableTask.java]: We need to make sure every commit compiles and passes tests (so you can bisect later). Squashing this commit into the previous one is probably easiest.

File: presto-spi/src/main/java/com/facebook/presto/spi/connector/ConnectorMetadata.java [hunk 35]
```diff
@@ -172,11 +172,12 @@ default void createTable(ConnectorSession session, ConnectorTableMetadata tableM
     }
 
     /**
-     * Drops the specified table
+     * Drops the specified table. If the table doesn't exist and
+     * {@code ignoreNonExisting} is false this method should throw an exception.
      *
-     * @throws RuntimeException if the table can not be dropped or table handle is no longer valid
+     * @throws RuntimeException if the table can not be dropped or table handle is no longer valid (when {@code ignoreNonExisting} is false)
```
Comment (electrum) [inline presto-spi/src/main/java/com/facebook/presto/spi/connector/ConnectorMetadata.java]: Use `@param`

File: presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java (hunk 20 above)
Comment (nezihyigitbasi) [reply presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java]: I wrote it initially like that, but based on the first set of comments I got I switched to this version.

File: presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java (hunk 27 above)
Comment (nezihyigitbasi) [reply presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java]: Putting it at the end of the outer try block will be incorrect as we should also set `tableCreated=true` in some cases on exception. It's also not correct to put it at the end of the inner try block either.

File: presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java (hunk 24 above)
Comment (nezihyigitbasi) [reply presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java]: Will update to `TRANSACTION_CONFLICT` per offline discussion.

File: presto-hive/src/test/java/com/facebook/presto/hive/AbstractTestHiveClient.java (hunk 28 above)
Comment (nezihyigitbasi) [reply presto-hive/src/test/java/com/facebook/presto/hive/AbstractTestHiveClient.java]: done.

File: presto-main/src/main/java/com/facebook/presto/testing/TestingMetadata.java [hunk 36]
```diff
@@ -166,10 +167,12 @@ public void renameTable(ConnectorSession session, ConnectorTableHandle tableHand
     }
 
     @Override
-    public void createTable(ConnectorSession session, ConnectorTableMetadata tableMetadata)
+    public void createTable(ConnectorSession session, ConnectorTableMetadata tableMetadata, boolean ignoreExisting)
     {
         ConnectorTableMetadata existingTable = tables.putIfAbsent(tableMetadata.getTable(), tableMetadata);
-        checkArgument(existingTable == null, "Table %s already exists", tableMetadata.getTable());
+        if (existingTable != null && !ignoreExisting) {
+            throw new IllegalArgumentException(format("Table %s already exists", tableMetadata.getTable()));
```
Comment (electrum) [inline presto-main/src/main/java/com/facebook/presto/testing/TestingMetadata.java]: Make the message format match `renameTable()` above

File: presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java [hunk 37]
```diff
@@ -2068,18 +2098,34 @@ public void run(ExtendedHiveMetastore metastore)
...
+        }
+
+        private boolean hasTheSameSchema(Table newTable, Table existingTable)
+        {
+            List<Column> newTableColumns = newTable.getDataColumns();
+            List<Column> existingTableColumns = existingTable.getDataColumns();
+            for (Column existingColumn : existingTableColumns) {
+                boolean found = newTableColumns.stream()
+                        .anyMatch(newColumn -> newColumn.getName().equals(existingColumn.getName()) && newColumn.getType().equals(existingColumn.getType()));
```
Comment (electrum) [inline presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java]: Probably easier to read if you wrap after the `&&`

File: presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java [hunk 38]
```diff
@@ -2068,18 +2098,34 @@ public void run(ExtendedHiveMetastore metastore)
...
+                if (!found) {
```
Comment (electrum) [inline presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java]: You can use `noneMatch()` to avoid the negation. Also, probably easier to read if you inline this

Comment (electrum) [reply presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java]:
```java
if (newTableColumns.stream().noneMatch(newColumn ->
        newColumn.getName().equals(existingColumn.getName()) &&
                newColumn.getType().equals(existingColumn.getType()))) {
    return;
}
```
(the extra indentation is unfortunate)

File: presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java [hunk 39]
```diff
@@ -2068,18 +2098,34 @@ public void run(ExtendedHiveMetastore metastore)
...
                 }
+
                 if (!done) {
                     throw e;
                 }
             }
+            tableCreated = true;
+        }
+
+        private boolean hasTheSameSchema(Table newTable, Table existingTable)
```
Comment (electrum) [inline presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java]: I think this method is either incorrect or incorrectly named. It seems to be checking if the existing table is a superset of the new table (but is allowed to have extra columns).

Comment (nezihyigitbasi) [reply presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java]: I guess It's the other way around (newTable can be a superset of existingTable based on this impl.) and I think I broke this during refactoring. This should check for equality. I will update this before merging.
