### PR TITLE
Fix JOIN ... USING semantics

### LINKED ISSUE #2311: Fix USING clause for JOINs
Columns that appear in a `USING` clause should not require qualification. This is particularly useful for outer joins, because the non-qualified reference always references the non-null value. It is not clear if qualifying reference is allowed: PostgreSQL allows it but Oracle does not. Allowing it is useful in order to do `IS NULL` checks for outer joins, especially when no other columns are available.

```
presto> select x from (values (1)) a (x) join (values (1)) b (x) using (x);
Query 20150202_160415_12625_wu6ji failed: Column 'x' is ambiguous
```

Additionally, because `USING` makes them the same column, the column should only appear once in the output descriptor:

```
presto> select * from (values (1)) a (x) join (values (1)) b (x) using (x);
 x | x 
---+---
 1 | 1 
(1 row)
```

Correct behavior for the above:

```
postgresql=# select x from (values (1)) a (x) join (values (1)) b (x) using (x);
 x 

---
 1
(1 row)

postgresql=# select * from (values (1)) a (x) join (values (1)) b (x) using (x);
 x 

---
 1
(1 row)
```

Additional test cases that should return the value from the outside of the join:

``` sql
SELECT x FROM (VALUES (1), (2)) a (x) LEFT JOIN (VALUES (1)) b (x) USING (x);
SELECT x FROM (VALUES (1)) a (x) RIGHT JOIN (VALUES (1), (2)) b (x) USING (x);
```

### PR DESCRIPTION
**Pull request by martint**
Given T(k1, .., kn, a1, ..., an) and U(k1, ... kn, b1, ..., bn),
the output of t JOIN u USING (k1, ..., kn) is expected to be a
table with the following schema:

(k1, ..., kn, a1, ..., an, b1, ..., bn)

The fields a_i and b_i are resolvable using the aliases for the
left and right tables. k_i are derived from coalesce(t.k_i, u.k_i)

Fixes #2311

### CODE REVIEW

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/Analysis.java [hunk 1]
```diff
@@ -614,4 +626,40 @@ public TableHandle getTarget()
...
+    public static final class JoinUsingAnalysis
+    {
+        private final List<Integer> leftJoinFields;
+        private final List<Integer> rightJoinFields;
+        private final List<Integer> otherLeftFields;
+        private final List<Integer> otherRightFields;
+
+        public JoinUsingAnalysis(List<Integer> leftJoinFields, List<Integer> rightJoinFields, List<Integer> otherLeftFields, List<Integer> otherRightFields)
+        {
+            this.leftJoinFields = leftJoinFields;
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/Analysis.java]: `requireNonNull` and `Immutable.copyOf`?

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java [hunk 2]
```diff
@@ -1116,34 +1116,76 @@ protected Scope visitJoin(Join node, Optional<Scope> scope)
...
-            if (node.getType() == Join.Type.CROSS || node.getType() == Join.Type.IMPLICIT) {
-                return output;
-            }
-
             if (criteria instanceof JoinUsing) {
-                // TODO: implement proper "using" semantics with respect to output columns
                 List<Identifier> columns = ((JoinUsing) criteria).getColumns();
 
-                List<Expression> expressions = new ArrayList<>();
+                List<Field> joinFields = new ArrayList<>();
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java]: maybe you could extract this `if` block content as method? Just to make it more readable.

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java [hunk 3]
```diff
@@ -1116,34 +1116,76 @@ protected Scope visitJoin(Join node, Optional<Scope> scope)
...
+
+                List<Integer> leftJoinFields = new ArrayList<>();
+                List<Integer> rightJoinFields = new ArrayList<>();
+
+                Set<Identifier> seen = new HashSet<>();
                 for (Identifier column : columns) {
-                    Expression leftExpression = new Identifier(column.getValue());
-                    Expression rightExpression = new Identifier(column.getValue());
+                    if (seen.contains(column)) {
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java]: you could use `if(!seen.add(..))`

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java [hunk 4]
```diff
@@ -1116,34 +1116,76 @@ protected Scope visitJoin(Join node, Optional<Scope> scope)
...
+                    }
+                }
+
+                List<Integer> rightFields = new ArrayList<>();
+                for (int i = 0; i < right.getRelationType().getAllFieldCount(); i++) {
+                    if (!rightJoinFields.contains(i)) {
+                        builder.add(right.getRelationType().getFieldByIndex(i));
+                        rightFields.add(i);
+                    }
+                }
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java]: this `for` code block is the same for `left` and `right` relation, please extract method

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java [hunk 5]
```diff
@@ -1116,34 +1116,76 @@ protected Scope visitJoin(Join node, Optional<Scope> scope)
...
+                    joinFields.add(Field.newUnqualified(column.getValue(), type.get()));
 
-                    addCoercionForJoinCriteria(node, leftExpression, rightExpression);
-                    expressions.add(new ComparisonExpression(EQUAL, leftExpression, rightExpression));
+                    leftJoinFields.add(leftField.get().getRelationFieldIndex());
+                    rightJoinFields.add(rightField.get().getRelationFieldIndex());
                 }
 
-                analysis.setJoinCriteria(node, ExpressionUtils.and(expressions));
+                ImmutableList.Builder<Field> builder = ImmutableList.builder();
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java]: Can you please use better name than `builder`. Maybe `output`?

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/Analysis.java (hunk 1 above)
Comment (kokosing) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/Analysis.java]: Can you please add `checkArgument` that `leftJoinFields` size is equal to `rightJoinFields`?

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java [hunk 6]
```diff
@@ -1116,34 +1116,76 @@ protected Scope visitJoin(Join node, Optional<Scope> scope)
...
+
+                List<Integer> leftJoinFields = new ArrayList<>();
+                List<Integer> rightJoinFields = new ArrayList<>();
+
+                Set<Identifier> seen = new HashSet<>();
                 for (Identifier column : columns) {
-                    Expression leftExpression = new Identifier(column.getValue());
-                    Expression rightExpression = new Identifier(column.getValue());
+                    if (seen.contains(column)) {
+                        throw new SemanticException(DUPLICATE_COLUMN_NAME, column, "Column '%s' appears multiple times in USING clause", column.getValue());
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java]: Is it really a semantic exception? To me it does not matter if some one write `USING(a)` or `USING(a,a,a,a)`. It is still semantically the same as `USING(a)`. Notice it is legal to write `ORDER BY a,a,a,a`.

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java [hunk 7]
```diff
@@ -1116,34 +1116,76 @@ protected Scope visitJoin(Join node, Optional<Scope> scope)
...
+                    try {
+                        metadata.getFunctionRegistry().resolveOperator(OperatorType.EQUAL, ImmutableList.of(
+                                leftField.get().getType(), rightField.get().getType()));
+                    }
+                    catch (OperatorNotFoundException e) {
+                        throw new SemanticException(TYPE_MISMATCH, node, "%s", e.getMessage());
+                    }
+
+                    Optional<Type> type = metadata.getTypeManager().getCommonSuperType(leftField.get().getType(), rightField.get().getType());
+                    analysis.addTypes(ImmutableMap.of(NodeRef.of(column), type.get()));
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java]: Please make sure that `type` is present. Maybe `checkState` or `verify`

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java [hunk 8]
```diff
@@ -1116,34 +1116,76 @@ protected Scope visitJoin(Join node, Optional<Scope> scope)
...
+                        throw new SemanticException(DUPLICATE_COLUMN_NAME, column, "Column '%s' appears multiple times in USING clause", column.getValue());
+                    }
+                    seen.add(column);
+
+                    QualifiedName columnName = QualifiedName.of(column.getValue());
+                    Optional<ResolvedField> leftField = left.tryResolveField(column, columnName);
+                    Optional<ResolvedField> rightField = right.tryResolveField(column, columnName);
+
+                    if (!leftField.isPresent() || !rightField.isPresent()) {
+                        throw missingAttributeException(column, columnName);
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java]: maybe we could say which relation is missing this column. What do you think?

File: presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java [hunk 9]
```diff
@@ -366,6 +372,112 @@ else if (firstDependencies.stream().allMatch(right::canResolve) && secondDepende
...
     }
 
+    private RelationPlan planJoinUsing(Join node, RelationPlan left, RelationPlan right)
+    {
+        /* Given: l JOIN r USING (k1, ..., kn)
+
+           produces:
+
+            - project
+                    coalesce(l.k1, r.k1)
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java]: is `coalesce` needed? In case any of them is null then join condition would not be met.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java [hunk 10]
```diff
@@ -366,6 +372,112 @@ else if (firstDependencies.stream().allMatch(right::canResolve) && secondDepende
         return new RelationPlan(root, analysis.getScope(node), outputSymbols);
     }
 
+    private RelationPlan planJoinUsing(Join node, RelationPlan left, RelationPlan right)
+    {
+        /* Given: l JOIN r USING (k1, ..., kn)
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java]: IMO this comment is not needed. There are plenty of places which requires knowledge about SQL semantic.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java [hunk 11]
```diff
@@ -366,6 +372,112 @@ else if (firstDependencies.stream().allMatch(right::canResolve) && secondDepende
...
+            // compute the coercion for the field on the right to the common supertype of left & right
+            Symbol rightOutput = symbolAllocator.newSymbol(identifier, type);
+            int rightField = joinAnalysis.getRightJoinFields().get(i);
+            rightCoercions.put(rightOutput, new Cast(right.getFieldMappings().get(rightField).toSymbolReference(), type.getTypeSignature().toString()));
+            rightJoinColumns.put(identifier, rightOutput);
+
+            clauses.add(new JoinNode.EquiJoinClause(leftOutput, rightOutput));
+        }
+
+        ProjectNode leftCoercion = new ProjectNode(idAllocator.getNextId(), left.getRoot(), leftCoercions.build());
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java]: Maybe you could extract code of this project node creation as method. Then you could call it for `left` and `right` side.

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java [hunk 12]
```diff
@@ -3783,13 +3783,6 @@ public void testRightJoinWithNullValues()
                 "ON lineitem.orderkey = orders.orderkey");
     }
 
-    @Test
-    public void testJoinWithDuplicateRelations()
-    {
-        assertQuery("SELECT * FROM orders JOIN orders USING (orderkey)", "SELECT * FROM orders o1 JOIN orders o2 ON o1.orderkey = o2.orderkey");
```
Comment (kokosing) [inline presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java]: what is wrong with these tests? It only requires `expected` query to be fixed.

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java [hunk 13]
```diff
@@ -679,7 +679,7 @@ public void testValues()
         assertQuery("SELECT * FROM (VALUES (1.1, 2), (sin(3.3), 2+2))");
         assertQuery(
                 "SELECT * FROM (VALUES (1.1, 2), (sin(3.3), 2+2)) x (a, b) LEFT JOIN (VALUES (1.1, 2), (1.1, 2+2)) y (a, b) USING (a)",
-                "VALUES (1.1, 2, 1.1, 4), (1.1, 2, 1.1, 2), (sin(3.3), 4, NULL, NULL)");
+                "VALUES (1.1, 2, 4), (1.1, 2, 2), (sin(3.3), 4, NULL)");
```
Comment (kokosing) [inline presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java]: If these queries are covered by `TestJoinUsing`, then maybe we could remove them from here?

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java (hunk 4 above)
Comment (martint) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java]: It produces two outputs, so hard to do without returning a holder object (more complexity) or having an "out" argument (yuck). Let me play with it a bit.

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java (hunk 6 above)
Comment (martint) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java]: I need to check the spec carefully. This is what postgreSQL does, so I chose to be more conservative.

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java (hunk 7 above)
Comment (martint) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java]: By definition, it should exist, otherwise the equality operator above wouldn't be found. Optional.get() will fail as a last resort (if there's a bug).

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java (hunk 8 above)
Comment (martint) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java]: Yes, good idea

File: presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java (hunk 9 above)
Comment (martint) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java]: Yes, an outer join might produce a null on one side. Also, that's how they are define in the spec:

>iii) Let SLCC be a <select list> of <derived column>s of the form:
COALESCE(RVA_i.CJCN_i, RVB_i.CJCN_i) AS CJCN_i
for every i, 1 (one) ≤ i N, in ascending order.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java (hunk 10 above)
Comment (martint) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java]: It helps understand what's the overall structure of the resulting. Sometimes, it's hard to reverse-engineer from the manipulation of nodes and fields needed.

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java (hunk 12 above)
Comment (martint) [reply presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java]: There's no easy way to express the same shape without listing all the columns.

It would need to be something like "SELECT o1.orderkey, <all fields in o1 except for orderkey>, <all fields in o2 except orderkey>", so it was just easier to remove it.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java (hunk 11 above)
Comment (martint) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java]: The problem is that it's intertwined with the creation of output symbols needed for the join clauses and collecting the join columns and the mapping to the identifiers to create the coalesce() calls below.

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java (hunk 6 above)
Comment (martint) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java]: Specifically, what's not clear is what that would do to the schema of the joined table. Would

```
SELECT * FROM (VALUES 1, 'a') t(k, v1) JOIN (VALUES 1, 'b') u(a, v2) USING (a, a)
```

produce `1, 1, 'a', 'b'` or `1, 'a', 'b'`?

Comment (martint) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java]: If duplicates were allowed, only SELECT * would be valid, since trying to reference the column by name would result in an "ambiguous reference" error.

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/Analysis.java [hunk 14]
```diff
@@ -89,6 +89,8 @@
     private final Map<NodeRef<OrderBy>, List<FunctionCall>> orderByWindowFunctions = new LinkedHashMap<>();
 
     private final Map<NodeRef<Join>, Expression> joins = new LinkedHashMap<>();
+    private final Map<NodeRef<Join>, JoinUsingAnalysis> joinUsing = new LinkedHashMap<>();
```
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/Analysis.java]: I think we could reuse existing analysis, e.g: synthesize join expressions (like it was before) but with field references, e.g:
```
new ComparisionExpression(EQUAL,
     new FieldReference(leftField.getRelationFieldIndex())),
     new FieldReference(leftField.getRelationFieldIndex())))
```
One benefit of that approach is that we gather coercion information at the analysis time and can reuse `ExpressionAnalyzer`.

Additionally, we could reuse `Analysis#outputExpressions` to "project" join output columns. So for instance output expressions would contain:
```
new Coalesce(
  new FieldReference(joinLeftField1.getRelationFieldIndex()),
  new FieldReference(joinRightField2.getRelationFieldIndex())),
...,
new FieldReference(leftField1.getRelationFieldIndex()),
...
new FieldRerference(rightField1.getRelationFieldIndex()),
)
```
This way we can clearly separate analysis from planning.  We kind of synthesize conditions with `FieldReferences`, but in your code you still synthesize join `Identifiers` so that you can retain type. What do you think?

File: presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java [hunk 15]
```diff
@@ -366,6 +372,112 @@ else if (firstDependencies.stream().allMatch(right::canResolve) && secondDepende
...
+        leftCoercions.putIdentities(left.getRoot().getOutputSymbols());
+        rightCoercions.putIdentities(right.getRoot().getOutputSymbols());
+        for (int i = 0; i < joinColumns.size(); i++) {
+            Identifier identifier = joinColumns.get(i);
+            Type type = analysis.getType(identifier);
+
+            // compute the coercion for the field on the left to the common supertype of left & right
+            Symbol leftOutput = symbolAllocator.newSymbol(identifier, type);
+            int leftField = joinAnalysis.getLeftJoinFields().get(i);
+            leftCoercions.put(leftOutput, new Cast(left.getFieldMappings().get(leftField).toSymbolReference(), type.getTypeSignature().toString()));
```
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java]: What if there is no coercion, see: `QueryPlanner#coerce` (cast is not inserted)

File: presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java [hunk 16]
```diff
@@ -366,6 +372,112 @@ else if (firstDependencies.stream().allMatch(right::canResolve) && secondDepende
         return new RelationPlan(root, analysis.getScope(node), outputSymbols);
     }
 
+    private RelationPlan planJoinUsing(Join node, RelationPlan left, RelationPlan right)
```
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java]: please take a look at my suggestion at the top of `Analysis.java`. If we go that way we may just need to add a code for that would "project" join output symbols instead of creating whole new code path for join using.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java [hunk 17]
```diff
@@ -366,6 +372,112 @@ else if (firstDependencies.stream().allMatch(right::canResolve) && secondDepende
...
+            rightCoercions.put(rightOutput, new Cast(right.getFieldMappings().get(rightField).toSymbolReference(), type.getTypeSignature().toString()));
+            rightJoinColumns.put(identifier, rightOutput);
+
+            clauses.add(new JoinNode.EquiJoinClause(leftOutput, rightOutput));
+        }
+
+        ProjectNode leftCoercion = new ProjectNode(idAllocator.getNextId(), left.getRoot(), leftCoercions.build());
+        ProjectNode rightCoercion = new ProjectNode(idAllocator.getNextId(), right.getRoot(), rightCoercions.build());
+
+        JoinNode join = new JoinNode(
```
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java]: are you sure that you correctly support all join cases (e.g: left outer, right outer, etc.). `RelationPlanner#visitJoin` has special handling code for joins that are not `INNER`.

Comment (martint) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java]: Yes, there are tests to cover these.

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/Analysis.java (hunk 14 above)
Comment (martint) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/Analysis.java]: Synthesizing expressions is a little like planning. I do want to keep the analysis as descriptive as possible and leave it to the planner to make all the choices regarding how a given SQL construct turns into a expression in the IR.

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java [hunk 18]
```diff
@@ -1170,6 +1152,72 @@ else if (criteria instanceof JoinOn) {
...
+                if (!leftField.isPresent()) {
+                    throw new SemanticException(MISSING_ATTRIBUTE, column, "Column '%s' is missing from left side of join", columnName);
+                }
+                if (!rightField.isPresent()) {
+                    throw new SemanticException(MISSING_ATTRIBUTE, column, "Column '%s' is missing from right side of join", columnName);
+                }
+
+                // ensure a comparison operator exists for the given types (applying coercions if necessary)
+                try {
+                    metadata.getFunctionRegistry().resolveOperator(OperatorType.EQUAL, ImmutableList.of(
```
[the remark this answers is not in the document]
Comment (martint) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java]: It's hard to report accurate errors that way. If a field is missing or there's a type mismatch, it would be reported for the synthetic expression, no the terms in the original SQL tree.

Also, FieldReference is actually something that shouldn't exist in the SQL tree. It's just an artifact of reusing the SQL tree for the IR (which I want to move away from).

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java [hunk 19]
```diff
@@ -1116,34 +1116,16 @@ protected Scope visitJoin(Join node, Optional<Scope> scope)
...
-                    checkState(leftExpressionAnalysis.getSubqueryInPredicates().isEmpty(), "INVARIANT");
-                    checkState(rightExpressionAnalysis.getSubqueryInPredicates().isEmpty(), "INVARIANT");
-                    checkState(leftExpressionAnalysis.getScalarSubqueries().isEmpty(), "INVARIANT");
-                    checkState(rightExpressionAnalysis.getScalarSubqueries().isEmpty(), "INVARIANT");
-
-                    addCoercionForJoinCriteria(node, leftExpression, rightExpression);
-                    expressions.add(new ComparisonExpression(EQUAL, leftExpression, rightExpression));
-                }
-
-                analysis.setJoinCriteria(node, ExpressionUtils.and(expressions));
```
[the remark this answers is not in the document]
Comment (martint) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java]: No, that was a hack from when I first added support for it. See my other comments.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java (hunk 15 above)
Comment (martint) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java]: It should be harmless, since every type can be cast to itself. But, let me try to avoid adding them if unnecessary.

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/Analysis.java (hunk 14 above)
Comment (sopel39) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/Analysis.java]: > Synthesizing expressions is a little like planning

Indeed, although we are not free from synthesizing with `JoinUsingAnalysis` too (we are synthesizing output identifiers). What I like mostly about creating comparison expression with field refs is that we would:
* reuse existing join planning code
* reuse expression analyzer
* properly derive types at analysis time.

We use `FieldReference` throughout the analyzer already since it allows to pass standardized information to planner (e.g: `field_ref1, field_ref2` instead of `*`), 
Basically what I mean is to gather all join information in a unified way for planner to plan.
After all `using` is some kind of syntax sugar (e.g: similar to '*') that we can turn into descriptor during analysis.

That being said, I won't object if you decide on other approach. I wonder if error messages will be displayed correctly with `JoinUsingAnalysis` (whether `NodeLocation` is preserved).

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java (hunk 18 above)
[the remark this answers is not in the document]
Comment (sopel39) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java]: > It's hard to report accurate errors that way. If a field is missing or there's a type mismatch, it would be reported for the synthetic expression, no the terms in the original SQL tree.

True. `FieldReference` maybe could have `NodeLocation`, but that seems like a hack. 

> It's just an artifact of reusing the SQL tree for the IR (which I want to move away from).

I think `FieldReference` is used in a dual way. Once for channel referencing (during physical planning) and once during `analysis<->planning` to reference anonymous columns (e.g '*' columns) or referencing column by long literal.
In the latter case maybe we could replace `FieldReference` by some kind of temporary identifier? For instance:
```
SELECT a ORDER BY 1
```
`1` gets converted to `FieldReference`, but could be converted to some temporary identifier. I don't think `FieldReference` is that evil in this context anyway.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java (hunk 15 above)
Comment (sopel39) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java]: Maybe they are not needed at `QueryPlanner#coerce` too.

Comment (sopel39) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java]: I haven't seen any rule that removes coercion. I don't think such code exists.

Comment (martint) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java]: It gets ugly, so I'll just leave it as is (i.e., plan it the naive way) and let the optimizer remove them if not necessary. I added a PR for that other issue, so I'll merge this one after that one gets in.

Comment (sopel39) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java]: I think you should also derive if the cast is type only coercion here and put that information into `Cast`.

Otherwise we could remove `typeOnly` from `Cast` node completely and rely on `TypeManager` in places where it's needed.

Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java]: Use `RelationPlan#getSymbol` instead.

**Comment by martint** [comment]
I added a commit to restore the old behavior under a config option/session property (set to new behavior by default). This is to facilitate migrating to the new behavior.

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java [hunk 20]
```diff
@@ -1126,6 +1129,28 @@ protected Scope visitJoin(Join node, Optional<Scope> scope)
                 return output;
             }
 
+            if (criteria instanceof JoinUsing) {
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java]: why not to make this an `else` block of `if` in 1122 line? I am afraid this code might be left when legacy flag is removed

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java [hunk 21]
```diff
@@ -1126,6 +1129,28 @@ protected Scope visitJoin(Join node, Optional<Scope> scope)
...
+                // TODO: implement proper "using" semantics with respect to output columns
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java]: add check state that legacy join using is turned on

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java [hunk 22]
```diff
@@ -1177,7 +1202,7 @@ private Scope analyzeJoinUsing(Join node, List<Identifier> columns, Optional<Sco
 
                 // ensure a comparison operator exists for the given types (applying coercions if necessary)
                 try {
-                    metadata.getFunctionRegistry().resolveOperator(OperatorType.EQUAL, ImmutableList.of(
+                    metadata.getFunctionRegistry().resolveOperator(EQUAL, ImmutableList.of(
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java]: undo?

File: presto-main/src/test/java/com/facebook/presto/sql/query/QueryAssertions.java [hunk 23]
```diff
@@ -58,6 +65,11 @@ public void assertFails(@Language("SQL") String sql, @Language("RegExp") String
         }
     }
 
+    public void addFunctions(List<? extends SqlFunction> functions)
```
[the remark this answers is not in the document]
Comment (martint) [reply presto-main/src/test/java/com/facebook/presto/sql/query/QueryAssertions.java]: Ah yes, leftover from some other change I was working on simultaneously.

**Comment by martint** [comment]
I redid the last commit. It should be much cleaner now.

File: presto-main/src/test/java/com/facebook/presto/sql/query/QueryAssertions.java [hunk 24]
```diff
@@ -66,6 +66,8 @@ public void assertQuery(@Language("SQL") String actual, @Language("SQL") String
             fail("Execution of 'expected' query failed: " + expected, ex);
         }
 
+        assertEquals(actualResults.getTypes(), expectedResults.getTypes(), "For query: \n " + actual + "\n:");
```
Comment (kokosing) [inline presto-main/src/test/java/com/facebook/presto/sql/query/QueryAssertions.java]: I would change the message a bit to: `"Types mismatch for query: \n " + actual + "\n:"`

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java [hunk 25]
```diff
@@ -1117,6 +1120,42 @@ protected Scope visitJoin(Join node, Optional<Scope> scope)
             Scope right = process(node.getRight(), isLateralRelation(node.getRight()) ? Optional.of(left) : scope);
 
             if (criteria instanceof JoinUsing) {
+                if (SystemSessionProperties.isLegacyJoinUsingEnabled(session)) {
+                    List<Identifier> columns = ((JoinUsing) criteria).getColumns();
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java]: I would wrap this a method `legacyAnalyzeJoinUsing`. Just to make it more readable.

File: presto-main/src/test/java/com/facebook/presto/sql/query/QueryAssertions.java [hunk 26]
```diff
@@ -34,21 +34,27 @@
...
+        session = testSessionBuilder()
                 .setCatalog("local")
                 .setSchema("default")
                 .build();
 
-        runner = new LocalQueryRunner(defaultSession);
+        runner = new LocalQueryRunner(session);
+    }
+
+    public void setSession(Session session)
```
Comment (kokosing) [inline presto-main/src/test/java/com/facebook/presto/sql/query/QueryAssertions.java]: Why not to pass session to constructor? Notice that your approach is vulnerable, as one may set session in test and that would make the other test to fail. Also it is not thread safe, tests cannot be run in parallel.

Comment (martint) [reply presto-main/src/test/java/com/facebook/presto/sql/query/QueryAssertions.java]: Another left-over from an experiment I was working on where I needed to do it this way. I'll fix it.
