### PR TITLE
Fixing bug: IS DISTINCT FROM NULL should work for NULL column values

### LINKED ISSUE #15107: IS DISTINCT FROM NULL gives wrong result when applied to columns with null values
Bug:
```
presto:ad_metrics> select x is distinct from null from (select cast(null as varchar))T(x);
 _col0 
-------
 true  
```

Works fine for literals though.
```
presto:ad_metrics> select null is distinct from null;
 _col0 
-------
 false 
```

### PR DESCRIPTION
**Pull request by ssaumitra**
Fixes #15107.

Test plan - Tested using the new test in `AbstractTestQueries`. Also ran the tests from `TestExpressionInterpreter.testIsDistinctFrom`
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by ssaumitra** [comment]
Fixes #15107 .

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java [hunk 1]
```diff
@@ -5341,4 +5341,12 @@ public void testMultipleSqlFunctionsWithLambda()
                 "SELECT array_sum(zip_with(a, b, (x, y) -> x * y)), array_sum(zip_with(a, b, (x, y) -> x * y)) + array_sum(zip_with(a, a, (x, y) -> x * y)) FROM (VALUES (ARRAY[1, 2, 3], ARRAY[1, 0, 0])) t(a, b)",
                 "SELECT 1, 15");
     }
+
+    @Test
+    public void testDistinctFrom()
```
Comment (rongrong) [inline presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java:5346]: Can we add more tests to cover all code paths (both left and right)? Also since we are adding a generic test for `IS DISTINCT FROM` here, probably should also test for other common scenarios.

**Review by rongrong — COMMENTED** [review]
Code looks good! Thanks for fixing this!

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java (hunk 1 above)
Comment (ssaumitra) [reply presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java:5346]: @rongrong I have now added several more tests. Tests for basic cases are already in place in https://github.com/prestodb/presto/blob/0cfa23fd729a/presto-main/src/test/java/com/facebook/presto/sql/TestExpressionInterpreter.java#L226 . Therefore I would like to focus only on nested queries over here.

**Review by rongrong — APPROVED** [review]
LGTM. @kaikalur do you want to take a look?
