### PR TITLE
Fix NegativeArraySizeException in REPLACE

### LINKED ISSUE #14592: java.lang.NegativeArraySizeException in string replace function
```
with t as (select replace('1234567890', '', '1234567890') as a),
u as (select replace(a, '', a) as b from t),
v as (select b, replace(b, '', b) as c from u)
select length(replace(c, '', b)) from v

java.lang.NegativeArraySizeException
	at io.airlift.slice.Slices.allocate(Slices.java:89)
	at com.facebook.presto.operator.scalar.StringFunctions.replace(StringFunctions.java:126)
	at com.facebook.presto.$gen.PageProjectionWork_20200530_012234_02084_yr33x_0_0_16_124736.evaluate(Unknown Source)
	at com.facebook.presto.$gen.PageProjectionWork_20200530_012234_02084_yr33x_0_0_16_124736.process(Unknown Source)
	at com.facebook.presto.operator.project.DictionaryAwarePageProjection$DictionaryAwarePageProjectionWork.process(DictionaryAwarePageProjection.java:174)
	at com.facebook.presto.operator.project.PageProcessor$ProjectSelectedPositions.processBatch(PageProcessor.java:313)
	at com.facebook.presto.operator.project.PageProcessor$ProjectSelectedPositions.process(PageProcessor.java:197)
	at com.facebook.presto.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:315)
	at com.facebook.presto.operator.WorkProcessorUtils$YieldingIterator.computeNext(WorkProcessorUtils.java:79)
	at com.facebook.presto.operator.WorkProcessorUtils$YieldingIterator.computeNext(WorkProcessorUtils.java:65)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.facebook.presto.operator.project.MergingPageOutput.getOutput(MergingPageOutput.java:113)
	at com.facebook.presto.operator.FilterAndProjectOperator.getOutput(FilterAndProjectOperator.java:102)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:382)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:284)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:277)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_0_235_1_7265eb8____20200528_234127_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

### PR DESCRIPTION
**Pull request by mbasmanova**
Update "replace" function to check for integer overflow and throw INVALID_FUNCTION_ARGUMENT with explanation instead of java.lang.NegativeArraySizeException.

Fixes #14592

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

File: presto-main/src/test/java/com/facebook/presto/operator/scalar/TestStringFunctions.java [hunk 1]
```diff
@@ -248,6 +248,9 @@ public void testReplace()
         assertFunction("CAST(REPLACE('abc' || utf8(from_hex('CE')) || 'xyz', '', 'X') AS VARBINARY)",
                 VARBINARY,
                 new SqlVarbinary(new byte[] {'X', 'a', 'X', 'b', 'X', 'c', 'X', (byte) 0xCE, 'X', 'x', 'X', 'y', 'X', 'z', 'X'}));
+
+        String longString = new String(new char[1_000_000]).replace("\0", "a");
```
Comment (kaikalur) [inline presto-main/src/test/java/com/facebook/presto/operator/scalar/TestStringFunctions.java:252]: Why "\0"? Shouldn't it be just ""?

Comment (mbasmanova) [reply presto-main/src/test/java/com/facebook/presto/operator/scalar/TestStringFunctions.java:252]: `new String(new char[1_000_000])` makes a string of 1M characters, each is `\0`.

Comment (kaikalur) [reply presto-main/src/test/java/com/facebook/presto/operator/scalar/TestStringFunctions.java:252]: Oh - I got mixed up between Java replace and sql replace :) Actually you should not need this replace at all because arrays are initialized to default value. So just leave it as is or may be use nCopies or something

Comment (mbasmanova) [reply presto-main/src/test/java/com/facebook/presto/operator/scalar/TestStringFunctions.java:252]: @kaikalur You are right. I don't need this replace. I'll change it to `String longString = new String(new char[1_000_000]);`

**Comment by mbasmanova** [comment]
@viczhang861 @kaikalur Vic, Sreeni, thank you for timely reviews.
