### PR TITLE
Fix ORC stripe skipping when using bloom filter

### LINKED ISSUE #12900: Fix ORC Bloom Filter
ORC Bloom Filter Support has been broken in latest presto release.Either we should fix this in corresponding previous branches too OR we should mark this in release note that ORC Bloom Filter Support while Querying ORC table having Bloom Filter will not take advantage of Bloom Filter.
The support is broken from Presto Release 0.214.
After changes of StreamId in readBloomFilterIndexes method of StripeReader class the Bloom filter does not skip unsatisfied Row Group of ORC due to coding bug as the below line return always `null`.

StripeReader.java
`List<HiveBloomFilter> bloomFilters = bloomFilterIndexes.get(entry.getKey());
`
@kevinwilfong 
@dain Please have a look, This have an impact on Presto ORC performance.

### PR DESCRIPTION
**Pull request by dilipkasana**
Fixes #12900

```
== RELEASE NOTES ==

Hive Changes
-----------------
* Fix ORC stripe skipping when using bloom filter
```

### CODE REVIEW

File: presto-orc/src/main/java/com/facebook/presto/orc/StripeReader.java [hunk 1]
```diff
@@ -392,30 +392,30 @@ static boolean isIndexStream(Stream stream)
...
             throws IOException
     {
-        ImmutableMap.Builder<StreamId, List<HiveBloomFilter>> bloomFilters = ImmutableMap.builder();
+        ImmutableMap.Builder<Integer, List<HiveBloomFilter>> bloomFilters = ImmutableMap.builder();
         for (Entry<StreamId, Stream> entry : streams.entrySet()) {
             Stream stream = entry.getValue();
             if (stream.getStreamKind() == BLOOM_FILTER) {
                 OrcInputStream inputStream = streamsData.get(entry.getKey());
-                bloomFilters.put(entry.getKey(), metadataReader.readBloomFilterIndexes(inputStream));
+                bloomFilters.put(entry.getKey().getColumn(), metadataReader.readBloomFilterIndexes(inputStream));
```
Comment (mbasmanova) [inline presto-orc/src/main/java/com/facebook/presto/orc/StripeReader.java]: Is it possible to have multiple streams for a given column?

**Comment by mbasmanova** [comment]
@dilipkasana `com.facebook.presto.orc.TestOrcReader` and `com.facebook.presto.orc.TestingOrcPredicate` might be helpful in building a test that confirms that bloom filters are not ignored when reading ORC files.

File: presto-orc/src/main/java/com/facebook/presto/orc/StripeReader.java (hunk 1 above)
Comment (dilipkasana) [reply presto-orc/src/main/java/com/facebook/presto/orc/StripeReader.java]: If Bloom Filter is enabled for a column Then only one Bloom Filter Stream exists per column.There can not exists more than one streams per column.
I will try to build a test case for this.

**Comment by wenleix** [comment]
cc @kevinwilfong

**Comment by mbasmanova** [comment]
@dilipkasana *ping*

**Comment by dilipkasana** [comment]
@mbasmanova Test cases has been added,Please merge this.

**Comment by mbasmanova** [comment]
@dilipkasana Dilip, GitHub shows `This branch has conflicts that must be resolved`. Could you rebase on top of latest master, resolve conflicts and update the PR. I'll take a look then.

**Comment by mbasmanova** [comment]
@dilipkasana Dilip, I'm still seeing conflicts. I'm also seeing that you are working off of local `master` branch. This might make it difficult to keep track of upstream master. A common practice is to have local `master` branch track upstream `master` and include no changes. Then, put changes into new branches.

Screen Shot 2019-09-16 at 9 57 57 AM

**Comment by dilipkasana** [comment]
@mbasmanova I have recommitted changes on top of latest upstream master and pushed.It seems some hive test cases timeout.
Is this belongs to my changes, I have seen most pull requests are failing here.

**Comment by mbasmanova** [comment]
@dilipkasana Thank you, Dilip. These tests have been timing out a lot recently. I restarted the job. I'm going to review the change now.

File: presto-orc/src/test/java/com/facebook/presto/orc/TestReadBloomFilter.java [hunk 2]
```diff
@@ -0,0 +1,133 @@
...
+        try (TempFile tempFile = new TempFile()) {
+            writeOrcColumnHive(tempFile.getFile(), ORC_12, SNAPPY, type, writeValues);
+
+            // without predicate a normal block will be created
+            try (OrcBatchRecordReader recordReader = createCustomOrcRecordReader(tempFile, OrcPredicate.TRUE, type, MAX_BATCH_SIZE)) {
+                assertEquals(recordReader.nextBatch(), 1024);
+            }
+
+            // predicate for specific value within the min/max range without bloom filter being enabled
+            TupleDomainOrcPredicate<String> noBloomFilterPredicate = new TupleDomainOrcPredicate<>(
```
Comment (mbasmanova) [inline presto-orc/src/test/java/com/facebook/presto/orc/TestReadBloomFilter.java]: the logic of building the predicate repeats multiple time; consider extracting a helper method

```
    private static <T> TupleDomainOrcPredicate<String> makeOrcPredicate(Type type, T value, boolean bloomFilterEnabled)
    {
        return new TupleDomainOrcPredicate<>(
                fromFixedValues(ImmutableMap.of("test", NullableValue.of(type, value))),
                ImmutableList.of(new ColumnReference<>("test", 0, type)),
                bloomFilterEnabled,
                Optional.empty());
    }
```

File: presto-orc/src/test/java/com/facebook/presto/orc/TestReadBloomFilter.java [hunk 3]
```diff
@@ -0,0 +1,133 @@
...
+
+        try (TempFile tempFile = new TempFile()) {
+            writeOrcColumnHive(tempFile.getFile(), ORC_12, SNAPPY, type, writeValues);
+
+            // without predicate a normal block will be created
+            try (OrcBatchRecordReader recordReader = createCustomOrcRecordReader(tempFile, OrcPredicate.TRUE, type, MAX_BATCH_SIZE)) {
+                assertEquals(recordReader.nextBatch(), 1024);
+            }
+
+            // predicate for specific value within the min/max range without bloom filter being enabled
```
Comment (mbasmanova) [inline presto-orc/src/test/java/com/facebook/presto/orc/TestReadBloomFilter.java]: these comments are a bit too similar which makes it different to get the difference between the test cases; consider breaking the code into three sections - // no predicate, // predicate for non-matching value, // predicate for matching value - and testing each case with and without the filter like so

```
        try (TempFile tempFile = new TempFile()) {
            writeOrcColumnHive(tempFile.getFile(), ORC_12, SNAPPY, type, writeValues);

            // no predicate
            try (OrcBatchRecordReader recordReader = createCustomOrcRecordReader(tempFile, type, Optional.empty(), true)) {
                assertEquals(recordReader.nextBatch(), MAX_BATCH_SIZE);
            }

            try (OrcBatchRecordReader recordReader = createCustomOrcRecordReader(tempFile, type, Optional.empty(), false)) {
                assertEquals(recordReader.nextBatch(), MAX_BATCH_SIZE);
            }

            // predicate for non-matching value
            try (OrcBatchRecordReader recordReader = createCustomOrcRecordReader(tempFile, type, Optional.of(notInBloomFilter), true)) {
                assertEquals(recordReader.nextBatch(), -1);
            }

            try (OrcBatchRecordReader recordReader = createCustomOrcRecordReader(tempFile, type, Optional.of(notInBloomFilter), false)) {
                assertEquals(recordReader.nextBatch(), MAX_BATCH_SIZE);
            }

            // predicate for matching value
            try (OrcBatchRecordReader recordReader = createCustomOrcRecordReader(tempFile, type, Optional.of(inBloomFilter), true)) {
                assertEquals(recordReader.nextBatch(), MAX_BATCH_SIZE);
            }

            try (OrcBatchRecordReader recordReader = createCustomOrcRecordReader(tempFile, type, Optional.of(inBloomFilter), false)) {
                assertEquals(recordReader.nextBatch(), MAX_BATCH_SIZE);
            }
        }


    private static <T> OrcBatchRecordReader createCustomOrcRecordReader(TempFile tempFile, Type type, Optional<T> filterValue, boolean bloomFilterEnabled)
            throws IOException
    {
        OrcPredicate predicate = filterValue.map(value -> makeOrcPredicate(type, value, bloomFilterEnabled)).map(OrcPredicate.class::cast).orElse(TRUE);

        OrcDataSource orcDataSource = new FileOrcDataSource(tempFile.getFile(), new DataSize(1, MEGABYTE), new DataSize(1, MEGABYTE), new DataSize(1, MEGABYTE), true);
        OrcReader orcReader = new OrcReader(orcDataSource, OrcEncoding.ORC, new DataSize(1, MEGABYTE), new DataSize(1, MEGABYTE), new DataSize(1, MEGABYTE));

        assertEquals(orcReader.getColumnNames(), ImmutableList.of("test"));
        assertEquals(orcReader.getFooter().getRowsInRowGroup(), 10_000);

        return orcReader.createBatchRecordReader(ImmutableMap.of(0, type), predicate, HIVE_STORAGE_TIME_ZONE, newSimpleAggregatedMemoryContext(), MAX_BATCH_SIZE);
    }

    private static <T> TupleDomainOrcPredicate<String> makeOrcPredicate(Type type, T value, boolean bloomFilterEnabled)
    {
        return new TupleDomainOrcPredicate<>(
                fromFixedValues(ImmutableMap.of("test", NullableValue.of(type, value))),
                ImmutableList.of(new ColumnReference<>("test", 0, type)),
                bloomFilterEnabled,
                Optional.empty());
    }
```

File: presto-orc/src/test/java/com/facebook/presto/orc/TestReadBloomFilter.java [hunk 4]
```diff
@@ -0,0 +1,133 @@
...
+    @Test
+    public void test()
+            throws Exception
+    {
+        testType(TINYINT, ImmutableList.of(1L, 50L, 100L), 50L, 77L);
+        testType(SMALLINT, ImmutableList.of(1L, 5000L, 10_000L), 5000L, 7777L);
+        testType(INTEGER, ImmutableList.of(1L, 500_000L, 1_000_000L), 500_000L, 777_777L);
+        testType(BIGINT, ImmutableList.of(1L, 500_000L, 1_000_000L), 500_000L, 777_777L);
+
+        // Bloom Filters are not supported for DECIMAL, FLOAT, DATE, TIMESTAMP, and CHAR
```
Comment (mbasmanova) [inline presto-orc/src/test/java/com/facebook/presto/orc/TestReadBloomFilter.java]: This comment is confusing to me. If bloom filters are not supported and this is test is specifically testing bloom-filter-enabled skipping, then how is the test passing for these types?

File: presto-orc/src/test/java/com/facebook/presto/orc/TestReadBloomFilter.java [hunk 5]
```diff
@@ -0,0 +1,133 @@
...
+import static com.google.common.collect.Iterables.limit;
+import static com.google.common.collect.Lists.newArrayList;
+import static io.airlift.slice.Slices.utf8Slice;
+import static io.airlift.units.DataSize.Unit.MEGABYTE;
+import static java.nio.charset.StandardCharsets.UTF_8;
+import static org.testng.Assert.assertEquals;
+
+public class TestReadBloomFilter
+{
+    private static final TimeZoneKey TIME_ZONE = TimeZoneKey.getTimeZoneKey(HIVE_STORAGE_TIME_ZONE.getID());
```
[the remark this answers is not in the document]
Comment (dilipkasana) [reply presto-orc/src/test/java/com/facebook/presto/orc/TestReadBloomFilter.java]: I have Removed the Variable and recommitted changes.

File: presto-orc/src/test/java/com/facebook/presto/orc/TestReadBloomFilter.java (hunk 3 above)
Comment (dilipkasana) [reply presto-orc/src/test/java/com/facebook/presto/orc/TestReadBloomFilter.java]: Thanks 
Yes, now the code looks clean and comment is quite simple to understand.

File: presto-orc/src/test/java/com/facebook/presto/orc/TestReadBloomFilter.java (hunk 4 above)
Comment (dilipkasana) [reply presto-orc/src/test/java/com/facebook/presto/orc/TestReadBloomFilter.java]: As the comment says  Bloom Filters are not supported for DECIMAL, FLOAT, DATE, TIMESTAMP, and CHAR are not yet implemented in 
com.facebook.presto.orc.TupleDomainOrcPredicate.checkInBloomFilter
method for details as that does not supports these types yet, That supports TINYINT, SMALLINT, INTEGER, BIGINT, DOUBLE, VarcharType and VarbinaryType.

Comment (mbasmanova) [reply presto-orc/src/test/java/com/facebook/presto/orc/TestReadBloomFilter.java]: @dilipkasana I must be missing something. It is confusing to me that although bloom filter is not supported for some types, the skipping still happens for these types. How does it work? I'd expect that for types that don't support bloom filters, stripe skipping won't work.

Comment (dilipkasana) [reply presto-orc/src/test/java/com/facebook/presto/orc/TestReadBloomFilter.java]: In Presto Bloom Filter check support for Types TINYINT, SMALLINT, INTEGER, BIGINT, DOUBLE, VarcharType and VarbinaryType is supported only as per the method (om.facebook.presto.orc.TupleDomainOrcPredicate.checkInBloomFilter) , I have not investigated efforts to get the support done for  DECIMAL, FLOAT, DATE, TIMESTAMP, and CHAR  in that method.
So tests for TINYINT, SMALLINT, INTEGER, BIGINT, DOUBLE, VarcharType and VarbinaryType  are added and test like below will be failed :

testType(DATE, ImmutableList.of(new SqlDate(1), new SqlDate(5_000), new SqlDate(10_000)), 5_000L, 7_777L);
        testType(TIMESTAMP,
                ImmutableList.of(new SqlTimestamp(1, TIME_ZONE), new SqlTimestamp(500_000L, TIME_ZONE), new SqlTimestamp(1_000_000L, TIME_ZONE)),
                500_000L + HIVE_STORAGE_TIME_ZONE.getOffset(500_000L),
                777_777L + HIVE_STORAGE_TIME_ZONE.getOffset(777_777L));

        testType(REAL, ImmutableList.of(1.11f, 500_000.56f, 1_000_000.99f), (long) floatToIntBits(500_000.56f), (long) floatToIntBits(777_777.77f));
        testType(DOUBLE, ImmutableList.of(1.11, 500_000.55, 1_000_000.99), 500_000.55, 777_777.77);

Comment (mbasmanova) [reply presto-orc/src/test/java/com/facebook/presto/orc/TestReadBloomFilter.java]: @dilipkasana Thanks for explaining. I understand it now. I got confused by seeing the comment in the middle of types. I didn't read carefully and assumed that types that appear after the comment are not supported. To avoid future confusion, I suggest to either move the comment to the end of the method or add `testTypeNotSupported` helper method that asserts that skipping never happens and use that to test the remaining types.

File: presto-orc/src/test/java/com/facebook/presto/orc/TestReadBloomFilter.java [hunk 6]
```diff
@@ -0,0 +1,143 @@
...
+        testType(INTEGER, ImmutableList.of(1L, 500_000L, 1_000_000L), 500_000L, 777_777L);
+        testType(BIGINT, ImmutableList.of(1L, 500_000L, 1_000_000L), 500_000L, 777_777L);
+        testType(DOUBLE, ImmutableList.of(1.11, 500_000.55, 1_000_000.99), 500_000.55, 777_777.77);
+
+        testType(VARCHAR, ImmutableList.of("a", "o", "z"), utf8Slice("o"), utf8Slice("w"));
+        testType(VARBINARY,
+                ImmutableList.of(new SqlVarbinary("a".getBytes(UTF_8)), new SqlVarbinary("o".getBytes(UTF_8)), new SqlVarbinary("z".getBytes(UTF_8))),
+                utf8Slice("o"),
+                utf8Slice("w"));
+        // Bloom Filters are not supported for DECIMAL, FLOAT, DATE, TIMESTAMP, and CHAR
```
Comment (mbasmanova) [inline presto-orc/src/test/java/com/facebook/presto/orc/TestReadBloomFilter.java]: nit: typo: Bloom Filters -> Bloom filters (capital F to lowercase f)

**Comment by mbasmanova** [comment]
@dilipkasana Dilip, ping me once Travis is green and I'll merge this PR.

File: presto-orc/src/test/java/com/facebook/presto/orc/TestReadBloomFilter.java [hunk 7]
```diff
@@ -0,0 +1,143 @@
...
+                assertEquals(recordReader.nextBatch(), MAX_BATCH_SIZE);
+            }
+
+            try (OrcBatchRecordReader recordReader = createCustomOrcRecordReader(tempFile, type, Optional.of(inBloomFilter), false)) {
+                assertEquals(recordReader.nextBatch(), MAX_BATCH_SIZE);
+            }
+        }
+    }
+
+    private static OrcBatchRecordReader createCustomOrcRecordReader(TempFile tempFile, OrcPredicate predicate, Type type, int initialBatchSize)
```
Comment (mbasmanova) [inline presto-orc/src/test/java/com/facebook/presto/orc/TestReadBloomFilter.java]: @dilipkasana Dilip, I was doing a final pass and noticed that this method is not used. Could you remove it?

**Comment by mbasmanova** [comment]
@dilipkasana Dilip, thank you for the contribution.
