### PR TITLE
Fix flaky TestQueues test

### LINKED ISSUE #8602: TestQueues.testTwoQueriesAtSameTime is flaky
Tests run: 1410, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,229.186 sec <<< FAILURE! - in TestSuite
testTwoQueriesAtSameTime(com.facebook.presto.execution.resourceGroups.db.TestQueues)  Time elapsed: 21.759 sec  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method com.facebook.presto.execution.resourceGroups.db.TestQueues.testTwoQueriesAtSameTime() didn't finish within the time-out 60000
	at com.facebook.presto.execution.resourceGroups.db.TestQueues.testTwoQueriesAtSameTime(TestQueues.java:127)

2017-07-26 13:45:47 INFO Life cycle stopping...
2017-07-26 13:45:47 INFO Life cycle stopped.
2017-07-26 13:45:47 INFO Life cycle stopping...
2017-07-26 13:45:47 INFO Life cycle stopped.
2017-07-26 13:45:47 INFO Life cycle stopping...
2017-07-26 13:45:47 INFO Life cycle stopped.
2017-07-26 13:45:47 INFO Life cycle stopping...
2017-07-26 13:45:47 INFO Life cycle stopping...
2017-07-26 13:45:47 INFO Life cycle stopping...
2017-07-26 13:45:47 INFO Life cycle stopped.
2017-07-26 13:45:47 INFO Life cycle stopping...
2017-07-26 13:45:47 INFO Life cycle stopping...
2017-07-26 13:45:47 INFO Life cycle stopping...
2017-07-26 13:45:47 INFO Life cycle stopping...

Results :

Failed tests: 
  TestQueues.testTwoQueriesAtSameTime:127 Â» ThreadTimeout Method com.facebook.pr...

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
Closing DistributedQueryRunner can take a variable amount of time
causing test timeouts. With this change I move the management of the runner
out of the unit tests to separate setup/tearDown methods to reduce the flakiness.

Should fix #8602, #8589.

Also includes #8650.

### CODE REVIEW

**Comment by kokosing** [comment]
CC: @losipiuk you might be intersted

File: presto-tests/src/test/java/com/facebook/presto/execution/resourceGroups/db/TestQueues.java [hunk 1]
```diff
@@ -51,180 +52,170 @@
...
+        QueryManager queryManager = queryRunner.getCoordinator().getQueryManager();
+        queryManager.getAllQueryInfo().forEach(queryInfo -> queryManager.cancelQuery(queryInfo.getQueryId()));
+        queryRunner.close();
+    }
 
     @Test(timeOut = 60_000)
     public void testRunningQuery()
             throws Exception
     {
-        try (DistributedQueryRunner queryRunner = getSimpleQueryRunner()) {
```
Comment (losipiuk) [inline presto-tests/src/test/java/com/facebook/presto/execution/resourceGroups/db/TestQueues.java]: I did not check.
`getSimpleQueryRunner()` is compatible with `QueryRunner` created in `setUp`?

Comment (nezihyigitbasi) [inline presto-tests/src/test/java/com/facebook/presto/execution/resourceGroups/db/TestQueues.java]: Yes, I guess the reason that `createQueryRunner()` is used in other tests is to get a reference to the `dao`.

**Comment by nezihyigitbasi** [comment]
Agreed, there are plenty of tests, including this one, that are slow & flaky, and it would be nice to make these faster/less flaky. 

And yes  I got the query runner management out of the measurement scope. I have seen in many cases the start/teardown of the query runner was taking a long and variable amount of time.
