### PR TITLE
Analyze table fails for tables with struct columns

### LINKED ISSUE #14494: `ANALYZE TABLE` fails on tables with structs
Starting with version 0.225 `ANALYZE TABLE` command on Hive connector fails for tables with struct columns.
Fails also on current v0.235.

> java.lang.IllegalArgumentException: unsupported type: struct<cause:string,is_enabled:boolean,created_at:date,disable_date:date,processed_last:date,processed_since:date>
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:210)
	at com.facebook.presto.hive.metastore.thrift.ThriftMetastoreUtil.createMetastoreColumnStatistics(ThriftMetastoreUtil.java:792)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.lambda$updateTableStatistics$18(ThriftHiveMetastore.java:412)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.updateTableStatistics(ThriftHiveMetastore.java:413)
	at com.facebook.presto.hive.metastore.thrift.BridgingHiveMetastore.updateTableStatistics(BridgingHiveMetastore.java:112)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.updateTableStatistics(CachingHiveMetastore.java:338)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.updateTableStatistics(CachingHiveMetastore.java:338)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.lambda$setTableStatistics$6(SemiTransactionalHiveMetastore.java:322)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:905)
	at com.facebook.presto.hive.HiveMetadata.commit(HiveMetadata.java:2518)
	at com.facebook.presto.hive.HiveConnector.commit(HiveConnector.java:211)
	at com.facebook.presto.transaction.InMemoryTransactionManager$TransactionMetadata$ConnectorTransactionMetadata.commit(InMemoryTransactionManager.java:601)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### PR DESCRIPTION
**Pull request by sujay-jain**
This PR filters out non-primitive column types when creating metastore column statistics. This fixes the issue of ```ANALYZE``` failing on tables due to the check [here](https://github.com/prestodb/presto/blob/master/presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java#L694)

Fixes #14494
```
== RELEASE NOTES ==

Hive Changes
* Fix  ANALYZE table_name failure for tables with map, list or struct columns (:issue:`14494`).
```

### CODE REVIEW

File: presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java [hunk 1]
```diff
@@ -691,32 +693,39 @@ private static StorageDescriptor makeStorageDescriptor(String tableName, List<Co
...
+                    return createLongStatistics(columnName, columnType, statistics);
+                case BINARY:
+                    return createBinaryStatistics(columnName, columnType, statistics, rowCount);
+                case DECIMAL:
+                    return createDecimalStatistics(columnName, columnType, statistics);
+                default:
+                    throw new IllegalArgumentException(format("unsupported type: %s", columnType));
+            }
+        }
+        else if (typeInfo.getCategory() == STRUCT || typeInfo.getCategory() == MAP) {
```
Comment (bhhari) [inline presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java:724]: this can just be if, as we have a sure return in the top if condition

File: presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java [hunk 2]
```diff
@@ -691,32 +693,39 @@ private static StorageDescriptor makeStorageDescriptor(String tableName, List<Co
...
+            return new ColumnStatisticsObj();
+        }
+        else {
```
Comment (bhhari) [inline presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java:727]: no need of this else

File: presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java [hunk 3]
```diff
@@ -691,32 +693,39 @@ private static StorageDescriptor makeStorageDescriptor(String tableName, List<Co
...
+                case BINARY:
+                    return createBinaryStatistics(columnName, columnType, statistics, rowCount);
+                case DECIMAL:
+                    return createDecimalStatistics(columnName, columnType, statistics);
+                default:
+                    throw new IllegalArgumentException(format("unsupported type: %s", columnType));
+            }
+        }
+        else if (typeInfo.getCategory() == STRUCT || typeInfo.getCategory() == MAP) {
+            return new ColumnStatisticsObj();
```
Comment (yingsu00) [inline presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java:725]: It looks like we only return an empty stats object now. I'm curious if we will be filling up the actual stats for structs and maps? How does the `analyze` result look like now with this change? Does it just leave that part empty? Is it possible to attach a printout of the result of it here?

Comment (sujay-jain) [reply presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java:726]: yes, that's correct we only return an empty stats right now since this is a fix for issue #14494. Here's a example of the output with and without this fix
```
presto:sj_test> select * from test;
     a      | b | c 
------------+---+---
 {b=1, c=2} | 3 | a 
(1 row)
```
without this change:
```
presto:sj_test> analyze test;
ANALYZE: 1 row

Query 20200515_162351_00021_y4gxt, FAILED, 2 nodes
Splits: 11 total, 11 done (100.00%)
0:00 [1 rows, 450B] [5 rows/s, 2.5KB/s]

Query 20200515_162351_00021_y4gxt failed: unsupported type: struct<b:int,c:int>
```

with this change:
```
presto:sj_test> analyze test;
ANALYZE: 1 row

Query 20200515_161538_00024_84q6a, FINISHED, 3 nodes
Splits: 11 total, 11 done (100.00%)
0:00 [1 rows, 452B] [10 rows/s, 4.8KB/s]
```

Comment (rschlussel) [reply presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java:726]: I agree with @yingsu00  here. I can't tell if the hive metastore accepts column stats for struct types (for the non type specific fields), but if it does and we have the stats here, I think you should create a proper stats object here with those things set 

Then you can test what happened by running "show stats" after running "analyze"

File: presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java [hunk 4]
```diff
@@ -691,33 +693,40 @@ private static StorageDescriptor makeStorageDescriptor(String tableName, List<Co
...
+                case BINARY:
+                    return createBinaryStatistics(columnName, columnType, statistics, rowCount);
+                case DECIMAL:
+                    return createDecimalStatistics(columnName, columnType, statistics);
+                default:
+                    throw new IllegalArgumentException(format("unsupported type: %s", columnType));
+            }
         }
+
+        if (typeInfo.getCategory() == STRUCT || typeInfo.getCategory() == MAP) {
```
Comment (mbasmanova) [inline presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java:725]: @sujay-jain LIST type needs to be handled as well, right? Otherwise ANALYZE will fail on tables with columns of array/list type.

File: presto-hive-metastore/src/test/java/com/facebook/presto/hive/metastore/thrift/TestThriftHiveMetastoreUtil.java [hunk 5]
```diff
@@ -371,6 +373,13 @@ public void testBasicStatisticsRoundTrip()
         testBasicStatisticsRoundTrip(new HiveBasicStatistics(OptionalLong.of(1), OptionalLong.of(2), OptionalLong.of(3), OptionalLong.of(4)));
     }
 
+    @Test
+    public void testCreateMetastoreColumnStatisticsComplexTypes()
```
Comment (mbasmanova) [inline presto-hive-metastore/src/test/java/com/facebook/presto/hive/metastore/thrift/TestThriftHiveMetastoreUtil.java:377]: @sujay-jain Would you also add end-to-end test to TestHiveTableStatistics?

File: presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java (hunk 3 above)
Comment (mbasmanova) [reply presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java:726]: @sujay-jain @yingsu00 @rschlussel It seems like ANALYZE statement never collected statistics for complex types, hence, fixing ANALYZE to not fail and produce empty statistics is a reasonable change. We may want to create an issue to add support for collecting stats for complex types, but priority of this would not be high and this can be handled separately at some future time.

Comment (rschlussel) [reply presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java:726]: Sure, but this just seems like such a quick thing to test out that I feel like it makes sense to try it now

Comment (rschlussel) [reply presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java:726]: Also @sujay-jain  can you show the show stats output for the current implementation.  Just to confirm the behavior is the same.

File: presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java (hunk 4 above)
Comment (rschlussel) [reply presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java:725]: maybe just make this an `else` to make sure we aren't missing anything else. I don't see a reason we need to throw an unsupported type exception for anything if we can return null stats.

File: presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java (hunk 3 above)
Comment (yingsu00) [reply presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java:726]: Thanks @sujay-jain . I'm ok with collecting the actual stats in a separate task/issue.

**Comment by sujay-jain** [comment]
> @sujay-jain This change looks good, but it is quite different from the previous version. Would you update PR description to explain the issue and the solution?

Ah, thanks for approving this. I was planning to explain this approach and address the comments after a green build.. but slept off waiting for it :) I'll do that now

File: presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java (hunk 3 above)
Comment (sujay-jain) [reply presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java]: > I agree with @yingsu00 here. I can't tell if the hive metastore accepts column stats for struct types (for the non type specific fields), but if it does and we have the stats here, I think you should create a proper stats object here with those things set

I don't see Struct or Map type ```ColumnStatsData``` in ```org.apache.hadoop.hive.metastore.api``` like there are ```ColumnStatsData``` types for primitives eg: ```BooleanColumnStatsData```. As far as I can tell this is not supported by default - we may have to implement something on our own. 
@rschlussel  let me know your thoughts regarding this and we can create a task/issue for it.

Comment (sujay-jain) [reply presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java]: Here's an output for ```analyze``` and ```show stats``` with my current change
```
presto:sj_test> analyze test;
ANALYZE: 1 row

Query 20200519_055255_00001_xtxwu, FINISHED, 1 node
Splits: 35 total, 35 done (100.00%)
0:01 [1 rows, 464B] [0 rows/s, 392B/s]
```
```
presto:sj_test> show stats for test;
 column_name | data_size | distinct_values_count | nulls_fraction | row_count | low_value | high_value 
-------------+-----------+-----------------------+----------------+-----------+-----------+------------
 a           | NULL      | NULL                  | NULL           | NULL      | NULL      | NULL       
 b           | NULL      |                   1.0 |            0.0 | NULL      | 3         | 3          
 c           |       1.0 |                   1.0 |            0.0 | NULL      | NULL      | NULL       
 NULL        | NULL      | NULL                  | NULL           |       1.0 | NULL      | NULL       
(4 rows)

Query 20200519_055302_00002_xtxwu, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]
```

**Comment by sujay-jain** [comment]
After some testing I noticed that returing the empty ColumnStatisticsObj causes issues with thrift Serialization/Deserialization due to required fields so that wouldn't be a good approach. Therefore I've moved the check one layer above to filter out non primitive column types. This fixes the Analyze issue as well as doesn't cause any Thrift issues.

**Running the new test**
Since TestHiveTableStatistics is part of pretso-product-tests running it requires a special setup - It needs docker setup and then you could follow the steps [here](https://github.com/prestodb/presto/tree/master/presto-product-tests) 
Message me incase there are any setup issues and I can help with the setup

File: presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java (hunk 3 above)
Comment (rschlussel) [reply presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/thrift/ThriftMetastoreUtil.java]: @sujay-jain nevermind then.  It was just an opportunisitic suggestion if it was easy.

**Comment by mbasmanova** [comment]
@sujay-jain Thanks for explaining. Would you add a release note? Also, consider updating presto-docs/src/main/sphinx/sql/analyze.rst to clarify that statistics are collected only for primitive types.

**Comment by sujay-jain** [comment]
> @sujay-jain Thanks for explaining. Would you add a release note? Also, consider updating presto-docs/src/main/sphinx/sql/analyze.rst to clarify that statistics are collected only for primitive types.

@mbasmanova Added release notes and updated analyze.rst. Please let me know if it looks okay or should be worded differently

**Comment by mbasmanova** [comment]
@sujay-jain Thank you, Sujay.
