### PR TITLE
Fix NPE when reading structs with a newly added subfield

### LINKED ISSUE #14358: NPE when reading structs with a newly added subfield
In case of a schema change where a new field is added to a struct there will be a missing stream when reading from older files. We need to create a MissingFieldsStreamReader to return an empty block.
This was handled for the case where the field was in the output. The same should be added when its pruned.

```
Caused by: java.lang.NullPointerException: streamDescriptor is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at com.facebook.presto.orc.reader.StructSelectiveStreamReader$PruningStreamReader.<init>(StructSelectiveStreamReader.java:703)
	at com.facebook.presto.orc.reader.StructSelectiveStreamReader$PruningStreamReader.<init>(StructSelectiveStreamReader.java:690)
	at com.facebook.presto.orc.reader.StructSelectiveStreamReader.<init>(StructSelectiveStreamReader.java:191)
	at com.facebook.presto.orc.reader.SelectiveStreamReaders.createStreamReader(SelectiveStreamReaders.java:85)
	at com.facebook.presto.orc.reader.StructSelectiveStreamReader.<init>(StructSelectiveStreamReader.java:176)
	at com.facebook.presto.orc.reader.SelectiveStreamReaders.createStreamReader(SelectiveStreamReaders.java:85)
	at com.facebook.presto.orc.OrcSelectiveRecordReader.createStreamReaders(OrcSelectiveRecordReader.java:587)
	at com.facebook.presto.orc.OrcSelectiveRecordReader.<init>(OrcSelectiveRecordReader.java:179)
	at com.facebook.presto.orc.OrcReader.createSelectiveRecordReader(OrcReader.java:253)
	at com.facebook.presto.hive.orc.OrcSelectivePageSourceFactory.createOrcPageSource(OrcSelectivePageSourceFactory.java:371)
	... 17 more
```

cc: @mbasmanova  @sujay-jain  @jbroll  @oerling

### PR DESCRIPTION
**Pull request by bhhari**
If a nestedStream is missing for a field in the schema create a MissingFieldStreamReader
Fixes #14358 
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by bhhari** [comment]
Fixes #14358

File: presto-orc/src/main/java/com/facebook/presto/orc/reader/StructSelectiveStreamReader.java [hunk 1]
```diff
@@ -166,13 +166,16 @@ else if (outputRequired || !fieldsWithFilters.isEmpty()) {
...
 
-                if (requiredField || fieldsWithFilters.contains(fieldName)) {
-                    Map<Subfield, TupleDomainFilter> nestedFilters = filters.entrySet().stream()
-                            .filter(entry -> entry.getKey().getPath().size() > 0)
-                            .filter(entry -> ((Subfield.NestedField) entry.getKey().getPath().get(0)).getName().equalsIgnoreCase(fieldName))
-                            .collect(toImmutableMap(entry -> entry.getKey().tail(fieldName), Map.Entry::getValue));
-                    List<Subfield> nestedRequiredSubfields = requiredFields.map(names -> names.get(fieldName)).orElse(ImmutableList.of());
-                    if (nestedStream != null) {
+                if (nestedStream == null) {
+                    nestedReaders.put(fieldName, new MissingFieldStreamReader(fieldOutputType.get()));
```
Comment (mbasmanova) [inline presto-orc/src/main/java/com/facebook/presto/orc/reader/StructSelectiveStreamReader.java:170]: @bhhari What happens if fieldOutputType is empty?

Comment (bhhari) [reply presto-orc/src/main/java/com/facebook/presto/orc/reader/StructSelectiveStreamReader.java:170]: We handle it in checkMissingFieldFilters. The outType is empty only in this case

Comment (bhhari) [reply presto-orc/src/main/java/com/facebook/presto/orc/reader/StructSelectiveStreamReader.java:171]: fieldOutType can not be null, as the nestedStream is null only because we have the field from schema and missing from data

Comment (mbasmanova) [reply presto-orc/src/main/java/com/facebook/presto/orc/reader/StructSelectiveStreamReader.java:171]: @bhhari Got it. If outputType is missing, we can't have nestedStream being null. 

`Set<String> structFields = outputType.isPresent() ? nestedTypes.keySet() : nestedStreams.keySet();`

Hence, if nestedStream is null, then outputType must be present. This invariant would be broken only if this method had a bug, hence, we should use `verify`. (checkState would be used if the caller invoked public methods in the wrong order.)

`verify(fieldOutputType.isPresent(), "Missing output type for subfield " + fieldName);`

File: presto-hive/src/test/java/com/facebook/presto/hive/TestHivePushdownFilterQueries.java [hunk 2]
```diff
@@ -875,6 +875,8 @@ public void testStructSchemaEvolution()
         Path newDirectoryPath = getOnlyPath("test_struct_add_column").getParent();
         Files.move(oldFilePath, Paths.get(newDirectoryPath.toString(), "old_file"), ATOMIC_MOVE);
         assertQuery("SELECT * FROM test_struct_add_column", "SELECT (1, 2, 3) UNION ALL SELECT (1, 2, null)");
+        assertQuery("SELECT x.a FROM test_struct_add_column", "SELECT 1 UNION ALL SELECT 1");
+        assertQuery("SELECT count(*)  FROM test_struct_add_column where x.c = 1", "SELECT 0");
```
Comment (mbasmanova) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestHivePushdownFilterQueries.java:879]: @bhhari nit: extra space before "FROM"

**Comment by bhhari** [comment]
link to travis : https://travis-ci.org/github/prestodb/presto/builds/673140023
