### PR TITLE
Disable aggregation pushdown through outer join if aggregation contai…

### LINKED ISSUE #10724: Multiple PushAggregationThroughOuterJoin issues
1.

Query:
```
presto> explain select x, max(x) from (select * from (values (1)) t(x) left join (values (1)) t2(y) on t.x = t2.y) group by x;
Query is gone (server restarted?)

java.lang.IllegalStateException: Cannot resolve symbol field
	at com.google.common.base.Preconditions.checkState(Preconditions.java:585)
	at com.facebook.presto.sql.planner.ExpressionSymbolInliner$Visitor.rewriteSymbolReference(ExpressionSymbolInliner.java:68)
	at com.facebook.presto.sql.planner.ExpressionSymbolInliner$Visitor.rewriteSymbolReference(ExpressionSymbolInliner.java:55)
```
Diagnosis: `PushAggregationThroughOuterJoin` should verify that aggregations don't contain probe symbols

2. 

With optimization:
```
presto> select x, count(*) from (select * from (values (1)) t(x) left join (select * from (values (1)) t2(y) where false) t2(y) on true) group by x;
 x | _col1
---+-------
 1 |     0
(1 row)
```
without:
```
presto> set session push_aggregation_through_join=false;
SET SESSION
presto> select x, count(*) from (select * from (values (1)) t(x) left join (select * from (values (1)) t2(y) where false) t2(y) on true) group by x;
 x | _col1
---+-------
 1 |     1
(1 row)
```

Diagnosis: `PushAggregationThroughOuterJoin` shouldn't fire if default aggregation would be pushed to build side

CC: @rschlussel2

### PR DESCRIPTION
**Pull request by atris**
…ns probe symbols

Fixes #10724

### CODE REVIEW

File: presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java [hunk 1]
```diff
@@ -168,7 +168,12 @@ public Result apply(AggregationNode aggregation, Captures captures, Context cont
                     join.getDistributionType());
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java]: commit message is too long, it wraps in github, please follow https://chris.beams.io/posts/git-commit/

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java [hunk 2]
```diff
@@ -2298,6 +2298,12 @@ public void testJoinWithInSubqueryToBeExecutedAsPostJoinFilter()
         }
     }
 
+    @Test
+    public void testAggregationPushdownThroughOuterJoinNotFiringInCorrelatedAggregates()
+    {
+        assertQuery("select x, max(x) from (select * from (values (1)) t(x) left join (values (1)) t2(y) on t.x = t2.y) group by x");
```
Comment (kokosing) [inline presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java]: - was this query failing before? If so please open an issue with a problem that you are solving here
 - please use capital letters for SQL keywords

File: presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java [hunk 3]
```diff
@@ -243,6 +252,20 @@ private PlanNode coalesceWithNullAggregation(AggregationNode aggregationNode, Pl
...
     }
 
+    private static boolean checkSymbolDependency(AggregationNode.Aggregation aggregation, Map<Symbol, SymbolReference> sourcesSymbolMapping)
+    {
+        FunctionCall functionCall = aggregation.getCall();
+        List<Expression> functionCallArguments = functionCall.getArguments();
+
+        for(int i = 0; i < functionCallArguments.size(); i++) {
+            if(!(sourcesSymbolMapping.containsKey(functionCallArguments.get(i)))) {
+                return false;
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java]: use:

```
functionCall.getArguments().stream().anyMatch(...)
```

File: presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java [hunk 4]
```diff
@@ -272,6 +295,12 @@ private MappedAggregationInfo createAggregationOverNull(AggregationNode referenc
         for (Map.Entry<Symbol, AggregationNode.Aggregation> entry : referenceAggregation.getAggregations().entrySet()) {
             Symbol aggregationSymbol = entry.getKey();
             AggregationNode.Aggregation aggregation = entry.getValue();
+
+            boolean symbolDependencyCorrect = checkSymbolDependency(aggregation, sourcesSymbolMapping);
+            if(!symbolDependencyCorrect) {
+                return null;
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java]: please return `Optional.empty()`, unless you have a really good reason to use `null` directly which can be only true in execution.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java [hunk 5]
```diff
@@ -243,6 +252,20 @@ private PlanNode coalesceWithNullAggregation(AggregationNode aggregationNode, Pl
         return new ProjectNode(idAllocator.getNextId(), crossJoin, assignmentsBuilder.build());
     }
 
+    private static boolean checkSymbolDependency(AggregationNode.Aggregation aggregation, Map<Symbol, SymbolReference> sourcesSymbolMapping)
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java]: put this method below its usage

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java [hunk 6]
```diff
@@ -2298,6 +2298,12 @@ public void testJoinWithInSubqueryToBeExecutedAsPostJoinFilter()
         }
     }
 
+    @Test
+    public void testAggregationPushdownThroughOuterJoinNotFiringInCorrelatedAggregates()
```
Comment (kokosing) [inline presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java]: please put this method to com.facebook.presto.tests.AbstractTestAggregations

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java (hunk 2 above)
Comment (kokosing) [reply presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java]: `select * from (values (1))` can be rewritten as just `values 1`

**Comment by atris** [comment]
@kokosing Updated, please review

File: presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java [hunk 7]
```diff
@@ -292,7 +315,21 @@ private MappedAggregationInfo createAggregationOverNull(AggregationNode referenc
...
                 Optional.empty());
-        return new MappedAggregationInfo(aggregationOverNullRow, aggregationsSymbolMapping);
+
+        return Optional.of(new MappedAggregationInfo(aggregationOverNullRow,
+                                aggregationsSymbolMapping));
+    }
+
+    private static boolean checkSymbolDependency(AggregationNode.Aggregation aggregation, Map<Symbol, SymbolReference> sourcesSymbolMapping)
+    {
+        FunctionCall functionCall = aggregation.getCall();
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java]: This could be inlined to:

```
return sourcesSymbolMapping.keySet().stream().anyMatch(currentArgument ->
                aggregation.getCall().getArguments().contains(currentArgument.toSymbolReference()));
```

But most readable would be:

```
List<Symbol> functionArguments =  aggregation.getCall().getArguments();
return sourcesSymbolMapping.keySet().stream()
     .map(Symbol::toSymbolReference)
     .anyMatch(functionArguments::contains);
```

File: presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java [hunk 8]
```diff
@@ -292,7 +315,21 @@ private MappedAggregationInfo createAggregationOverNull(AggregationNode referenc
                 AggregationNode.Step.SINGLE,
                 Optional.empty(),
                 Optional.empty());
-        return new MappedAggregationInfo(aggregationOverNullRow, aggregationsSymbolMapping);
+
+        return Optional.of(new MappedAggregationInfo(aggregationOverNullRow,
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java]: either do not break the line or put each argument in separate line

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestAggregations.java [hunk 9]
```diff
@@ -78,6 +78,13 @@ public void testCountWithNullIfPredicate()
         assertQuery("SELECT COUNT(*) FROM orders WHERE NULLIF(orderstatus, 'F') = orderstatus ");
     }
 
+    @Test
+    public void testAggregationPushdownThroughOuterJoinNotFiringInCorrelatedAggregates()
+    {
+        assertQuery("SELECT max(x) from (SELECT * from (VALUES (1)) t(x) LEFT JOIN (VALUES (1)) t2(y) ON t.x = t2.y) GROUP BY x",
```
Comment (kokosing) [inline presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestAggregations.java]: can you also test:
```
SELECT max(y) from (SELECT * from (VALUES (1)) t(x) LEFT JOIN (VALUES (1)) t2(y) ON t.x = t2.y) GROUP BY y
```

Comment (kokosing) [reply presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestAggregations.java]: can you add more rows to left and right join side? Maybe `1, 2, null` vs `1, 3, null`

Comment (kokosing) [reply presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestAggregations.java]: `(VALUES (1))` can be written as `(VALUES 1)`. Multiple single column rows can be written as `VALUES 1,2,3`.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java [hunk 10]
```diff
@@ -240,10 +255,12 @@ private PlanNode coalesceWithNullAggregation(AggregationNode aggregationNode, Pl
                 assignmentsBuilder.put(symbol, symbol.toSymbolReference());
             }
         }
-        return new ProjectNode(idAllocator.getNextId(), crossJoin, assignmentsBuilder.build());
+        return Optional.of(new ProjectNode(idAllocator.getNextId(),
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java]: either each parameter in separate line or none

File: presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java [hunk 11]
```diff
@@ -292,7 +315,21 @@ private MappedAggregationInfo createAggregationOverNull(AggregationNode referenc
...
+
+        return Optional.of(new MappedAggregationInfo(aggregationOverNullRow,
+                                aggregationsSymbolMapping));
+    }
+
+    private static boolean checkSymbolDependency(AggregationNode.Aggregation aggregation, Map<Symbol, SymbolReference> sourcesSymbolMapping)
+    {
+        FunctionCall functionCall = aggregation.getCall();
+
+        if (!sourcesSymbolMapping.keySet().stream().anyMatch(currentArgument ->
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java]: instead of `sourcesSymbolMapping.keySet()` you can use `referenceAggregation.getSource().getOutputSymbols()`. That would be more clear.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java [hunk 12]
```diff
@@ -272,6 +289,12 @@ private MappedAggregationInfo createAggregationOverNull(AggregationNode referenc
         for (Map.Entry<Symbol, AggregationNode.Aggregation> entry : referenceAggregation.getAggregations().entrySet()) {
             Symbol aggregationSymbol = entry.getKey();
             AggregationNode.Aggregation aggregation = entry.getValue();
+
+            boolean symbolDependencyCorrect = checkSymbolDependency(aggregation, sourcesSymbolMapping);
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java]: inline this variable

File: presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java [hunk 13]
```diff
@@ -292,7 +315,21 @@ private MappedAggregationInfo createAggregationOverNull(AggregationNode referenc
                 AggregationNode.Step.SINGLE,
                 Optional.empty(),
                 Optional.empty());
-        return new MappedAggregationInfo(aggregationOverNullRow, aggregationsSymbolMapping);
+
+        return Optional.of(new MappedAggregationInfo(aggregationOverNullRow,
+                                aggregationsSymbolMapping));
+    }
+
+    private static boolean checkSymbolDependency(AggregationNode.Aggregation aggregation, Map<Symbol, SymbolReference> sourcesSymbolMapping)
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java]: Accept a `List<Symbol>` or `Set<Symbol>` here (not `Map<Symbol, SymbolReference>`)

Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java]: Please rename this method to something `isUsingSymbols` or `dependsOn`. Then return value to match the name.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java (hunk 12 above)
Comment (kokosing) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java]: It looks like you haven't updated the code yet. Please ping me once you do it.

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestAggregations.java [hunk 14]
```diff
@@ -78,6 +78,20 @@ public void testCountWithNullIfPredicate()
         assertQuery("SELECT COUNT(*) FROM orders WHERE NULLIF(orderstatus, 'F') = orderstatus ");
     }
 
+    @Test
+    public void testAggregationPushdownThroughOuterJoinNotFiringInCorrelatedAggregatesLeftSide()
+    {
+        assertQuery("SELECT max(x) from (SELECT * from (VALUES 1) t(x) LEFT JOIN (VALUES 1) t2(y) ON t.x = t2.y) GROUP BY x",
+                "VALUES 1");
```
Comment (atris) [inline presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestAggregations.java]: @kokosing The test cannot use multiple values here because ``PushAggregationThroughOuterJoin`` checks for distinct output from the Join's Outer Table, which translates to ``ValuesNode`` having a single row. For multiple values, the rule will not run and the functionality will not be tested

**Comment by atris** [comment]
@kokosing Updated, please review

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestAggregations.java (hunk 14 above)
Comment (kokosing) [reply presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestAggregations.java]: Sure. Thanks for checking.

**Comment by atris** [comment]
@kokosing I have addressed the existing comments. Let me know if there is any other change you would like me to do.

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestAggregations.java [hunk 15]
```diff
@@ -78,6 +78,20 @@ public void testCountWithNullIfPredicate()
...
+    }
+
+    @Test
+    public void testAggregationPushdownThroughOuterJoinNotFiringInCorrelatedAggregatesRightSide()
+    {
+        assertQuery("SELECT max(y) from (SELECT * from (VALUES 1) t(x) LEFT JOIN (VALUES 1) t2(y) ON t.x = t2.y) GROUP BY y",
```
Comment (kokosing) [inline presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestAggregations.java]: please put each parameter in separate line :)

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestAggregations.java [hunk 16]
```diff
@@ -78,6 +78,20 @@ public void testCountWithNullIfPredicate()
         assertQuery("SELECT COUNT(*) FROM orders WHERE NULLIF(orderstatus, 'F') = orderstatus ");
     }
 
+    @Test
+    public void testAggregationPushdownThroughOuterJoinNotFiringInCorrelatedAggregatesLeftSide()
+    {
+        assertQuery("SELECT max(x) from (SELECT * from (VALUES 1) t(x) LEFT JOIN (VALUES 1) t2(y) ON t.x = t2.y) GROUP BY x",
```
Comment (kokosing) [inline presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestAggregations.java]: please put each parameter in separate line :)

File: presto-main/src/test/java/com/facebook/presto/sql/planner/iterative/rule/TestPushAggregationThroughOuterJoin.java [hunk 17]
```diff
@@ -181,4 +181,22 @@ public void testDoesNotFireWhenGroupingOnInner()
                         .addGroupingSet(new Symbol("COL1"), new Symbol("COL3"))))
                 .doesNotFire();
     }
+
+    @Test
+    public void testDoesNotFireWhenAggregationDoesNotHaveSymbols()
+    {
+        tester().assertThat(new PushAggregationThroughOuterJoin())
+                .on(p -> p.aggregation(ab -> ab
+                        .source(p.join(JoinNode.Type.LEFT,
```
Comment (kokosing) [inline presto-main/src/test/java/com/facebook/presto/sql/planner/iterative/rule/TestPushAggregationThroughOuterJoin.java]: please put each parameter in separate line :)

File: presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java [hunk 18]
```diff
@@ -207,10 +213,21 @@ private static boolean groupsOnAllOuterTableColumns(AggregationNode node, PlanNo
     // of an aggregation over a single null row is one or zero rather than null. In order to ensure correct results,
     // we add a coalesce function with the output of the new outer join and the agggregation performed over a single
     // null row.
-    private PlanNode coalesceWithNullAggregation(AggregationNode aggregationNode, PlanNode outerJoin, SymbolAllocator symbolAllocator, PlanNodeIdAllocator idAllocator, Lookup lookup)
+    private Optional<PlanNode> coalesceWithNullAggregation(AggregationNode aggregationNode, PlanNode outerJoin, SymbolAllocator symbolAllocator, PlanNodeIdAllocator idAllocator, Lookup lookup)
     {
         // Create an aggregation node over a row of nulls.
-        MappedAggregationInfo aggregationOverNullInfo = createAggregationOverNull(aggregationNode, symbolAllocator, idAllocator, lookup);
+        Optional<MappedAggregationInfo> aggregationOverNullInfoResultNode = createAggregationOverNull(
+                                                                                aggregationNode,
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java]: why is it indented so deeply? IIRC it should fail the travis build

File: presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java [hunk 19]
```diff
@@ -272,6 +293,11 @@ private MappedAggregationInfo createAggregationOverNull(AggregationNode referenc
         for (Map.Entry<Symbol, AggregationNode.Aggregation> entry : referenceAggregation.getAggregations().entrySet()) {
             Symbol aggregationSymbol = entry.getKey();
             AggregationNode.Aggregation aggregation = entry.getValue();
+
+            if (!isUsingSymbols(aggregation, sourcesSymbolMapping.keySet())) {
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java]: nice, not it is readable!

**Comment by atris** [comment]
@kokosing Updated, please see

File: presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java [hunk 20]
```diff
@@ -292,7 +318,19 @@ private MappedAggregationInfo createAggregationOverNull(AggregationNode referenc
                 AggregationNode.Step.SINGLE,
                 Optional.empty(),
                 Optional.empty());
-        return new MappedAggregationInfo(aggregationOverNullRow, aggregationsSymbolMapping);
+
+        return Optional.of(
```
Comment (electrum) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java]: This wrapping is not necessary and makes the code less readable.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java [hunk 21]
```diff
@@ -240,10 +257,14 @@ private PlanNode coalesceWithNullAggregation(AggregationNode aggregationNode, Pl
                 assignmentsBuilder.put(symbol, symbol.toSymbolReference());
             }
         }
-        return new ProjectNode(idAllocator.getNextId(), crossJoin, assignmentsBuilder.build());
+        return Optional.of(
```
Comment (electrum) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java]: This wrapping is not necessary and makes the code less readable.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java [hunk 22]
```diff
@@ -207,10 +213,21 @@ private static boolean groupsOnAllOuterTableColumns(AggregationNode node, PlanNo
     // of an aggregation over a single null row is one or zero rather than null. In order to ensure correct results,
     // we add a coalesce function with the output of the new outer join and the agggregation performed over a single
     // null row.
-    private PlanNode coalesceWithNullAggregation(AggregationNode aggregationNode, PlanNode outerJoin, SymbolAllocator symbolAllocator, PlanNodeIdAllocator idAllocator, Lookup lookup)
+    private Optional<PlanNode> coalesceWithNullAggregation(AggregationNode aggregationNode, PlanNode outerJoin, SymbolAllocator symbolAllocator, PlanNodeIdAllocator idAllocator, Lookup lookup)
     {
         // Create an aggregation node over a row of nulls.
-        MappedAggregationInfo aggregationOverNullInfo = createAggregationOverNull(aggregationNode, symbolAllocator, idAllocator, lookup);
+        Optional<MappedAggregationInfo> aggregationOverNullInfoResultNode = createAggregationOverNull(
```
Comment (electrum) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java]: This local variable name seems excessively long. If you shorten it, you won't need to add wrapping here.
