### PR TITLE
Fix crc computation to properly support integers.

### LINKED ISSUE #16256: CRC calculation in PagesSerde is incorrect
com.facebook.presto.spi.page.PagesSerdeUtil#computeSerializedPageChecksum method uses "update(int)" method for 3 integers: markers, positionCount and uncompressedSize. It appears that this method doesn't consider all the bytes of the integer, but just one byte. The following test demonstrates the problem and proposed solution.

```
        CRC32 crc32 = new CRC32();
        crc32.update(pageData.byteArray(), pageData.byteArrayOffset(), pageData.length());
        crc32.update(markers);
        crc32.update(positionCount);
        crc32.update(uncompressedSize);
        return crc32.getValue();
```

```
    private void computeCrc(int value)
    {
        CRC32 crc32 = new CRC32();
        crc32.update(value);
        System.out.println("value: " + value + ", " + crc32.getValue());
    }

    private void computeCrc2(int value)
    {
        byte[] bytes = ByteBuffer.allocate(4).order(ByteOrder.LITTLE_ENDIAN).putInt(value).array();
        CRC32 crc32 = new CRC32();
        crc32.update(bytes, 0, 4);
        System.out.println("value: " + value + ", " + crc32.getValue());
    }

    @Test
    public void test()
    {
        computeCrc(25);
        computeCrc(25 + (1 << 8));
        computeCrc(25 + (1 << 16));
        computeCrc(25 + (1 << 20));

        computeCrc2(25);
        computeCrc2(25 + (1 << 8));
        computeCrc2(25 + (1 << 16));
        computeCrc2(25 + (1 << 20));
    }


/// The results for all values are the same before only least significant byte is considered
value: 25, 3060352845
value: 281, 3060352845
value: 65561, 3060352845
value: 1048601, 3060352845

/// The results for all values are different before all bytes are considered
value: 25, 206948105
value: 281, 228044094
value: 65561, 357496392
value: 1048601, 1184355672

```

CC: @arhimondr @tdcmeehan @amitkdutta

### PR DESCRIPTION
**Pull request by amitkdutta**
Fixes #16256

Make sure to use all bytes of an integer (positionCount and uncompressedSize) when calculating checksum for the SerializedPage.

### CODE REVIEW

File: presto-spi/src/main/java/com/facebook/presto/spi/page/PagesSerdeUtil.java [hunk 1]
```diff
@@ -99,16 +101,20 @@ public static long writeSerializedPages(SliceOutput sliceOutput, Iterable<Serial
...
     {
         CRC32 crc32 = new CRC32();
         if (!pageData.hasByteArray()) {
             throw new IllegalArgumentException("pageData slice is expected to be based on byte array");
         }
         crc32.update(pageData.byteArray(), pageData.byteArrayOffset(), pageData.length());
-        crc32.update(markers);
-        crc32.update(positionCount);
-        crc32.update(uncompressedSize);
+        crc32.update(getBytes(markers)[0]);
```
Comment (mbasmanova) [inline presto-spi/src/main/java/com/facebook/presto/spi/page/PagesSerdeUtil.java:115]: this change seems unnecessary

File: presto-spi/src/main/java/com/facebook/presto/spi/page/PagesSerdeUtil.java [hunk 2]
```diff
@@ -99,16 +101,20 @@ public static long writeSerializedPages(SliceOutput sliceOutput, Iterable<Serial
         return size;
     }
 
+    public static byte[] getBytes(int value) {
```
Comment (mbasmanova) [inline presto-spi/src/main/java/com/facebook/presto/spi/page/PagesSerdeUtil.java:104]: - public -> private
- nit: getBytes -> toBytes

File: presto-spi/src/test/java/com/facebook/presto/spi/page/TestPageCodecMarker.java [hunk 3]
```diff
@@ -84,4 +87,20 @@ public void testSummaryString()
...
+    @Test
+    public void testComputeCRC() {
+        Slice data = utf8Slice("This is a random text");
+        byte pageCodecmarker = 4;
+        int positionCount = 12444567;
+        int uncompressedSize = 10020078;
+        long crc = computeSerializedPageChecksum(data, pageCodecmarker, positionCount, uncompressedSize);
+        assertEquals(1051058195, crc);
+
+        pageCodecmarker = 0;
```
Comment (mbasmanova) [inline presto-spi/src/test/java/com/facebook/presto/spi/page/TestPageCodecMarker.java:100]: this is a strange case; if pageCodecmarker is 0, we won't be calculating the checksum

File: presto-spi/src/test/java/com/facebook/presto/spi/page/TestPageCodecMarker.java [hunk 4]
```diff
@@ -84,4 +87,20 @@ public void testSummaryString()
             assertTrue(allMarkersSummary.contains(marker.name()));
         }
     }
+
+    @Test
+    public void testComputeCRC() {
+        Slice data = utf8Slice("This is a random text");
+        byte pageCodecmarker = 4;
+        int positionCount = 12444567;
```
Comment (mbasmanova) [inline presto-spi/src/test/java/com/facebook/presto/spi/page/TestPageCodecMarker.java:95]: consider inlining positionCount and uncompressedSize

**Review by mbasmanova — COMMENTED** [review]
@amitkdutta Looks good overall. Some comments below.

File: presto-spi/src/test/java/com/facebook/presto/spi/page/TestPageCodecMarker.java (hunk 3 above)
Comment (amitkdutta) [reply presto-spi/src/test/java/com/facebook/presto/spi/page/TestPageCodecMarker.java]: Using 7 where all bits are set.

File: presto-spi/src/test/java/com/facebook/presto/spi/page/TestPageCodecMarker.java [hunk 5]
```diff
@@ -84,4 +87,19 @@ public void testSummaryString()
             assertTrue(allMarkersSummary.contains(marker.name()));
         }
     }
+
+    @Test
+    public void testComputeCRC() {
+        Slice data = utf8Slice("This is a random text");
+        byte pageCodecmarker = 4;
+        int positionCount = 12444567, uncompressedSize = 10020078;
```
Comment (mbasmanova) [inline presto-spi/src/test/java/com/facebook/presto/spi/page/TestPageCodecMarker.java:95]: The common practice is to define each variable separately. Here, however, there doesn't seem to be any need for these variables. Inlining might be better:

```computeSerializedPageChecksum(data, pageCodecMarker, 12444567, 10020078)```

File: presto-spi/src/test/java/com/facebook/presto/spi/page/TestPageCodecMarker.java [hunk 6]
```diff
@@ -84,4 +87,19 @@ public void testSummaryString()
             assertTrue(allMarkersSummary.contains(marker.name()));
         }
     }
+
+    @Test
+    public void testComputeCRC() {
+        Slice data = utf8Slice("This is a random text");
+        byte pageCodecmarker = 4;
```
Comment (mbasmanova) [inline presto-spi/src/test/java/com/facebook/presto/spi/page/TestPageCodecMarker.java:94]: typo: pageCodecmarker -> pageCodecMarker or marker

File: presto-spi/src/main/java/com/facebook/presto/spi/page/PagesSerdeUtil.java [hunk 7]
```diff
@@ -107,8 +113,8 @@ public static long computeSerializedPageChecksum(Slice pageData, byte markers, i
         }
         crc32.update(pageData.byteArray(), pageData.byteArrayOffset(), pageData.length());
         crc32.update(markers);
-        crc32.update(positionCount);
-        crc32.update(uncompressedSize);
+        crc32.update(toBytes(positionCount));
```
Comment (arhimondr) [inline presto-spi/src/main/java/com/facebook/presto/spi/page/PagesSerdeUtil.java:116]: `Integer.reverseBytes` to avoid extra allocations (static import `reverseBytes`)

**Review by arhimondr — APPROVED** [review]
LGTM % comments

File: presto-spi/src/test/java/com/facebook/presto/spi/page/TestPageCodecMarker.java (hunk 5 above)
Comment (amitkdutta) [reply presto-spi/src/test/java/com/facebook/presto/spi/page/TestPageCodecMarker.java:95]: Oh this is what you meant by inline. Fixing.

File: presto-spi/src/main/java/com/facebook/presto/spi/page/PagesSerdeUtil.java (hunk 7 above)
Comment (arhimondr) [reply presto-spi/src/main/java/com/facebook/presto/spi/page/PagesSerdeUtil.java:116]: Discussed offline with @mbasmanova . The CRC interface take's an integer, but only adds the last byte of an integer to the checksum. I'm thinking if we can avoid an extra allocation. Maybe we an feed the integer byte-by-byte to the checksum?

Comment (amitkdutta) [reply presto-spi/src/main/java/com/facebook/presto/spi/page/PagesSerdeUtil.java]: @arhimondr Address this issue by calculating crc iteratively.

**Review by arhimondr — APPROVED** [review]

**Review by mbasmanova — APPROVED** [review]

File: presto-spi/src/main/java/com/facebook/presto/spi/page/PagesSerdeUtil.java [hunk 8]
```diff
@@ -20,6 +20,8 @@
 import io.airlift.slice.SliceInput;
 import io.airlift.slice.SliceOutput;
 
+import java.nio.ByteBuffer;
```
Comment (mbasmanova) [inline presto-spi/src/main/java/com/facebook/presto/spi/page/PagesSerdeUtil.java:23]: I don't think you need these anymore.

**Review by tdcmeehan — APPROVED** [review]

**Comment by ajaygeorge** [comment]
@amitkdutta This PR is missing release notes. Can you please add them.

**Comment by mbasmanova** [comment]
> @amitkdutta This PR is missing release notes. Can you please add them.

@ajaygeorge There is no user-visible change here.
