### PR TITLE
[Parquet]Fix writing columns with all null values after row group flush

### LINKED ISSUE #22907: Flaky test TestParquetReader.testStructOfTwoNestedArrays
Error:  Tests run: 3131, Failures: 1, Errors: 0, Skipped: 90, Time elapsed: 2,626.714 s <<< FAILURE! - in TestSuite
Error:  com.facebook.presto.hive.parquet.TestParquetReader.testStructOfTwoNestedArrays  Time elapsed: 0.238 s  <<< FAILURE!
java.lang.NullPointerException
	at com.facebook.presto.parquet.reader.ParquetColumnChunk.readDictionaryPage(ParquetColumnChunk.java:241)
	at com.facebook.presto.parquet.reader.ParquetColumnChunk.buildPageReader(ParquetColumnChunk.java:116)
	at com.facebook.presto.parquet.reader.ParquetReader.createPageReaderInternal(ParquetReader.java:494)
	at com.facebook.presto.parquet.reader.ParquetReader.createPageReader(ParquetReader.java:487)
	at com.facebook.presto.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:366)
	at com.facebook.presto.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:550)
	at com.facebook.presto.parquet.reader.ParquetReader.readArray(ParquetReader.java:273)
	at com.facebook.presto.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:547)
	at com.facebook.presto.parquet.reader.ParquetReader.readArray(ParquetReader.java:273)
	at com.facebook.presto.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:547)
	at com.facebook.presto.parquet.reader.ParquetReader.readStruct(ParquetReader.java:309)
	at com.facebook.presto.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:541)
	at com.facebook.presto.parquet.reader.ParquetReader.readBlock(ParquetReader.java:533)
	at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:230)
	at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:208)
	at com.facebook.presto.common.block.LazyBlock.assureLoaded(LazyBlock.java:313)
	at com.facebook.presto.common.block.LazyBlock.isNull(LazyBlock.java:277)
	at com.facebook.presto.hive.parquet.ParquetTester.decodeObject(ParquetTester.java:811)
	at com.facebook.presto.hive.parquet.ParquetTester.assertPageSource(ParquetTester.java:546)
	at com.facebook.presto.hive.parquet.ParquetTester.assertPageSource(ParquetTester.java:530)
	at com.facebook.presto.hive.parquet.ParquetTester.assertFileContents(ParquetTester.java:522)
	at com.facebook.presto.hive.parquet.ParquetTester.assertRoundTrip(ParquetTester.java:391)
	at com.facebook.presto.hive.parquet.ParquetTester.testRoundTripType(ParquetTester.java:321)
	at com.facebook.presto.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:223)
	at com.facebook.presto.hive.parquet.AbstractTestParquetReader.testStructOfTwoNestedArrays(AbstractTestParquetReader.java:787)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

### PR DESCRIPTION
**Pull request by hantangwangd**
## Description

This PR fix a bug in parquet which cased the flaky #22907. The direct reason is, when Parquet writes a data page with a column that is all null right after row group level flush, the handling of that column is incorrect: its encoding still uses dictionary encoding, but no dictionary page is output.

The core reason is, we shouldn't simply `reset` and reuse the `ValuesWriter`s after each row group level flush, it's different from the behavior after each data page level flush. We should close and re-create `ValuesWriter`'s after each row group level flush. See Parquet's comment for `ValuesWriterFactory` [here](https://github.com/apache/parquet-java/blob/92354f6be7ee3b5930c82408102b10a6b2b5f3c2/parquet-column/src/main/java/org/apache/parquet/column/values/factory/ValuesWriterFactory.java#L35). It seems that Parquet is designed this way.

## Motivation and Context

Fix #22907 

## Impact

N/A

## Test Plan

 - Newly added test case `TestParquetWriter.testWriteAllNullDataPageAfterRowGroupFlush()` which can reproduce the issue without this change.
 - Set the invocation count for `testSingleLevelSchemaArrayOfArrayOfStructOfArray()` to 1024, and make sure the issue do not appear anymore.

## Contributor checklist

- [x] Please make sure your submission complies with our [contributing guide](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md), in particular [code style](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#code-style) and [commit standards](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#commit-standards).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [x] CI passed.

## Release Notes

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by jaystarshot** [comment]
>  The core reason is that, when Parquet writes a data page with a column that is all null right after row group level flush, the handling of that column is incorrect

It sounds like the reset() method of the columnWriter is incorrect in this case? maybe that would be a better fix?

**Comment by hantangwangd** [comment]
> It sounds like the reset() method of the columnWriter is incorrect in this case? maybe that would be a better fix?

Yes I think you're right, the `reset()` of a `ColumnWriter` is only invoked on row group level flush, so we can reset and reuse `PrimitiveColumnWriter`, and fix the reset logic to recreate the `ValuesWriter` in it. Will do a fix in this way.

**Comment by hantangwangd** [comment]
But through checking the code and comment in `parquet-columns`, I believe the `ValuesWriter` should not be reset and reuse after each row group level flush, see [here](https://github.com/apache/parquet-java/blob/92354f6be7ee3b5930c82408102b10a6b2b5f3c2/parquet-column/src/main/java/org/apache/parquet/column/values/factory/ValuesWriterFactory.java#L35). It seems that Parquet is designed this way.

**Comment by hantangwangd** [comment]
After check the code in `presto-parquet`, I think we should distinguish the processing logic for data page level flushing and row group level flushing. On data page level flushing, we should reset and reuse the `ValuesWriter`, since all data pages in the same column chunk shares the same dictionary page. But on row group level flushing, we should close and re-create the `ValuesWriter`, all states including dictionary state is independent between different chunks.

The new change added a method `resetChunk()` for `ColumnWriter`, and invoked this method only on row group level flushing. In this way, fixed the problem that caused this flaky test. Please take a look when convenient, thanks! @jaystarshot @rschlussel @ZacBlanco @beinan @shangxinli

**Review by ZacBlanco — DISMISSED** [review]

File: presto-parquet/src/main/java/com/facebook/presto/parquet/writer/valuewriter/PrimitiveValueWriter.java [hunk 1]
```diff
@@ -77,6 +81,12 @@ public void reset()
         this.statistics = Statistics.createStats(parquetType);
     }
 
+    public void resetChunk()
```
Comment (yingsu00) [inline presto-parquet/src/main/java/com/facebook/presto/parquet/writer/valuewriter/PrimitiveValueWriter.java:84]: It seems after this change, the original reset() is not used anymore. Can we just make reset() as the following:
```
public void reset()
    {
        valuesWriter = valuesWriterSupplier.get();
        this.statistics = Statistics.createStats(parquetType);
    }
```
This way we don't need change the ColumnWriters that much

File: presto-parquet/src/main/java/com/facebook/presto/parquet/writer/valuewriter/DoubleValueWriter.java [hunk 2]
```diff
@@ -37,7 +35,7 @@ public void write(Block block)
         for (int i = 0; i < block.getPositionCount(); ++i) {
             if (!block.isNull(i)) {
                 double value = DOUBLE.getDouble(block, i);
-                valuesWriter.writeDouble(value);
+                getValueWriter().writeDouble(value);
```
Comment (yingsu00) [inline presto-parquet/src/main/java/com/facebook/presto/parquet/writer/valuewriter/DoubleValueWriter.java:38]: It seems this is only a cosmetic change that doesn't affect logic or performance. But putting it here in the same commit would make the readers wonder if it's a required change to fix this problem. I would recommend put it in a separate commit, but it's up to you.

File: presto-parquet/src/main/java/com/facebook/presto/parquet/writer/ParquetWriter.java [hunk 3]
```diff
@@ -71,7 +71,7 @@ public class ParquetWriter
     private static final int CHUNK_MAX_BYTES = toIntExact(DataSize.valueOf("128MB").toBytes());
     private static final int DEFAULT_ROW_GROUP_MAX_ROW_COUNT = 10_000;
 
-    private final List<ColumnWriter> columnWriters;
+    private List<ColumnWriter> columnWriters;
```
Comment (yingsu00) [inline presto-parquet/src/main/java/com/facebook/presto/parquet/writer/ParquetWriter.java:74]: Why remove the final?

File: presto-parquet/src/main/java/com/facebook/presto/parquet/writer/valuewriter/PrimitiveValueWriter.java (hunk 1 above)
Comment (hantangwangd) [reply presto-parquet/src/main/java/com/facebook/presto/parquet/writer/valuewriter/PrimitiveValueWriter.java:84]: Actually, the method `reset()` of `PrimitiveValueWriter` will be called on each data page level flush, so we shouldn't re-create new valuesWriter in it.

File: presto-parquet/src/main/java/com/facebook/presto/parquet/writer/ParquetWriter.java (hunk 3 above)
Comment (hantangwangd) [reply presto-parquet/src/main/java/com/facebook/presto/parquet/writer/ParquetWriter.java]: Oh, I guess it's a misoperation, fixed!

File: presto-parquet/src/main/java/com/facebook/presto/parquet/writer/valuewriter/DoubleValueWriter.java (hunk 2 above)
Comment (hantangwangd) [reply presto-parquet/src/main/java/com/facebook/presto/parquet/writer/valuewriter/DoubleValueWriter.java:38]: I think the change here is necessary, because the shadowing field `valuesWriter` held by subclasses like `DoubleValueWriter` will prevent them to be aware of the re-creation and reassignment doing in their parent's method `PrimitiveValueWriter.resetChunk()`.

But following your suggestion, I have moved these changes to a separate commit to make it clearer for readers. Please take a look when convenient, thanks.

File: presto-parquet/src/main/java/com/facebook/presto/parquet/writer/valuewriter/PrimitiveValueWriter.java (hunk 1 above)
Comment (yingsu00) [reply presto-parquet/src/main/java/com/facebook/presto/parquet/writer/valuewriter/PrimitiveValueWriter.java:84]: > Oh, I guess our conversation above confused the `reset()` method between `PrimitiveColumnWriter` and `PrimitiveValueWriter`. What you meant was that `PrimitiveColumnWriter.reset()` is only called on row group level flushing, so there is no need to add a `resetChunk()` method for `ColumnWriter`, we can directly change the logic in `PrimitiveColumnWriter.reset()`, right? I agree with you about this, and have fixed the code.
> 
> As for `PrimitiveValueWriter.reset()`, it will be called by the method `flushCurrentPageToBuffer()`, so will indeed be called during page level flushing. To make it more apparent, I modified the `maxPageSize` and `maxBlockSize` in the newly added test case, in this way, `PrimitiveValueWriter.reset()` will be called several times before `PrimitiveValueWriter.resetChunk()` be called. Please take a look when convenient, thanks a lot!

Oh yes I meant PrimitiveColumnWriter. I usually download the PR to local then comment on the webpage. It seems I commented at the wrong place and I'm sorry for the confusion. Thanks for fixing it!

File: presto-parquet/src/main/java/com/facebook/presto/parquet/writer/PrimitiveColumnWriter.java [hunk 4]
```diff
@@ -203,7 +203,10 @@ public long getRetainedBytes()
     public void reset()
```
Comment (yingsu00) [inline presto-parquet/src/main/java/com/facebook/presto/parquet/writer/PrimitiveColumnWriter.java:203]: It might be better to rename it to resetChunk to keep the meaning consistent with the ValueWriters.

Comment (hantangwangd) [reply presto-parquet/src/main/java/com/facebook/presto/parquet/writer/PrimitiveColumnWriter.java]: Sure, done! Please take a look when convenient.

**Review by yingsu00 — APPROVED** [review]
