### PR TITLE
Fix recoverable execution and enable flaky test in TestHiveRecoverableExecution

### LINKED ISSUE #20466: Flaky TestHiveRecoverableExecution.testInsertBucketedTable
https://github.com/prestodb/presto/actions/runs/5738922951/job/15553489289?pr=20459

```
Error:  Failures: 
Error:    TestHiveRecoverableExecution.testInsertBucketedTable:191->testRecoverableGroupedExecution:390 » Execution java.lang.RuntimeException: statisticsPages is present for recoverable grouped execution only
```

CC: @tdcmeehan @aditi-pandit @rschlussel

### PR DESCRIPTION
**Pull request by hantangwangd**
## Description

A committed `LIFESPAN_COMMIT` task may happens losing contact and being rescheduled. TableFinishOperator should handle this situation and do not try to make statistics for it again. Or we would meet the error described in #20466 and #20272.

This PR fix #20466 and #20272.

## Test Plan

 - Existing tests `testCreateBucketedTable` and `testInsertBucketedTable` in `TestHiveRecoverableExecution`
 - Before this fix, this error almost certain to occur when running the tests 300 times continuously. After this fix, it never occur again.

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [x] CI passed.

## Release Notes

```

General Changes
* Fix bug with recoverable execution
```

### CODE REVIEW

File: presto-main/src/main/java/com/facebook/presto/operator/TableFinishOperator.java [hunk 1]
```diff
@@ -246,12 +249,18 @@ public void addInput(Page page)
...
+        boolean flag = lifespanAndStageStateTracker.update(page, tableCommitContext);
+        if (flag) {
+            lifespanAndStageStateTracker.getStatisticsPagesToProcess(page, tableCommitContext).forEach(statisticsPage -> {
+                OperationTimer timer = new OperationTimer(statisticsCpuTimerEnabled);
+                statisticsAggregationOperator.addInput(statisticsPage);
+                timer.end(statisticsTiming);
+            });
+        }
+        else {
+            LOG.info("The lifeSpanAndStage %s has been committed before", LifespanAndStage.fromTableCommitContext(tableCommitContext));
```
Comment (elharo) [inline presto-main/src/main/java/com/facebook/presto/operator/TableFinishOperator.java:261]: Since this isn't actionable and no one needs to read this, this doesn't seem worth an info log. Debug level at most, but better yet nothing at all.

**Review by elharo — CHANGES_REQUESTED** [review]

File: presto-main/src/main/java/com/facebook/presto/operator/TableFinishOperator.java (hunk 1 above)
Comment (hantangwangd) [reply presto-main/src/main/java/com/facebook/presto/operator/TableFinishOperator.java]: Sure, the log is removed! Thanks for the suggestion.

**Review by tdcmeehan — APPROVED** [review]
Nice fix!

**Review by elharo — APPROVED** [review]

**Comment by elharo** [comment]
Possibly flaky:

[ERROR]   TestPrestoNativeJoinQueries>AbstractTestNativeJoinQueries.testAntiJoin:86->AbstractTestQueryFramework.assertQuery:159 Execution of 'actual' query failed: SELECT * FROM lineitem WHERE linenumber = 3 OR orderkey NOT IN (SELECT orderkey FROM orders WHERE (orderkey + custkey) % 2 = 0)
[ERROR]   TestPrestoNativeJoinQueries>AbstractTestNativeJoinQueries.testBucketedInnerJoin:61->AbstractTestQueryFramework.assertQuery:159 Execution of 'actual' query failed: SELECT b.name, c.name FROM customer_bucketed b, customer c WHERE b.name=c.name

**Comment by hantangwangd** [comment]
> Possibly flaky:
> 
> [ERROR] TestPrestoNativeJoinQueries>AbstractTestNativeJoinQueries.testAntiJoin:86->AbstractTestQueryFramework.assertQuery:159 Execution of 'actual' query failed: SELECT * FROM lineitem WHERE linenumber = 3 OR orderkey NOT IN (SELECT orderkey FROM orders WHERE (orderkey + custkey) % 2 = 0) [ERROR] TestPrestoNativeJoinQueries>AbstractTestNativeJoinQueries.testBucketedInnerJoin:61->AbstractTestQueryFramework.assertQuery:159 Execution of 'actual' query failed: SELECT b.name, c.name FROM customer_bucketed b, customer c WHERE b.name=c.name

Seems unrelated.
