### PR TITLE
Fix precision loss in from_unixtime(double) function

### LINKED ISSUE #21891: FROM_UNIXTIME(double) implementation harbors double precision bug.
## Your Environment
Presto cluster. Latest version.

## Expected Behavior
Query (see the reproduce' section) should return
```
    event_time     |        action_ts
-------------------+-------------------------
 1.7041507095805E9 | 2024-01-01 15:11:49.580
```

Machine-representable double for the `1.7041507095805E9` is `1704150709.58049988746643066406`.
`1704150709` goes to seconds and `0.580499887466` should be rounded to `580` milliseconds.
Because `580.499887466 < 580.5`.

## Current Behavior
Currently the query returns 
```
    event_time     |        action_ts
-------------------+-------------------------
 1.7041507095805E9 | 2024-01-01 15:11:49.581
```

The resulting timestamp gets `1704150709` seconds and `581` milliseconds.
It is because the function is implemented as `Math.round(unixTime * 1000);`
`unixTime * 1000` part loses precision in some corner cases.
In our case it pushes the resulting number to `1704150709580.500000000`,
which after rounding gives us `1704150709581`,
meaning `581` milliseconds.

## Possible Solution
Changing the existing code to
`(long)Math.floor(unixTime) * 1000 + Math.round((unixTime - Math.floor(unixTime)) * 1000)`
would avoid accumulating floating point error and will produce the right result.

## Steps to Reproduce
A table with a double column (in this example event_time).
Query to reproduce:
```
SELECT 
  event_time, 
  FROM_UNIXTIME(event_time) action_ts 
FROM 
  (
    SELECT 
      if(
        event_time is not null,
        1.7041507095805E9, 
        1.7E9
      ) as event_time 
    FROM 
      table1 
    LIMIT 
      1
  )
```

## Context
The issue was noticed when comparing Presto Native with Presto on real world data and query.

### PR DESCRIPTION
**Pull request by hainenber**
## Description
Apply [spershin's proposed change](https://github.com/prestodb/presto/issues/21891#issue-2126580070) to fix precision loss for timestamp yielded from `FROM_UNIXTIME()` function.

## Motivation and Context

Fixes #21891 

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [x] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
*  Fixes precision loss when timestamp yielded from `from_unixtime(double)` function.
```

### CODE REVIEW

**Review by mbasmanova — COMMENTED** [review]
@hainenber Thank you for the fix.

Please, review Contributing guidelines at  https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md and update the PR to comply.

**Comment by hainenber** [comment]
Commits squashed and adhere to commit message guideline.

File: presto-main/src/test/java/com/facebook/presto/operator/scalar/TestDateTimeFunctionsBase.java [hunk 1]
```diff
@@ -193,6 +195,9 @@ public void testFromUnixTime()
         dateTime = new DateTime(2001, 1, 22, 3, 4, 5, 888, DATE_TIME_ZONE);
         seconds = dateTime.getMillis() / 1000.0;
         assertFunction("from_unixtime(" + seconds + ")", TimestampType.TIMESTAMP, sqlTimestampOf(dateTime, session));
+
+        SqlTimestamp expected = sqlTimestampOf(2024, 1, 1, 23, 11, 49, 580, UTC, session.getTimeZoneKey(), session.toConnectorSession());
+        assertFunction("from_unixtime(1.7041507095805E9)", TimestampType.TIMESTAMP, expected);
```
Comment (mbasmanova) [inline presto-main/src/test/java/com/facebook/presto/operator/scalar/TestDateTimeFunctionsBase.java:200]: Would you confirm that this test fails without the change?

File: presto-main/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java [hunk 2]
```diff
@@ -182,7 +182,7 @@ public static long localTimestamp(SqlFunctionProperties properties)
     @SqlType(StandardTypes.TIMESTAMP)
     public static long fromUnixTime(@SqlType(StandardTypes.DOUBLE) double unixTime)
     {
-        return Math.round(unixTime * 1000);
+        return Math.round(Math.floor(unixTime) * 1000 + Math.round((unixTime - Math.floor(unixTime)) * 1000));
```
Comment (mbasmanova) [inline presto-main/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java:185]: This is a tricky change. Future readers won't know why this is done in this particular way and 'git log' won't help much because commit message just says 'loses precision in some corner cases' without providing any details.

Would you add a comment here to explain what's going on and why the computation is done this way and also update commit message to explain clearly the problem and solution?

Comment (spershin) [reply presto-main/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java:185]: @hainenber 
We could reuse some sentences from the issue and put them in comment.

File: presto-main/src/test/java/com/facebook/presto/operator/scalar/TestDateTimeFunctionsBase.java (hunk 1 above)
Comment (spershin) [reply presto-main/src/test/java/com/facebook/presto/operator/scalar/TestDateTimeFunctionsBase.java:200]: Maybe adding a comment that this particular double was causing loss of precision in the function before the fix and hence we are testing it here.
In case anyone wondering why this number.

**Review by spershin — COMMENTED** [review]
@hainenber 

Thank you for tacking ling this change.
It is good to go.
Please, add some comments to the new code as reviewers suggested.

File: presto-main/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java (hunk 2 above)
Comment (hainenber) [reply presto-main/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java:191]: I've amended the change with more details in the form of comments and commit message.

**Comment by spershin** [comment]
@hainenber 
You might want to rebase your PR on the fresh master and resubmit - there was an update to prevent e2e tests from failing all the time.

**Review by mbasmanova — COMMENTED** [review]
@hainenber Thank you for iterating on this PR. Looks good % some nits and commit message needs updating.

There are typos in the commit message, the title is too long and the body has some lines that are too long. I suggest to use the following as the commit message.

```
Fix precision loss in from_unixtime(double) function

from_unixtime(1.7041507095805E9) used to return 1704150709 seconds and 581
milliseconds. It should return 580 milliseconds.

Before this change, the function used Math.round(unixTime * 1000), which loses
precision in some cases.

In the above case, it pushes the resulting number to 1704150709580.500000000,
which after rounding becomes 1704150709581, e.g. 581 milliseconds.
``` 

Current commit message:
Screenshot 2024-02-14 at 1 58 50 AM

**Comment by mbasmanova** [comment]
CC: @kaikalur @aditi-pandit

File: presto-main/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java [hunk 3]
```diff
@@ -180,9 +180,15 @@ public static long localTimestamp(SqlFunctionProperties properties)
 
     @ScalarFunction("from_unixtime")
     @SqlType(StandardTypes.TIMESTAMP)
+    // This implementation fixes previous issue of precision loss when it comes for some edge cases.
+    // For example, 1.7041507095805E9 would correctly yield "2024-01-01 15:11:49.580"
+    // Machine-representable double for the 1.7041507095805E9 is 1704150709.58049988746643066406.
```
[the remark this answers is not in the document]
Comment (hainenber) [reply presto-main/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java:185]: Yes, that's the original [sentence](https://github.com/prestodb/presto/issues/21891#issue-2126580070) from the author :D

**Review by spershin — APPROVED** [review]
Looks good, thank you for working on this and addressing tons of comments!

**Comment by spershin** [comment]
@hainenber 

Let's rebase and merge this change.
Thanks!

**Comment by spershin** [comment]
@hainenber 

Let's rebase and merge this change.
Let us know, please, if you for some reason are unable to do this.
Thanks!

**Comment by hainenber** [comment]
hi there, this change can have other folks taking over.  Sorry for the belated info!

**Comment by tdcmeehan** [comment]
@spershin rebased, could you please re-review?

**Review by spershin — APPROVED** [review]
Thanks for the fix!

**Comment by spershin** [comment]
@tdcmeehan 

Accepted, however, I'm not a committer, so a committer needs to review this too.

cc @mbasmanova ?

**Review by mbasmanova — APPROVED** [review]
Thanks.
