### PR TITLE
exclude Pacific/Kanton from testNamedZones

### LINKED ISSUE #21996: Pacific/Kanton timezone causes TestTimeZoneUtils.testNamedZones to fail
## Your Environment

* Presto version used:
* HEAD
java -version
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Temurin)(build 25.302-b08, mixed mode)

## Expected Behavior
test passes

## Current Behavior
[ERROR] Tests run: 8198, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 3,007.826 s <<< FAILURE! - in TestSuite
[ERROR] com.facebook.presto.util.TestTimeZoneUtils.testNamedZones  Time elapsed: 0.037 s  <<< FAILURE!
java.time.zone.ZoneRulesException: Unknown time-zone ID: Pacific/Kanton
	at java.time.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:272)
	at java.time.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:227)
	at java.time.ZoneRegion.ofId(ZoneRegion.java:120)
	at java.time.ZoneId.of(ZoneId.java:411)
	at java.time.ZoneId.of(ZoneId.java:359)
	at com.facebook.presto.util.TestTimeZoneUtils.assertTimeZone(TestTimeZoneUtils.java:108)

## Possible Solution

Either upgrade minimum JDK to 8u321 (currently documented as 8u151+ in CONTRIBUTING) or special case it in the test. 

## Steps to Reproduce

Run mvn test on JDK 8u302

See https://www.oracle.com/java/technologies/tzdata-versions.html for details on minimum JDK versions that contain this zone.

### PR DESCRIPTION
**Pull request by elharo**
## Motivation and Context
fixes #21996 by excluding test for timezone not available in all supported JDKs

## Impact
none, test only

## Test Plan
../mvnw test

## Release Notes

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by elharo** [comment]
CI failures look unrelated, possibly flaky. Will rerun:

INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestPrestoNativeGeneralQueriesJSON>AbstractTestNativeGeneralQueries.testFiltersAndProjections:205->AbstractTestQueryFramework.assertQuery:149->AbstractTestQueryFramework.assertQuery:154 Execution of 'actual' query failed: SELECT * FROM lineitem WHERE shipinstruct like 'TAKE BACK#%' escape '#'
[ERROR]   TestPrestoNativeGeneralQueriesJSON>AbstractTestNativeGeneralQueries.testWidthBucket:932->AbstractTestQueryFramework.assertQuery:149->AbstractTestQueryFramework.assertQuery:154 Execution of 'actual' query failed: SELECT width_bucket(to_unixtime(cast(ds as timestamp)), array[1609487900.1, 1619740800.2, 1622419200.3]) FROM customer_bucketed
[INFO] 
[ERROR] Tests run: 76, Failures: 2, Errors: 0, Skipped: 0
[INFO]

**Comment by elharo** [comment]
Yes, they're just flaky. Ready for review

File: presto-main/src/test/java/com/facebook/presto/util/TestTimeZoneUtils.java [hunk 1]
```diff
@@ -87,6 +87,12 @@ public void testNamedZones()
             DateTimeZone indexedZone = getDateTimeZone(TimeZoneKey.getTimeZoneKey(zoneId));
 
             assertDateTimeZoneEquals(zoneId, indexedZone);
+            if (dateTimeZone.getID().equals("Pacific/Kanton")) {
```
Comment (jainxrohit) [inline presto-main/src/test/java/com/facebook/presto/util/TestTimeZoneUtils.java:90]: Can we add context why this is being excluded?

**Review by jainxrohit — COMMENTED** [review]
Please squash all commits in one commit.

**Comment by jainxrohit** [comment]
Squash all commits in to one commit?

**Comment by rschlussel** [comment]
> Is squash and merge enabled on the repo?

squash and merge is not enabled on this repo.  We require rebase and merge.

File: presto-main/src/test/java/com/facebook/presto/util/TestTimeZoneUtils.java (hunk 1 above)
Comment (rschlussel) [reply presto-main/src/test/java/com/facebook/presto/util/TestTimeZoneUtils.java:90]: can this be moved above with the other zoneId checks?

Comment (elharo) [reply presto-main/src/test/java/com/facebook/presto/util/TestTimeZoneUtils.java:90]: No, it can't. There's an extra weirdness with this particular timezone. If you start with Pacific/Enderbury as the zoneId. getDateTimeZone will return the new name Pacific/Kanton so this check needs to come after line 87.

**Review by rschlussel — APPROVED** [review]
