### PR TITLE
Fix round for float value when input out of long range

### LINKED ISSUE #23763: Round function returns incorrect results for large floats
## Steps to Reproduce

```
SELECT
    c0 AS value,
    "round"(c0, 1) AS rounded
FROM (
    VALUES
        (CAST(1E19 AS REAL))
) t(c0);
```

## Expected Behavior

```
 value  |    rounded    
--------+---------------
 1.0E19 | 1.0E19
(1 row)
```
## Current Behavior

```
 value  |    rounded    
--------+---------------
 1.0E19 | -8.4467441E18 
(1 row)
```
Issue only occurs when casting to real and using scientific notation.

### PR DESCRIPTION
**Pull request by hantangwangd**
## Description

Fixes #23763 

## Motivation and Context

Fix issue: #23763 

## Impact

N/A

## Test Plan

 - Newly added test case in `TestMathFuntions.testRoundForUnderlyingValueOutOfRange()` to cover the scenario mentioned in issue #23763 

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [x] CI passed.

## Release Notes

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

File: presto-main/src/test/java/com/facebook/presto/operator/scalar/TestMathFunctions.java [hunk 1]
```diff
@@ -814,6 +814,9 @@ public void testRound()
         assertFunction("round(REAL '90000000.0', 1000)", REAL, 90000000.0f);
         assertFunction("round(REAL '300000000.0', 100)", REAL, 300000000.0f);
         assertFunction("round(REAL '-300000000.0', 100)", REAL, -300000000.0f);
+        assertFunction("round(REAL '1.0E19', 1)", REAL, 1.0E19f);
```
Comment (elharo) [inline presto-main/src/test/java/com/facebook/presto/operator/scalar/TestMathFunctions.java:817]: These should probably go in a new test method with a comment linking to the bug so they can pass or fail independently

**Review by elharo — COMMENTED** [review]
Nice fix!

**Review by elharo — APPROVED** [review]

**Review by tdcmeehan — APPROVED** [review]
