### PR TITLE
Fix overflow

### LINKED ISSUE #10276: java.lang.ArrayIndexOutOfBoundsException in geometry_to_bing_tiles
```
PrestoQueryError: java.lang.ArrayIndexOutOfBoundsException: 1590457587 
	at com.facebook.presto.spi.block.LongArrayBlockBuilder.writeLong(LongArrayBlockBuilder.java:63) 
	at com.facebook.presto.spi.type.AbstractLongType.writeLong(AbstractLongType.java:66) 
	at com.facebook.presto.plugin.geospatial.BingTileFunctions.writeTilesToBlockBuilder(BingTileFunctions.java:300) 
	at com.facebook.presto.plugin.geospatial.BingTileFunctions.geometryToBingTiles(BingTileFunctions.java:207) 
	at com.facebook.presto.$gen.PageProjectionWork_20180327_232031_05145_43rh8_2_2_1233773.lambda_1(Unknown Source) 
	at com.facebook.presto.operator.scalar.TryFunction.tryBlock(TryFunction.java:105) 
	at com.facebook.presto.$gen.PageProjectionWork_20180327_232031_05145_43rh8_2_2_1233773.evaluate(Unknown Source) 
	at com.facebook.presto.$gen.PageProjectionWork_20180327_232031_05145_43rh8_2_2_1233773.process(Unknown Source) 
	at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.processBatch(PageProcessor.java:275) 
	at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.computeNext(PageProcessor.java:180) 
	at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.computeNext(PageProcessor.java:127) 
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) 
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) 
	at com.facebook.presto.operator.project.PageProcessorOutput.hasNext(PageProcessorOutput.java:49) 
	at com.facebook.presto.operator.project.MergingPageOutput.getOutput(MergingPageOutput.java:110) 
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:295) 
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:234) 
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379) 
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:278) 
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:645) 
	at com.facebook.presto.operator.Driver.processFor(Driver.java:272) 
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975) 
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162) 
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492) 
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
	at java.base/java.lang.Thread.run(Thread.java:844) 
```

### PR DESCRIPTION
**Pull request by mbasmanova**
Fixes #10276

### CODE REVIEW

File: presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/BingTileFunctions.java [hunk 1]
```diff
@@ -234,13 +234,14 @@ private static BingTile getTileCoveringLowerRightCorner(Envelope envelope, int z
...
 
-    private static void checkGeometryToBingTilesLimits(OGCGeometry geometry, boolean pointOrRectangle, int tileCount)
+    private static void checkGeometryToBingTilesLimits(OGCGeometry geometry, boolean pointOrRectangle, long tileCount)
     {
         if (pointOrRectangle) {
             checkCondition(tileCount <= 1_000_000, "The number of input tiles is too large (more than 1M) to compute a set of covering bing tiles.");
         }
         else {
-            long complexity = ((long) tileCount) * getPointCount(geometry.getEsriGeometry());
+            checkCondition((int) tileCount == tileCount, "The zoom level is too high to compute a set of covering bing tiles.");
```
Comment (martint) [inline presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/BingTileFunctions.java]: Why is this check needed? Doesn’t the check below cover it? In fact, for complexity to be < 25M, tilecount cannot be larger than that.

File: presto-spi/src/test/java/com/facebook/presto/spi/block/TestBlockUtil.java [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+
+import static org.testng.Assert.assertEquals;
+import static org.testng.Assert.assertTrue;
+
+public class TestBlockUtil
+{
+    @Test
+    public void testCalculateNewArraySize()
+    {
+        int size = 1;
```
Comment (nezihyigitbasi) [inline presto-spi/src/test/java/com/facebook/presto/spi/block/TestBlockUtil.java]: I think this is a simpler test to cover the cases in this loop:

```
assertEquals(BlockUtil.calculateNewArraySize(200), 300);
assertEquals(BlockUtil.calculateNewArraySize(Integer.MAX_VALUE), MAX_ARRAY_SIZE);
try {
    BlockUtil.calculateNewArraySize(MAX_ARRAY_SIZE);
}
catch (IllegalArgumentException e) {
    assertEquals(e.getMessage(), format("Can not grow array beyond '%s'", MAX_ARRAY_SIZE));
}
```

File: presto-spi/src/main/java/com/facebook/presto/spi/block/BlockUtil.java [hunk 3]
```diff
@@ -59,7 +59,7 @@ static void checkValidPosition(int position, int positionCount)
     static int calculateNewArraySize(int currentSize)
     {
         // grow array by 50%
-        long newSize = currentSize + (currentSize >> 1);
+        long newSize = (long) currentSize + (currentSize >> 1);
```
Comment (nezihyigitbasi) [inline presto-spi/src/main/java/com/facebook/presto/spi/block/BlockUtil.java]: nice catch!

File: presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/BingTileFunctions.java (hunk 1 above)
Comment (nezihyigitbasi) [reply presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/BingTileFunctions.java]: Also, on L183 you call `toIntExact(tileCount)`, which will throw in this case anyway.

Comment (mbasmanova) [reply presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/BingTileFunctions.java]: > Why is this check needed?

@martint This check is needed to avoid long overflow when calculating `complexity`.

@nezihyigitbasi  `toIntExact(tileCount)` throws `ArithmeticException`, which is not helpful to the user. With explicit check I can provide a clear error message.

Comment (nezihyigitbasi) [reply presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/BingTileFunctions.java]: @mbasmanova That check may not catch long overflow when calculating complexity. Assume that `tileCount` is `Integer.MAX_VALUE` and the number of points is, say, 306783378, then `complexity = Integer.MAX_VALUE * 306783378;`, which will be `-306783378` (overflow).

Comment (mbasmanova) [reply presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/BingTileFunctions.java]: @nezihyigitbasi What's the best way to address that? Should I use `Math.multiplyExact`, catch `ArithmeticException` and translate it to `PrestoException(INVALID_FUNCTION_ARGUMENT, ...)`?

Comment (nezihyigitbasi) [reply presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/BingTileFunctions.java]: That sounds reasonable.

File: presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/BingTileFunctions.java [hunk 4]
```diff
@@ -234,14 +234,22 @@ private static BingTile getTileCoveringLowerRightCorner(Envelope envelope, int z
...
+    private static void checkGeometryToBingTilesLimits(OGCGeometry geometry, boolean pointOrRectangle, long tileCount)
     {
         if (pointOrRectangle) {
-            checkCondition(tileCount <= 1_000_000, "The number of input tiles is too large (more than 1M) to compute a set of covering bing tiles.");
+            checkCondition(tileCount <= 1_000_000, "The number of input tiles is too large (more than 1M) to compute a set of covering Bing tiles.");
         }
         else {
-            long complexity = ((long) tileCount) * getPointCount(geometry.getEsriGeometry());
-            checkCondition(complexity <= 25_000_000, "The zoom level is too high or the geometry is too complex to compute a set of covering bing tiles. " +
+            checkCondition((int) tileCount == tileCount, "The zoom level is too high to compute a set of covering Bing tiles.");
```
Comment (nezihyigitbasi) [inline presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/BingTileFunctions.java]: You were saying previously that this check is needed to `avoid long overflow when calculating complexity`. Now that you handle the overflow case by catching `ArithmeticException` below, do you still need this?

Comment (mbasmanova) [reply presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/BingTileFunctions.java]: @nezihyigitbasi I want to keep this check so I can provide a more specific error message - "zoom level is too high" - as opposed to more generic one - "zoom level is too high or the geometry is too complex".

**Comment by mbasmanova** [comment]
@nezihyigitbasi Nezih, thanks for editing the commit message. I updated accordingly.
