### PR TITLE
Fix a binding issue in presto-verifier

### LINKED ISSUE #20828: Missing bindings for `SnapshotQueryConsumer` and `SnapshotQuerySupplier` in `VerifierModule`
Missing bindings for `SnapshotQueryConsumer` and `SnapshotQuerySupplier` in `VerifierModule`.

Verifier bootstrap fails with
```
Bootstrap Uncaught exception in thread main
com.google.inject.CreationException: Unable to create injector, see the following errors:
1) Explicit bindings are required and com.facebook.presto.verifier.source.SnapshotQueryConsumer is not explicitly bound.
  while locating com.facebook.presto.verifier.source.SnapshotQueryConsumer
    for the 2nd parameter of com.facebook.presto.verifier.framework.VerificationManager.<init>(VerificationManager.java:133)
 at com.facebook.presto.verifier.framework.VerifierModule.setup(VerifierModule.java:130)
2) Explicit bindings are required and com.facebook.presto.verifier.source.SnapshotQuerySupplier is not explicitly bound.
  while locating com.facebook.presto.verifier.source.SnapshotQuerySupplier
    for the 3rd parameter of com.facebook.presto.verifier.framework.VerificationManager.<init>(VerificationManager.java:133)
 at com.facebook.presto.verifier.framework.VerifierModule.setup(VerifierModule.java:130)
```

_Originally posted by @vermapratyush in https://github.com/prestodb/presto/issues/19253#issuecomment-1714203681_

### PR DESCRIPTION
**Pull request by v-jizhang**
## Description

The bindings are in SourceQueryModule.java, but are guarded by an if statement. Move them out of the if statement and add tests to make sure the bindings work.

com.google.inject.CreationException: Unable to create injector, see the following errors:
1) Explicit bindings are required and
  com.facebook.presto.verifier.source.SnapshotQueryConsumer is not
  explicitly bound. while locating
  com.facebook.presto.verifier.source.SnapshotQueryConsumer for
  the 2nd parameter of
  com.facebook.presto.verifier.framework.VerificationManager.<init>
  (VerificationManager.java:133) at
  com.facebook.presto.verifier.framework.VerifierModule.setup
  (VerifierModule.java:130)
2) Explicit bindings are required and
  com.facebook.presto.verifier.source.SnapshotQuerySupplier is not
  explicitly bound. while locating
  com.facebook.presto.verifier.source.SnapshotQuerySupplier for
  the 3rd parameter of
  com.facebook.presto.verifier.framework.VerificationManager.<init>
  (VerificationManager.java:133) at
  com.facebook.presto.verifier.framework.VerifierModule.setup
  (VerifierModule.java:130)

## Motivation and Context
Quick fix for the binding issue, see Description above.

## Impact
Fixes #20828

## Test Plan
Make sure all tests pass.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by ericyuliu — APPROVED** [review]
LG

**Review by ajaygeorge — CHANGES_REQUESTED** [review]
Can you add a test which fails if this change is not present so that next time we can catch such issues.

**Comment by v-jizhang** [comment]
> Can you add a test which fails if this change is not present so that next time we can catch such issues.

It never happened in my environment. I'll add a test anyway.

File: presto-verifier/src/main/java/com/facebook/presto/verifier/source/SourceQueryModule.java [hunk 1]
```diff
@@ -47,11 +47,13 @@ protected void setup(Binder binder)
         String sourceQuerySupplierType = buildConfigObject(VerifierConfig.class).getSourceQuerySupplier();
         checkArgument(supportedSourceQuerySupplierTypes.contains(sourceQuerySupplierType), "Unsupported SourceQuerySupplier: %s", sourceQuerySupplierType);
 
+        // Snapshots are supported by Mysql only
```
Comment (vermapratyush) [inline presto-verifier/src/main/java/com/facebook/presto/verifier/source/SourceQueryModule.java:50]: nit: 
```suggestion
        // Snapshots are supported by Mysql only.
```

File: presto-verifier/src/test/java/com/facebook/presto/verifier/source/TestSourceQueryModule.java [hunk 2]
```diff
@@ -51,6 +51,44 @@ public void testMySqlSourceQuerySupplier()
...
+                        .build());
+        Injector injector = app
+                .setRequiredConfigurationProperties(ImmutableMap.<String, String>builder()
+                        .putAll(DEFAULT_CONFIGURATION_PROPERTIES)
+                        .put("source-query.database", "jdbc://localhost:1080")
+                        .put("source-query.suites", "test")
+                        .put("source-query.max-queries-per-suite", "1000")
+                        .build())
+                .initialize();
+        assertTrue(injector.getInstance(SnapshotQueryConsumer.class) instanceof MysqlSnapshotQueryConsumer);
```
Comment (vermapratyush) [inline presto-verifier/src/test/java/com/facebook/presto/verifier/source/TestSourceQueryModule.java:89]: I think the tests can be merged into one.

**Review by vermapratyush — APPROVED** [review]
Thanks for the fix @v-jizhang

**Comment by ajaygeorge** [comment]
@v-jizhang Can you please update the description.
Now it says
> The bindings are in SourceQueryModule.java, but the error complains about VerifierModule.java. Move the bindings to VerifierModule.java.

I don't see any changes to `VerifierModule`

**Comment by v-jizhang** [comment]
> @v-jizhang Can you please update the description. Now it says
> 
> > The bindings are in SourceQueryModule.java, but the error complains about VerifierModule.java. Move the bindings to VerifierModule.java.
> 
> I don't see any changes to `VerifierModule`

It doesn't matter where the binding is as long as it is bound somewhere. The problem is that the binding code in SourceQueryModule.java was guarded by an if statement. Moving the binding out of the if statement solves the problem.

**Comment by ajaygeorge** [comment]
@v-jizhang sure it might not matter where the binding is. What I am recommending is to update the PR description to reflect what you are trying to do. Now they are out of sync.

**Review by ajaygeorge — APPROVED** [review]

**Comment by vermapratyush** [comment]
@v-jizhang Can you please address the remaining commit message before merging.

**Comment by v-jizhang** [comment]
> @v-jizhang sure it might not matter where the binding is. What I am recommending is to update the PR description to reflect what you are trying to do. Now they are out of sync.

Changed.

**Comment by v-jizhang** [comment]
I've done before and after tests, the failures exist in both cases. They are unrelated to the PR.
