### PR TITLE
Wait for indexes to load for IndexJoin

### LINKED ISSUE #12826: Failing runtime assertion: "Driver should never block"
```
java.lang.IllegalStateException: Driver should never block
	at com.google.common.base.Preconditions.checkState(Preconditions.java:504)
	at com.facebook.presto.operator.index.IndexLoader$IndexSnapshotLoader.load(IndexLoader.java:337)
	at com.facebook.presto.operator.index.IndexLoader.getIndexedDataForKeys(IndexLoader.java:180)
	at com.facebook.presto.operator.index.IndexLoader.getIndexedDataForKeys(IndexLoader.java:158)
	at com.facebook.presto.operator.index.IndexLookupSource.getJoinPosition(IndexLookupSource.java:83)
	at com.facebook.presto.operator.index.IndexLookupSource.getJoinPosition(IndexLookupSource.java:74)
	at com.facebook.presto.operator.JoinProbe.getCurrentJoinPosition(JoinProbe.java:87)
	at com.facebook.presto.operator.LookupJoinOperator.advanceProbePosition(LookupJoinOperator.java:565)
	at com.facebook.presto.operator.LookupJoinOperator.processProbe(LookupJoinOperator.java:478)
	at com.facebook.presto.operator.LookupJoinOperator.lambda$processProbe$3(LookupJoinOperator.java:399)
	at com.facebook.presto.operator.StaticLookupSourceProvider.withLease(StaticLookupSourceProvider.java:34)
	at com.facebook.presto.operator.LookupJoinOperator.processProbe(LookupJoinOperator.java:396)
	at com.facebook.presto.operator.LookupJoinOperator.getOutput(LookupJoinOperator.java:311)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at com.facebook.presto.$gen.Presto_0_219____20190514_204259_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

### PR DESCRIPTION
**Pull request by rschlussel**
Wait for indexes to load for IndexJoins until a configured time
out. Add configuration property index-loader-timeout and session
property index_loader_timeout to configure this timeout.  Previously
queries would fail with the error "driver should never block" if the
index server for the index join was slow. (Fixes #12826)

```
== RELEASE NOTES ==

General Changes
* Fix a bug where index joins would fail with the error "driver should never block".  Now queries will wait until a configured timeout for the indexes to load.  The timeout can be configured with the configuration property index-loader-timeout and the session property index_loader_timeout. 
```

### CODE REVIEW

**Comment by rschlussel** [comment]
I tested that index joins worked in our production environment, but i didn't have a good way to test a slow index server, or an exceeded timeout.  any suggestions?

File: presto-main/src/main/java/com/facebook/presto/operator/index/IndexLoader.java [hunk 1]
```diff
@@ -334,7 +347,18 @@ public boolean load(List<UpdateRequest> requests)
                 driver.updateSource(new TaskSource(sourcePlanNodeId, ImmutableSet.of(split), true));
                 while (!driver.isFinished()) {
                     ListenableFuture<?> process = driver.process();
-                    checkState(process.isDone(), "Driver should never block");
+                    long start = System.currentTimeMillis();
+                    while (!process.isDone() && System.currentTimeMillis() - start > timeout.toMillis()) {
```
Comment (highker) [inline presto-main/src/main/java/com/facebook/presto/operator/index/IndexLoader.java]: `process.get(timeout.toMillis(), TimeUnit.MILLISECONDS);` + some try/catching handling maybe?

Comment (rschlussel) [reply presto-main/src/main/java/com/facebook/presto/operator/index/IndexLoader.java]: thanks, that's much nicer!

Comment (hellium01) [reply presto-main/src/main/java/com/facebook/presto/operator/index/IndexLoader.java]: Instead of using a loop, can we do:
```
try {
	process.get( 1000, MILLISECONDS);
} catch (TimeoutException e) {
    throw new PrestoException(...);
}
catch (ExecutionException e) {
    throw new PrestoException(..., e.getCause());
}
catch (InterruptedException e) {
	Thread.currentThread().interrupt();
	throw Throwables.propagate(e);
}
```

File: presto-main/src/main/java/com/facebook/presto/operator/index/IndexLoader.java [hunk 2]
```diff
@@ -334,7 +350,15 @@ public boolean load(List<UpdateRequest> requests)
...
                 while (!driver.isFinished()) {
                     ListenableFuture<?> process = driver.process();
-                    checkState(process.isDone(), "Driver should never block");
+                    try {
+                        process.get(timeout.toMillis(), MILLISECONDS);
+                    }
+                    catch (TimeoutException e) {
+                        throw new PrestoException(INDEX_LOADER_TIMEOUT, format("Exceeded the time limit of %s loading indexes for index join", timeout));
+                    }
+                    catch (InterruptedException | ExecutionException e) {
```
Comment (hellium01) [inline presto-main/src/main/java/com/facebook/presto/operator/index/IndexLoader.java]: `InterruptedException` should interrupt current thread. Also, it might be better we unwrap the `ExecutionException` to get more meaningful stack trace but that's should be minor difference.

**Comment by hellium01** [comment]
I am not quite sure about testing though. It is very hard to reproduce with test environment. Probably add some sleep between `IndexSource`'s table read? but that might not always trigger this issue definitely.

File: presto-main/src/main/java/com/facebook/presto/operator/index/IndexLoader.java [hunk 3]
```diff
@@ -334,7 +350,15 @@ public boolean load(List<UpdateRequest> requests)
...
+                        throw new PrestoException(GENERIC_INTERNAL_ERROR, e);
```
Comment (highker) [inline presto-main/src/main/java/com/facebook/presto/operator/index/IndexLoader.java]: Maybe add a more informative error message.

File: presto-main/src/main/java/com/facebook/presto/operator/index/IndexLoader.java (hunk 2 above)
Comment (rschlussel) [reply presto-main/src/main/java/com/facebook/presto/operator/index/IndexLoader.java]: I'm not sure what you mean about the Interrupted Exception.  The current thread would probably get interrupted too, but we have to catch the InterruptedException here anyway because otherwise we'd have an uncaught exception.

Comment (hellium01) [reply presto-main/src/main/java/com/facebook/presto/operator/index/IndexLoader.java]: It is always a safe play to interrupt the thread when there is a `InterruptedException` unless you know for sure we can ignore it:
https://www.ibm.com/developerworks/library/j-jtp05236/

Comment (rschlussel) [reply presto-main/src/main/java/com/facebook/presto/operator/index/IndexLoader.java]: I see, thanks for the link.  So throwing a PrestoException isn't sufficiently interruptive because it can be caught without realizing it was really an InterruptedException.  So instead I should explicitly interrupt the current thread.

**Comment by rschlussel** [comment]
As per discussion with @hellium01, I'll merge this even though I wasn't able to reproduce the issue for a test.  It doesn't break anything and shouldn't make the problem worse.
