### PR TITLE
Fix flaky test (TestQueues::testTooManyQueries)

### LINKED ISSUE #8268: Intermittent failure in TestQueues.testTooManyQueries()
```
Tests run: 1405, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,184.734 sec <<< FAILURE! - in TestSuite

testTooManyQueries(com.facebook.presto.execution.resourceGroups.db.TestQueues)  Time elapsed: 22.001 sec  <<< FAILURE!

org.testng.internal.thread.ThreadTimeoutException: Method com.facebook.presto.execution.resourceGroups.db.TestQueues.testTooManyQueries() didn't finish within the time-out 60000

	at com.facebook.presto.execution.resourceGroups.db.TestQueues.testTooManyQueries(TestQueues.java:173)
```

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
This should hopefully fix #8268.

### CODE REVIEW

**Comment by haozhun** [comment]
Use commit message: `Fix flaky test TestQueues.testTooManyQueries`

File: presto-tests/src/test/java/com/facebook/presto/execution/resourceGroups/db/TestQueues.java [hunk 1]
```diff
@@ -150,21 +148,22 @@ public void testTooManyQueries()
...
-            while (manager.getResourceGroupInfo(
-                    new ResourceGroupId(new ResourceGroupId(new ResourceGroupId("global"), "user-user"), "dashboard-user")).getMaxRunningQueries() != 1) {
-                MILLISECONDS.sleep(500);
-            }
+            dbConfigurationManager.load();
             // Cancel query and verify that third query is still queued
             cancelQuery(queryRunner, firstDashboardQuery);
-            waitForQueryState(queryRunner, firstDashboardQuery, FAILED);
-            MILLISECONDS.sleep(2000);
+            waitForQueryState(queryRunner, firstDashboardQuery, ImmutableSet.of(FAILED, FINISHED));
```
Comment (haozhun) [inline presto-tests/src/test/java/com/facebook/presto/execution/resourceGroups/db/TestQueues.java]: FINISHED won't help.

File: presto-tests/src/test/java/com/facebook/presto/execution/resourceGroups/db/TestQueues.java [hunk 2]
```diff
@@ -150,21 +148,22 @@ public void testTooManyQueries()
...
-            ResourceGroupManager manager = queryRunner.getCoordinator().getResourceGroupManager().get();
-            while (manager.getResourceGroupInfo(
-                    new ResourceGroupId(new ResourceGroupId(new ResourceGroupId("global"), "user-user"), "dashboard-user")).getMaxRunningQueries() != 1) {
-                MILLISECONDS.sleep(500);
-            }
+            dbConfigurationManager.load();
             // Cancel query and verify that third query is still queued
             cancelQuery(queryRunner, firstDashboardQuery);
-            waitForQueryState(queryRunner, firstDashboardQuery, FAILED);
-            MILLISECONDS.sleep(2000);
```
Comment (haozhun) [inline presto-tests/src/test/java/com/facebook/presto/execution/resourceGroups/db/TestQueues.java]: Keep the timeout.

Alternatively, add `waitForQueryState` with timeout.
