### PR TITLE
De-flake TestUnweightedDoubleReservoirSample#testMany

### LINKED ISSUE #13459: Flaky test TestUnweightedDoubleReservoirSample
TestUnweightedDoubleReservoirSample fails sometimes:

```
[ERROR] Tests run: 5921, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,502.223 s <<< FAILURE! - in TestSuite
[ERROR] testMany(com.facebook.presto.operator.aggregation.reservoirsample.TestUnweightedDoubleReservoirSample)  Time elapsed: 0.069 s  <<< FAILURE!
java.lang.AssertionError: Expected quantized[i] > got: i=0, quantized=35.0, got=35 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.facebook.presto.operator.aggregation.reservoirsample.TestUnweightedDoubleReservoirSample.testMany(TestUnweightedDoubleReservoirSample.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

CC: @atavory

### PR DESCRIPTION
**Pull request by atavory**
Weighted reservoir sampling tests, some of which were randomized, sporadically failed. Adjusted the bounds to account for many times the tests run.

Fixes #13459

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by atavory** [comment]
@mbasmanova Could you please review? Thanks!

**Comment by caithagoras** [comment]
Still seeing flaky tests on Travis. Any updates? Thanks!

**Comment by caithagoras** [comment]
Updated PR description to indicate no release notes.

File: presto-main/src/test/java/com/facebook/presto/operator/aggregation/reservoirsample/TestUnweightedDoubleReservoirSample.java [hunk 1]
```diff
@@ -58,17 +58,17 @@ public void testMany()
...
+            reservoir.add(i);
         }
 
         double[] quantized = new double[4];
         for (double sample : reservoir.getSamples()) {
-            int index = (int) (4.0 * sample / (10.0 * streamLength + 1));
+            int index = (int) (4.0 * sample / (streamLength + 1));
             ++quantized[index];
         }
+        int expectedMin = 25;
```
Comment (wenleix) [inline presto-main/src/test/java/com/facebook/presto/operator/aggregation/reservoirsample/TestUnweightedDoubleReservoirSample.java]: so the number is changed from 35 to 25, assume this is intentional to make sure test is no longer that flaky? ;)
