### PR TITLE
Fix LocalFileRecordCursor timestamp parser

### LINKED ISSUE #9601: presto generates http-request .log containing records that fail queries on localfile.logs.http_request_log
# The short story
```
presto> select * from localfile.logs.http_request_log;

... Invalid format: "2017-12-21T00:12:27Z" is malformed at "Z"
```

Presto is looking for timestamp in `yyyy-MM-ddTHH:mm:ss.fffZ` format (please note the `.fff`).
In case the fractional part is missing, presto yields an error.
After editing the log and changing the timestamp to `2017-12-21T00:12:27.000Z` (please note the `.000`) the query worked fine.

# Version
presto-server-0.191
presto-cli-0.191-executable.jar

# localfile.properties
connector.name=localfile
presto-logs.http-request-log.location=/var/presto/data/var/log
presto-logs.http-request-log.pattern=http-request.log

# connect & run query
./presto --server localhost:8080 --catalog localfile --schema logs
presto:logs> select * from http_request_log;

Query 20171221_104944_00046_yfeuc, FAILED, 1 node
Splits: 17 total, 0 done (0.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20171221_104944_00046_yfeuc failed: Invalid format: "2017-12-21T00:12:27Z" is malformed at "Z"

presto:logs>

# http-request.log
dumarkov@dumarkov-presto:~/presto$ grep '2017-12-21T00:12:27Z' /var/presto/data/var/log/http-request.log
2017-12-21T00:12:27Z    127.0.0.1       GET     /v1/service/collector/general   null    1       200     0       36      1       830605f1fcac4d879453552
beeafaf4700000030d6

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
If the JVM default timezone is UTC then HTTP request log timestamp
will not be parseable by the LocalFileRecordCursor (e.g.,
2017-12-21T00:12:27Z and 2017-12-21T00:12:27.000Z).

This change uses the same formatter as in [HttpLogLayout](https://github.com/airlift/airlift/blob/8231839017159b70029dda31fababdc672348c55/http-server/src/main/java/io/airlift/http/server/HttpLogLayout.java#L13).

Fixes #9601.

Given the log (the last two timestamps are not parseable with the current code):
```
2018-05-24T23:59:59.006-07:00	2401:db00:21:7095:face:0:2d:0	GET	/v1/statement/20180525_065921_13647_iwv5x/32	null	null	200	0	54	1002	null
2017-12-21T00:12:27Z	2401:db00:21:7095:face:0:2d:0	GET	/v1/statement/20180525_065921_13647_iwv5x/32	null	null	200	0	54	1002	null
2017-12-21T00:12:27.000Z	2401:db00:21:7095:face:0:2d:0	GET	/v1/statement/20180525_065921_13647_iwv5x/32	null	null	200	0	54	1002	null
```

We get:

```
 select * from localfile.logs.http_request_log;
 server_address |        timestamp        |        client_address         | method |                 request_uri                  | user | agent | response_code | request_size | res
----------------+-------------------------+-------------------------------+--------+----------------------------------------------+------+-------+---------------+--------------+----
 127.0.0.1:8080 | 2018-05-24 23:59:59.006 | 2401:db00:21:7095:face:0:2d:0 | GET    | /v1/statement/20180525_065921_13647_iwv5x/32 | NULL | NULL  |           200 |            0 |
 127.0.0.1:8080 | 2017-12-21 00:12:27.000 | 2401:db00:21:7095:face:0:2d:0 | GET    | /v1/statement/20180525_065921_13647_iwv5x/32 | NULL | NULL  |           200 |            0 |
 127.0.0.1:8080 | 2017-12-21 00:12:27.000 | 2401:db00:21:7095:face:0:2d:0 | GET    | /v1/statement/20180525_065921_13647_iwv5x/32 | NULL | NULL  |           200 |            0 |
(3 rows)
```

### CODE REVIEW

File: presto-local-file/src/main/java/com/facebook/presto/localfile/LocalFileRecordCursor.java [hunk 1]
```diff
@@ -67,10 +67,7 @@
     private static final Splitter LINE_SPLITTER = Splitter.on("\t").trimResults();
 
     // TODO This should be a config option as it may be different for different log files
-    public static final DateTimeFormatter ISO_FORMATTER = new DateTimeFormatterBuilder()
-            .append(ISODateTimeFormat.dateHourMinuteSecondFraction())
-            .appendTimeZoneOffset("Z", true, 2, 2)
-            .toFormatter();
+    public static final DateTimeFormatter ISO_FORMATTER = DateTimeFormatter.ISO_OFFSET_DATE_TIME.withZone(ZoneId.systemDefault());
```
Comment (dain) [inline presto-local-file/src/main/java/com/facebook/presto/localfile/LocalFileRecordCursor.java]: static import?
