### PR TITLE
Fix failure with enabling JDBC autocommit

### LINKED ISSUE #15916: SQLException thrown when Connection.setAutoCommit(false) and then Connection.setAutoCommit(false);
SQLException is thrown when : 
```
      Class.forName(JDBC_DRIVER);
      con = DriverManager.getConnection(DB_URL, USER, PASS);

      con.setAutoCommit(false);
      con.setAutoCommit(true); // <--- Exception here
```
java.sql.SQLException: Connection is in auto-commit mode
	at com.facebook.presto.jdbc.PrestoConnection.commit(PrestoConnection.java:173)
	at com.facebook.presto.jdbc.PrestoConnection.setAutoCommit(PrestoConnection.java:155)
	at presto_jdbc.main(presto_jdbc.java:34)

These sequence of operations are common in BI Tools. Expectation is that the second `setAutoCommit(true)` will commit any changes and then continue without exception.

### PR DESCRIPTION
**Pull request by rschlussel**
## Description
There was a bug where enabling autocommit when it had previously been false would cause failure like:
java.sql.SQLException: Connection is in auto-commit mode

This was due to calling commit() from setAutoCommit() after autocommit had already been changed to true.
## Motivation and Context
Fixes #15916

## Impact
Fixes a failure when using JDBC when setting AutoCommit from false to true

## Test Plan
unit test
## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

JDBC Changes
* Fix failure when setting autoCommit from false to true :pr:`23453`

### CODE REVIEW

**Comment by steveburnett** [comment]
Just a nit to add the PR number to release note entry.

```
== RELEASE NOTES ==

JDBC Changes
* Fix failure when setting autoCommit from false to true :pr:`23453`

File: presto-jdbc/src/test/java/com/facebook/presto/jdbc/TestJdbcConnection.java [hunk 1]
```diff
@@ -105,21 +105,86 @@ public void teardownServer()
     public void testCommit()
             throws SQLException
     {
-        try (Connection connection = createConnection()) {
-            connection.setAutoCommit(false);
-            try (Statement statement = connection.createStatement()) {
-                statement.execute("CREATE TABLE test_commit (x bigint)");
+        try {
```
Comment (rschlussel) [inline presto-jdbc/src/test/java/com/facebook/presto/jdbc/TestJdbcConnection.java:108]: It's hard to see in github, but the only thing that's changed about this test is that it's wrapped in an extra try so I could put a finally at the end to drop the table.

Comment (tdcmeehan) [reply presto-jdbc/src/test/java/com/facebook/presto/jdbc/TestJdbcConnection.java:108]: A neat trick is to take the url in the browser and add the query parameter `?w=1`, which will cause whitespaces to be ignored.  e.g. https://github.com/prestodb/presto/pull/23453/files?w=1

**Review by tdcmeehan — DISMISSED** [review]

File: presto-jdbc/src/test/java/com/facebook/presto/jdbc/TestJdbcConnection.java [hunk 2]
```diff
@@ -105,21 +105,86 @@ public void teardownServer()
...
+                connection.setAutoCommit(true);
+            }
+
+            try (Connection connection = createConnection()) {
+                assertThat(listTables(connection)).contains("test_reset_autocommit");
+            }
+        }
+        finally {
+            try (Connection connection = createConnection()) {
+                connection.setAutoCommit(false);
```
Comment (hantangwangd) [inline presto-jdbc/src/test/java/com/facebook/presto/jdbc/TestJdbcConnection.java:183]: Should we set  autoCommit to `false` here if we intend to to drop the test table in the finally clause?

**Review by hantangwangd — COMMENTED** [review]
LGTM, one little nit.

File: presto-jdbc/src/test/java/com/facebook/presto/jdbc/TestJdbcConnection.java (hunk 2 above)
Comment (rschlussel) [reply presto-jdbc/src/test/java/com/facebook/presto/jdbc/TestJdbcConnection.java]: gah, thanks. Bad copy/paste

**Review by hantangwangd — APPROVED** [review]
Thanks for the quick fix.

**Review by ZacBlanco — APPROVED** [review]

**Review by tdcmeehan — APPROVED** [review]
