### PR TITLE
Fix artificially high queued query metrics

### LINKED ISSUE #14705: Some queries that end in User Error cause queuedQueries metric to be inaccurate
I recently discovered that the queued queries metric reported through JMX by our Presto cluster is wildly inaccurate: reported value of nearly 4k when the Cluster Overview UI shows 0 queued queries.

After a restart to zero it out, it seems like the inaccuracies in reported queuedQueries value track with queries that end in User Error. Looking at the source, it seems plausible that the query was cancelled before it triggered the queryStarted() method of QueryManagerStats, and thus the counter is not getting decremented.

Please let me know if I can be of any further help in addressing this problem
Screen Shot 2020-06-23 at 11 40 55 AM

### PR DESCRIPTION
**Pull request by jeremy-degroot**
Fixes #14705

Fixed a bug where queries that users cancelled early in their life-cycle would not decrement the queued queries counter, causing this metric to be artificially high.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

File: presto-tests/src/test/java/com/facebook/presto/tests/TestQueryManager.java [hunk 1]
```diff
@@ -90,6 +92,39 @@ public void testFailQuery()
...
+                .get();
+
+        // wait until it's admitted but fail it before it starts
+        while (true) {
+            QueryState state = dispatchManager.getQueryInfo(queryId).getState();
+            if (state.ordinal() >= RUNNING.ordinal()) {
+                fail("unexpected query state: " + state);
+            }
+            if (state.ordinal() >= DISPATCHING.ordinal()) {
+                System.out.println("Breaking on state:" + state);
```
Comment (tdcmeehan) [inline presto-tests/src/test/java/com/facebook/presto/tests/TestQueryManager.java:118]: We don't print to console

File: presto-tests/src/test/java/com/facebook/presto/tests/TestQueryManager.java [hunk 2]
```diff
@@ -90,6 +92,39 @@ public void testFailQuery()
...
+                break;
+            }
+            Thread.sleep(10);
+        }
+
+        // cancel query
+        QueryManager queryManager = queryRunner.getCoordinator().getQueryManager();
+        queryManager.failQuery(queryId, new PrestoException(GENERIC_USER_ERROR, "mock exception"));
```
Comment (tdcmeehan) [inline presto-tests/src/test/java/com/facebook/presto/tests/TestQueryManager.java:126]: Also add a check here to make sure we're not killing an already-running query.

File: presto-main/src/main/java/com/facebook/presto/execution/QueryManagerStats.java [hunk 3]
```diff
@@ -169,6 +173,8 @@ public void stateChanged(QueryState newValue)
                     stopped = true;
                     if (started) {
                         queryStopped();
+                    } else {
+                        queryDequeued();
```
Comment (tdcmeehan) [inline presto-main/src/main/java/com/facebook/presto/execution/QueryManagerStats.java:177]:
```suggestion
                    } 
                    else {
                        queryDequeued();
```

File: presto-main/src/main/java/com/facebook/presto/execution/QueryManagerStats.java [hunk 4]
```diff
@@ -76,13 +76,17 @@ private void queryStarted()
...
         runningQueries.incrementAndGet();
-        queuedQueries.decrementAndGet();
+        queryDequeued();
     }
 
     private void queryStopped()
     {
         runningQueries.decrementAndGet();
     }
+    private void queryDequeued()
```
Comment (tdcmeehan) [inline presto-main/src/main/java/com/facebook/presto/execution/QueryManagerStats.java:86]:
```suggestion

    private void queryDequeued()
```

File: presto-tests/src/test/java/com/facebook/presto/tests/TestQueryManager.java (hunk 2 above)
Comment (jeremy-degroot) [reply presto-tests/src/test/java/com/facebook/presto/tests/TestQueryManager.java:126]: Not sure why that should be necessary; the test will fail on line 115 if it gets as far as RUNNING

Comment (tdcmeehan) [reply presto-tests/src/test/java/com/facebook/presto/tests/TestQueryManager.java:125]: Query execution is proceeding in the background, so this is a last-moment check that the presumptions still hold.

Comment (jeremy-degroot) [reply presto-tests/src/test/java/com/facebook/presto/tests/TestQueryManager.java:125]: Fair enough

**Comment by tdcmeehan** [comment]
Looks like a test failure on Travis

**Comment by jeremy-degroot** [comment]
> Looks like a test failure on Travis

It's the new test. It works in my IDE but fails when I run it through `./mvnw`. Any idea what would cause that? I tried adding some debug output/logging, but I can't see it, even for stuff I know is running from the signals I do get.

**Comment by tdcmeehan** [comment]
Looks like the test was fixed.  Next, you'll need to:

1) Sign the CLA
2) Squash your commits and have them follow our commit guidelines.  I would suggest simply renaming the squashed commit to your PR title, that should be fine.

**Comment by jeremy-degroot** [comment]
I did sign the CLA after I saw that error message, do I need to do anything else to clear it?

**Comment by jeremy-degroot** [comment]
> 2\. Squash your commits and have them follow our [commit guidelines](https://chris.beams.io/posts/git-commit/).  I would suggest simply renaming the squashed commit to your PR title, that should be fine.

D

**Comment by tdcmeehan** [comment]
> I did sign the CLA after I saw that error message, do I need to do anything else to clear it?

It looks like this is because the user id in your commit is not linked to your Github account.  Try to follow these steps to resolve: https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by jeremy-degroot** [comment]
That test appears to be flaky at a 100ms pause for stats to update. I've upped it to 1000ms and run it several times to verify no more failures, I'm going to verify Travis passes then re-squash everything

**Comment by mbasmanova** [comment]
@tdcmeehan Tim, is this good to merge?

**Comment by mbasmanova** [comment]
@viczhang861 Vic, would you also like to take a look before merging?
