### PR TITLE
Silently drop Iceberg tables with missing filesystem metadata

### LINKED ISSUE #20529: Iceberg connector not able to drop tables with missing table metadata in Filesystem
## Your Environment

* Presto version used: 0.284-SNAPSHOT (master)
* Storage (HDFS/S3/GCS..): S3
* Data source and connector used: Iceberg with catalog type as Hive
* Deployment (Cloud or On-prem): Cloud

## Expected Behavior

Drop table should work and drop the table even if metadata/data doesn't exist in filesystem 

## Current Behavior

**"Table metadata is missing"** thrown in `com.facebook.presto.iceberg.HiveTableOperations#refreshFromMetadataLocation` when trying to check table properties https://github.com/prestodb/presto/blob/703e9429b8ce0a4bbec3ee6e361c0605bbf35a91/presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergHiveMetadata.java#L441-L446

## Possible Solution

Refactor current implementation to take into account such cases

## Steps to Reproduce

1. Create an iceberg table
2. Delete data from the filesystem
3. Try to drop the iceberg table

### PR DESCRIPTION
**Pull request by kiersten-stokes**
## Description
Adds two utility methods to bypass the previous "Table metadata is missing" error thrown when attempting to drop a Hive-backed table for which a metadata file or folder is missing from the underlying file system. The utility methods (accessed when attempting a fetch of the table properties or snapshotId) eat the `TableNotFoundException`, log a warning, and continue with the drop task. Other tasks like select and insert will still throw the error as expected.

## Motivation and Context
Fixes #20529 

## Impact
Logs a warning indicating property or snapshotId couldn't be fetched in lieu of throwing an exception

## Test Plan
Tested manually. One new test case is also added that deletes filesystem files and asserts that a drop task succeeds without throwing an error and drops the table from the expected schema. 

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [x] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== NO RELEASE NOTES ==
```

### CODE REVIEW

File: presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergUtil.java [hunk 1]
```diff
@@ -127,15 +129,15 @@ public static long resolveSnapshotId(Table table, long snapshotId)
                 .orElseThrow(() -> new PrestoException(ICEBERG_INVALID_SNAPSHOT_ID, format("Invalid snapshot [%s] for table: %s", snapshotId, table)));
     }
 
-    public static Optional<Long> resolveSnapshotIdByName(Table table, IcebergTableName name)
+    public static Optional<Long> resolveSnapshotIdByName(Table table, IcebergTableName name, Logger log)
```
Comment (tdcmeehan) [inline presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergUtil.java:132]: Just use a local logger in `IcebergUtil`

**Review by tdcmeehan — CHANGES_REQUESTED** [review]
LGTM % the logger change

File: presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergUtil.java (hunk 1 above)
Comment (kiersten-stokes) [reply presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergUtil.java]: 🤦‍♀️ of course. Done!

File: presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergAbstractMetadata.java [hunk 2]
```diff
@@ -414,7 +418,6 @@ public IcebergTableHandle getTableHandle(ConnectorSession session, SchemaTableNa
 
         // use a new schema table name that omits the table type
         Table table = getIcebergTable(session, new SchemaTableName(tableName.getSchemaName(), name.getTableName()));
-        validateTableMode(session, table);
```
Comment (tdcmeehan) [inline presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergAbstractMetadata.java:417]: CC: @s-akhtar-baig -- can you double check this?

File: presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergHiveMetadata.java [hunk 3]
```diff
@@ -316,11 +319,13 @@ public void dropTable(ConnectorSession session, ConnectorTableHandle tableHandle
         IcebergTableHandle handle = (IcebergTableHandle) tableHandle;
         // TODO: support path override in Iceberg table creation
         org.apache.iceberg.Table table = getHiveIcebergTable(metastore, hdfsEnvironment, session, handle.getSchemaTableName());
-        if (table.properties().containsKey(OBJECT_STORE_PATH) ||
-                table.properties().containsKey("write.folder-storage.path") || // Removed from Iceberg as of 0.14.0, but preserved for backward compatibility
-                table.properties().containsKey(WRITE_METADATA_LOCATION) ||
-                table.properties().containsKey(WRITE_DATA_LOCATION)) {
-            throw new PrestoException(NOT_SUPPORTED, "Table " + handle.getSchemaTableName() + " contains Iceberg path override properties and cannot be dropped from Presto");
+        if (tryGetProperties(table).isPresent()) {
+            if (table.properties().containsKey(OBJECT_STORE_PATH) ||
```
Comment (tdcmeehan) [inline presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergHiveMetadata.java:323]: Since this does two IO operations, please save the results of `tryGetProperties` so we can just retrieve it from the optional?

**Review by tdcmeehan — APPROVED** [review]
One more nit, please address and feel free to merge once the tests are green
