### PR TITLE
Fix flaky test testRunawayRegexAnalyzerTimeout

### LINKED ISSUE #20411: Test TestHivePushdownDistributedQueries testRunawayRegexAnalyzerTimeout fails with a timeout
https://github.com/prestodb/presto/actions/runs/5685313042/job/15409924223?pr=20409

Error:  Failures: 
Error:    TestHivePushdownDistributedQueries.testRunawayRegexAnalyzerTimeout » Test 
The exception was thrown with the wrong message: expected "Regexp matching interrupted" but got "The query optimizer exceeded the timeout of 1.00s."

### PR DESCRIPTION
**Pull request by ClarenceThreepwood**
Fixes #20411 

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by tdcmeehan — DISMISSED** [review]

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestDistributedQueries.java [hunk 1]
```diff
@@ -373,12 +374,24 @@ public void testExplainAnalyzeDDL()
         computeActual("EXPLAIN ANALYZE DROP TABLE orders");
     }
 
-    // Flaky test: https://github.com/prestodb/presto/issues/20764
-    @Test(expectedExceptions = RuntimeException.class, expectedExceptionsMessageRegExp = "Regexp matching interrupted", timeOut = 30_000, enabled = false)
-    public void testRunawayRegexAnalyzerTimeout()
+    @DataProvider
+    public static Object[][] timeouts()
```
Comment (rschlussel) [inline presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestDistributedQueries.java:378]: curious why you parametrized the test.

**Review by rschlussel — APPROVED** [review]
i apologize. i only saw this after i merged my change.  but adding the exception to the expected regex i think is probably a more reliable fix than what i had.  My only question is why test different timeout settings.

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestDistributedQueries.java (hunk 1 above)
Comment (ClarenceThreepwood) [reply presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestDistributedQueries.java:378]: With an optimizer timeout of 0.01s - you are much more likely to hit the other error message. But it might be overkill

Comment (rschlussel) [reply presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestDistributedQueries.java:378]: yeah, i think the point of this test is to make sure that a long running regex gets interrupted.  It's just sometimes possible that the timeout will be hit elsewhere.

Comment (ClarenceThreepwood) [reply presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestDistributedQueries.java:378]: ok - I'll remove the parametrization and keep the regex

**Review by rschlussel — APPROVED** [review]
