### PR TITLE
Optimize remaining expression and return empty result if its null/false 

### LINKED ISSUE #13992: Aria scan fails with "filter must be present if outputRequired is false"
An error occurs if filter pushdown is enabled and filter expression can be optimized in a way that reduces the set of inputs: 

```
> set session hive.pushdown_filter_enabled=true;
SET SESSION

> SELECT partkey FROM lineitem WHERE orderkey > 10 OR if(json_extract(json_parse('{}'), '$.a') IS NOT NULL, quantity * discount) > 0;

Query 20200121_154338_00012_v6fkz failed: Error opening Hive split file:/Users/mbasmanova/aria/test_data/hive_data/tpch/lineitem/20190723_181544_00002_ea4mu_628f36fa-c8f1-472d-9f9c-e8be512ab8d5 (offset=0, length=140103): filter must be present if outputRequired is false
com.facebook.presto.spi.PrestoException: Error opening Hive split file:/Users/mbasmanova/aria/test_data/hive_data/tpch/lineitem/20190723_181544_00002_ea4mu_628f36fa-c8f1-472d-9f9c-e8be512ab8d5 (offset=0, length=140103): filter must be present if outputRequired is false
	at com.facebook.presto.hive.orc.OrcSelectivePageSourceFactory.createOrcPageSource(OrcSelectivePageSourceFactory.java:407)
	at com.facebook.presto.hive.orc.OrcSelectivePageSourceFactory.createPageSource(OrcSelectivePageSourceFactory.java:223)
	at com.facebook.presto.hive.HivePageSourceProvider.createSelectivePageSource(HivePageSourceProvider.java:220)
	at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:126)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:51)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:58)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:248)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at com.facebook.presto.$gen.Presto_null__testversion____20200121_154218_2.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: filter must be present if outputRequired is false
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
	at com.facebook.presto.orc.reader.DoubleSelectiveStreamReader.<init>(DoubleSelectiveStreamReader.java:92)
	at com.facebook.presto.orc.reader.SelectiveStreamReaders.createStreamReader(SelectiveStreamReaders.java:71)
	at com.facebook.presto.orc.OrcSelectiveRecordReader.createStreamReaders(OrcSelectiveRecordReader.java:584)
	at com.facebook.presto.orc.OrcSelectiveRecordReader.<init>(OrcSelectiveRecordReader.java:177)
	at com.facebook.presto.orc.OrcReader.createSelectiveRecordReader(OrcReader.java:236)
	at com.facebook.presto.hive.orc.OrcSelectivePageSourceFactory.createOrcPageSource(OrcSelectivePageSourceFactory.java:370)
	... 17 more
```

CC: @prestodb/aria

### PR DESCRIPTION
**Pull request by bhhari**
A SelectiveStreamReader should be created only if the column is in output or required in a filter function evaluation. In this case we get the columns to be read from unoptimized expression, but column mappings are created from optimized expression which will ignore this column if the expression resolves to "null", which will result in creating a SelectiveReader which is not required and hence throws an exception. The fix is to ignore the interim column if the optimized expression discards it.

Fixes #13992
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

File: presto-hive/src/main/java/com/facebook/presto/hive/HivePageSourceProvider.java [hunk 1]
```diff
@@ -177,8 +178,15 @@ public ConnectorPageSource createPageSource(ConnectorTransactionHandle transacti
             TypeManager typeManager,
             LoadingCache<RowExpressionCacheKey, RowExpression> rowExpressionCache)
     {
-        Set<HiveColumnHandle> interimColumns = ImmutableSet.<HiveColumnHandle>builder()
-                .addAll(layout.getPredicateColumns().values())
+        RowExpression optimizedRemainingPredicate = rowExpressionCache.getUnchecked(new RowExpressionCacheKey(layout.getRemainingPredicate(), session));
+
+        ImmutableSet.Builder<HiveColumnHandle> interimColumnsBuilder = ImmutableSet.builder();
```
Comment (mbasmanova) [inline presto-hive/src/main/java/com/facebook/presto/hive/HivePageSourceProvider.java]: @bhhari Filter expressions that get optimized into `null` should be eliminated at the query planning phase. Why is this not happening? CC: @highker

Comment (mbasmanova) [reply presto-hive/src/main/java/com/facebook/presto/hive/HivePageSourceProvider.java]: @bhhari There is another scenario that needs to be handled. An original expression may use 3 columns, but optimized one only one column. In this case, we need to scan only one column, not three.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PickTableLayout.java [hunk 2]
```diff
@@ -329,6 +333,14 @@ public static PlanNode pushPredicateIntoTableScan(
             return new ValuesNode(idAllocator.getNextId(), node.getOutputVariables(), ImmutableList.of());
         }
 
+        RowExpression optimizedRemainingExpression = new RowExpressionOptimizer(metadata).optimize(translatedExpression.getRemainingExpression(), OPTIMIZED, session.toConnectorSession());
```
Comment (mbasmanova) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PickTableLayout.java]: @bhhari Looks like there is some redundancy here. The expression is being split into tuple domain and remaining predicate and these parts are being checked for "always-false" separately. Let's just optimize the whole expression and check the result.

Looks like `translatedExpression.getRemainingExpression(),` can be replaced by `expression` and logic using `translatedExpression` can be removed. 

```
        // optimize rowExpression and return ValuesNode if false. e.g. 0=1 => false, 1>2 => false, (a = 1 and a = 2) => false
        RowExpression optimizedRemainingExpression = new RowExpressionOptimizer(metadata).optimize(expression, OPTIMIZED, session.toConnectorSession());
        if (optimizedRemainingExpression instanceof ConstantExpression) {
            ConstantExpression constantExpression = (ConstantExpression) optimizedRemainingExpression;
            if (FALSE_CONSTANT.equals(constantExpression) || constantExpression.getValue() == null) {
                return new ValuesNode(idAllocator.getNextId(), node.getOutputVariables(), ImmutableList.of());
            }
        }
```

There is still a question about the case when optimized expression is not always-false, but rather uses fewer columns when original expression. This will generate an error, right?

Comment (bhhari) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PickTableLayout.java]: yes mentioned that in the commit message, it looks like if we use the optmization level as "Optimize" we can not serialize it back. This commit only solves the case where its null/false

Comment (mbasmanova) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PickTableLayout.java]: @bhhari  Are you planning to add another commit to fix the remaining issue. Something similar to the original fix could work. E.g. prune the predicate columns on the worker after optimizing the remaining expression.

Comment (bhhari) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PickTableLayout.java]: I m going to update the same commit, prune it during the planning

File: presto-hive/src/main/java/com/facebook/presto/hive/HiveMetadata.java [hunk 3]
```diff
@@ -1911,7 +1911,9 @@ public ConnectorPushdownFilterResult pushdownFilter(ConnectorSession session, Co
         domainPredicate.getDomains().get().keySet().stream()
                 .map(Subfield::getRootName)
                 .forEach(predicateColumnNames::add);
-        extractAll(decomposedFilter.getRemainingExpression()).stream()
+        // optimize the remaining expression before adding to predicateColumns
```
Comment (mbasmanova) [inline presto-hive/src/main/java/com/facebook/presto/hive/HiveMetadata.java]: Let's add a test case for expression over multiple columns being optimized into an expression over fewer columns.

File: presto-hive/src/main/java/com/facebook/presto/hive/HiveMetadata.java [hunk 4]
```diff
@@ -1911,7 +1911,9 @@ public ConnectorPushdownFilterResult pushdownFilter(ConnectorSession session, Co
...
+        RowExpression optimizedRemainingExpression = rowExpressionService.getExpressionOptimizer().optimize(decomposedFilter.getRemainingExpression(), OPTIMIZED, session);
+        extractAll(optimizedRemainingExpression).stream()
```
Comment (mbasmanova) [inline presto-hive/src/main/java/com/facebook/presto/hive/HiveMetadata.java]: I'm seeing the following test case failing. It used to work because PickTableLayout extract tuple domain and checked for isNone. I don't think that's a proper way though. It seems like HiveMetadata.pushdownFilter needs to check decomposedFilter.getTupleDomain() for isNone.

```
        assertPlan(pushdownFilterEnabled(), "SELECT linenumber FROM lineitem WHERE linenumber > 10 AND linenumber < 0",
                output(values("linenumber")));
```

Comment (bhhari) [reply presto-hive/src/main/java/com/facebook/presto/hive/HiveMetadata.java]: yes looks like the optmization does not do a good job there, so I will put my previous version

Comment (mbasmanova) [reply presto-hive/src/main/java/com/facebook/presto/hive/HiveMetadata.java]: @bhhari The previous version is masking the bug in the connector, but it doesn't fix it. The connector must handle properly the case when tuple domain part of the expression matches nothing (e.g. isNone() == true). Currently, it treats it as if any value matches. You can see that the bug is still there, by changing the query to use range filters on struct subfields:

```
SELECT id FROM test WHERE x.a > 10 AND x.a < 0
```

Here, the connector simply drops the filter as if it is always true.

A proper fix could be to 

- [Hive connector] check isNone on tuple domain and `return new ConnectorPushdownFilterResult(getTableLayout(session, currentLayoutHandle.get()), FALSE_CONSTANT);`
- [Hive connector] check if optimized remaining expression is always false and  `return new ConnectorPushdownFilterResult(getTableLayout(session, currentLayoutHandle.get()), FALSE_CONSTANT);`
- [Engine/PickTableLayout] Optimize entire expression and, if always false, return ValuesNode without calling the connector. This optimization is optional though. There might not be any reason to put it in. E.g. the change might be to just remove the existing optimization that extracts tuple domain and checks it for isNone.

**Comment by mbasmanova** [comment]
@bhhari 

Travis shows some tests failures that appear related to this change:

```
[ERROR] Tests run: 135, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,450.242 s <<< FAILURE! - in TestSuite
[ERROR] testStructs(com.facebook.presto.hive.TestHivePushdownFilterQueries)  Time elapsed: 33.048 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT orderkey FROM lineitem_ex WHERE info IS NOT NULL AND info.orderkey = 16515 and info.orderkye = 16516
	at org.testng.Assert.fail(Assert.java:83)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:150)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:138)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertQueryUsingH2Cte(TestHivePushdownFilterQueries.java:1070)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.testStructs(TestHivePushdownFilterQueries.java:647)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: line 1:87: Column 'info.orderkye' cannot be resolved
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:115)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:391)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:147)
	... 17 more
```

File: presto-hive/src/test/java/com/facebook/presto/hive/TestHivePushdownFilterQueries.java [hunk 5]
```diff
@@ -1033,6 +1034,15 @@ public void testNans()
         }
     }
 
+    @Test
+    public void testFilterFunctionsWithOptimization()
+    {
+        // the RowExpressionOptimizer optimizes the second part of the 2nd cardinality function to null hence not pushing down the linenumber as required predicate column
+        assertQuerySucceeds(getSession(), "SELECT partkey FROM lineitem WHERE " +
+                "cardinality(ARRAY_INTERSECT(ARRAY[orderkey], map_values(CAST(json_extract(json_parse('{\"a\": {\"a1\": {\"0\": 1}}}'),concat(concat('$.', 'a'), '[\"a1\"]')) AS MAP(VARCHAR, BIGINT))))) > 0 " +
```
Comment (mbasmanova) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestHivePushdownFilterQueries.java]: This query is a bit difficult to understand. Consider a simpler one:

```
SELECT partkey FROM lineitem WHERE orderkey > 10 OR if(json_extract(json_parse('{}'), '$.a') IS NOT NULL, quantity * discount) > 0
```

The results of that query can be verified and the verification could double-serve as documentation:

```
        assertQuery("SELECT partkey FROM lineitem WHERE orderkey > 10 OR if(json_extract(json_parse('{}'), '$.a') IS NOT NULL, quantity * discount) > 0",
                "SELECT partkey FROM lineitem WHERE orderkey > 10");
```

It would be nice to add this test to TestHiveLogicalPlanner where we can verify explicitly the list of columns in layout.predicateColumns.

File: presto-hive/src/main/java/com/facebook/presto/hive/HiveMetadata.java [hunk 6]
```diff
@@ -1894,8 +1895,25 @@ public ConnectorPushdownFilterResult pushdownFilter(ConnectorSession session, Co
             }
         }
 
+        SchemaTableName tableName = ((HiveTableHandle) tableHandle).getSchemaTableName();
         HivePartitionResult hivePartitionResult = partitionManager.getPartitions(metastore, tableHandle, constraint, session);
 
+        //if TupleDomain isNone or optmized remaningExpression is false return ConnectorPushdownFilterResult with TupleDomain.none() layout
+        if (decomposedFilter.getTupleDomain().isNone()) {
+            return new ConnectorPushdownFilterResult(
```
[the remark this answers is not in the document]
Comment (bhhari) [reply presto-hive/src/main/java/com/facebook/presto/hive/HiveMetadata.java]: "I would also update PickTableLayout to remove the logic of extracting TupleDomain and checking for none."  This will result in assertion failure in MetadaManager.pushdownFilter

File: presto-hive/src/test/java/com/facebook/presto/hive/TestHivePushdownFilterQueries.java [hunk 7]
```diff
@@ -1033,6 +1034,14 @@ public void testNans()
         }
     }
 
+    @Test
+    public void testFilterFunctionsWithOptimization()
+    {
+        // the RowExpressionOptimizer optimizes the second part of the 2nd cardinality function to null hence not pushing down the linenumber as required predicate column
```
Comment (mbasmanova) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestHivePushdownFilterQueries.java]: This comment is too low level for this high-level test. Consider removing.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PickTableLayout.java [hunk 8]
```diff
@@ -323,17 +324,17 @@ public static PlanNode pushPredicateIntoTableScan(
...
-        }
-
         BiMap<VariableReferenceExpression, VariableReferenceExpression> symbolToColumnMapping = node.getAssignments().entrySet().stream()
                 .collect(toImmutableBiMap(
                         Map.Entry::getKey,
                         entry -> new VariableReferenceExpression(getColumnName(session, metadata, node.getTable(), entry.getValue()), entry.getKey().getType())));
-        PushdownFilterResult pushdownFilterResult = metadata.pushdownFilter(session, node.getTable(), replaceExpression(expression, symbolToColumnMapping));
+
+        RowExpression replacedExpression = replaceExpression(expression, symbolToColumnMapping);
+        // replaceExpression() may further optimize the expression, if the resulting expression is false and return an empty result
```
Comment (mbasmanova) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PickTableLayout.java]: typos: `replaceExpression() may further optimize the expression; if the resulting expression is always false, then return empty Values node`
