### PR TITLE
Handle missing StorageDescriptor in Hive Glue tables

### LINKED ISSUE #17643: Missing StorageDescriptor in Hive Glue tables
Context: https://prestodb.slack.com/archives/C07JH9WMQ/p1649880784944269

```
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException: Table StorageDescriptor is null
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.get(CachingHiveMetastore.java:317)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.getTable(CachingHiveMetastore.java:362)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.getTable(SemiTransactionalHiveMetastore.java:170)
	at com.facebook.presto.hive.HiveMetadata.getViews(HiveMetadata.java:2262)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.getViews(ClassLoaderSafeConnectorMetadata.java:484)
	at com.facebook.presto.metadata.MetadataManager.getView(MetadataManager.java:1005)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1204)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:321)
	at com.facebook.presto.sql.tree.Table.accept(Table.java:53)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:335)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:2446)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1506)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:321)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:138)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:335)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:345)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1075)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:321)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:105)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:335)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:313)
	at com.facebook.presto.sql.analyzer.Analyzer.analyzeSemantic(Analyzer.java:89)
	at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:193)
	at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:98)
	at com.facebook.presto.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:834)
	at com.facebook.presto.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:123)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NullPointerException: Table StorageDescriptor is null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.facebook.presto.hive.metastore.glue.converter.GlueToPrestoConverter.convertTable(GlueToPrestoConverter.java:69)
	at com.facebook.presto.hive.metastore.glue.GlueHiveMetastore.lambda$getTable$3(GlueHiveMetastore.java:289)
	at java.util.Optional.map(Optional.java:215)
	at com.facebook.presto.hive.metastore.glue.GlueHiveMetastore.getTable(GlueHiveMetastore.java:289)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.loadTable(CachingHiveMetastore.java:373)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:188)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	... 39 more
```

Can be fixed by https://github.com/trinodb/trino/pull/11092

### PR DESCRIPTION
**Pull request by v-jizhang**
Cherry-pick of https://github.com/trinodb/trino/pull/11092

Fixes #17643

Co-authored-by: Alex <jo.alex2144@gmail.com>

Test plan - Test added

```
== RELEASE NOTES ==
Hive Changes
* Handle missing StorageDescriptor in Hive Glue tables
```

### CODE REVIEW

**Comment by prithvip** [comment]
@ChunxuTang could you take a look and review this?

**Comment by prithvip** [comment]
@ChunxuTang could you take a look and review this?

**Comment by ChunxuTang** [comment]
@prithvip Sure! Glad to help. Will take a look today.

File: presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/file/FileHiveMetastore.java [hunk 1]
```diff
@@ -106,6 +106,7 @@
 import static com.google.common.base.MoreObjects.toStringHelper;
 import static com.google.common.base.Preconditions.checkArgument;
 import static com.google.common.collect.ImmutableList.toImmutableList;
+import static java.util.Locale.ENGLISH;
```
Comment (ChunxuTang) [inline presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/file/FileHiveMetastore.java:109]: I think most changes in this file could be moved to `HiveUtil`, as the changes are mostly related to some helper functions.

File: presto-hive/src/test/java/com/facebook/presto/hive/metastore/glue/TestHiveClientGlueMetastore.java [hunk 2]
```diff
@@ -139,4 +159,57 @@ public void testGetPartitions()
...
+    @Test
+    public void testTableWithoutStorageDescriptor()
+    {
+        // StorageDescriptor is an Optional field for Glue tables. Iceberg and Delta Lake tables may not have it set.
+        SchemaTableName table = temporaryTable("test_missing_storage_descriptor");
+        DeleteTableRequest deleteTableRequest = new DeleteTableRequest()
+                .withDatabaseName(table.getSchemaName())
+                .withName(table.getTableName());
+        AWSGlueAsync glueClient = AWSGlueAsyncClientBuilder.defaultClient();
+        try (Transaction transaction = newTransaction()) {
```
Comment (ChunxuTang) [inline presto-hive/src/test/java/com/facebook/presto/hive/metastore/glue/TestHiveClientGlueMetastore.java:172]: Is this `Transaction transaction = newTransaction()` necessary? Looks like it's not used.

**Review by ChunxuTang — COMMENTED** [review]
Hi @v-jizhang, thanks a lot for your nice work!
I just left some minor suggestions. Feel free to have a look. 
Additionally, as the PR was sent around two weeks ago, when you push new changes, could you also merge the current presto master branch to avoid potential merge conflicts? Thanks!

File: presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/file/FileHiveMetastore.java [hunk 3]
```diff
@@ -503,9 +506,25 @@ public synchronized MetastoreOperationResult renameTable(MetastoreContext metast
...
+
+    public static boolean isIcebergTable(Table table)
+    {
+        return isIcebergTable(table.getParameters());
+    }
+
+    public static boolean isIcebergTable(Map<String, String> tableParameters)
+    {
+        return ICEBERG_TABLE_TYPE_VALUE.equalsIgnoreCase(tableParameters.get(ICEBERG_TABLE_TYPE_NAME));
     }
```
[the remark this answers is not in the document]
Comment (v-jizhang) [reply presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/file/FileHiveMetastore.java:528]: HiveUtil is in presto-hive module and if put them there, to avoid circular dependency, they cannot be referenced in presto-hive-metastore.

File: presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/file/FileHiveMetastore.java (hunk 1 above)
Comment (v-jizhang) [reply presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/file/FileHiveMetastore.java:109]: HiveUtil is in presto-hive and because presto-hive depends on presto-hive-metastore, presto-hive-metastore can't use anything in HiveUtil

File: presto-hive/src/test/java/com/facebook/presto/hive/metastore/glue/TestHiveClientGlueMetastore.java (hunk 2 above)
Comment (v-jizhang) [reply presto-hive/src/test/java/com/facebook/presto/hive/metastore/glue/TestHiveClientGlueMetastore.java:172]: You're right. It's not used.

**Comment by v-jizhang** [comment]
@ChunxuTang @rohanpednekar:  There is fix https://github.com/trinodb/trino/pull/12130. I'd like to port it in this PR also.

Thanks

**Review by ChunxuTang — COMMENTED** [review]
Hi @v-jizhang, thanks a lot for your work!
Sorry for my late reply. Let some minor suggestions~

BTW, I noticed that https://github.com/trinodb/trino/pull/12130 also contains two new functions `testIcebergTableNonNullStorageDescriptor` and `testDeltaTableNonNullStorageDescriptor ` in the `TestGlueToTrinoConverter`. Would you mind also cherry-picking them here?

**Comment by v-jizhang** [comment]
> Hi @v-jizhang, thanks a lot for your work! Sorry for my late reply. Let some minor suggestions~
> 
> BTW, I noticed that [trinodb/trino#12130](https://github.com/trinodb/trino/pull/12130) also contains two new functions `testIcebergTableNonNullStorageDescriptor` and `testDeltaTableNonNullStorageDescriptor ` in the `TestGlueToTrinoConverter`. Would you mind also cherry-picking them here?

Added tests. Thanks

**Review by ChunxuTang — APPROVED** [review]
@v-jizhang LGTM! Thanks for your work! BTW, I noticed that there's a testing failure. Could you re-run the tests to pass all of them?

Hi @beinan, would you like to also take a quick look at this PR?

**Review by beinan — APPROVED** [review]
lgtm, thx!
