### PR TITLE
Expose aggregation keys that are also source fields to ORDER BY

### LINKED ISSUE #8250: Column name resolution issue
I've found following issue regarding column name resolution when switching from version 0.158 to 0.178.
Using version 0.158 this query:
 > SELECT catalog.schema.table."column" FROM catalog.schema.table GROUP BY "column" ORDER BY catalog.schema.table."column" ASC;

Worked fine. Using v 0.178 I've got:
 > Query 20170613_104018_34104_v6755 failed: line 1:95: Column 'catalog.schema.table.column' cannot be resolved

It seems to be a problem with `ExpressionAnalyzer` that has changed over those versions.

Stacktrace for this query:
 > com.facebook.presto.sql.analyzer.SemanticException: line 1:95: Column 'catalog.schema.table.column' cannot be resolved
 >	at com.facebook.presto.sql.analyzer.SemanticExceptions.missingAttributeException(SemanticExceptions.java:30)
 >	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitDereferenceExpression(ExpressionAnalyzer.java:399)
 >	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitDereferenceExpression(ExpressionAnalyzer.java:282)
 >	at com.facebook.presto.sql.tree.DereferenceExpression.accept(DereferenceExpression.java:53)
 >	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
 >	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:301)
 >	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:258)
 >	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpressions(ExpressionAnalyzer.java:1441)
 >	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpressionsWithSymbols(ExpressionAnalyzer.java:1394)
 >	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.getExpressionTypes(ExpressionAnalyzer.java:1360)
 >	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.getExpressionTypes(ExpressionAnalyzer.java:1348)
 >	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.getExpressionTypes(ExpressionAnalyzer.java:1336)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.desugar(DesugaringOptimizer.java:203)
 >	at com.facebook.presto.sql.planner.plan.Assignments.lambda$rewrite$1(Assignments.java:109)
 >	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
 >	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
 >	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
 >	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
 >	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
 >	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
 >	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
 >	at com.facebook.presto.sql.planner.plan.Assignments.rewrite(Assignments.java:110)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:125)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:77)
 >	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
 >	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
 >	at java.util.Collections$2.tryAdvance(Collections.java:4717)
 >	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
 >	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
 >	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
 >	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
 >	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
 >	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitPlan(DesugaringOptimizer.java:99)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitPlan(DesugaringOptimizer.java:77)
 >	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitSort(PlanVisitor.java:104)
 >	at com.facebook.presto.sql.planner.plan.SortNode.accept(SortNode.java:88)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:95)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:124)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:77)
 >	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:95)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:124)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:77)
 >	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:95)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:124)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:77)
 >	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
 >	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
 >	at java.util.Collections$2.tryAdvance(Collections.java:4717)
 >	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
 >	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
 >	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
 >	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
 >	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
 >	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitPlan(DesugaringOptimizer.java:99)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitPlan(DesugaringOptimizer.java:77)
 >	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
 >	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:27)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer.optimize(DesugaringOptimizer.java:74)
 >	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:130)
 >	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:121)
 >	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:312)
 >	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:291)
 >	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:247)
 >	at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:62)
 >	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 >	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 >	at java.lang.Thread.run(Thread.java:745)

### PR DESCRIPTION
**Pull request by findepi**
Fixes #8250. However, more proper fix would be to remove need for scopes in translation map and use `FieldId`-s exclusively (#7398)

### CODE REVIEW

**Comment by sopel39** [comment]
> However, more proper fix would be to remove need for scopes in translation map and use FieldId-s exclusively.
There is issue for that: https://github.com/prestodb/presto/issues/7398

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java [hunk 1]
```diff
@@ -1594,9 +1594,17 @@ private Scope computeAndAssignOrderByScopeWithAggregation(OrderBy node, Scope ou
...
 
             // generate placeholder fields
+            Set<Field> seen = new HashSet<>();
             List<Field> orderByAggregationSourceFields = orderByAggregationExpressions.stream()
-                    .map(analysis::getType)
-                    .map(type -> Field.newUnqualified(Optional.empty(), type))
+                    .map(expression -> {
+                        // Expose aggregation keys that are also source fields to ORDER BY
+                        Optional<Field> sourceField = sourceScope.tryResolveField(expression)
+                                .filter(ResolvedField::isLocal)
```
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java]: I don't think it needs to be local. It is subquery planer responsibility to fail if it cannot support such correlated subqueries.

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java [hunk 2]
```diff
@@ -1594,9 +1594,17 @@ private Scope computeAndAssignOrderByScopeWithAggregation(OrderBy node, Scope ou
                     .collect(toImmutableList());
 
             // generate placeholder fields
+            Set<Field> seen = new HashSet<>();
```
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java]: do we really care about duplicates? I guess not. Unaliasing will take care about duplicates later.

Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java]: In https://github.com/prestodb/presto/pull/8252/files#diff-1a785e48f45c659076f1e4ec089517deR1590 I don't think it needed to filter aggregates which are just pure column references.

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java [hunk 3]
```diff
@@ -1858,19 +1877,19 @@ public void testGrouping()
             throws Exception
     {
         assertQuery(
-            "SELECT a, b as t, sum(c), grouping(a, b) + grouping(a) " +
-                    "FROM (VALUES ('h', 'j', 11), ('k', 'l', 7)) AS t (a, b, c) " +
-                    "GROUP BY GROUPING SETS ( (a), (b)) " +
-                    "ORDER BY grouping(b) ASC",
-            "VALUES (NULL, 'j', 11, 3), (NULL, 'l', 7, 3), ('h', NULL, 11, 1), ('k', NULL, 7, 1)");
+                "SELECT a, b as t, sum(c), grouping(a, b) + grouping(a) " +
```
Comment (sopel39) [inline presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java]: unrelated changes

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java [hunk 4]
```diff
@@ -1115,6 +1116,10 @@ public void testOrderByWithOutputColumnReference()
         assertQueryOrdered("select a as foo FROM (values (1,2),(3,2)) t(a,b) GROUP BY GROUPING SETS ((a), (a, b)) HAVING b IS NOT NULL ORDER BY -a", "VALUES 3, 1");
         assertQueryOrdered("select max(a) FROM (values (1,2),(3,2)) t(a,b) ORDER BY max(-a)", "VALUES 3");
         assertQueryFails("SELECT max(a) AS a FROM (values (1,2)) t(a,b) GROUP BY b ORDER BY max(a+b)", ".*Invalid reference to output projection attribute from ORDER BY aggregation");
+        assertQueryOrdered("SELECT -a as a, a as b FROM (VALUES 1, 2) t(a) GROUP BY t.a ORDER BY a", "VALUES (-2, 2), (-1, 1)");
+        assertQueryOrdered("SELECT -a as a, a as b FROM (VALUES 1, 2) t(a) GROUP BY t.a ORDER BY t.a", "VALUES (-1, 1), (-2, 2)");
+        assertQueryOrdered("SELECT -a as a, a as b FROM (VALUES 1, 2) t(a) GROUP BY a ORDER BY t.a", "VALUES (-1, 1), (-2, 2)");
+        // TODO #7398: assertQueryOrdered("SELECT -a as a, a as b FROM (VALUES 1, 2) t(a) GROUP BY a ORDER BY t.a-a", "VALUES (-1, 1), (-2, 2)");
```
Comment (sopel39) [inline presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java]: this can be fixed. Maybe I will make fix for this since I have the most context. Otherwise, we need to remove scopes from initial planning

**Comment by findepi** [comment]
@sopel39 , you're taking the lead here :)

**Comment by sopel39** [comment]
Thanks! Sooner or later we will need to resolve https://github.com/prestodb/presto/issues/7398 though.

**Comment by sopel39** [comment]
Fixed

**Comment by findepi** [comment]
@sopel39, what is fixed?

**Comment by sopel39** [comment]
@findepi the TODO test case (`SELECT ... as a GROUP BY a ORDER BY t.a + a`)
