### PR TITLE
Limit number of stages in a query

### LINKED ISSUE #10867: Add limit on maximum stages for a query
We should add a `query.max-stages` config property that is similar to `query.max-length` (max query text length) as a sanity check against queries that are unlikely to succeed (they will fail in weird ways or not render in the UI). These massive queries are usually generated as a list of `UNION ALL`, often as the result of users not being aware of `GROUPING SETS` (or `CUBE` / `ROLLUP`).

I'm not sure what a good default would be. `100` seems safe, but might fail some legitimate queries that used to work.

### PR DESCRIPTION
**Pull request by haozhun**
Fixes #10867.

### CODE REVIEW

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/FeaturesConfig.java [hunk 1]
```diff
@@ -816,4 +817,16 @@ public FeaturesConfig setMaxGroupingSets(int maxGroupingSets)
...
         return this;
     }
+
+    public int getMaxStageCount()
+    {
+        return maxStageCount;
+    }
+
+    @Config("max-stage-count")
+    public FeaturesConfig setMaxStageCount(int maxStageCount)
```
Comment (martint) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/FeaturesConfig.java]: There’s probably a better place for this config. The name should also be prefixed with “query.” or something. Take a look at other configs.

Comment (martint) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/FeaturesConfig.java]: See QueryManagerConfig

Comment (nezihyigitbasi) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/FeaturesConfig.java]: Also please specify a min/max.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/PlanFragmenter.java [hunk 2]
```diff
@@ -82,11 +98,24 @@ public static SubPlan createSubPlans(Session session, Metadata metadata, NodePar
...
 
+    private void sanityCheckFragmentedPlan(SubPlan subPlan)
+    {
+        subPlan.sanityCheck();
+        int fragmentCount = subPlan.getAllFragments().size();
+        if (fragmentCount > maxStageCount) {
+            throw new PrestoException(QUERY_TOO_MANY_STAGES, format(
+                    "Number of stages in the query (%s) exceeds the allowed maximum (%s). " +
+                            "If the query contains multiple DISTINCTs, please set the use_mark_distinct session property to false. " +
+                            "If the query contains multiple CTEs that are referenced more than once, please create temporary table for one or more of the CTEs.",
```
Comment (nezihyigitbasi) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/PlanFragmenter.java]: `create temporary table` -> `create temporary table(s)` ?

**Comment by haozhun** [comment]
@nezihyigitbasi, please take another look.

* I added `@Min`. I didn't add a `@Max` because I don't know what it should be. If you have an idea, I can add it.
* I added session property. I put it in a separate commit, and kept the code that would allow it to just be a config property around.

File: presto-spi/src/main/java/com/facebook/presto/spi/StandardErrorCode.java [hunk 3]
```diff
@@ -60,6 +60,7 @@
     EXCEEDED_FUNCTION_MEMORY_LIMIT(0x0000_0025, USER_ERROR),
     ADMINISTRATIVELY_KILLED(0x0000_0026, USER_ERROR),
     INVALID_COLUMN_PROPERTY(0x0000_0027, USER_ERROR),
+    QUERY_TOO_MANY_STAGES(0x0000_0028, USER_ERROR),
```
Comment (nezihyigitbasi) [inline presto-spi/src/main/java/com/facebook/presto/spi/StandardErrorCode.java]: How about we name this as `MAX_STAGE_COUNT_EXCEEDED`? This will make this error code sound more consistent with the other error codes, and also will make it consistent with the config/session property name.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/PlanFragmenter.java [hunk 4]
```diff
@@ -98,12 +94,12 @@ public SubPlan createSubPlans(Session session, Metadata metadata, NodePartitioni
         subPlan = analyzeGroupedExecution(session, metadata, nodePartitioningManager, subPlan);
 
         checkState(!isForceSingleNodeOutput(session) || subPlan.getFragment().getPartitioning().isSingleNode(), "Root of PlanFragment is not single node");
-        sanityCheckFragmentedPlan(subPlan);
+        sanityCheckFragmentedPlan(subPlan, SystemSessionProperties.getQueryMaxStageCount(session));
```
Comment (nezihyigitbasi) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/PlanFragmenter.java]: static import

File: presto-spi/src/main/java/com/facebook/presto/spi/StandardErrorCode.java (hunk 3 above)
Comment (haozhun) [reply presto-spi/src/main/java/com/facebook/presto/spi/StandardErrorCode.java]: I see
 
```
QUERY_TEXT_TOO_LARGE
PAGE_TOO_LARGE
TOO_MANY_REQUESTS_FAILED
```

and
```
EXCEEDED_FUNCTION_MEMORY_LIMIT
EXCEEDED_MEMORY_LIMIT
EXCEEDED_TIME_LIMIT
EXCEEDED_CPU_LIMIT
EXCEEDED_SPILL_LIMIT
```

I can do either `QUERY_TOO_MANY_STAGES` or `EXCEEDED_STAGE_COUNT_LIMIT`. I did the former because I find this one more similar in nature to `PAGE_TOO_LARGE`. But I don't feel strongly.
