### PR TITLE
Fix cli crash when trying to use `extract` with an invalid field

### LINKED ISSUE #5156: Typo in extract call crashes CLI
```
select extract(hou from create_time) from (values 1);
```
```
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.facebook.presto.sql.tree.Extract.Field.HOU
        at java.lang.Enum.valueOf(Enum.java:238)
        at com.facebook.presto.sql.tree.Extract$Field.valueOf(Extract.java:30)
        at com.facebook.presto.sql.parser.AstBuilder.visitExtract(AstBuilder.java:978)
        at com.facebook.presto.sql.parser.AstBuilder.visitExtract(AstBuilder.java:151)
        at com.facebook.presto.sql.parser.SqlBaseParser$ExtractContext.accept(SqlBaseParser.java:6210)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
        at com.facebook.presto.sql.parser.SqlBaseBaseVisitor.visitValueExpressionDefault(SqlBaseBaseVisitor.java:573)
        at com.facebook.presto.sql.parser.SqlBaseParser$ValueExpressionDefaultContext.accept(SqlBaseParser.java:5532)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
        at com.facebook.presto.sql.parser.AstBuilder.visitPredicated(AstBuilder.java:768)
        at com.facebook.presto.sql.parser.AstBuilder.visitPredicated(AstBuilder.java:151)
        at com.facebook.presto.sql.parser.SqlBaseParser$PredicatedContext.accept(SqlBaseParser.java:5103)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
        at com.facebook.presto.sql.parser.SqlBaseBaseVisitor.visitBooleanDefault(SqlBaseBaseVisitor.java:496)
        at com.facebook.presto.sql.parser.SqlBaseParser$BooleanDefaultContext.accept(SqlBaseParser.java:4809)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
        at com.facebook.presto.sql.parser.SqlBaseBaseVisitor.visitExpression(SqlBaseBaseVisitor.java:482)
        at com.facebook.presto.sql.parser.SqlBaseParser$ExpressionContext.accept(SqlBaseParser.java:4737)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
        at com.facebook.presto.sql.parser.AstBuilder.visitSelectSingle(AstBuilder.java:489)
        at com.facebook.presto.sql.parser.AstBuilder.visitSelectSingle(AstBuilder.java:151)
        at com.facebook.presto.sql.parser.SqlBaseParser$SelectSingleContext.accept(SqlBaseParser.java:3772)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.facebook.presto.sql.parser.AstBuilder.visit(AstBuilder.java:1296)
```

### PR DESCRIPTION
**Pull request by geraint0923**
Fix #5156

### CODE REVIEW

File: presto-parser/src/main/java/com/facebook/presto/sql/parser/AstBuilder.java [hunk 1]
```diff
@@ -989,7 +989,13 @@ public Node visitSpecialDateTimeFunction(SqlBaseParser.SpecialDateTimeFunctionCo
     @Override
     public Node visitExtract(SqlBaseParser.ExtractContext context)
     {
-        return new Extract(getLocation(context), (Expression) visit(context.valueExpression()), Extract.Field.valueOf(context.identifier().getText().toUpperCase()));
+        String field = context.identifier().getText();
+        try {
+            return new Extract(getLocation(context), (Expression) visit(context.valueExpression()), Extract.Field.valueOf(field.toUpperCase()));
+        }
+        catch (IllegalArgumentException e) {
```
Comment (martint) [inline presto-parser/src/main/java/com/facebook/presto/sql/parser/AstBuilder.java]: This `catch` is overly broad. If any of the other calls throws an IllegalArgumentException, this will incorrectly produce an "invalid extract field" error.

File: presto-parser/src/main/java/com/facebook/presto/sql/parser/AstBuilder.java [hunk 2]
```diff
@@ -989,7 +989,13 @@ public Node visitSpecialDateTimeFunction(SqlBaseParser.SpecialDateTimeFunctionCo
...
+            throw new ParsingException("Invalid extract field: " + field, null, context.getStart().getLine(), context.getStart().getCharPositionInLine());
```
Comment (martint) [inline presto-parser/src/main/java/com/facebook/presto/sql/parser/AstBuilder.java]: Change the message to something like "Invalid field for EXTRACT expression", or "Expected EXTRACT field to be one of xxx, yyy, zzz, ..."

File: presto-parser/src/main/java/com/facebook/presto/sql/parser/AstBuilder.java [hunk 3]
```diff
@@ -989,7 +989,13 @@ public Node visitSpecialDateTimeFunction(SqlBaseParser.SpecialDateTimeFunctionCo
     @Override
     public Node visitExtract(SqlBaseParser.ExtractContext context)
     {
-        return new Extract(getLocation(context), (Expression) visit(context.valueExpression()), Extract.Field.valueOf(context.identifier().getText().toUpperCase()));
```
Comment (martint) [inline presto-parser/src/main/java/com/facebook/presto/sql/parser/AstBuilder.java]: The commit subject should say something like "Throw proper exception when parsing invalid field for EXTRACT", and describe the consequence of now doing that (i.e., CLI can't handle it) in the commit message

**Comment by geraint0923** [comment]
Address the comments.

The error message now looks like:
```
presto:tiny> select extract(hou from create_time) from (values 1);
select extract(hou from create_time) from (values 1);
Query 20160502_190530_00005_dncmy failed: line 1:8: Expected EXTRACT field to be one of [YEAR, QUARTER, MONTH, WEEK, DAY, DAY_OF_MONTH, DAY_OF_WEEK, DOW, DAY_OF_YEAR, DOY, YEAR_OF_WEEK, YOW, HOUR, MINUTE, SECOND, TIMEZONE_MINUTE, TIMEZONE_HOUR], but it is: hou
LINE 1: select extract(hou from create_time) from (values 1)
               ^
```

**Comment by electrum** [comment]
Don't list all the values, especially not the aliases.

File: presto-parser/src/main/java/com/facebook/presto/sql/parser/AstBuilder.java [hunk 4]
```diff
@@ -995,7 +997,15 @@ public Node visitSpecialDateTimeFunction(SqlBaseParser.SpecialDateTimeFunctionCo
...
+        String fieldString = context.identifier().getText();
+        Extract.Field field = null;
+        try {
+            field = Extract.Field.valueOf(fieldString.toUpperCase());
+        }
+        catch (IllegalArgumentException e) {
+            check(field != null, format("Expected EXTRACT field to be one of %s, but it is: %s", Arrays.asList(Extract.Field.values()), fieldString), context);
```
Comment (electrum) [inline presto-parser/src/main/java/com/facebook/presto/sql/parser/AstBuilder.java]: Make the message
```java
format("Invalid EXTRACT field: %s", fieldString)

File: presto-parser/src/main/java/com/facebook/presto/sql/parser/AstBuilder.java [hunk 5]
```diff
@@ -995,7 +996,15 @@ public Node visitSpecialDateTimeFunction(SqlBaseParser.SpecialDateTimeFunctionCo
...
     public Node visitExtract(SqlBaseParser.ExtractContext context)
     {
-        return new Extract(getLocation(context), (Expression) visit(context.valueExpression()), Extract.Field.valueOf(context.identifier().getText().toUpperCase()));
+        String fieldString = context.identifier().getText();
+        Extract.Field field = null;
+        try {
+            field = Extract.Field.valueOf(fieldString.toUpperCase());
+        }
+        catch (IllegalArgumentException e) {
+            check(field != null, format("Invalid EXTRACT field: %s", fieldString), context);
```
Comment (martint) [inline presto-parser/src/main/java/com/facebook/presto/sql/parser/AstBuilder.java]: `field` is always null here, so the `field != null` check is unnecessary and confusing.

**Comment by geraint0923** [comment]
@martint @electrum Address the comment.

@electrum I am still confused why not list all the valid values, thus the users could know what values are valid.

Anyway, the error message now looks like:
```
presto:tiny> select extract(hou from create_time) from (values 1);
select extract(hou from create_time) from (values 1);
Query 20160502_213739_00011_dncmy failed: line 1:8: Invalid EXTRACT field: hou
LINE 1: select extract(hou from create_time) from (values 1)
               ^
```

**Comment by electrum** [comment]
It makes the error too long, and we don't want to list non-canonical aliases (several of which are not self descriptive). That's why we have documentation.

File: presto-parser/src/main/java/com/facebook/presto/sql/parser/AstBuilder.java (hunk 5 above)
Comment (geraint0923) [inline presto-parser/src/main/java/com/facebook/presto/sql/parser/AstBuilder.java]: @martint  Since I want to re-use `check` here and must have a condition here, is it okay to use `check(false, ...)` or I have to use `throw new ParsingException(...)` instead?

Comment (martint) [inline presto-parser/src/main/java/com/facebook/presto/sql/parser/AstBuilder.java]: Just throw a `new ParsingException(...)`

**Comment by geraint0923** [comment]
Address the comment.

**Comment by martint** [comment]
looks good
