### PR TITLE
Reimplement getRange and copyRange for InterleavedBlock

### LINKED ISSUE #5516: Division by zero error with empty interleaved block
This change 373c745b30b2db1e96eef844096b3620a11a84c7 added this bit to `InterleavedBlockEncoding.readBlock`:

```java
byte isEmpty = sliceInput.readByte();
if (isEmpty == 1) {
    return new InterleavedBlock(new Block[0]);
}
```

InterleavedBlock performs divisions using the length of that array (columns), which result in division by zero errors:

```java
int positionInBlock = position / columns;
```

```
java.sql.SQLException: Query failed (#20160623_104612_01302_fsieu): / by zero
	at com.facebook.presto.jdbc.PrestoResultSet.resultsException(PrestoResultSet.java:1799)
	at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1787)
	at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1756)
	at com.facebook.presto.jdbc.internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.facebook.presto.jdbc.internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.facebook.presto.jdbc.internal.guava.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.facebook.presto.jdbc.internal.guava.collect.Iterators$5.hasNext(Iterators.java:547)
	at com.facebook.presto.jdbc.PrestoResultSet.next(PrestoResultSet.java:149)
	at com.facebook.presto.verifier.Validator.convertJdbcResultSet(Validator.java:520)
	at com.facebook.presto.verifier.Validator.lambda$getResultSetConverter$4(Validator.java:494)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:130)
	at com.facebook.presto.verifier.Validator.executeQuery(Validator.java:426)
	at com.facebook.presto.verifier.Validator.executeQueryTest(Validator.java:304)
	at com.facebook.presto.verifier.Validator.validate(Validator.java:218)
	at com.facebook.presto.verifier.Validator.valid(Validator.java:190)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArithmeticException: / by zero
	at com.facebook.presto.spi.block.AbstractInterleavedBlock.getRegion(AbstractInterleavedBlock.java:260)
	at com.facebook.presto.spi.block.AbstractInterleavedBlock.copyRegion(AbstractInterleavedBlock.java:249)
	at com.facebook.presto.spi.block.AbstractArrayBlock.getSingleValueBlock(AbstractArrayBlock.java:234)
	at com.facebook.presto.operator.TopNOperator$TopNBuilder.getValues(TopNOperator.java:338)
	at com.facebook.presto.operator.TopNOperator$TopNBuilder.addRow(TopNOperator.java:313)
	at com.facebook.presto.operator.TopNOperator$TopNBuilder.mergeWithGlobalCandidates(TopNOperator.java:284)
	at com.facebook.presto.operator.TopNOperator$TopNBuilder.processPage(TopNOperator.java:273)
	at com.facebook.presto.operator.TopNOperator.addInput(TopNOperator.java:202)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:384)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:618)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:529)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:665)
	... 3 more
```

This reproduces the issue:

```java
InterleavedBlock block = new InterleavedBlock(new Block[0]);
block.copyRegion(0, 0);
```

(is that call to copyRegion even valid? If not, there might be another bug further up the stack, too)

Also, the test in `AbstractInterleavedBlock`'s constructor is a bit suspect. The condition checks for "non-negative", but the message says "positive". Moreover, given that methods use that value in division operations, it would seem that we should ensure the value is never 0.

```java
if (columns < 0) {
    throw new IllegalArgumentException("Number of blocks in InterleavedBlock must be positive");
}
```

### PR DESCRIPTION
**Pull request by haozhun**
Fixes #5516 

* The new implementation does not support non-aligned getRange and copyRange.
* Special handling for zero-column InterleavedBlock is removed because they
  are no longer constructed.
* This fixes bugs related handling of zero-column InterleavedBlock
  and zero-position InterleavedBlock. Specifically,
  * Before this commit, calling copyRegion on a zero-column InterleavedBlock
    causes div-by-zero exception
  * Before this commit, calling getRegion and semiCompact subsequently on a
    zero-length block can produce a zero-column InterleavedBlock

### CODE REVIEW

File: presto-main/src/test/java/com/facebook/presto/block/TestInterleavedBlock.java [hunk 1]
```diff
@@ -134,15 +134,16 @@ private void assertValues(Slice[] expectedValues)
         Type type = TYPES.get(position % TYPES.size());
         assertInterleavedPosition(ImmutableList.of(type), block.getSingleValueBlock(position), 0, expectedValue);
 
-        assertInterleavedPosition(ImmutableList.of(type), block.getRegion(position, 1), 0, expectedValue);
-        assertInterleavedPosition(TYPES, block.getRegion(0, position + 1), position, expectedValue);
-        assertInterleavedPosition(ImmutableList.of(type), block.getRegion(position, block.getPositionCount() - position), 0, expectedValue);
+        int positionFloored = position / COLUMN_COUNT * COLUMN_COUNT;
```
Comment (martint) [inline presto-main/src/test/java/com/facebook/presto/block/TestInterleavedBlock.java]: `alignedPosition`, or `entryStartPosition`, maybe?

Also, either add clarifying parenthesis or rewrite it as `position - position % COLUMN_COUNT`

**Comment by martint** [comment]
Other than that, it looks good.
