### PR TITLE
more lenient assertion for somewhat random test that is expected to f…

### LINKED ISSUE #22165: TestNoisySumGaussianRealAggregation.testNoisySumGaussianRealClippingSomeNoiseScaleWithinSomeStd
Possibly flaky. Seen on https://github.com/prestodb/presto/actions/runs/8248026106/job/22557471680?pr=22163

com.facebook.presto.operator.aggregation.noisyaggregation.TestNoisySumGaussianRealAggregation.testNoisySumGaussianRealClippingSomeNoiseScaleWithinSomeStd  Time elapsed: 0.004 s  <<< FAILURE!
2024-03-12T11:52:47.9286505Z java.lang.AssertionError: Test: Inconsistent results with large group id, Expected: 47.52453364071998, actual: 42.442403576947314
2024-03-12T11:52:47.9288028Z 	at org.testng.Assert.fail(Assert.java:110)
2024-03-12T11:52:47.9290046Z 	at com.facebook.presto.operator.aggregation.AggregationTestUtils.assertFunctionEquals(AggregationTestUtils.java:138)
2024-03-12T11:52:47.9395032Z 	at com.facebook.presto.operator.aggregation.AggregationTestUtils.groupedAggregation(AggregationTestUtils.java:390)
2024-03-12T11:52:47.9397665Z 	at com.facebook.presto.operator.aggregation.AggregationTestUtils.groupedAggregation(AggregationTestUtils.java:355)
2024-03-12T11:52:47.9402222Z 	at com.facebook.presto.operator.aggregation.AggregationTestUtils.assertAggregationInternal(AggregationTestUtils.java:124)
2024-03-12T11:52:47.9404706Z 	at com.facebook.presto.operator.aggregation.AggregationTestUtils.assertAggregation(AggregationTestUtils.java:85)
2024-03-12T11:52:47.9409938Z 	at com.facebook.presto.operator.aggregation.noisyaggregation.TestNoisySumGaussianRealAggregation.testNoisySumGaussianRealClippingSomeNoiseScaleWithinSomeStd(TestNoisySumGaussianRealAggregation.java:296)
2024-03-12T11:52:47.9413341Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-03-12T11:52:47.9420899Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-03-12T11:52:47.9422451Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-03-12T11:52:47.9423703Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2024-03-12T11:52:47.9424994Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
2024-03-12T11:52:47.9426568Z 	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
2024-03-12T11:52:47.9427969Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
2024-03-12T11:52:47.9429384Z 	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
2024-03-12T11:52:47.9430876Z 	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
2024-03-12T11:52:47.9432407Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
2024-03-12T11:52:47.9433963Z 	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
2024-03-12T11:52:47.9435460Z 	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
2024-03-12T11:52:47.9436848Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2024-03-12T11:52:47.9438228Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2024-03-12T11:52:47.9439941Z 	at java.lang.Thread.run(Thread.java:750)
2024-03-12T11:52:47.9440402Z 
2024-03-12T11:52:48.1097174Z [INFO] 
2024-03-12T11:52:48.1098020Z [INFO] Results:
2024-03-12T11:52:48.1098798Z [INFO] 
2024-03-12T11:52:48.1100625Z [ERROR] Failures: 
2024-03-12T11:52:48.1102867Z [ERROR]   TestNoisySumGaussianRealAggregation.testNoisySumGaussianRealClippingSomeNoiseScaleWithinSomeStd:296 Test: Inconsistent results with large group id, Expected: 47.52453364071998, actual: 42.442403576947314

### PR DESCRIPTION
**Pull request by elharo**
## Description
Allow more slack in test of semi-random result. Fixes #22165

## Motivation and Context
This test failed previously with a failure just barely outside the range of +/-5 so increase the allowed pass range to +/-6.

2024-03-12T11:52:47.9286505Z java.lang.AssertionError: Test: Inconsistent results with large group id, Expected: 47.52453364071998, actual: 42.442403576947314

I don't think this change increases the test from a 5 standard deviations failure to 6 standard deviations. I think the code was simply mistaken about how standard deviations work. However, I'd need to pull out my old statistics book to define this test correctly with respect to the number of standard deviations we want to test for. If there's a statistician in the house who can do the math, let me know.

## Impact
none

## Test Plan
CI

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [x] CI passed.

## Release Notes

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by tdcmeehan** [comment]
Please fix commit message to follow guidelines in contributing, maybe:

```
Relax assertions in TestNoisySumGaussianRealAggregation
```

**Comment by elharo** [comment]
done

File: presto-main/src/test/java/com/facebook/presto/operator/aggregation/noisyaggregation/TestNoisySumGaussianRealAggregation.java [hunk 1]
```diff
@@ -285,7 +285,8 @@ public void testNoisySumGaussianRealClippingSomeNoiseScaleWithinSomeStd()
         BiFunction<Object, Object, Boolean> withinSomeStdDoubleAssertion = (actual, expected) -> {
             double actualValue = new Double(actual.toString());
             double expectedValue = new Double(expected.toString());
-            return expectedValue - 5 * DEFAULT_TEST_STANDARD_DEVIATION <= actualValue && actualValue <= expectedValue + 5 * DEFAULT_TEST_STANDARD_DEVIATION;
+            // TODO calculate how many standard deviations this is
```
Comment (tdcmeehan) [inline presto-main/src/test/java/com/facebook/presto/operator/aggregation/noisyaggregation/TestNoisySumGaussianRealAggregation.java:288]: Should we address the TODO?  @duykienvp thoughts on this?

**Comment by elharo** [comment]
This one flaked again yesterday on an unrelated PR. Can we go ahead and merge it?

**Comment by elharo** [comment]
If we're not going to merge this PR, I should disable the test. As currently written, it's definitely broken.

File: presto-main/src/test/java/com/facebook/presto/operator/aggregation/noisyaggregation/TestNoisySumGaussianRealAggregation.java (hunk 1 above)
Comment (tdcmeehan) [reply presto-main/src/test/java/com/facebook/presto/operator/aggregation/noisyaggregation/TestNoisySumGaussianRealAggregation.java:288]: @jonhehir could you help?

**Review by tdcmeehan — APPROVED** [review]
Approved because it appears to make the test less flaky which will often block CI, but can you create an issue to follow up on the TODO?  I'm just not sure if this test is providing good test coverage as it is.

**Comment by elharo** [comment]
https://github.com/prestodb/presto/issues/22325
