### PR TITLE
Fix analysis/planning when lambda arguments clash with relation's columns

### LINKED ISSUE #9023: Analysis error for table alias in lambda
```
presto:default> select transform(array[1], x -> x + t.a) from (values 1, 2, 3) t(a);
Query 20170921_015629_01585_tme2n failed: line 1:37: Column 't' cannot be resolved
com.facebook.presto.sql.analyzer.SemanticException: line 1:37: Column 't' cannot be resolved
	at com.facebook.presto.sql.analyzer.SemanticExceptions.missingAttributeException(SemanticExceptions.java:30)
	at com.facebook.presto.sql.analyzer.Scope.lambda$resolveField$0(Scope.java:104)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.facebook.presto.sql.analyzer.Scope.resolveField(Scope.java:104)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:371)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:282)
	at com.facebook.presto.sql.tree.Identifier.accept(Identifier.java:70)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:301)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitDereferenceExpression(ExpressionAnalyzer.java:404)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitDereferenceExpression(ExpressionAnalyzer.java:282)
	at com.facebook.presto.sql.tree.DereferenceExpression.accept(DereferenceExpression.java:54)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:301)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.getOperator(ExpressionAnalyzer.java:1145)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitArithmeticBinary(ExpressionAnalyzer.java:575)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitArithmeticBinary(ExpressionAnalyzer.java:282)
	at com.facebook.presto.sql.tree.ArithmeticBinaryExpression.accept(ArithmeticBinaryExpression.java:85)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:301)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitLambdaExpression(ExpressionAnalyzer.java:1080)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitLambdaExpression(ExpressionAnalyzer.java:282)
	at com.facebook.presto.sql.tree.LambdaExpression.accept(LambdaExpression.java:60)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:301)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:264)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.access$1900(ExpressionAnalyzer.java:160)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.lambda$visitFunctionCall$1(ExpressionAnalyzer.java:799)
	at com.facebook.presto.sql.analyzer.TypeSignatureProvider.getTypeSignature(TypeSignatureProvider.java:60)
	at com.facebook.presto.metadata.SignatureBinder$FunctionSolver.update(SignatureBinder.java:725)
	at com.facebook.presto.metadata.SignatureBinder.iterativeSolve(SignatureBinder.java:399)
	at com.facebook.presto.metadata.SignatureBinder.bindVariables(SignatureBinder.java:114)
	at com.facebook.presto.metadata.SignatureBinder.bind(SignatureBinder.java:91)
	at com.facebook.presto.metadata.FunctionRegistry.identifyApplicableFunctions(FunctionRegistry.java:734)
	at com.facebook.presto.metadata.FunctionRegistry.matchFunction(FunctionRegistry.java:703)
	at com.facebook.presto.metadata.FunctionRegistry.matchFunctionExact(FunctionRegistry.java:693)
	at com.facebook.presto.metadata.FunctionRegistry.resolveFunction(FunctionRegistry.java:648)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.resolveFunction(ExpressionAnalyzer.java:1321)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:808)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:282)
	at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:111)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:301)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:258)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:1472)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeExpression(StatementAnalyzer.java:1901)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelect(StatementAnalyzer.java:1713)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.legacyVisitQuerySpecification(StatementAnalyzer.java:968)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:913)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:245)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:127)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:257)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:267)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:648)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:245)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:94)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:257)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:231)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:72)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:64)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:351)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:337)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
select transform(array[1], x -> x + t.a) from (values 1, 2, 3) t(a)

### LINKED ISSUE #9025: Wrong query results when lambda scope shadows column name
It's not possible to use dereference expressions in lambda context (#9023) except when dereferencing lambda argument's field (https://github.com/prestodb/presto/commit/789e4772527037efaed9e3bfbccfdee42697fa4b). 

However, even in the "supported" case, result is different when lambda arguement shadows a column reference:
```
SELECT transform(array[CAST(ROW(10) AS ROW(x INTEGER))], r -> r.x) FROM (VALUES 1) u(x);
 _col0 
-------
 [10]  
(1 row)

SELECT transform(array[CAST(ROW(10) AS ROW(x INTEGER))], r -> r.x) FROM (VALUES 1) r(x);
 _col0 
-------
 [1]   
(1 row)
```

IMO both queries should produce `10`, as column is being shadowed by lambda's formal argument.

### PR DESCRIPTION
**Pull request by findepi**
Fix lambda arguments handling in `ExpressionAnalyzer` and during query planning (`TranslationMap`).

Fixes #9023, #7784, #9025 

cc @martint @sopel39

### CODE REVIEW

**Comment by findepi** [comment]
I like #9090 more.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/TranslationMap.java [hunk 1]
```diff
@@ -300,8 +302,13 @@ private Expression coerceIfNecessary(Expression original, Expression rewritten)
         }, expression, null);
     }
 
-    Optional<Symbol> getSymbol(RelationPlan plan, Expression expression)
+    private Optional<Symbol> getSymbol(RelationPlan plan, Expression expression)
     {
+        if (!analysis.isColumnReference(expression)) {
```
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/TranslationMap.java]: check state instead?

Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/TranslationMap.java]: when this is needed?

**Comment by sopel39** [comment]
> I like #9090 more.

Nah. #9090 reapplies part of analysis in `TranslationMap` while you already have information which Node is column reference and lambda argument reference. In a way #9090 applies redundant logic and contains intermediate (unnecessary) step (creating scope for lambda analysis in translation map). This one is cleaner since it relies on already performed analysis.

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java [hunk 2]
```diff
@@ -1065,16 +1065,29 @@ protected Type visitLambdaExpression(LambdaExpression node, StackableAstVisitorC
...
+                    .withRelationType(RelationId.of(node), new RelationType(fields.build()))
+                    .build();
+
+            ImmutableMap.Builder<FieldId, LambdaArgumentDeclaration> fieldToLambdaArgumentDeclaration = ImmutableMap.builder();
+            if (context.getContext().isInLambda()) {
+                fieldToLambdaArgumentDeclaration.putAll(context.getContext().getFieldToLambdaArgumentDeclaration());
             }
-            Type returnType = process(node.getBody(), new StackableAstVisitorContext<>(Context.inLambda(context.getContext().getScope(), nameToLambdaArgumentDeclarationMap)));
+            for (LambdaArgumentDeclaration lambdaArgument : lambdaArguments) {
+                ResolvedField resolvedField = lambdaScope.resolveField(lambdaArgument, QualifiedName.of(lambdaArgument.getName().getValue()));
```
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java]: you can directly create field id here from `RelationId.of(node)` and index of `LambdaArgumentDeclaration`.
You can even use int stream for that, e.g:
```
IntStream.range(0, lambdaArguments.size())
  .forEach(index -> fieldToLambdaArgumentDeclaration.put(new FieldId(RelationId.of(node), index)); 
```
, but for loop is also enough

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java [hunk 3]
```diff
@@ -388,17 +388,17 @@ protected Type visitDereferenceExpression(DereferenceExpression node, StackableA
...
-                if (qualifiedName != null) {
-                    Scope scope = context.getContext().getScope();
-                    Optional<ResolvedField> resolvedField = scope.tryResolveField(node, qualifiedName);
-                    if (resolvedField.isPresent()) {
+            // If this Dereference looks like column reference, try match it to column first.
+            if (qualifiedName != null) {
+                Scope scope = context.getContext().getScope();
+                Optional<ResolvedField> resolvedField = scope.tryResolveField(node, qualifiedName);
+                if (resolvedField.isPresent()) {
+                    if (!context.getContext().isInLambda() || !context.getContext().getFieldToLambdaArgumentDeclaration().containsKey(FieldId.from(resolvedField.get()))) {
```
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java]: I don't think this special case is required as lambda won't resolve entire deference expression.

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java [hunk 4]
```diff
@@ -282,11 +282,11 @@ private Type analyze(Expression expression, Scope scope, Context context)
     private class Visitor
             extends StackableAstVisitor<Type, Context>
     {
-        private final Scope scope;
+        private final Scope baseScope;
```
[the remark this answers is not in the document]
Comment (findepi) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java]: This `Scope` is used to resolve `FieldReference` instances. Scope from context cannot be used for that.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/TranslationMap.java (hunk 1 above)
Comment (findepi) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/TranslationMap.java]: This is needed e.g. when `r` is a column reference of type `row(a: integer, ...)` and we try to get symbol for `r.a`.

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (sopel39) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java]: From semantic point of view `FieldReference` expressions should only be created for top level expressions (e.g: not in lambdas). Therefore context scope should be OK.

I guess the problem might be with `analyzeExpressionsWithInputs` which is used in `LocalExecutionPlanner` after `SymbolToInputRewriter`. However, I think that there should be another kind of expression (e.g: `ChannelReference`) for which type should be returned without using `Scope` at all (see https://github.com/prestodb/presto/issues/7398, `ChannelReference` would only be produced by SymbolToInputRewriter.

[the remark this answers is not in the document]
Comment (findepi) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java]: I think you're right about where the problematic `FieldReference` instances come from. What you suggest sounds like a good direction for the future.

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java (hunk 3 above)
Comment (findepi) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java]: Done

File: presto-main/src/main/java/com/facebook/presto/sql/planner/TranslationMap.java (hunk 1 above)
Comment (sopel39) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/TranslationMap.java]: When this would happen and why it wasn't a problem before?
Scope shouldn't resolve non column reference fields with `.tryResolveField(expression)`. What test does fail?

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (sopel39) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java]: At least minimally you should fix `ExpressionAnalyzer` with

> Alternatively, ExpressionAnalyzer might have optional Map<Integer, Type> inputMapping that would be used for FieldReference resolving (if present). The idea is that original (AST) FieldReferences would be translated to symbols so FieldReferences in LocalExecutionPlanner are only created by SymbolToInputRewriter. I think this is nicer temporary solution.

This will allow to void double scoping now in `ExpressionAnalyzer`.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/TranslationMap.java (hunk 1 above)
Comment (findepi) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/TranslationMap.java]: It would be redoing analysis in the query planning. Why would I want that?

**Comment by findepi** [comment]
rebased

File: presto-main/src/main/java/com/facebook/presto/sql/planner/TranslationMap.java (hunk 1 above)
Comment (sopel39) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/TranslationMap.java]: Well, using scope again is redoing analysis, but we have to live with this for now (this method will be gone eventually). However, as I mentioned, scope resolves only column references. That is why this change is questionable. In fact, the intention was to prevent using incorrect (non-lambda) scope for lambda arg reference. Because of such, it would be more natural to check if expression is not a lambda reference.

Comment (findepi) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/TranslationMap.java]: I agree with you. Except that it's not possible to just "check if expression is not a lambda reference" without redoing analysis, so I'd argue that the presented solution is more natural. Are we bike shedding?

Comment (sopel39) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/TranslationMap.java]: > Except that it's not possible to just "check if expression is not a lambda reference"

What about adding method to:
```
boolean Analysis::isLambdaArgumentReference(Expression expression) {
  returns expression instanceof Identifier && lambdaArgumentReferences.contains(NodeRef.of((Identifier) identifier));
}
```
which would be similar to `isColumnReference(Expression expression)`
?

Comment (findepi) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/TranslationMap.java]: Indeed, this would work. But also it would also make logic more complex. Instead of "is column reference so resolvable with scope" it would be "is not lambda reference, so probably column reference so resolvable with scope".

Comment (sopel39) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/TranslationMap.java]: > Instead of "is column reference so resolvable with scope"

This is actually: "is expression that is column reference resolvable with scope (than only resolves column references)", but then I think: "hey, if it's not a column reference then it shouldn't be resolved by scope anyway, so why this additional check"

The entire planner and analyzer is very complex piece of code. The less WTF code the better (you experienced that too). The code here deserves comment at least.

Comment (findepi) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/TranslationMap.java]: > The code here deserves comment at least.

Done.

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (findepi) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java]: I added a comment explaining purpose of the `ExpressionAnalyzer.Visitor#baseScope` field.

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java [hunk 5]
```diff
@@ -361,24 +360,26 @@ protected Type visitSymbolReference(SymbolReference node, StackableAstVisitorCon
...
         {
-            return handleResolvedField(node, FieldId.from(resolvedField), resolvedField.getType());
+            return handleResolvedField(node, FieldId.from(resolvedField), resolvedField.getType(), context);
         }
 
-        private Type handleResolvedField(Expression node, FieldId fieldId, Type resolvedType)
+        private Type handleResolvedField(Expression node, FieldId fieldId, Type resolvedType, StackableAstVisitorContext<Context> context)
         {
+            if (context.getContext().isInLambda()) {
+                LambdaArgumentDeclaration lambdaArgumentDeclaration = context.getContext().getFieldToLambdaArgumentDeclaration().get(fieldId);
```
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java]: ditto, `if (context.getContext().isInLambda()) {` seems not required.

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java [hunk 6]
```diff
@@ -793,11 +793,11 @@ protected Type visitFunctionCall(FunctionCall node, StackableAstVisitorContext<C
                                         parameters,
                                         isDescribe);
                                 if (context.getContext().isInLambda()) {
-                                    for (LambdaArgumentDeclaration argument : context.getContext().getNameToLambdaArgumentDeclarationMap().values()) {
+                                    for (LambdaArgumentDeclaration argument : context.getContext().getFieldToLambdaArgumentDeclaration().values()) {
                                         innerExpressionAnalyzer.setExpressionType(argument, getExpressionType(argument));
                                     }
                                 }
-                                return innerExpressionAnalyzer.analyze(expression, scope, context.getContext().expectingLambda(types)).getTypeSignature();
+                                return innerExpressionAnalyzer.analyze(expression, baseScope, context.getContext().expectingLambda(types)).getTypeSignature();
```
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java]: `context.getContext().getScope()`? Definitely `expectingLambda` preserves `this.nameToLambdaArgumentDeclarationMap` in current master. Add test for this case (some kind of nested lambdas with reference to outer lambda argument)?

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java [hunk 7]
```diff
@@ -1065,16 +1065,29 @@ protected Type visitLambdaExpression(LambdaExpression node, StackableAstVisitorC
...
+                setExpressionType(lambdaArgument, type);
+            }
+
+            Scope lambdaScope = Scope.builder()
+                    .withParent(context.getContext().getScope())
+                    .withRelationType(RelationId.of(node), new RelationType(fields.build()))
+                    .build();
+
+            ImmutableMap.Builder<FieldId, LambdaArgumentDeclaration> fieldToLambdaArgumentDeclaration = ImmutableMap.builder();
+            if (context.getContext().isInLambda()) {
```
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java]: I don't think this check is required.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/TranslationMap.java [hunk 8]
```diff
@@ -258,12 +258,14 @@ private Expression rewriteExpressionWithResolvedName(Expression node)
...
             {
-                Optional<ResolvedField> resolvedField = rewriteBase.getScope().tryResolveField(node);
-                if (resolvedField.isPresent()) {
-                    if (resolvedField.get().isLocal()) {
-                        return getSymbol(rewriteBase, node)
-                                .map(symbol -> coerceIfNecessary(node, symbol.toSymbolReference()))
-                                .orElseThrow(() -> new IllegalStateException("No symbol mapping for node " + node));
+                if (analysis.isColumnReference(node)) {
+                    Optional<ResolvedField> resolvedField = rewriteBase.getScope().tryResolveField(node);
+                    if (resolvedField.isPresent()) {
```
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/TranslationMap.java]: I think this should be check state: `checkState(resolvedField.isPresent()`) as column references should be resolvable by corresponding scope

Comment (findepi) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/TranslationMap.java]: I think they don't need to be. The check was here before and i think i tried to remove it..

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java (hunk 6 above)
Comment (sopel39) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java]: I guess the problem is with this `Map<Integer, Type>` map that is used to resolve `FieldReferences` (this information needs to be passed to `innerExpressionAnalyzer`). However, https://github.com/prestodb/presto/pull/9099#discussion_r145956962 might work here. It's strange though that no test failed (lack of proper test?)

File: presto-main/src/main/java/com/facebook/presto/sql/planner/TranslationMap.java (hunk 8 above)
Comment (sopel39) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/TranslationMap.java]: It would be strange if the `if (resolvedField.isPresent()) {` is needed for tests to pass. If the expression is column reference then the scope here should be the one that resolved it during analysis. Subqueries should be translated already and lambda scope doesn't resolve column references at all.

If the scope here is different than the one that resolved column reference during analysis then it's potentially semantically incorrect. Such different scope might not resolve field, but it might also (incorrectly) resolve field to a wrong field index.

In any case, we need to investigate if this issue is introduced by this PR or was already in the code. It could be that the `if (resolvedField.isPresent()) {` is required and correct because it's just some edge case (e.g: part of ORDER BY support or some subquery is not supported and wasn't rewritten).

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java (hunk 6 above)
Comment (findepi) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java]: The right `Scope` is passed via `context.getContext().expectingLambda(types)` expression, so this is correct.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/TranslationMap.java (hunk 8 above)
Comment (findepi) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/TranslationMap.java]: There is an edge-case related to order by planning in `QueryPlanner`, needs to stay

**Comment by sopel39** [comment]
This will be merged again after release is closed

**Comment by findepi** [comment]
@sopel39 , to facilitate (testing and) merging once release is out, i created a new PR: #9269
