### PR TITLE
Fix timestamp escaping in FileHiveMetastore

### LINKED ISSUE #8743: Wrong results when filtering on partitioned char(x) or long decimal column
The following example is based on TestHiveIntegrationSmokeTest.createPartitionedTable()

```
CREATE TABLE test_partitioned_table ( 
                  _string VARCHAR 
                ,  _varchar VARCHAR(65535) 
                , _char CHAR(10) 
                , _bigint BIGINT 
                , _integer INTEGER 
                , _smallint SMALLINT 
                , _tinyint TINYINT 
                , _real REAL 
                , _double DOUBLE 
                , _boolean BOOLEAN 
                , _decimal_short DECIMAL(3,2) 
                , _decimal_long DECIMAL(30,10) 
                , _partition_string VARCHAR 
                , _partition_varchar VARCHAR(65535) 
                , _partition_char CHAR(10) 
                , _partition_tinyint TINYINT 
                , _partition_smallint SMALLINT 
                , _partition_integer INTEGER 
                , _partition_bigint BIGINT 
                , _partition_decimal_short DECIMAL(3,2) 
                , _partition_decimal_long DECIMAL(30,10) 
                )  
                WITH ( 
                partitioned_by = ARRAY[ '_partition_string', '_partition_varchar', '_partition_char', '_partition_tinyint', '_partition_smallint', '_partition_integer', '_partition_bigint', '_partition_decimal_short', '_partition_decimal_long' ] 
                ) ;
```

```
INSERT INTO test_partitioned_table SELECT 
'foo' _string , 
'bar' _varchar , 
CAST('boo' AS CHAR(10)) _char , 
CAST(1 AS BIGINT) _bigint , 
2 _integer , 
CAST (3 AS SMALLINT) _smallint , 
CAST (4 AS TINYINT) _tinyint , 
CAST('123.45' AS REAL) _real , 
CAST('3.14' AS DOUBLE) _double , 
true _boolean , 
CAST('3.14' AS DECIMAL(3,2)) _decimal_short ,
CAST('12345678901234567890.0123456789' AS DECIMAL(30,10)) _decimal_long ,
'foo' _partition_string , 
'bar' _partition_varchar , 
CAST('boo' AS CHAR(10)) _partition_char , 
CAST(1 AS TINYINT) _partition_tinyint , 
CAST(1 AS SMALLINT) _partition_smallint , 
1 _partition_integer , 
CAST (1 AS BIGINT) _partition_bigint , 
CAST('3.14' AS DECIMAL(3,2)) _partition_decimal_short , CAST('12345678901234567890.0123456789' AS DECIMAL(30,10)) _partition_decimal_long;
```

Running
`SELECT * from test_partitioned_table WHERE CAST('boo' AS CHAR(10)) = _partition_char;`  returns 0 rows
 
The same is true for filters on the long decimal column e.g. 
`SELECT * from test_partitioned_table WHERE CAST('12345678901234567890.0123456789' AS DECIMAL(30,10)) =_partition_decimal_long;` 
returns 0 results

Filtering by the rest of the partitioning keys returns correct results

### PR DESCRIPTION
**Pull request by rschlussel**
Filtering on char(x) or long decimal partition columns would return zero
rows. This was because when we checked if we could prune any partitions,
we didn't convert the filter values correctly from slices to strings, so
the metastore would think there were no matching partitions.

Fixes #8743

### CODE REVIEW

File: presto-hive/src/main/java/com/facebook/presto/hive/HivePartitionManager.java [hunk 1]
```diff
@@ -25,6 +25,9 @@
 import com.facebook.presto.spi.predicate.NullableValue;
 import com.facebook.presto.spi.predicate.TupleDomain;
 import com.facebook.presto.spi.predicate.ValueSet;
+import com.facebook.presto.spi.type.CharType;
+import com.facebook.presto.spi.type.DecimalType;
+import com.facebook.presto.spi.type.SqlDecimal;
```
Comment (findepi) [inline presto-hive/src/main/java/com/facebook/presto/hive/HivePartitionManager.java]: typo in cmt msg "decimla"

File: presto-hive/src/main/java/com/facebook/presto/hive/HivePartitionManager.java [hunk 2]
```diff
@@ -225,7 +229,25 @@ private Table getTable(SemiTransactionalHiveMetastore metastore, SchemaTableName
...
+                            builder.append(' ');
+                        }
+
+                        filter.add(builder.toString());
+                    }
+                    else if (type instanceof DecimalType) {
+                        filter.add(new SqlDecimal(unscaledDecimalToBigInteger(slice), ((DecimalType) type).getPrecision(), ((DecimalType) type).getScale()).toString());
+                    }
+                    else {
+                        filter.add(slice.toStringUtf8());
```
Comment (findepi) [inline presto-hive/src/main/java/com/facebook/presto/hive/HivePartitionManager.java]: Is it safe _now_?

File: presto-hive/src/main/java/com/facebook/presto/hive/HivePartitionManager.java [hunk 3]
```diff
@@ -225,7 +229,25 @@ private Table getTable(SemiTransactionalHiveMetastore metastore, SchemaTableName
...
                 else if (value instanceof Slice) {
-                    filter.add(((Slice) value).toStringUtf8());
+                    Type type = domain.getType();
+                    Slice slice = (Slice) value;
+                    if (type instanceof CharType) {
+                        int length = ((CharType) type).getLength();
+                        StringBuilder builder = new StringBuilder(length);
+                        String sliceString = slice.toStringUtf8();
+                        builder.append(sliceString);
+                        for (int i = sliceString.length(); i < length; i++) {
```
Comment (findepi) [inline presto-hive/src/main/java/com/facebook/presto/hive/HivePartitionManager.java]: extract to a method (possibility in some reusable place)... unless there isn't one already?

File: presto-hive/src/main/java/com/facebook/presto/hive/HivePartitionManager.java [hunk 4]
```diff
@@ -225,7 +229,25 @@ private Table getTable(SemiTransactionalHiveMetastore metastore, SchemaTableName
...
+                            builder.append(' ');
+                        }
+
+                        filter.add(builder.toString());
+                    }
+                    else if (type instanceof DecimalType) {
+                        filter.add(new SqlDecimal(unscaledDecimalToBigInteger(slice), ((DecimalType) type).getPrecision(), ((DecimalType) type).getScale()).toString());
```
Comment (findepi) [inline presto-hive/src/main/java/com/facebook/presto/hive/HivePartitionManager.java]: Is `SqlDecimal#toString` guaranteed to return value in the form that is desired here?

File: presto-hive/src/main/java/com/facebook/presto/hive/HivePartitionManager.java (hunk 2 above)
Comment (kokosing) [inline presto-hive/src/main/java/com/facebook/presto/hive/HivePartitionManager.java]: Maybe we should check if type is `VarcharType` and raise error in last `else` block?

File: presto-hive/src/main/java/com/facebook/presto/hive/HivePartitionManager.java [hunk 5]
```diff
@@ -225,7 +229,25 @@ private Table getTable(SemiTransactionalHiveMetastore metastore, SchemaTableName
...
-                    filter.add(((Slice) value).toStringUtf8());
+                    Type type = domain.getType();
+                    Slice slice = (Slice) value;
+                    if (type instanceof CharType) {
+                        int length = ((CharType) type).getLength();
+                        StringBuilder builder = new StringBuilder(length);
+                        String sliceString = slice.toStringUtf8();
+                        builder.append(sliceString);
+                        for (int i = sliceString.length(); i < length; i++) {
+                            builder.append(' ');
```
Comment (kokosing) [inline presto-hive/src/main/java/com/facebook/presto/hive/HivePartitionManager.java]: what about using `com.facebook.presto.spi.type.Chars#padSpaces(io.airlift.slice.Slice, com.facebook.presto.spi.type.Type)`?

Comment (rschlussel) [inline presto-hive/src/main/java/com/facebook/presto/hive/HivePartitionManager.java]: Didn't know about that, thanks!

File: presto-hive/src/main/java/com/facebook/presto/hive/HivePartitionManager.java (hunk 4 above)
Comment (rschlussel) [inline presto-hive/src/main/java/com/facebook/presto/hive/HivePartitionManager.java]: I'm not sure. I was hesitant because it doesn't seem parallel to what happens with ShortDecimal below (which is just value.toString()), but I tried it out and it worked.  

Also, I think I'll change this to use `Decimals.toString(slice, scale)`.

File: presto-hive/src/main/java/com/facebook/presto/hive/HivePartitionManager.java [hunk 6]
```diff
@@ -225,7 +230,20 @@ private Table getTable(SemiTransactionalHiveMetastore metastore, SchemaTableName
...
+                        filter.add(padSpaces(slice, type).toStringUtf8());
+                    }
+                    else if (type instanceof DecimalType) {
+                        filter.add(Decimals.toString(slice, ((DecimalType) type).getScale()));
+                    }
+                    else if (type instanceof VarcharType) {
+                        filter.add(slice.toStringUtf8());
+                    }
+                    else {
+                        throw new PrestoException(NOT_SUPPORTED, format("Unsupported partitioning key type: %s", type.getDisplayName()));
```
Comment (nezihyigitbasi) [inline presto-hive/src/main/java/com/facebook/presto/hive/HivePartitionManager.java]: `partitioning key` -> `partition key`

File: presto-hive/src/test/java/com/facebook/presto/hive/TestHiveIntegrationSmokeTest.java [hunk 7]
```diff
@@ -302,6 +302,18 @@ public void createPartitionedTable(Session session, HiveStorageFormat storageFor
 
         assertUpdate(session, "INSERT INTO test_partitioned_table " + select, 1);
         assertQuery(session, "SELECT * from test_partitioned_table", select);
+        assertQuery(session,
+                "SELECT * from test_partitioned_table WHERE" +
+                        " 'foo' =  _partition_string" +
```
Comment (nezihyigitbasi) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestHiveIntegrationSmokeTest.java]: nit: two spaces after `=` on L307, L309, L312, L313, and no space after `=` on L315.

also seems like in this class we are not consistent with the spacing around `CAST` calls.

Comment (rschlussel) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestHiveIntegrationSmokeTest.java]: fixed. Made the spacing after cast calls in this select statement consistent, but didn't touch the rest of the class.

File: presto-hive/src/main/java/com/facebook/presto/hive/HivePartitionManager.java [hunk 8]
```diff
@@ -225,7 +230,20 @@ private Table getTable(SemiTransactionalHiveMetastore metastore, SchemaTableName
                     filter.add(HivePartitionKey.HIVE_DEFAULT_DYNAMIC_PARTITION);
                 }
                 else if (value instanceof Slice) {
-                    filter.add(((Slice) value).toStringUtf8());
+                    Type type = domain.getType();
```
Comment (losipiuk) [inline presto-hive/src/main/java/com/facebook/presto/hive/HivePartitionManager.java]: This change looks good, but I am not quite sure why it work e.g. for short decimal.
It uses `long` as container type so for value `3.14` value`"314"` will be generated as filter.
I guess Hive expects `"3.14"`. 

Note: This hole dispatching based on container type looks like wrong approach. We should do the dispatching based on the Presto type. That is what you did within `Slice` branch.

File: presto-hive/src/test/java/com/facebook/presto/hive/TestHiveIntegrationSmokeTest.java [hunk 9]
```diff
@@ -302,6 +302,18 @@ public void createPartitionedTable(Session session, HiveStorageFormat storageFor
...
+        assertQuery(session,
+                "SELECT * from test_partitioned_table WHERE" +
+                        " 'foo' = _partition_string" +
+                        " AND 'bar' = _partition_varchar" +
+                        " AND CAST('boo' AS CHAR(10)) = _partition_char" +
+                        " AND CAST(1 AS TINYINT) = _partition_tinyint" +
+                        " AND CAST(1 AS SMALLINT) = _partition_smallint" +
+                        " AND 1 = _partition_integer" +
+                        " AND CAST(1 AS BIGINT) = _partition_bigint" +
+                        " AND CAST('3.14' AS DECIMAL(3,2)) = _partition_decimal_short" +
```
Comment (losipiuk) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestHiveIntegrationSmokeTest.java]: does this test really work? See my comment above.
Does this query return some rows?

Comment (rschlussel) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestHiveIntegrationSmokeTest.java]: Yes, it returns one row.  I also don't understand why short decimal works.

Comment (rschlussel) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestHiveIntegrationSmokeTest.java]: oh, assumeCanonicalPartitionKeys has always been false when I've run this, so it just puts in the wildcard.  I bet we'd have the same problem with short decimal if assumeCanonicalPartitionKeys were true.  

Also, do you know if decimal has the same problem with 0s that all the number/boolean values have?  Do In need to add a check about assumeCanonicalPartitionKeys there too?

Comment (rschlussel) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestHiveIntegrationSmokeTest.java]: confirmed that shortDecimal doesn't work when assumeCanonicalPartitionKeys is true;

**Comment by rschlussel** [comment]
Also, I'm not sure it covers all the types.  I just took the ones that were in the createPartitionedTable test, but what about timestamp and date? We support those kind of partition keys, right?

**Comment by losipiuk** [comment]
> Also, I'm not sure it covers all the types. I just took the ones that were in the createPartitionedTable test, but what about timestamp and date? We support those kind of partition keys, right?

Yeah - I think so.

Those were covered previously by the case for `long` container type. But I don't know if the behaviour was correct. I guess metastore does not assume `number of milliseconds since epoch` to be correct partitioning key for `date`/`timestamp`.

File: presto-hive/src/test/java/com/facebook/presto/hive/HiveQueryRunner.java [hunk 10]
```diff
@@ -103,6 +103,7 @@ public static DistributedQueryRunner createQueryRunner(Iterable<TpchTable<?>> ta
                     .put("hive.time-zone", TIME_ZONE.getID())
                     .put("hive.security", security)
                     .put("hive.max-partitions-per-scan", "1000")
+                    .put("hive.assume-canonical-partition-keys", "true")
```
Comment (rschlussel) [inline presto-hive/src/test/java/com/facebook/presto/hive/HiveQueryRunner.java]: This way all tests exercise the partition key code.

File: presto-hive/src/test/java/com/facebook/presto/hive/TestHiveIntegrationSmokeTest.java [hunk 11]
```diff
@@ -237,12 +237,14 @@ public void createPartitionedTable(Session session, HiveStorageFormat storageFor
                 ", _partition_smallint SMALLINT" +
                 ", _partition_integer INTEGER" +
                 ", _partition_bigint BIGINT" +
+                ", _partition_boolean BOOLEAN" +
                 ", _partition_decimal_short DECIMAL(3,2)" +
                 ", _partition_decimal_long DECIMAL(30,10)" +
+                ", _partition_date DATE" +
```
Comment (rschlussel) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestHiveIntegrationSmokeTest.java]: I didn't include timestamp in the test because I ran into an unrelated issue where timestamp partitions were getting escaped twice (the ':' gets escaped and then the '%' from the escape sequence gets escaped), and only unescaped once, so then Presto can't parse the timestamp.  This occurs when doing a select * on the table without any filtering.  I can investigate the issue separately.

File: presto-hive/src/test/java/com/facebook/presto/hive/HiveQueryRunner.java (hunk 10 above)
Comment (losipiuk) [inline presto-hive/src/test/java/com/facebook/presto/hive/HiveQueryRunner.java]: It would be nice to verify that it actually happen. E.g. create two partitions and then somehow test that only one was read from Hive. Not sure it is possible this or some other way but without it is hard to be sure we have coverage.

Comment (rschlussel) [inline presto-hive/src/test/java/com/facebook/presto/hive/HiveQueryRunner.java]: There was a test that tested non-canonical partition keys but it's been disabled for over a year.  But when that gets reenabled, we can set this to false for that test.

**Comment by rschlussel** [comment]
The problem with timestamp was in the FileHiveMetastore (which is also why I couldn't reproduce it when running against a real hive instance).  I added a commit here that fixes that issue and adds timestamp to the test.

**Comment by rschlussel** [comment]
Also, if there are comments on the second commit, can you please merge the first commit by itself. It's blocking https://github.com/prestodb/presto/pull/8735

**Comment by losipiuk** [comment]
I merged the `Fix partition filtering for various types`

File: presto-hive/src/main/java/com/facebook/presto/hive/metastore/file/FileHiveMetastore.java [hunk 12]
```diff
@@ -630,7 +631,7 @@ public synchronized void alterPartition(String databaseName, String tableName, P
                     childPartitionValues = listPartitions(fileStatus.getPath(), partitionColumns.subList(1, partitionColumns.size()));
                 }
 
-                String value = fileStatus.getPath().getName().substring(directoryPrefix.length());
+                String value = unescapePathName(fileStatus.getPath().getName().substring(directoryPrefix.length()));
```
Comment (losipiuk) [inline presto-hive/src/main/java/com/facebook/presto/hive/metastore/file/FileHiveMetastore.java]: It is unclear to me what is the current semantics of `ExtendedHiveMetastore.listPartitions` concerning unescaping partition names.
I would guess that it is expected to return escaped values, which are then unescaped in `HivePartitionManager.
This semantics looks weird and I would like `ExtendedHiveMetastore` to not use escaped strings anywhere as an interface. Yet it seems to me that change here should imply removing escaping in `HivePartitionManager`.

Please talk to @haozhun how to straighten this up.

Comment (haozhun) [reply presto-hive/src/main/java/com/facebook/presto/hive/metastore/file/FileHiveMetastore.java]: Escaping in this context is not a problem that I have carefully thought about.

It is not possible that `ExtendedHiveMetastore` never use escaped strings. If you have a partition name, it has to be escaped because you could have `=` and `/` in partition column name or value.

Therefore, it seems to me that it would be reasonable if
* partitionName (`col1=x/col2=y`) is always escaped
* partitionColumn (`col1`, `col2`) and partitionValue (`x`, `y`) is never escaped.

Do you think this is reasonable and maintenable?

Comment (rschlussel) [reply presto-hive/src/main/java/com/facebook/presto/hive/metastore/file/FileHiveMetastore.java]: I'm not sure I understand the suggestion.  The problem I was seeing is that with the FileHiveMetastore the Partition names were being escaped twice.  It looks like the other escaping comes from the makePartName() call on line 603 which does its own escaping.  So the two options I see are 
1. unescape before calling that method, which is what I do here
2. reimplement makePartName in FileHiveMetastore to do the same thing but without escaping the partition names.  I'm less inclined to do that since the MetastoreUtil method calls `makePartName` from hive's FileUtils (which is the bit that does the escaping), and even though the rest of the logic of that method probably won't change, in theory it could.

Comment (rschlussel) [reply presto-hive/src/main/java/com/facebook/presto/hive/metastore/file/FileHiveMetastore.java]: but maybe I should do the unescaping higher up (i.e. in getPartitionNames() instead of listPartitions()) and put a comment explaining the reason

Comment (losipiuk) [reply presto-hive/src/main/java/com/facebook/presto/hive/metastore/file/FileHiveMetastore.java]: > Therefore, it seems to me that it would be reasonable if
> 
> * partitionNames (col1=x/col2=y) are always escaped
> * partitionColumns (col1, col2) and partitionValues (x, y) are never escaped.
>
> Do you think this is reasonable and maintainable?
 
@Haozhun it would be great if we could remove `partitionNames` at all from being part of `EHM` interface. And always return and take as parameters parsed structures. Like list of `partitionValues` or list of tuples `(partitionKey, partitionValue)`. And perform encoding/decoding to/from `partitionNames` only internally.
 I do not know if that is possible and if how much of an effort is that. 

If above is not possible, then is seems to me that what you propose is reasonable. Isn't that what we have already?

**Comment by findepi** [comment]
@rschlussel is the PR title up to date (`Fix partition filtering for char(x) and long decimals`)? First commit mentions `date` data type as well.

**Comment by rschlussel** [comment]
first commit has already been merged.  The PR expanded in scope, so the title is no longer correct.

**Comment by rschlussel** [comment]
rebased on master and retitled the pr for what it's actually about now.  Would still appreciate thoughts on my comments here: https://github.com/prestodb/presto/pull/8745#discussion_r136191106

**Comment by kokosing** [comment]
Rebased. @losipiuk @haozhun @sopel39 Are you ok with merging this?

**Comment by losipiuk** [comment]
Fine for me.

**Comment by haozhun** [comment]
Fine for me.

**Comment by findepi** [comment]
Travis says "LGTM" too now. Merge?
