### PR TITLE
Delete staging files in the background on startup

### LINKED ISSUE #5828: Fix Raptor hang at startup deleting large staging directory
We currently block on startup while deleting the staging directory contents. This can take a while for a large staging directory, which can cause health checks for the process to fail.

One solution to this is to simply list all the files on startup, then delete them in a background thread.

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
Fixes #5828

### CODE REVIEW

File: presto-raptor/src/main/java/com/facebook/presto/raptor/storage/FileStorageService.java [hunk 1]
```diff
@@ -140,6 +143,22 @@ public static File getFileSystemPath(File base, UUID shardUuid)
                 .toFile();
     }
 
+    private void deleteFilesAsync(List<File> files)
+    {
+        if (files != null && !files.isEmpty()) {
+            new Thread(() -> {
```
Comment (martint) [inline presto-raptor/src/main/java/com/facebook/presto/raptor/storage/FileStorageService.java]: Use an executor instead of creating a thread every time.

**Comment by nezihyigitbasi** [comment]
updated.

File: presto-raptor/src/main/java/com/facebook/presto/raptor/storage/FileStorageService.java [hunk 2]
```diff
@@ -140,6 +147,22 @@ public static File getFileSystemPath(File base, UUID shardUuid)
...
+    private void deleteFilesAsync(List<File> files)
+    {
+        if (files != null && !files.isEmpty()) {
+            executor.submit(() -> {
+                for (File file : files) {
+                    try {
+                        Files.deleteIfExists(file.toPath());
+                    }
+                    catch (IOException e) {
+                        log.warn("Failed to delete file: %s", file.getAbsolutePath());
```
Comment (electrum) [inline presto-raptor/src/main/java/com/facebook/presto/raptor/storage/FileStorageService.java]: Log the original exception -- failure to delete a local file is very unexpected, so knowing what happened is useful

File: presto-raptor/src/main/java/com/facebook/presto/raptor/storage/FileStorageService.java [hunk 3]
```diff
@@ -29,20 +30,26 @@
...
         implements StorageService
 {
+    private static final Logger log = Logger.get(FileStorageService.class);
+
     private static final Pattern HEX_DIRECTORY = Pattern.compile("[0-9a-f]{2}");
     private static final String FILE_EXTENSION = ".orc";
 
     private final File baseStorageDir;
     private final File baseStagingDir;
+    private final ExecutorService executor = newSingleThreadExecutor(threadsNamed("background-staging-delete"));
```
Comment (electrum) [inline presto-raptor/src/main/java/com/facebook/presto/raptor/storage/FileStorageService.java]: I think the original way of creating a thread is better since this is a one-shot event at startup (no need for the thread to hang around after that). Will discuss with @martint

Comment (nezihyigitbasi) [inline presto-raptor/src/main/java/com/facebook/presto/raptor/storage/FileStorageService.java]: the only issue with having a one-shot thread is that way the `deleteFilesAsync` method is making an assumption about being called only once at startup. If we don't want to make such an assumption we can also inline the old version in the `start` method.

Comment (electrum) [inline presto-raptor/src/main/java/com/facebook/presto/raptor/storage/FileStorageService.java]: That assumption is fine since it's a private helper method. Though you could make it a no-args method named something like `deleteStagingFilesAsync` and put the listing logic in there.

File: presto-raptor/src/main/java/com/facebook/presto/raptor/storage/FileStorageService.java [hunk 4]
```diff
@@ -140,6 +143,23 @@ public static File getFileSystemPath(File base, UUID shardUuid)
                 .toFile();
     }
 
+    private void deleteStagingFilesAsync()
+    {
+        List<File> files = listFiles(baseStagingDir, null);
+        if (files != null && !files.isEmpty()) {
```
Comment (electrum) [inline presto-raptor/src/main/java/com/facebook/presto/raptor/storage/FileStorageService.java]: The null check isn't needed

Comment (nezihyigitbasi) [inline presto-raptor/src/main/java/com/facebook/presto/raptor/storage/FileStorageService.java]: yep, removed.
