### PR TITLE
Fix reporting of output data size for PartitionedOutputOperator

### LINKED ISSUE #11770: PartitionedOutputOperator reports incorrect output data size
PartitionedOutputOperator reports the input data size as the output data size. However, output data size might be larger due to loss of run-length and/or dictionary encodings.

### PR DESCRIPTION
**Pull request by ajaygeorge**
This PR is to fix the PartitionedOutputOperator's incorrect output data size.
We used to record the output size of the PartitionedOutputOperator the same as input size. This could be wrong for pages containing Dictionary/RLE blocks because the Dictionary/RLE wrapping would be ripped out during repartitioning, or when rows are replicated. We now record the output size based on the actual output sizes of the pageBuilders.

Fixes #11770

`EXPLAIN ANALYZE` command now shows the correct data size.

e.g.
```
EXPLAIN ANALYZE 
SELECT checksum(l.shipmode) 
FROM lineitem l, partsupp p 
WHERE l.partkey = p.partkey AND l.suppkey = p.suppkey AND p.availqty < 1000;
```
Before this fix 
```
Fragment 3 [SOURCE]
     CPU: 162.60ms, Scheduled: 289.28ms, Input: 60175 rows (1.27MB); per task: avg.: 20058.33 std.dev.: 25721.42, Output: 60175 rows (1.78MB)
```
After this fix

```
Fragment 3 [SOURCE]
     CPU: 188.25ms, Scheduled: 310.65ms, Input: 60175 rows (1.27MB); per task: avg.: 20058.33 std.dev.: 19657.87, Output: 60175 rows (2.08MB)
```
After the fix the Output size is correctly recorded as 2.08 MB instead of the original 1.78 MB

```
== RELEASE NOTES ==
General
--------
* Fix the issue that fragment's output size was under-recorded for cases where input data is dictionary or run-length encoded, or the rows are replicated(#11770)
```

### CODE REVIEW

File: presto-main/src/main/java/com/facebook/presto/operator/PartitionedOutputOperator.java [hunk 1]
```diff
@@ -396,9 +396,35 @@ public void partitionPage(Page page)
...
                 }
             }
+
+            long newSizeInBytes = getSizeInBytesFromPageBuilders();
+            int newPositionCount = getPositionCountFromPageBuilders();
+
+            operatorContext.recordOutput(newSizeInBytes - sizeInBytesFromPageBuilder, newPositionCount - positionCountFromPageBuilder);
+            sizeInBytesFromPageBuilder = newSizeInBytes;
+            positionCountFromPageBuilder = newPositionCount;
+
```
[the remark this answers is not in the document]
Comment (yingsu00) [reply presto-main/src/main/java/com/facebook/presto/operator/PartitionedOutputOperator.java]: Actually I think updating the counter in the flush() method like in previous comment would be better. I ran the benchmark the performance penalty is less than 3% with and without updating the counters.

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 2]
```diff
@@ -0,0 +1,340 @@
...
+        PartitionedOutputOperator.PartitionedOutputFactory operatorFactory = null;
+        if (shouldReplicate) {
+            operatorFactory = new PartitionedOutputOperator.PartitionedOutputFactory(
+                    partitionFunction,
+                    ImmutableList.of(0),
+                    ImmutableList.of(Optional.empty()),
+                    true,
+                    OptionalInt.of(0),
+                    buffer,
+                    new DataSize(1, GIGABYTE));
```
Comment (yingsu00) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: Make this DataSize a static final field. Also let's use a smaller size so that flush will happen when we add multiple pages. We can make it 5MB and it will be shared by 512 partitions, so each partition has 10KB memory. We can then add multiple pages to trigger the flushing.

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 3]
```diff
@@ -0,0 +1,340 @@
...
+    private Page copyPositions(Page page, List<Integer> positions)
+    {
+        Block[] blocks = new Block[page.getChannelCount()];
+        for (int i = 0; i < blocks.length; i++) {
+            blocks[i] = page.getBlock(i).copyPositions(positions.stream().mapToInt(j -> j).toArray(), 0, positions.size());
+        }
+        return new Page(positions.size(), blocks);
+    }
+
+    private Page createSimplePage()
```
Comment (yingsu00) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: There is only one line in this method. Let's inline it.

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 4]
```diff
@@ -0,0 +1,340 @@
...
+
+    Block buildBigintBlock(int positionCount, boolean allowNulls)
+    {
+        return createLongsBlock(
+                IntStream.range(0, positionCount)
+                        .mapToObj(i -> allowNulls && i % 7 == 0 ? null : RANDOM.nextLong())
+                        .collect(Collectors.toList()));
+    }
+
+    Block buildBlockWithType(Type type, int positionCount, boolean allowNulls, boolean isView, Optional<String> wrappings)
```
Comment (yingsu00) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: buildBlockWithType was created in https://github.com/prestodb/presto/pull/13183 mainly for nested types. Here we don't need to use it because we only need to test on BIGINT and create LongArrayBlock.

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 5]
```diff
@@ -0,0 +1,340 @@
...
+        return new DictionaryBlock(dictionary, ids);
+    }
+
+    RunLengthEncodedBlock buildRleBlock(Block block, int positionCount)
+    {
+        checkArgument(block.getPositionCount() > 0);
+        return new RunLengthEncodedBlock(block.getRegion(block.getPositionCount() / 2, 1), positionCount);
+    }
+
+    Block buildDictRleBlock(Block block, int positionCount, Optional<String> wrappings)
```
Comment (yingsu00) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: We also don't need to use this method here. buildDictRleBlock was created to create multiple level nested Dictionary/Rle blocks to test block flattening and it's not our main goal here. We only need to keep the buildDictionaryBlock() and buildRleBlock().

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 6]
```diff
@@ -0,0 +1,340 @@
...
+                block = buildRleBlock(block, positionCount);
+            }
+            else {
+                throw new IllegalArgumentException(format("wrappings %s is incorrect", wrappings));
+            }
+        }
+        return block;
+    }
+
+    Block buildNullBlock(Type type, int positionCount)
```
Comment (yingsu00) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: This method is only called once. Let's inline it.

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 7]
```diff
@@ -0,0 +1,340 @@
...
+    private static final Random RANDOM = new Random(0);
+    private static final ExecutorService EXECUTOR = newCachedThreadPool(daemonThreadsNamed("test-EXECUTOR-%s"));
+    private static final ScheduledExecutorService SCHEDULER = newScheduledThreadPool(1, daemonThreadsNamed("test-%s"));
+
+    @Test
+    public void testAddInputForSimplePage()
+    {
+        PartitionedOutputOperator partitionedOutputOperator = createPartitionedOutputOperator(false);
+        Page simplePage = createSimplePage();
+        partitionedOutputOperator.addInput(simplePage);
```
Comment (yingsu00) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: Add a blank line above this line.

Comment (yingsu00) [reply presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: Call finish() after calling addInput()

`partitionedOutputOperator.finish();`

Comment (yingsu00) [reply presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: We should create multiple pages like 100 pages, and call addInput() in a loop. Outside of the loop we call finish() so that everything is flushed. Then we can assert on the data sizes/positionCount. Same for other tests.

File: presto-main/src/main/java/com/facebook/presto/operator/PartitionedOutputOperator.java [hunk 8]
```diff
@@ -377,7 +377,7 @@ public PartitionedOutputInfo getInfo()
             return new PartitionedOutputInfo(rowsAdded.get(), pagesAdded.get(), outputBuffer.getPeakMemoryUsage());
         }
 
-        public void partitionPage(Page page)
+        public void partitionPage(Page page, OperatorContext operatorContext)
```
[the remark this answers is not in the document]
Comment (ajaygeorge) [reply presto-main/src/main/java/com/facebook/presto/operator/PartitionedOutputOperator.java]: Done

File: presto-main/src/main/java/com/facebook/presto/operator/PartitionedOutputOperator.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (ajaygeorge) [reply presto-main/src/main/java/com/facebook/presto/operator/PartitionedOutputOperator.java]: Done

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 9]
```diff
@@ -0,0 +1,340 @@
...
+                    buffer,
+                    new DataSize(1, GIGABYTE));
+        }
+
+        return (PartitionedOutputOperator) operatorFactory
+                .createOutputOperator(0, new PlanNodeId("plan-node-0"), TYPES, Function.identity(), serdeFactory)
+                .createOperator(createDriverContext());
+    }
+
+    private Page copyPositions(Page page, List<Integer> positions)
```
[the remark this answers is not in the document]
Comment (ajaygeorge) [reply presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: Done

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 10]
```diff
@@ -0,0 +1,340 @@
...
+        PartitionFunction partitionFunction = new LocalPartitionGenerator(new InterpretedHashGenerator(ImmutableList.of(BIGINT), new int[] {0}), PARTITION_COUNT);
+        PagesSerdeFactory serdeFactory = new PagesSerdeFactory(new BlockEncodingManager(new TypeRegistry()), false);
+        OutputBuffers buffers = createInitialEmptyOutputBuffers(PARTITIONED);
+        for (int partition = 0; partition < PARTITION_COUNT; partition++) {
+            buffers = buffers.withBuffer(new OutputBuffers.OutputBufferId(partition), partition);
+        }
+        PartitionedOutputBuffer buffer = createPartitionedBuffer(
+                buffers.withNoMoreBufferIds(),
+                new DataSize(Long.MAX_VALUE, BYTE)); // don't let output buffer block
+        buffer.registerLifespanCompletionCallback(ignore -> {});
```
[the remark this answers is not in the document]
Comment (ajaygeorge) [reply presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: Done

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java (hunk 2 above)
Comment (ajaygeorge) [reply presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: Done

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java (hunk 3 above)
Comment (ajaygeorge) [reply presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: This was for readability, since there is no Performance advantage with this change I hope this is ok to leave as is.

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java (hunk 4 above)
Comment (ajaygeorge) [reply presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: done

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java (hunk 5 above)
Comment (ajaygeorge) [reply presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: done

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java (hunk 6 above)
Comment (ajaygeorge) [reply presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: done

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java (hunk 7 above)
Comment (ajaygeorge) [reply presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: done

File: presto-main/src/main/java/com/facebook/presto/operator/PartitionedOutputOperator.java [hunk 11]
```diff
@@ -220,7 +220,8 @@ public PartitionedOutputOperator(
                 serdeFactory,
                 sourceTypes,
                 maxMemory,
-                operatorContext.getDriverContext().getLifespan());
+                operatorContext.getDriverContext().getLifespan(),
```
Comment (yingsu00) [inline presto-main/src/main/java/com/facebook/presto/operator/PartitionedOutputOperator.java]: No need to pass this anymore. It can be acquired from operatorContext passed in.

File: presto-main/src/main/java/com/facebook/presto/operator/PartitionedOutputOperator.java [hunk 12]
```diff
@@ -309,6 +308,7 @@ public Page getOutput()
         private final AtomicLong rowsAdded = new AtomicLong();
         private final AtomicLong pagesAdded = new AtomicLong();
         private boolean hasAnyRowBeenReplicated;
+        private OperatorContext operatorContext;
```
Comment (yingsu00) [inline presto-main/src/main/java/com/facebook/presto/operator/PartitionedOutputOperator.java]: make it final

File: presto-main/src/main/java/com/facebook/presto/operator/PartitionedOutputOperator.java [hunk 13]
```diff
@@ -320,7 +320,8 @@ public PagePartitioner(
                 PagesSerdeFactory serdeFactory,
                 List<Type> sourceTypes,
                 DataSize maxMemory,
-                Lifespan lifespan)
+                Lifespan lifespan,
```
Comment (yingsu00) [inline presto-main/src/main/java/com/facebook/presto/operator/PartitionedOutputOperator.java]: don't need to pass in lifespan. Get it from the operatorContext

File: presto-main/src/main/java/com/facebook/presto/operator/PartitionedOutputOperator.java [hunk 14]
```diff
@@ -396,6 +398,7 @@ public void partitionPage(Page page)
                     appendRow(pageBuilders[partition], page, position);
                 }
             }
+
```
Comment (yingsu00) [inline presto-main/src/main/java/com/facebook/presto/operator/PartitionedOutputOperator.java]: nit: remove the blank line

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 15]
```diff
@@ -0,0 +1,274 @@
...
+
+public class TestPartitionedOutputOperator
+{
+    private static final int PARTITION_COUNT = 512;
+    private static final DataSize MAX_MEMORY = new DataSize(1, GIGABYTE);
+    private static final List<Type> TYPES = ImmutableList.of(BIGINT);
+    private static final Random RANDOM = new Random(0);
+    private static final ExecutorService EXECUTOR = newCachedThreadPool(daemonThreadsNamed("test-EXECUTOR-%s"));
+    private static final ScheduledExecutorService SCHEDULER = newScheduledThreadPool(1, daemonThreadsNamed("test-%s"));
+    private static final DataSize PARTITION_MAX_MEMORY = new DataSize(5, MEGABYTE);
```
Comment (yingsu00) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: Make it adjacent to the line of MAX_MEMORY

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 16]
```diff
@@ -0,0 +1,274 @@
...
+    private static final int NUM_OF_ITERATIONS = 100;
+
+    @Test
+    public void testAddInputForSimplePage()
+    {
+        PartitionedOutputOperator partitionedOutputOperator = createPartitionedOutputOperator(false);
+        for (int i = 0; i < NUM_OF_ITERATIONS; i++) {
+            partitionedOutputOperator.addInput(createSimplePage());
+        }
+        partitionedOutputOperator.finish();
```
Comment (yingsu00) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: add a blank line below

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 17]
```diff
@@ -0,0 +1,274 @@
...
+        OperatorContext operatorContext = partitionedOutputOperator.getOperatorContext();
+        long outputSize = operatorContext.getOutputDataSize().getTotalCount();
+        long outputPositionCount = operatorContext.getOutputPositions().getTotalCount();
+        assertEquals(outputSize, 900_000);
+        assertEquals(outputPositionCount, 100_000);
+        assertEquals(createSimplePage().getSizeInBytes() * NUM_OF_ITERATIONS, outputSize);
```
Comment (yingsu00) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: This rely on the fact that every page created has the same size. But by looking at the function name createSimplePage() we can't tell if the size is fixed. I think it's better to accumulate the page sizes inside of the for loop using addition.

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 18]
```diff
@@ -0,0 +1,274 @@
...
+        PartitionedOutputOperator partitionedOutputOperator = createPartitionedOutputOperator(false);
+        for (int i = 0; i < NUM_OF_ITERATIONS; i++) {
+            partitionedOutputOperator.addInput(createSimplePage());
+        }
+        partitionedOutputOperator.finish();
+        OperatorContext operatorContext = partitionedOutputOperator.getOperatorContext();
+        long outputSize = operatorContext.getOutputDataSize().getTotalCount();
+        long outputPositionCount = operatorContext.getOutputPositions().getTotalCount();
+        assertEquals(outputSize, 900_000);
+        assertEquals(outputPositionCount, 100_000);
```
Comment (yingsu00) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: inline outputPositionCount and make it either before or after the two assertions on outputSize. (group the assertions)

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 19]
```diff
@@ -0,0 +1,274 @@
...
+    {
+        PartitionedOutputOperator partitionedOutputOperator = createPartitionedOutputOperator(true);
+        for (int i = 0; i < NUM_OF_ITERATIONS; i++) {
+            partitionedOutputOperator.addInput(createSimplePage());
+        }
+        partitionedOutputOperator.finish();
+        OperatorContext operatorContext = partitionedOutputOperator.getOperatorContext();
+        long outputSize = operatorContext.getOutputDataSize().getTotalCount();
+        long outputPositionCount = operatorContext.getOutputPositions().getTotalCount();
+        assertEquals(outputSize, 904599);
```
Comment (yingsu00) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: 904_599

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 20]
```diff
@@ -0,0 +1,274 @@
...
+    }
+
+    @Test
+    public void testAddInputForPageWithDictionaryAndReplication()
+    {
+        PartitionedOutputOperator partitionedOutputOperator = createPartitionedOutputOperator(true);
+        for (int i = 0; i < NUM_OF_ITERATIONS; i++) {
+            partitionedOutputOperator.addInput(createPageWithDictionary());
+        }
+
```
Comment (yingsu00) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: remove this blank line and add a blank line after the line calling finish()

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 21]
```diff
@@ -0,0 +1,274 @@
...
+        PartitionedOutputOperator partitionedOutputOperator = createPartitionedOutputOperator(true);
+        for (int i = 0; i < NUM_OF_ITERATIONS; i++) {
+            partitionedOutputOperator.addInput(createSimplePage());
+        }
+        partitionedOutputOperator.finish();
+        OperatorContext operatorContext = partitionedOutputOperator.getOperatorContext();
+        long outputSize = operatorContext.getOutputDataSize().getTotalCount();
+        long outputPositionCount = operatorContext.getOutputPositions().getTotalCount();
+        assertEquals(outputSize, 904599);
+        assertEquals(outputPositionCount, 100_511);
```
Comment (yingsu00) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: why is it 100_511? Could you please verify if all rows were indeed replicated and copied to all pageBuilders?

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 22]
```diff
@@ -0,0 +1,274 @@
...
+        assertEquals(outputSize, 904_599);
+        assertEquals(outputPositionCount, 100_511);
+        assertTrue(outputSize > createPageWithRunLength().getSizeInBytes() * NUM_OF_ITERATIONS);
+    }
+
+    private PartitionedOutputOperator createPartitionedOutputOperator(boolean shouldReplicate)
+    {
+        PartitionFunction partitionFunction = new LocalPartitionGenerator(new InterpretedHashGenerator(ImmutableList.of(BIGINT), new int[] {0}), PARTITION_COUNT);
+        PagesSerdeFactory serdeFactory = new PagesSerdeFactory(new BlockEncodingManager(new TypeRegistry()), false);
+        OutputBuffers buffers = createInitialEmptyOutputBuffers(PARTITIONED);
```
Comment (yingsu00) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: Move line 177-180 to inside of createPartitionedOutputBuffer

```
private PartitionedOutputBuffer createPartitionedOutputBuffer()
        {
            OutputBuffers buffers = createInitialEmptyOutputBuffers(PARTITIONED);
            for (int partition = 0; partition < PARTITION_COUNT; partition++) {
                buffers = buffers.withBuffer(new OutputBuffers.OutputBufferId(partition), partition);
            }
            PartitionedOutputBuffer buffer = createPartitionedBuffer(
                    buffers.withNoMoreBufferIds(),
                    new DataSize(Long.MAX_VALUE, BYTE)); // don't let output buffer block
            buffer.registerLifespanCompletionCallback(ignore -> {});

            return buffer;
        }
```

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 23]
```diff
@@ -0,0 +1,274 @@
...
+        return new PartitionedOutputBuffer(
+                "task-instance-id",
+                new StateMachine<>("bufferState", SCHEDULER, OPEN, TERMINAL_BUFFER_STATES),
+                buffers,
+                dataSize,
+                () -> new SimpleLocalMemoryContext(newSimpleAggregatedMemoryContext(), "test"),
+                SCHEDULER);
+    }
+
+    Block buildBigintBlock(int positionCount, boolean allowNulls)
```
Comment (yingsu00) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: make this method and the next two private

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 24]
```diff
@@ -0,0 +1,274 @@
...
+    private static final List<Type> TYPES = ImmutableList.of(BIGINT);
+    private static final Random RANDOM = new Random(0);
+    private static final ExecutorService EXECUTOR = newCachedThreadPool(daemonThreadsNamed("test-EXECUTOR-%s"));
+    private static final ScheduledExecutorService SCHEDULER = newScheduledThreadPool(1, daemonThreadsNamed("test-%s"));
+    private static final DataSize PARTITION_MAX_MEMORY = new DataSize(5, MEGABYTE);
+    private static final int POSITION_COUNT = 1000;
+    private static final int NUM_OF_ITERATIONS = 100;
+
+    @Test
+    public void testAddInputForSimplePage()
```
Comment (yingsu00) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: rename to testOutputForSimplePage

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 25]
```diff
@@ -0,0 +1,274 @@
...
+        OperatorContext operatorContext = partitionedOutputOperator.getOperatorContext();
+        long outputSize = operatorContext.getOutputDataSize().getTotalCount();
+        long outputPositionCount = operatorContext.getOutputPositions().getTotalCount();
+        assertEquals(outputSize, 900_000);
+        assertEquals(outputPositionCount, 100_000);
+        assertEquals(createSimplePage().getSizeInBytes() * NUM_OF_ITERATIONS, outputSize);
+    }
+
+    @Test
+    public void testAddInputForPageWithDictionary()
```
Comment (yingsu00) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: testOutputForDictionaryPage

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 26]
```diff
@@ -0,0 +1,274 @@
...
+        OperatorContext operatorContext = partitionedOutputOperator.getOperatorContext();
+        long outputSize = operatorContext.getOutputDataSize().getTotalCount();
+        long outputPositionCount = operatorContext.getOutputPositions().getTotalCount();
+        assertEquals(outputSize, 900_000);
+        assertEquals(outputPositionCount, 100_000);
+        assertTrue(outputSize > createPageWithDictionary().getSizeInBytes() * NUM_OF_ITERATIONS);
+    }
+
+    @Test
+    public void testAddInputForPageWithRunLength()
```
Comment (yingsu00) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: testOutputForRlePage

**Comment by mbasmanova** [comment]
@ajaygeorge Ajay, thanks for fixing this problem. I haven't looked at the code yet, but I'm seeing that Travis reports stylecheck failures. Could you fix these and update the PR?

```
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ presto-main ---
[INFO] There are 2 errors reported by Checkstyle 8.7 with src/checkstyle/presto-checks.xml ruleset.
[ERROR] src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java:[0] (misc) NewlineAtEndOfFile: File does not end with a newline.
[ERROR] src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java:[272] (regexp) RegexpMultiline: Blank line before closing brace
```

You can reproduce these locally by running `mvn install -DskipTests -T1C -pl '!presto-docs,!presto-server-rpm'`

Also, this change will have user-visible effect and therefore requires release notes. Specifically, I expect the output of `EXPLAIN ANALYZE` command to start showing data size for exchanges correctly. Would you confirm this and update PR description to include some text for the release notes?

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java (hunk 21 above)
Comment (ajaygeorge) [reply presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: Math behind this .
100_511 = 1511 + 1000*(100-1)
Order of progression is this.
|  Num of Iterations | Position Count  |
|--| -|
| 1  | 1511  |
|  2 | 2511  |
|   3|  3511 |
|  4 | 4511  |
|  10 | 10511  |
|  100 | 100511  |

Was able to debug through the code and check that all appendRow was getting called for all PageBuilders. Let me know if this looks good

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java (hunk 18 above)
Comment (ajaygeorge) [reply presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: @yingsu00 Didn't quite get this (understood the inlining part). Can you help me understand how to group assertions.

File: presto-main/src/main/java/com/facebook/presto/operator/PartitionedOutputOperator.java [hunk 27]
```diff
@@ -433,11 +430,13 @@ public void flush(boolean force)
                     Page pagePartition = partitionPageBuilder.build();
                     partitionPageBuilder.reset();
 
+                    operatorContext.recordOutput(pagePartition.getSizeInBytes(), pagePartition.getPositionCount());
```
Comment (mbasmanova) [inline presto-main/src/main/java/com/facebook/presto/operator/PartitionedOutputOperator.java]: @ajaygeorge Is this correct? `recordOutput` is called multiple times, once per partition with partition-specific data. Shouldn't it be called only once with a total sum across all partitions?

**Comment by yingsu00** [comment]
@ajaygeorge Could you please squash the 3 commits together?

File: presto-main/src/main/java/com/facebook/presto/operator/PartitionedOutputOperator.java (hunk 27 above)
Comment (yingsu00) [reply presto-main/src/main/java/com/facebook/presto/operator/PartitionedOutputOperator.java]: @mbasmanova recordOutput calls the update() on the CounterStat which is accumulating the counts each time it's called. It can be called multiple times. 
```
public void recordOutput(long sizeInBytes, long positions)
    {
        outputDataSize.update(sizeInBytes);
        outputPositions.update(positions);
    }
```

```
public void update(long count)
    {
        oneMinute.add(count);
        fiveMinute.add(count);
        fifteenMinute.add(count);
        this.count.addAndGet(count);
    }
```

In fact in previous implementation it is called every time a page is added. In this fix it is called when flush happens but on every partition. The performance penalty calling this line on 5000 pages and forcing flush quite often is fairly small (<=3%). So comparing the fix complexity/code cleanliess/performance penalty I think this is best choice.

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java (hunk 21 above)
Comment (yingsu00) [reply presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: You need to add a nullChannel in the page in order for the replicated case to happen. Let's see this piece of code in partitionPage() to understand how we can reproduce the case every row is replicated:

```
boolean shouldReplicate = (replicatesAnyRow && !hasAnyRowBeenReplicated) ||
                        nullChannel.isPresent() && page.getBlock(nullChannel.getAsInt()).isNull(position);
```
You set the replicatesAnyRow to true when constructing the operator, but it only replicates one row and the next time hasAnyRowBeenReplicated would be true and no more rows would be replicated. If we want to replicate all rows, it needs nullChannel.isPresent() && page.getBlock(nullChannel.getAsInt()).isNull(position) to be true. For that we need an extra block that contains all null values. We can construct such a page like this:

```
private Page createPageWithNullBlock()
    {
        Block[] blocks = new Block[2];
        blocks[0] = new RunLengthEncodedBlock(BIGINT.createBlockBuilder(null, 1).appendNull().build(), POSITION_COUNT);
        blocks[1] = buildBigintBlock(POSITION_COUNT, false);
        
        return new Page(POSITION_COUNT, blocks);
    }
```
Then in the replicated test cases, you add this page instead of the simple page. The expected output number of rows should be 51,200,000.

Comment (ajaygeorge) [reply presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: A quick note here. To properly account for the sizeInBytes the PartitionOperator construction has to change to account for the null block addition for replicated scenarios.
I have added that as well. Please review.

**Comment by ajaygeorge** [comment]
@mbasmanova I have updated the `RELEASE NOTES` and fixed the checkstyle errors as well.
@yingsu00 Once I get a final signoff will squash and merge.

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 28]
```diff
@@ -0,0 +1,311 @@
...
+        return new PartitionedOutputBuffer(
+                "task-instance-id",
+                new StateMachine<>("bufferState", SCHEDULER, OPEN, TERMINAL_BUFFER_STATES),
+                buffers,
+                dataSize,
+                () -> new SimpleLocalMemoryContext(newSimpleAggregatedMemoryContext(), "test"),
+                SCHEDULER);
+    }
+
+    private Block buildBigIntBlock(int positionCount, boolean allowNulls)
```
Comment (mbasmanova) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: Use methods from BlockAssertions class:

```
createLongSequenceBlock(0, POSITION_COUNT)

createLongDictionaryBlock(0, POSITION_COUNT)

createRLEBlock(RANDOM.nextLong(), POSITION_COUNT)
```

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 29]
```diff
@@ -0,0 +1,311 @@
...
+    {
+        return new Page(buildDictionaryBlock(buildBigIntBlock(POSITION_COUNT, false), POSITION_COUNT));
+    }
+
+    private Page createPageWithRunLength()
+    {
+        return new Page(buildRleBlock(buildBigIntBlock(POSITION_COUNT, false), POSITION_COUNT));
+    }
+
+    private Page createPageWithNullBlock()
```
Comment (mbasmanova) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: - add a constant for null block
- use `Page(int positionCount, Block... blocks)` constructor
- inline this method and the next 2 methods

```
private static final Block NULL_BLOCK = new RunLengthEncodedBlock(BIGINT.createBlockBuilder(null, 1).appendNull().build(), POSITION_COUNT);;
...
        for (int i = 0; i < NUM_OF_ITERATIONS; i++) {
            partitionedOutputOperator.addInput(new Page(POSITION_COUNT, NULL_BLOCK, createLongSequenceBlock(0, POSITION_COUNT)));
        }

        for (int i = 0; i < NUM_OF_ITERATIONS; i++) {
            partitionedOutputOperator.addInput(new Page(POSITION_COUNT, NULL_BLOCK, createLongDictionaryBlock(0, POSITION_COUNT)));
        }

        for (int i = 0; i < NUM_OF_ITERATIONS; i++) {
            partitionedOutputOperator.addInput(new Page(POSITION_COUNT, NULL_BLOCK, createRLEBlock(RANDOM.nextLong(), POSITION_COUNT)));
        }
```

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 30]
```diff
@@ -0,0 +1,311 @@
...
+    private Page createPageWithRunLengthAndNullBlock()
+    {
+        Block[] blocks = new Block[2];
+        blocks[0] = new RunLengthEncodedBlock(BIGINT.createBlockBuilder(null, 1).appendNull().build(), POSITION_COUNT);
+        blocks[1] = buildRleBlock(buildBigIntBlock(POSITION_COUNT, false), POSITION_COUNT);
+
+        return new Page(POSITION_COUNT, blocks);
+    }
+
+    private DriverContext createDriverContext()
```
Comment (mbasmanova) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: inline this method; it is used only once

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 31]
```diff
@@ -0,0 +1,311 @@
...
+                    OptionalInt.empty(),
+                    buffer,
+                    PARTITION_MAX_MEMORY);
+            return (PartitionedOutputOperator) operatorFactory
+                    .createOutputOperator(0, new PlanNodeId("plan-node-0"), TYPES, Function.identity(), serdeFactory)
+                    .createOperator(createDriverContext());
+        }
+    }
+
+    private PartitionedOutputBuffer createPartitionedOutputBuffer()
```
Comment (mbasmanova) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: make this method static

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 32]
```diff
@@ -0,0 +1,311 @@
...
+
+        OperatorContext operatorContext = partitionedOutputOperator.getOperatorContext();
+        long outputSize = operatorContext.getOutputDataSize().getTotalCount();
+        long outputPositionCount = operatorContext.getOutputPositions().getTotalCount();
+        assertEquals(outputSize, 461_260_800);
+        assertEquals(outputPositionCount, 51_200_000);
+        assertTrue(outputSize > createPageWithRunLength().getSizeInBytes() * NUM_OF_ITERATIONS);
+    }
+
+    private PartitionedOutputOperator createPartitionedOutputOperator(boolean shouldReplicate)
```
Comment (mbasmanova) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: make this method static

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 33]
```diff
@@ -0,0 +1,311 @@
...
+    private static final List<Type> TYPES = ImmutableList.of(BIGINT);
+    private static final List<Type> REPLICATION_TYPES = ImmutableList.of(BIGINT, BIGINT);
+    private static final Random RANDOM = new Random(0);
+    private static final ExecutorService EXECUTOR = newCachedThreadPool(daemonThreadsNamed("test-EXECUTOR-%s"));
+    private static final ScheduledExecutorService SCHEDULER = newScheduledThreadPool(1, daemonThreadsNamed("test-%s"));
+    private static final int POSITION_COUNT = 1000;
+    private static final int NUM_OF_ITERATIONS = 100;
+
+    @Test
+    public void testOutputForSimplePage()
```
Comment (mbasmanova) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: Hardcoding expected values is problematic, because, it is hard for a reader to understand where these numbers come from and they need to be changed when parameters like POSITION_COUNT change.

I suggest to write these tests like so:

```
 private static final Block NULL_BLOCK = new RunLengthEncodedBlock(BIGINT.createBlockBuilder(null, 1).appendNull().build(), POSITION_COUNT);;
    private static final Block TESTING_BLOCK = createLongSequenceBlock(0, POSITION_COUNT);
    private static final Block TESTING_DICTIONARY_BLOCK = createLongDictionaryBlock(0, POSITION_COUNT);
    private static final Block TESTING_RLE_BLOCK = createRLEBlock(RANDOM.nextLong(), POSITION_COUNT);
    private static final Page TESTING_PAGE = new Page(TESTING_BLOCK);
    private static final Page TESTING_PAGE_WITH_NULL_BLOCK = new Page(POSITION_COUNT, NULL_BLOCK, createLongSequenceBlock(0, POSITION_COUNT));

    @Test
    public void testOutputForSimplePage()
    {
        PartitionedOutputOperator operator = createPartitionedOutputOperator(false);
        for (int i = 0; i < NUM_OF_ITERATIONS; i++) {
            operator.addInput(TESTING_PAGE);
        }
        operator.finish();

        OperatorContext context = operator.getOperatorContext();
        assertEquals(context.getOutputDataSize().getTotalCount(), NUM_OF_ITERATIONS * TESTING_PAGE.getSizeInBytes());
        assertEquals(context.getOutputPositions().getTotalCount(), NUM_OF_ITERATIONS * TESTING_PAGE.getPositionCount());
    }

    @Test
    public void testOutputForDictionaryPage()
    {
        PartitionedOutputOperator operator = createPartitionedOutputOperator(false);
        for (int i = 0; i < NUM_OF_ITERATIONS; i++) {
            operator.addInput(new Page(TESTING_DICTIONARY_BLOCK));
        }
        operator.finish();

        OperatorContext context = operator.getOperatorContext();
        assertEquals(context.getOutputDataSize().getTotalCount(), NUM_OF_ITERATIONS * TESTING_PAGE.getSizeInBytes());
        assertEquals(context.getOutputPositions().getTotalCount(), NUM_OF_ITERATIONS * TESTING_PAGE.getPositionCount());
    }

    @Test
    public void testOutputForRlePage()
    {
        PartitionedOutputOperator operator = createPartitionedOutputOperator(false);
        for (int i = 0; i < NUM_OF_ITERATIONS; i++) {
            operator.addInput(new Page(TESTING_RLE_BLOCK));
        }
        operator.finish();

        OperatorContext context = operator.getOperatorContext();
        assertEquals(context.getOutputDataSize().getTotalCount(), NUM_OF_ITERATIONS * TESTING_PAGE.getSizeInBytes());
        assertEquals(context.getOutputPositions().getTotalCount(), NUM_OF_ITERATIONS * TESTING_PAGE.getPositionCount());
    }

    @Test
    public void testOutputForSimplePageWithReplication()
    {
        PartitionedOutputOperator operator = createPartitionedOutputOperator(true);
        for (int i = 0; i < NUM_OF_ITERATIONS; i++) {
            operator.addInput(new Page(POSITION_COUNT, NULL_BLOCK, TESTING_BLOCK));
        }
        operator.finish();

        OperatorContext context = operator.getOperatorContext();
        assertEquals(context.getOutputDataSize().getTotalCount(), PARTITION_COUNT * TESTING_PAGE_WITH_NULL_BLOCK.getSizeInBytes() * NUM_OF_ITERATIONS);
        assertEquals(context.getOutputPositions().getTotalCount(), PARTITION_COUNT * TESTING_PAGE_WITH_NULL_BLOCK.getPositionCount() * NUM_OF_ITERATIONS);
    }

    @Test
    public void testOutputForDictionaryPageWithReplication()
    {
        PartitionedOutputOperator operator = createPartitionedOutputOperator(true);
        for (int i = 0; i < NUM_OF_ITERATIONS; i++) {
            operator.addInput(new Page(POSITION_COUNT, NULL_BLOCK, TESTING_DICTIONARY_BLOCK));
        }
        operator.finish();

        OperatorContext context = operator.getOperatorContext();
        assertEquals(context.getOutputDataSize().getTotalCount(),PARTITION_COUNT * TESTING_PAGE_WITH_NULL_BLOCK.getSizeInBytes() * NUM_OF_ITERATIONS);
        assertEquals(context.getOutputPositions().getTotalCount(),PARTITION_COUNT * TESTING_PAGE_WITH_NULL_BLOCK.getPositionCount() * NUM_OF_ITERATIONS);
    }

    @Test
    public void testOutputForRlePageWithReplication()
    {
        PartitionedOutputOperator operator = createPartitionedOutputOperator(true);
        for (int i = 0; i < NUM_OF_ITERATIONS; i++) {
            operator.addInput(new Page(POSITION_COUNT, NULL_BLOCK, TESTING_RLE_BLOCK));
        }
        operator.finish();

        OperatorContext context = operator.getOperatorContext();
        assertEquals(context.getOutputDataSize().getTotalCount(), PARTITION_COUNT * TESTING_PAGE_WITH_NULL_BLOCK.getSizeInBytes() * NUM_OF_ITERATIONS);
        assertEquals(context.getOutputPositions().getTotalCount(), PARTITION_COUNT * TESTING_PAGE_WITH_NULL_BLOCK.getPositionCount() * NUM_OF_ITERATIONS);
    }
```

**Comment by mbasmanova** [comment]
@ajaygeorge Ajay, thanks for adding release notes. Here are the guidelines https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines and examples https://prestodb.github.io/docs/current/release/release-0.224.html Based on these, I'd adjust the release notes like so:

```
General
--------
* Fix fragment's output size in the output of `EXPLAIN ANALYZE`. It used to be lower then actual for input data that's dictionary or run-length encoded. (#11770)
```

File: presto-main/src/main/java/com/facebook/presto/operator/PartitionedOutputOperator.java (hunk 27 above)
Comment (yingsu00) [reply presto-main/src/main/java/com/facebook/presto/operator/PartitionedOutputOperator.java]: Alternatively we can have two class members to track the output data sizes and rows, and update them at the same place in flush(). Then update the operatorContext stat in finish() just once. I expect the performance would be similar.

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java (hunk 33 above)
Comment (ajaygeorge) [reply presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: Thank you @mbasmanova . This is a great comment and helps in making test cases clear.

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java (hunk 30 above)
Comment (ajaygeorge) [reply presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: This is actually used twice.

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java (hunk 31 above)
Comment (ajaygeorge) [reply presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: Wondering what is the rationale to mark it as `static` ? . If it is though of as a utility method then probably we need to move this to a better home in one of the helper classes like the  `TestingBuilders`, Ying is working on.

**Comment by yingsu00** [comment]
"We were relying on the Input Page's size which could be wrong for Dictionary/RLE pages.
We are now relying on PageBuilders to get the accurate size which gets recorded during the appendRow operation."

I think this description could be more accurate:

"We used to record the output size of the PartitionedOutputOperator the same as input size. This could be wrong for Dictionary/RLE pages because the Dictionary/RLE wrapping would be ripped out during repartitioning. We now record the output size based on the actual output sizes of the pageBuilders."

Masha, what do you think?

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java (hunk 30 above)
Comment (mbasmanova) [reply presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: I should have been clearer. 
- `createDriverContext` is used only in `createPartitionedOutputOperator`. 
- It is used in two branches of a single if-else block. 
- There is `createPartitionedOutputBuffer` that could have been used the same way, but it is not. Instead, a local variable outside of if-else block hold the value of `createPartitionedOutputBuffer()` and if used in both branches.
- To be consistent, another local variable should be used to hold the value of `createDriverContext()` and used in both branches. 
- Once you make that change, there will be only single usage of `createDriverContext` and single usage of `createPartitionedOutputBuffer`. 
- `createPartitionedOutputOperator` is relatively small and therefore the preference is to inline both `createDriverContext` and `createPartitionedOutputBuffer`. This makes it easier to read the code as the reader doesn't need to jump back and forth between different small functions.

Here is what we could have:

```
    private PartitionedOutputOperator createPartitionedOutputOperator(boolean shouldReplicate)
    {
        PartitionFunction partitionFunction = new LocalPartitionGenerator(new InterpretedHashGenerator(ImmutableList.of(BIGINT), new int[] {0}), PARTITION_COUNT);
        PagesSerdeFactory serdeFactory = new PagesSerdeFactory(new BlockEncodingManager(new TypeRegistry()), false);

        DriverContext driverContext = TestingTaskContext.builder(EXECUTOR, SCHEDULER, TEST_SESSION)
                .setMemoryPoolSize(MAX_MEMORY)
                .setQueryMaxTotalMemory(MAX_MEMORY)
                .build()
                .addPipelineContext(0, true, true, false)
                .addDriverContext();

        OutputBuffers buffers = createInitialEmptyOutputBuffers(PARTITIONED);
        for (int partition = 0; partition < PARTITION_COUNT; partition++) {
            buffers = buffers.withBuffer(new OutputBuffers.OutputBufferId(partition), partition);
        }
        PartitionedOutputBuffer buffer = new PartitionedOutputBuffer(
                "task-instance-id",
                new StateMachine<>("bufferState", SCHEDULER, OPEN, TERMINAL_BUFFER_STATES),
                buffers.withNoMoreBufferIds(),
                new DataSize(Long.MAX_VALUE, BYTE),
                () -> new SimpleLocalMemoryContext(newSimpleAggregatedMemoryContext(), "test"),
                SCHEDULER);
        buffer.registerLifespanCompletionCallback(ignore -> {});

        PartitionedOutputOperator.PartitionedOutputFactory operatorFactory;
        if (shouldReplicate) {
            operatorFactory = new PartitionedOutputOperator.PartitionedOutputFactory(
                    partitionFunction,
                    ImmutableList.of(0),
                    ImmutableList.of(Optional.empty()),
                    true,
                    OptionalInt.of(0),
                    buffer,
                    PARTITION_MAX_MEMORY);
            return (PartitionedOutputOperator) operatorFactory
                    .createOutputOperator(0, new PlanNodeId("plan-node-0"), REPLICATION_TYPES, Function.identity(), serdeFactory)
                    .createOperator(driverContext);
        }
        else {
            operatorFactory = new PartitionedOutputOperator.PartitionedOutputFactory(
                    partitionFunction,
                    ImmutableList.of(0),
                    ImmutableList.of(Optional.empty(), Optional.empty()),
                    false,
                    OptionalInt.empty(),
                    buffer,
                    PARTITION_MAX_MEMORY);
            return (PartitionedOutputOperator) operatorFactory
                    .createOutputOperator(0, new PlanNodeId("plan-node-0"), TYPES, Function.identity(), serdeFactory)
                    .createOperator(driverContext);
        }
    }
```

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java (hunk 31 above)
Comment (mbasmanova) [reply presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: Methods that don't need access to instance variables should be marked `static`. This way there is only one copy of the method and individual object instances don't need to have separate copies of it.

**Comment by yingsu00** [comment]
"
== RELEASE NOTES ==
General
--------
* Fix fragment's output size in the output of `EXPLAIN ANALYZE`. It used to be lower then actual for input data that's dictionary or run-length encoded. (#11770)
"

==>
* Fix the issue that PartitionedOutputOperator output size was incorrectly recorded for pages containing Dictionary/RunLengthEncoded blocks or rows are replicated. (#11770)

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 34]
```diff
@@ -0,0 +1,231 @@
...
+{
+    private static final int PARTITION_COUNT = 512;
+    private static final DataSize MAX_MEMORY = new DataSize(1, GIGABYTE);
+    private static final DataSize PARTITION_MAX_MEMORY = new DataSize(5, MEGABYTE);
+    private static final List<Type> TYPES = ImmutableList.of(BIGINT);
+    private static final List<Type> REPLICATION_TYPES = ImmutableList.of(BIGINT, BIGINT);
+    private static final Random RANDOM = new Random(0);
+    private static final ExecutorService EXECUTOR = newCachedThreadPool(daemonThreadsNamed("test-EXECUTOR-%s"));
+    private static final ScheduledExecutorService SCHEDULER = newScheduledThreadPool(1, daemonThreadsNamed("test-%s"));
+    private static final int POSITION_COUNT = 1000;
```
Comment (mbasmanova) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: This constant specifies number of positions per page, hence, I'd rename to POSITIONS_PER_PAGE.

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 35]
```diff
@@ -0,0 +1,231 @@
...
+    private static final Block NULL_BLOCK = new RunLengthEncodedBlock(BIGINT.createBlockBuilder(null, 1).appendNull().build(), POSITION_COUNT);
+    private static final Block TESTING_BLOCK = createLongSequenceBlock(0, POSITION_COUNT);
+    private static final Block TESTING_DICTIONARY_BLOCK = createLongDictionaryBlock(0, POSITION_COUNT);
+    private static final Block TESTING_RLE_BLOCK = createRLEBlock(RANDOM.nextLong(), POSITION_COUNT);
+    private static final Page TESTING_PAGE = new Page(TESTING_BLOCK);
+    private static final Page TESTING_PAGE_WITH_NULL_BLOCK = new Page(POSITION_COUNT, NULL_BLOCK, createLongSequenceBlock(0, POSITION_COUNT));
+    private static final int NUM_OF_ITERATIONS = 100;
```
Comment (mbasmanova) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: This constant specifies the number of pages, hence, I'd rename to PAGE_COUNT. I'd also put POSITIONS_PER_PAGE and PAGE_COUNT constants next to each other as they are related. 

```
    private static final int PAGE_COUNT = 100;
    private static final int POSITIONS_PER_PAGE = 1_000;
```

I'd further break all constants into three groups of related values:

```
    private static final int PARTITION_COUNT = 512;
    private static final DataSize MAX_MEMORY = new DataSize(1, GIGABYTE);
    private static final DataSize PARTITION_MAX_MEMORY = new DataSize(5, MEGABYTE);
    private static final List<Type> TYPES = ImmutableList.of(BIGINT);
    private static final List<Type> REPLICATION_TYPES = ImmutableList.of(BIGINT, BIGINT);
    private static final ExecutorService EXECUTOR = newCachedThreadPool(daemonThreadsNamed("test-EXECUTOR-%s"));
    private static final ScheduledExecutorService SCHEDULER = newScheduledThreadPool(1, daemonThreadsNamed("test-%s"));

    private static final int PAGE_COUNT = 100;
    private static final int POSITIONS_PER_PAGE = 1_000;

    private static final Block NULL_BLOCK = new RunLengthEncodedBlock(BIGINT.createBlockBuilder(null, 1).appendNull().build(), POSITIONS_PER_PAGE);
    private static final Block TESTING_BLOCK = createLongSequenceBlock(0, POSITIONS_PER_PAGE);
    private static final Block TESTING_DICTIONARY_BLOCK = createLongDictionaryBlock(0, POSITIONS_PER_PAGE);
    private static final Block TESTING_RLE_BLOCK = createRLEBlock(new Random(0).nextLong(), POSITIONS_PER_PAGE);
    private static final Page TESTING_PAGE = new Page(TESTING_BLOCK);
    private static final Page TESTING_PAGE_WITH_NULL_BLOCK = new Page(POSITIONS_PER_PAGE, NULL_BLOCK, createLongSequenceBlock(0, POSITIONS_PER_PAGE));
```

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 36]
```diff
@@ -0,0 +1,218 @@
...
+{
+    private static final int PAGE_COUNT = 100;
+    private static final int POSITIONS_PER_PAGE = 1000;
+
+    private static final int PARTITION_COUNT = 512;
+    private static final DataSize MAX_MEMORY = new DataSize(1, GIGABYTE);
+    private static final DataSize PARTITION_MAX_MEMORY = new DataSize(5, MEGABYTE);
+    private static final List<Type> TYPES = ImmutableList.of(BIGINT);
+    private static final List<Type> REPLICATION_TYPES = ImmutableList.of(BIGINT, BIGINT);
+    private static final Random RANDOM = new Random(0);
```
Comment (yingsu00) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: RANDOM is only used in TESTING_RLE_BLOCK. Could you please inline it?

File: presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java [hunk 37]
```diff
@@ -0,0 +1,218 @@
...
+    private static final ExecutorService EXECUTOR = newCachedThreadPool(daemonThreadsNamed("test-EXECUTOR-%s"));
+    private static final ScheduledExecutorService SCHEDULER = newScheduledThreadPool(1, daemonThreadsNamed("test-%s"));
+
+    private static final Block NULL_BLOCK = new RunLengthEncodedBlock(BIGINT.createBlockBuilder(null, 1).appendNull().build(), POSITIONS_PER_PAGE);
+    private static final Block TESTING_BLOCK = createLongSequenceBlock(0, POSITIONS_PER_PAGE);
+    private static final Block TESTING_DICTIONARY_BLOCK = createLongDictionaryBlock(0, POSITIONS_PER_PAGE);
+    private static final Block TESTING_RLE_BLOCK = createRLEBlock(RANDOM.nextLong(), POSITIONS_PER_PAGE);
+    private static final Page TESTING_PAGE = new Page(TESTING_BLOCK);
+    private static final Page TESTING_PAGE_WITH_NULL_BLOCK = new Page(POSITIONS_PER_PAGE, NULL_BLOCK, createLongSequenceBlock(0, POSITIONS_PER_PAGE));
```
Comment (yingsu00) [inline presto-main/src/test/java/com/facebook/presto/operator/TestPartitionedOutputOperator.java]: Replace createLongSequenceBlock(0, POSITIONS_PER_PAGE) with TESTING_BLOCK

**Comment by mbasmanova** [comment]
@yingsu00 I'll merge once remaining comments are addressed and tests are green.

**Comment by mbasmanova** [comment]
@ajaygeorge Ajay, thanks for the contribution.
