### PR TITLE
Validate selectors when configuring the resource manager

### LINKED ISSUE #6022: Rule without matching resource group does not report error at loading time
I created a rule:

``` json
    {
        "source": ".*monitoring.*",
        "group": "monitoring"
    }
```

But the group `monitoring` was missing. I then got:

```
PrestoQueryError: Error querying Presto:
java.lang.IllegalStateException: No matching configuration found for: monitoring
```

When executing a query with a sourcing matching that rule. Presto should report the error when it loads the `resource-groups.json` file.

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
Fixes #6022

### CODE REVIEW

**Comment by cberner** [comment]
There are some conflicts and Travis failed, could you rebase?

**Comment by nezihyigitbasi** [comment]
@cberner rebased.

File: presto-resource-group-managers/src/main/java/com/facebook/presto/resourceGroups/AbstractResourceConfigurationManager.java [hunk 1]
```diff
@@ -70,11 +70,28 @@ protected void validateRootGroups(ManagerSpec managerSpec)
...
+        if (selectorGroups.isEmpty()) {
+            return;
+        }
+        ResourceGroupNameTemplate groupName = selectorGroups.get(0);
+        Optional<ResourceGroupSpec> match = groups
+                .stream()
+                .filter(groupSpec -> groupSpec.getName().equals(groupName))
+                .findFirst();
+        if (!match.isPresent()) {
+            throw new IllegalArgumentException(format("Selector refers to nonexistent group: %s", groupName));
```
Comment (cberner) [inline presto-resource-group-managers/src/main/java/com/facebook/presto/resourceGroups/AbstractResourceConfigurationManager.java]: I think this message is going to be hard to understand. I would change this to use an iterative approach instead of recursion, so that you can print the fully qualified group name. The test you have below has an exception for the group "X", but there could be two groups with that name in different parts of the tree, like "a.b.X" and "a.c.X"

**Comment by nezihyigitbasi** [comment]
rebased & addressed comments.
