### PR TITLE
Fix join property derivations when not all columns are output

### LINKED ISSUE #7753: Query Optimizer failed to eliminating Remote Exchange
The following query will generate non-optimal plan:

```
explain (type distributed) 
select b.orderkey, count(*) 
from 
  (SELECT * FROM orders) a 
  JOIN 
  (SELECT * FROM lineitem) b 
ON a.orderkey = b.orderkey 
GROUP BY 1;
```

The plan: (we can eliminate the remote exchange between Fragment 1 and 2)

```
                                                              Query Plan                                                               
---------------------------------------------------------------------------------------------------------------------------------------
 Fragment 0 [SINGLE]                                                                                                                   
     Output layout: [orderkey_35, count]                                                                                               
     Output partitioning: SINGLE []                                                                                                    
     - Output[orderkey, _col1] => [orderkey_35:bigint, count:bigint]                                                                   
             orderkey := orderkey_35                                                                                                   
             _col1 := count                                                                                                            
         - RemoteSource[1] => [orderkey_35:bigint, count:bigint]                                                                       
                                                                                                                                       
 Fragment 1 [HASH]                                                                                                                     
     Output layout: [orderkey_35, count]                                                                                               
     Output partitioning: SINGLE []                                                                                                    
     - Aggregate(FINAL)[orderkey_35] => [orderkey_35:bigint, count:bigint]                                                             
             count := "count"("count_113")                                                                                             
         - LocalExchange[HASH][$hashvalue] ("orderkey_35") => orderkey_35:bigint, count_113:bigint, $hashvalue:bigint                  
             - RemoteSource[2] => [orderkey_35:bigint, count_113:bigint, $hashvalue_114:bigint]                                        
                                                                                                                                       
 Fragment 2 [tpch:orders:15000]                                                                                                        
     Output layout: [orderkey_35, count_113, $hashvalue_119]                                                                           
     Output partitioning: HASH [orderkey_35][$hashvalue_119]                                                                           
     - Project[] => [orderkey_35:bigint, count_113:bigint, $hashvalue_119:bigint]                                                      
             $hashvalue_119 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("orderkey_35"), 0))                           
         - Aggregate(PARTIAL)[orderkey_35] => [orderkey_35:bigint, count_113:bigint]                                                   
                 count_113 := "count"(*)                                                                                               
             - InnerJoin[("orderkey" = "orderkey_35")][$hashvalue_115, $hashvalue_116] => [orderkey_35:bigint]                         
                 - ScanProject[table = tpch:tpch:orders:sf0.01, originalConstraint = true] => [orderkey:bigint, $hashvalue_115:bigint] 
                         $hashvalue_115 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("orderkey"), 0))                  
                         orderkey := tpch:orderkey                                                                                     
                 - LocalExchange[HASH][$hashvalue_116] ("orderkey_35") => orderkey_35:bigint, $hashvalue_116:bigint                    
                     - RemoteSource[3] => [orderkey_35:bigint, $hashvalue_117:bigint]                                                  
                                                                                                                                       
 Fragment 3 [tpch:orders:15000]                                                                                                        
     Output layout: [orderkey_35, $hashvalue_118]                                                                                      
     Output partitioning: tpch:orders:15000 [orderkey_35]                                                                              
     - ScanProject[table = tpch:tpch:lineitem:sf0.01, originalConstraint = true] => [orderkey_35:bigint, $hashvalue_118:bigint]        
             $hashvalue_118 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("orderkey_35"), 0))                           
             orderkey_35 := tpch:orderkey                                                                                              
(1 row)
```                                                                                                                                       
                                                                                                                                       

The following queries can generate the correct plan:

- GROUP BY `a.orderkey` instead:
```
explain (type distributed) 
select a.orderkey, count(*) 
from 
  (SELECT * FROM orders) a 
  JOIN 
  (SELECT * FROM lineitem) b 
ON a.orderkey = b.orderkey 
GROUP BY 1;
```

- No subquery:
```
explain (type distributed) 
select b.orderkey, count(*) 
from orders a JOIN lineitem b
ON a.orderkey = b.orderkey 
GROUP BY 1;
```

### PR DESCRIPTION
**Pull request by martint**
Property derivation logic was producing properties in terms of
columns that might not be output by the join. This is an invalid
derivation.

As a result, AddExchanges could make suboptimal decisions when
deciding whether an operation could leverage the properties from
its inputs.

This change fixes it the logic to either remove or translate the
columns (where appropriate, based on equality conditions) so that
properties only reference output columns from the join.

Fixes #7753

### CODE REVIEW

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PropertyDerivations.java [hunk 1]
```diff
@@ -335,25 +349,28 @@ public ActualProperties visitDelete(DeleteNode node, List<ActualProperties> inpu
...
+                    Map<Symbol, NullableValue> constants = new HashMap<>();
+                    constants.putAll(probeProperties.getConstants());
+                    constants.putAll(buildProperties.getConstants());
+
                     return ActualProperties.builderFrom(probeProperties)
-                            .constants(ImmutableMap.<Symbol, NullableValue>builder()
-                                    .putAll(probeProperties.getConstants())
-                                    .putAll(buildProperties.getConstants())
-                                    .build())
+                            .constants(constants)
```
Comment (dain) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PropertyDerivations.java]: Any reason why you pulled this out to a variable?

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PropertyDerivations.java [hunk 2]
```diff
@@ -335,25 +349,28 @@ public ActualProperties visitDelete(DeleteNode node, List<ActualProperties> inpu
...
                             .build();
                 case LEFT:
-                    return ActualProperties.builderFrom(probeProperties)
-                            .constants(probeProperties.getConstants())
+                    return ActualProperties.builderFrom(probeProperties.translate(column -> filterIfMissing(node.getOutputSymbols(), column)))
                             .build();
                 case RIGHT:
-                    return ActualProperties.builderFrom(buildProperties)
-                            .constants(buildProperties.getConstants())
```
Comment (dain) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PropertyDerivations.java]: Did you mean to remove the constants?

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PropertyDerivations.java [hunk 3]
```diff
@@ -335,25 +349,28 @@ public ActualProperties visitDelete(DeleteNode node, List<ActualProperties> inpu
...
                     return ActualProperties.builderFrom(probeProperties)
-                            .constants(ImmutableMap.<Symbol, NullableValue>builder()
-                                    .putAll(probeProperties.getConstants())
-                                    .putAll(buildProperties.getConstants())
-                                    .build())
+                            .constants(constants)
                             .build();
                 case LEFT:
-                    return ActualProperties.builderFrom(probeProperties)
-                            .constants(probeProperties.getConstants())
```
Comment (dain) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PropertyDerivations.java]: Did you mean to remove the constants?

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/StreamPropertyDerivations.java [hunk 4]
```diff
@@ -117,8 +119,19 @@ public static StreamProperties deriveProperties(PlanNode node, List<StreamProper
...
-        return node.accept(new Visitor(metadata, session), inputProperties)
+        StreamProperties result = node.accept(new Visitor(metadata, session), inputProperties)
                 .withOtherActualProperties(otherProperties);
+
+        result.getPartitioningColumns().ifPresent(columns ->
+                verify(node.getOutputSymbols().containsAll(columns), "Stream-level partitioning properties contain columns not present in node's output"));
+
+        List<Symbol> localPropertyColumns = result.getLocalProperties().stream()
+                .flatMap(property -> property.getColumns().stream())
+                .collect(Collectors.toList());
```
Comment (dain) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/StreamPropertyDerivations.java]: Collect to set?

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PropertyDerivations.java (hunk 1 above)
Comment (martint) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PropertyDerivations.java]: It's because ImmutableMap builder doesn't allow dups, which can happen due to the translation we're doing now.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PropertyDerivations.java (hunk 3 above)
Comment (martint) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PropertyDerivations.java]: builderFrom already does that internally, so I just got rid of it.
