### PR TITLE
Fix flaky test: TestIcebergHiveStatistics.testStatisticsCachePartialEviction

### LINKED ISSUE #24742: Flaky test TestIcebergHiveStatistics.testStatisticsCachePartialEviction

### PR DESCRIPTION
**Pull request by ZacBlanco**
## Description

RuntimeStats are not reset by default in the builder. They need to be reset manually. If other tests are executed concurrently, they can pollute the RuntimeStats object and cause this test to fail.

## Motivation and Context

Fixes #24742 

Originally reported in #24736 - This test failed in CI 3 times in a row with the following stacktrace.

```
Error:  Tests run: 4439, Failures: 1, Errors: 0, Skipped: 27, Time elapsed: 2,279.117 s <<< FAILURE! - in TestSuite
Error:  com.facebook.presto.iceberg.hive.TestIcebergHiveStatistics.testStatisticsCachePartialEviction  Time elapsed: 0.371 s  <<< FAILURE!
java.lang.AssertionError: expected [32] but found [13]
	at org.testng.Assert.fail(Assert.java:110)
	at org.testng.Assert.failNotEquals(Assert.java:1413)
	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
	at org.testng.Assert.assertEquals(Assert.java:131)
	at org.testng.Assert.assertEquals(Assert.java:911)
	at org.testng.Assert.assertEquals(Assert.java:945)
	at com.facebook.presto.iceberg.hive.TestIcebergHiveStatistics.lambda$testStatisticsCachePartialEviction$1(TestIcebergHiveStatistics.java:438)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.facebook.presto.iceberg.hive.TestIcebergHiveStatistics.testStatisticsCachePartialEviction(TestIcebergHiveStatistics.java:438)
...
```

## Impact

N/A

## Test Plan

Existing tests. Could not reproduce again locally after this fix

## Contributor checklist

- [x] Please make sure your submission complies with our [contributing guide](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md), in particular [code style](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#code-style) and [commit standards](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#commit-standards).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [x] CI passed.

## Release Notes

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

File: presto-iceberg/src/test/java/com/facebook/presto/iceberg/hive/TestIcebergHiveStatistics.java [hunk 1]
```diff
@@ -415,42 +415,51 @@ public void testPredicateOnlyColumnInStatisticsOutput(boolean pushdownFilterEnab
...
-                .orElseThrow(() -> new RuntimeException("partial miss on statistics cache should have occurred"));
-        assertTrue(partialMiss.getCount() > 0);
-
-        statistics.getColumnStatistics().forEach((handle, stats) -> {
-            assertFalse(stats.getDistinctValuesCount().isUnknown());
-            if (isKllHistogramSupportedType(((IcebergColumnHandle) handle).getType())) {
-                assertTrue(stats.getHistogram().isPresent());
-            }
-        });
+        String tableName = "lineitem_statisticsFileCache";
```
Comment (ZacBlanco) [inline presto-iceberg/src/test/java/com/facebook/presto/iceberg/hive/TestIcebergHiveStatistics.java:420]: new table name variable so we have this table only for this test

File: presto-iceberg/src/test/java/com/facebook/presto/iceberg/hive/TestIcebergHiveStatistics.java [hunk 2]
```diff
@@ -415,42 +415,51 @@ public void testPredicateOnlyColumnInStatisticsOutput(boolean pushdownFilterEnab
...
+        try {
+            Map<String, String> catalogProperties = ImmutableMap.<String, String>builder().putAll(icebergQueryRunner.getIcebergCatalogs().get("iceberg"))
+                    .put("iceberg.max-statistics-file-cache-size", "1024B")
+                    .build();
+            getQueryRunner().createCatalog(catalogName, "iceberg", catalogProperties);
+            Session session = Session.builder(getSession())
+                    // runtime stats must be reset manually when using the builder
+                    .setRuntimeStats(new RuntimeStats())
```
Comment (ZacBlanco) [inline presto-iceberg/src/test/java/com/facebook/presto/iceberg/hive/TestIcebergHiveStatistics.java:428]: reset runtime stats manually to prevent pollution (main fix)

File: presto-iceberg/src/test/java/com/facebook/presto/iceberg/hive/TestIcebergHiveStatistics.java [hunk 3]
```diff
@@ -415,42 +415,51 @@ public void testPredicateOnlyColumnInStatisticsOutput(boolean pushdownFilterEnab
...
+                    .setCatalog(catalogName)
+                    // set histograms enabled to increase statistics cache size
+                    .setSystemProperty(OPTIMIZER_USE_HISTOGRAMS, "true")
+                    .setCatalogSessionProperty(catalogName, STATISTICS_KLL_SKETCH_K_PARAMETER, "32768")
+                    .build();
+
+            assertQuerySucceeds(format("CREATE TABLE %s as SELECT * FROM lineitem", tableName));
```
Comment (ZacBlanco) [inline presto-iceberg/src/test/java/com/facebook/presto/iceberg/hive/TestIcebergHiveStatistics.java:435]: CTAS for new table

File: presto-iceberg/src/test/java/com/facebook/presto/iceberg/hive/TestIcebergHiveStatistics.java [hunk 4]
```diff
@@ -415,42 +415,51 @@ public void testPredicateOnlyColumnInStatisticsOutput(boolean pushdownFilterEnab
...
+
+            statistics.getColumnStatistics().forEach((handle, stats) -> {
+                assertFalse(stats.getDistinctValuesCount().isUnknown());
+                if (isKllHistogramSupportedType(((IcebergColumnHandle) handle).getType())) {
+                    assertTrue(stats.getHistogram().isPresent());
+                }
+            });
+        }
+        finally {
+            assertQuerySucceeds("DROP TABLE " + tableName);
```
Comment (ZacBlanco) [inline presto-iceberg/src/test/java/com/facebook/presto/iceberg/hive/TestIcebergHiveStatistics.java:461]: final drop which was not present before

**Review by ZacBlanco — COMMENTED** [review]
Changes highlighted below

**Review by hantangwangd — APPROVED** [review]
Thanks for this fix, lgtm.

**Review by agrawalreetika — APPROVED** [review]
