### PR TITLE
Use names to map struct field to underlying data in ORC

### LINKED ISSUE #11001: Name based struct field mapping for ORC files
## Summary

Currently fields in structs are mapped to the underlying data based on the ordinal of the data field. This approach does not work in the case where the table schema changes to drop a field from the struct that is not the last field. Currently, such a change will cause all fields following the dropped field to be mis-aligned. 

### Current behavior
Consider the case of a struct `<a string, b string, c string>` being changed to `<a string, c string, d string>`. 
* The data of the deleted column `b` will be assigned to column `c`.
* The data from column `c` from the files which have data for column `b` will be assigned to column `d`.

### Desired behavior
* Data in the deleted column `b` should be ignored. 
* Column `c` should be  read correctly from files written before and after the schema change. 
* Column `d` should be null when reading files prior to the schema change and should be read in correctly from  the files written after  the schema change.

## Proposal

Similar to the `hive.orc.use-column-names` property, create a `hive.orc.use-struct-field-names` that maps to the underlying data based on field names rather than the position.

### PR DESCRIPTION
**Pull request by shreyasjoshis**
Fixes #11001. A summary for completeness:

Previously, presto used the ordinal position of a struct field to map a field to its corresponding data. The method does not work if fields are removed from the struct.

Let's say we have `struct <a:string, b string, c:string>` that changes to `struct <a:string, c:string>` (Field `b` is dropped). In this case the value of `c` from the old ORC files would be incorrect. It would read in the value of `b` from the underlying ORC files and misrepresent it as the values for `c`.

With this change, the old values of `b` will be ignored. `c` will be null if it is missing from an ORC file, or it will have the right value assigned to it.

### CODE REVIEW

File: presto-orc/src/main/java/com/facebook/presto/orc/reader/StructStreamReader.java [hunk 1]
```diff
@@ -55,15 +59,15 @@
...
         this.streamDescriptor = requireNonNull(streamDescriptor, "stream is null");
-
         List<StreamDescriptor> nestedStreams = streamDescriptor.getNestedStreams();
-        this.structFields = new StreamReader[nestedStreams.size()];
-        for (int i = 0; i < nestedStreams.size(); i++) {
-            StreamDescriptor nestedStream = nestedStreams.get(i);
-            this.structFields[i] = createStreamReader(nestedStream, hiveStorageTimeZone);
+        this.structFields = new HashMap<>();
+
+        for (StreamDescriptor nestedStream : nestedStreams) {
```
Comment (dain) [inline presto-orc/src/main/java/com/facebook/presto/orc/reader/StructStreamReader.java]: Build this into an Immutable map using stream collectors:
```java
        structFields = streamDescriptor.getNestedStreams().stream()
                .collect(toImmutableMap(StreamDescriptor::getFieldName, stream -> createStreamReader(stream, hiveStorageTimeZone)));
```

File: presto-orc/src/main/java/com/facebook/presto/orc/reader/StructStreamReader.java [hunk 2]
```diff
@@ -88,42 +92,26 @@ public Block readBlock(Type type)
...
-                        blocks[i] = structField.readBlock(typeParameters.get(i));
-                    }
-                    else {
-                        blocks[i] = getNullBlock(typeParameters.get(i), nextBatchSize - nullValues);
-                    }
-                }
+                blocks = getBlocksForType(type, nextBatchSize - nullValues);
             }
             else {
+                blocks = new Block[typeParameters.size()];
```
Comment (dain) [inline presto-orc/src/main/java/com/facebook/presto/orc/reader/StructStreamReader.java]: Since `typeParameters` is only used in this branch move the declaration down to here.

File: presto-orc/src/main/java/com/facebook/presto/orc/reader/StructStreamReader.java [hunk 3]
```diff
@@ -196,6 +184,28 @@ public String toString()
...
     }
 
+    private Block[] getBlocksForType(Type type, int positionCount) throws IOException
+    {
+        RowType rowType = (RowType) type;
+
+        Block[] blocks = new Block[rowType.getFields().size()];
+
+        for (int i = 0; i < rowType.getFields().size(); i++) {
+            Optional<String> fieldName = rowType.getFields().get(i).getName();
```
Comment (dain) [inline presto-orc/src/main/java/com/facebook/presto/orc/reader/StructStreamReader.java]: IIRC there was some issue with case sensitivity when we added this feature to the Parquet reader.  I think the issue was that Presto lower cases the field names in the type, so we may have to lower case when building the `structFields` map in the constructor. cc @nezihyigitbasi @zhenxiao for context on Parquet

File: presto-orc/src/main/java/com/facebook/presto/orc/reader/StructStreamReader.java [hunk 4]
```diff
@@ -196,6 +184,28 @@ public String toString()
...
+            Type fieldType = rowType.getFields().get(i).getType();
+
+            if (fieldName.isPresent() && structFields.containsKey(fieldName.get())) {
```
Comment (dain) [inline presto-orc/src/main/java/com/facebook/presto/orc/reader/StructStreamReader.java]: If the field name isn't present, shouldn't that be an error?

File: presto-orc/src/test/java/com/facebook/presto/orc/OrcTester.java [hunk 5]
```diff
@@ -353,19 +353,60 @@ private void testStructRoundTrip(Type type, List<?> values)
...
+        Type writeType = namedRowType(type, "field_a", "field_b", "field_d"); // missing field_c
 
-            assertRoundTrip(writeType, readType, writeValues, readValues, true);
-        }
+        List writeValues = values.stream()
+                .map(OrcTester::toHiveStruct)
+                .collect(toList());
+
+        List readValues = values.stream()
+                .map(value -> asList(value, value, null, value))
```
Comment (dain) [inline presto-orc/src/test/java/com/facebook/presto/orc/OrcTester.java]: I'm concerned that these tests won't catch reading the wrong fields, so I propose that we do something like: 
````
for i to values.lenght
  asList(
        i % 3 = 0 ? value : null,
        i % 3 = 1 ? value : null,
        null,
        i % 3 = 2 ? value : null)
``

File: presto-orc/src/main/java/com/facebook/presto/orc/reader/StructStreamReader.java (hunk 4 above)
Comment (shreyasjoshis) [reply presto-orc/src/main/java/com/facebook/presto/orc/reader/StructStreamReader.java]: I guess I don't know under what circumstances this can happen. I thought in case we have mix of fields, some with names and some without, it might be better to read the fields that we can, rather than erroring out.

File: presto-orc/src/test/java/com/facebook/presto/orc/OrcTester.java (hunk 5 above)
Comment (shreyasjoshis) [reply presto-orc/src/test/java/com/facebook/presto/orc/OrcTester.java]: Agreed. I also think that there really isn't a need to run these tests in particular with different data types. The behavior should not depend on whether we are dealing with a struct of doubles or strings. I put them here because this is where the other tests are.

Is there a better place to put these tests? If not I'll make this change. Also, in this case is there a danger that we end up always having nulls? Maybe we can default to different and unique values instead of defaulting to a null?

File: presto-orc/src/main/java/com/facebook/presto/orc/reader/StructStreamReader.java (hunk 4 above)
Comment (dain) [reply presto-orc/src/main/java/com/facebook/presto/orc/reader/StructStreamReader.java]: The `type` field is being supplied by Presto, based on the struct field names declared in the metastore, so I would say it is a bug in Presto if the names are not present... so let's throw an exception.

File: presto-orc/src/test/java/com/facebook/presto/orc/OrcTester.java (hunk 5 above)
Comment (dain) [reply presto-orc/src/test/java/com/facebook/presto/orc/OrcTester.java]: Take a look at `TestOrcWriter` it writes data and then reads it back in.  It looks like it would be easy to make a new test like that for struct type migrations.

**Comment by shreyasjoshis** [comment]
@dain Could you take a look at this when you get a moment?

File: presto-orc/src/test/java/com/facebook/presto/orc/TestStructStreamReader.java [hunk 6]
```diff
@@ -0,0 +1,293 @@
...
+    /**
+     * Reader and writer have the same fields. Checks that fields are read in correctly
+     *
+     */
+    @Test
+    public void testValuesAreReadInCorrectly() throws IOException
+    {
+        List<String> readerFields = new ArrayList<>(Arrays.asList("field_a", "field_b", "field_c"));
+        List<String> writerFields = new ArrayList<>(Arrays.asList("field_a", "field_b", "field_c"));
+        List<String> writerData = new ArrayList<>(Arrays.asList("field_a_value",
```
Comment (dain) [inline presto-orc/src/test/java/com/facebook/presto/orc/TestStructStreamReader.java]: no wrap.. basically don't rap unless it is really long 180, or there is something interesting at the end of the line

File: presto-orc/src/test/java/com/facebook/presto/orc/TestStructStreamReader.java [hunk 7]
```diff
@@ -0,0 +1,293 @@
...
+                                                                "field_b_value", "field_c_value"));
+        Type readerType = getTypeNullName(readerFields.size());
+        Type writerType = getType(writerFields);
+
+        write(tempFile, writerType, writerData);
+        RowBlock readBlock = read(tempFile, readerType);
```
Comment (dain) [inline presto-orc/src/test/java/com/facebook/presto/orc/TestStructStreamReader.java]: variable is not needed

File: presto-orc/src/test/java/com/facebook/presto/orc/TestStructStreamReader.java [hunk 8]
```diff
@@ -0,0 +1,293 @@
...
+
+    /**
+     * The reader has a field that is missing from the ORC file
+     */
+    @Test
+    public void testExtraFieldsInReader() throws IOException
+    {
+        List<String> readerFields = new ArrayList<>(Arrays.asList("field_a", "field_b", "field_c"));
+
+        //field_b is missing
```
Comment (dain) [inline presto-orc/src/test/java/com/facebook/presto/orc/TestStructStreamReader.java]: add space after `//`

File: presto-orc/src/test/java/com/facebook/presto/orc/TestStructStreamReader.java [hunk 9]
```diff
@@ -0,0 +1,293 @@
...
+        List actual = (List) readerType.getObjectValue(SESSION, readBlock, 0);
+
+        assertEquals(actual.size(), readerFields.size());
+        assertEquals(actual.get(0), "field_a_value");
+        assertNull(actual.get(1));
+        assertEquals(actual.get(2), "field_c_value");
+    }
+
+    /**
+     * The ORC file has a field that is mising from t he reader
```
Comment (dain) [inline presto-orc/src/test/java/com/facebook/presto/orc/TestStructStreamReader.java]: extra space

File: presto-orc/src/test/java/com/facebook/presto/orc/TestStructStreamReader.java [hunk 10]
```diff
@@ -0,0 +1,293 @@
...
+     */
+    @Test
+    public void testExtraFieldsInWriter() throws IOException
+    {
+        //field_b is missing
```
Comment (dain) [inline presto-orc/src/test/java/com/facebook/presto/orc/TestStructStreamReader.java]: space after `//`

File: presto-orc/src/test/java/com/facebook/presto/orc/TestStructStreamReader.java [hunk 11]
```diff
@@ -0,0 +1,293 @@
...
+        assertEquals(actual.size(), readerFields.size());
+        assertEquals(actual.get(0), "field_a_value");
+        assertEquals(actual.get(1), "field_c_value");
+    }
+
+    private void write(TempFile tempFile, Type writerType, List<String> data) throws IOException
+    {
+        OrcWriter writer =
+                new OrcWriter(new OutputStreamOrcDataSink(new FileOutputStream(tempFile.getFile())),
+                              com.google.common.collect.ImmutableList.of(STRUCT_COL_NAME),
```
Comment (dain) [inline presto-orc/src/test/java/com/facebook/presto/orc/TestStructStreamReader.java]: import `ImmutableList`

File: presto-orc/src/test/java/com/facebook/presto/orc/TestStructStreamReader.java [hunk 12]
```diff
@@ -0,0 +1,293 @@
...
+                              com.google.common.collect.ImmutableList.of(writerType), ORC, NONE,
+                              new OrcWriterOptions().withStripeMinSize(new DataSize(0, MEGABYTE))
+                                      .withStripeMaxSize(new DataSize(32, MEGABYTE))
+                                      .withStripeMaxRowCount(ORC_STRIPE_SIZE)
+                                      .withRowGroupMaxRowCount(ORC_ROW_GROUP_SIZE)
+                                      .withDictionaryMaxMemory(new DataSize(32, MEGABYTE)),
+                              ImmutableMap.of(), HIVE_STORAGE_TIME_ZONE, true,
+                              OrcWriteValidation.OrcWriteValidationMode.BOTH, new OrcWriterStats());
```
Comment (dain) [inline presto-orc/src/test/java/com/facebook/presto/orc/TestStructStreamReader.java]: Static import `BOTH`

File: presto-orc/src/test/java/com/facebook/presto/orc/TestStructStreamReader.java [hunk 13]
```diff
@@ -0,0 +1,293 @@
...
+
+        int entries = 10;
+        boolean[] rowIsNull = new boolean[entries];
+        Arrays.fill(rowIsNull, false);
+
+        BlockBuilder blockBuilder = TEST_DATA_TYPE.createBlockBuilder(null, entries);
+        for (int i = 0; i < data.size(); i++) {
+            byte[] bytes = data.get(i).getBytes();
+            for (int j = 0; j < entries; j++) {
+                blockBuilder
```
Comment (dain) [inline presto-orc/src/test/java/com/facebook/presto/orc/TestStructStreamReader.java]: one line

File: presto-orc/src/test/java/com/facebook/presto/orc/TestStructStreamReader.java [hunk 14]
```diff
@@ -0,0 +1,293 @@
...
+                        .writeBytes(Slices.wrappedBuffer(bytes, 0, bytes.length), 0, bytes.length);
```
Comment (dain) [inline presto-orc/src/test/java/com/facebook/presto/orc/TestStructStreamReader.java]: you can use the simpler form `Slices.wrapBuffer(bytes)`

File: presto-orc/src/test/java/com/facebook/presto/orc/TestStructStreamReader.java [hunk 15]
```diff
@@ -0,0 +1,293 @@
...
+    {
+        ImmutableList.Builder<TypeSignatureParameter> typeSignatureParameters =
+                ImmutableList.builder();
+        for (int i = 0; i < numFields; i++) {
+            typeSignatureParameters.add(TypeSignatureParameter.of(new NamedTypeSignature(
+                    Optional.empty(),
+                    TEST_DATA_TYPE.getTypeSignature())));
+        }
+        return TYPE_MANAGER
+                .getParameterizedType(StandardTypes.ROW, typeSignatureParameters.build());
```
Comment (dain) [inline presto-orc/src/test/java/com/facebook/presto/orc/TestStructStreamReader.java]: all of the lines above this split should be on one line

File: presto-orc/src/test/java/com/facebook/presto/orc/TestStructStreamReader.java [hunk 16]
```diff
@@ -0,0 +1,293 @@
...
+
+        assertEquals(actual.size(), readerFields.size());
+        assertEquals(actual.get(0), "field_a_value");
+        assertEquals(actual.get(1), "field_c_value");
+    }
+
+    private void write(TempFile tempFile, Type writerType, List<String> data) throws IOException
+    {
+        OrcWriter writer =
+                new OrcWriter(new OutputStreamOrcDataSink(new FileOutputStream(tempFile.getFile())),
```
Comment (dain) [inline presto-orc/src/test/java/com/facebook/presto/orc/TestStructStreamReader.java]: This is a good example of something that is better across many lines.  In cases like this, the you put the first argument on the next line.

File: presto-orc/src/test/java/com/facebook/presto/orc/OrcTester.java (hunk 5 above)
Comment (dain) [reply presto-orc/src/test/java/com/facebook/presto/orc/OrcTester.java]: The new tests look good, so let's remove these ones.

**Comment by dain** [comment]
This generally looks good, but you got a compile error in Travis.  Can you fix that up and then squash the commits and I'll merge this?

File: presto-orc/src/main/java/com/facebook/presto/orc/reader/StructStreamReader.java [hunk 17]
```diff
@@ -55,16 +60,13 @@
 
     private boolean rowGroupOpen;
 
-    public StructStreamReader(StreamDescriptor streamDescriptor, DateTimeZone hiveStorageTimeZone)
+    StructStreamReader(StreamDescriptor streamDescriptor, DateTimeZone hiveStorageTimeZone)
     {
         this.streamDescriptor = requireNonNull(streamDescriptor, "stream is null");
-
         List<StreamDescriptor> nestedStreams = streamDescriptor.getNestedStreams();
```
Comment (oneonestar) [inline presto-orc/src/main/java/com/facebook/presto/orc/reader/StructStreamReader.java]: `nestedStreams` is unused variable

**Comment by shreyasjoshis** [comment]
Not sure why the `presto-docs` tests are failing

**Comment by dain** [comment]
I'm not sure either.  Is this based on Presto trunk?  (I can't seem to find a place that lists the parent sha of your commit)

**Comment by shreyasjoshis** [comment]
I rebased it on `prestodb/presto` master

**Comment by electrum** [comment]
I wasn't able to reproduce the Travis failure locally. I'm re-running the Travis job now.

**Comment by electrum** [comment]
Travis passed this time. I cleared the cache before running it, so that might have been related.

**Comment by dain** [comment]
Merged.  Thank!
