### PR TITLE
Fix bugs in DictionaryBlock and Block.getRegionSizeInBytes

### LINKED ISSUE #7414: Broken full CI tests in presto-orc
Running full-ci in Jenkins turns up the following test failures. These can be reproduced in IntelliJ also.

```
testCharDirectSequence(com.facebook.presto.orc.TestFullOrcReader)  Time elapsed: 2.737 sec  <<< FAILURE!
java.lang.ArrayIndexOutOfBoundsException: 11111

testStringDirectSequence(com.facebook.presto.orc.TestFullOrcReader)  Time elapsed: 55.727 sec  <<< FAILURE!
java.lang.ArrayIndexOutOfBoundsException


Results :

Failed tests: 
  TestFullOrcReader>AbstractTestOrcReader.testCharDirectSequence:308 » ArrayIndexOutOfBounds
  TestFullOrcReader.testStringDirectSequence » ArrayIndexOutOfBounds
```

### PR DESCRIPTION
**Pull request by haozhun**
Fixes #7414

### CODE REVIEW

File: presto-spi/src/main/java/com/facebook/presto/spi/block/DictionaryBlockEncoding.java [hunk 1]
```diff
@@ -82,7 +82,7 @@ public Block readBlock(SliceInput sliceInput)
         long sequenceId = sliceInput.readLong();
 
         // we always compact the dictionary before we send it
```
Comment (dain) [inline presto-spi/src/main/java/com/facebook/presto/spi/block/DictionaryBlockEncoding.java]: maybe update the comment
