### PR TITLE
[Iceberg] Add predicate in layout without pushdown_filter_enabled

### LINKED ISSUE #22357: [Iceberg] Distinct value statistics are wrong when filters are applied
When calling `getTableStatistics` with a filter on a partition column, the distinct value count and some other statistics are wrong.

## Your Environment

- Iceberg connector with `HADOOP` catalog configured
- Presto 0.286

## Expected Behavior

Stats should be correct, or at least a closer estimate. NDVs should never exceed row counts. See test cases below for exact scenarios.

## Current Behavior

Table statistics are incorrect when filters are pushed down to the table scan using the Iceberg connector with a `HADOOP` configured catalog.

## Possible Solution

- For fixing min/max, make sure predicates are applied properly in the table scan.
- For fixing distinct value counts, we don't have a good way to merge distinct counts from separate partitions
  - Iceberg partition statistics don't have a way to get better estimates through probabilistic data structures like HLL or theta sketch. Likely need to resort to some heuristic.
  - a simple heuristic to start could be to use the entire distinct count of the table, and multiple by the ratio of selected rows from the partition filters.
  - e.g. table with $R$ rows has $D$ distinct values. A query for a set of partitions returns $R_p$ rows, when all manifest row counts are added together. The returned distinct value count could be $\frac{R_p}{R}\cdot D$. This would assume a uniform distribution of distinct values across partitions.

## Steps to Reproduce

```sql
-- setup
CREATE TABLE t (i int) WITH (partitioning = ARRAY['i']);
INSERT INTO t VALUES 1, 2, 3, 4, 5, 6, 7, 7, 7, 7;
ANALYZE t;
```

We can see stats for the whole table are correct with min/max and distinct values.

```sql
presto:z> SHOW STATS FOR t;
 column_name | data_size | distinct_values_count | nulls_fraction | row_count | low_value | high_value
-------------+-----------+-----------------------+----------------+-----------+-----------+------------
 i           | NULL      |                   7.0 |            0.0 | NULL      | 1         | 7
 NULL        | NULL      | NULL                  | NULL           |      10.0 | NULL      | NULL
(2 rows)
```

Now, apply some filters to the table:

`i = 7`: _BUG_: This should show distinct_values_count = 1. min = 7, max = 7, row count should be 4.
```sql
presto:z> SHOW STATS FOR (SELECT * FROM t WHERE i = 7);
 column_name | data_size | distinct_values_count | nulls_fraction | row_count | low_value | high_value
-------------+-----------+-----------------------+----------------+-----------+-----------+------------
 i           | NULL      |                   7.0 |            0.0 | NULL      | 1         | 7
 NULL        | NULL      | NULL                  | NULL           |      10.0 | NULL      | NULL
```

`i < 7`: _BUG_: distinct values should be 6 here.
```sql
presto:z> SHOW STATS FOR (SELECT * FROM t WHERE i < 7);
 column_name | data_size | distinct_values_count | nulls_fraction | row_count | low_value | high_value
-------------+-----------+-----------------------+----------------+-----------+-----------+------------
 i           | NULL      |                   7.0 |            0.0 | NULL      | 1         | 6
 NULL        | NULL      | NULL                  | NULL           |       6.0 | NULL      | NULL
```

`i <= 7`: _Correct_ because this contains all rows.
```sql
presto:z> SHOW STATS FOR (SELECT * FROM t WHERE i <= 7);
 column_name | data_size | distinct_values_count | nulls_fraction | row_count | low_value | high_value
-------------+-----------+-----------------------+----------------+-----------+-----------+------------
 i           | NULL      |                   7.0 |            0.0 | NULL      | 1         | 7
 NULL        | NULL      | NULL                  | NULL           |      10.0 | NULL      | NULL
```

`i >= 7`: _BUG_: distinct values count should be 1. Other statistics are correct.
```sql
presto:z> SHOW STATS FOR (SELECT * FROM t WHERE i >= 7);
 column_name | data_size | distinct_values_count | nulls_fraction | row_count | low_value | high_value
-------------+-----------+-----------------------+----------------+-----------+-----------+------------
 i           | NULL      |                   7.0 |            0.0 | NULL      | 7         | 7
 NULL        | NULL      | NULL                  | NULL           |       4.0 | NULL      | NULL
```

`i > 7`: _Correct_. No files should be scanned here, so we shouldn't have any statistics.
```sql
presto:z> SHOW STATS FOR (SELECT * FROM t WHERE i > 7);
 column_name | data_size | distinct_values_count | nulls_fraction | row_count | low_value | high_value
-------------+-----------+-----------------------+----------------+-----------+-----------+------------
 i           | NULL      | NULL                  | NULL           | NULL      | NULL      | NULL
 NULL        | NULL      | NULL                  | NULL           |       0.0 | NULL      | NULL
```

## Context

Incorrect NDV counts affects query join plans and results in longer execution times.

### PR DESCRIPTION
**Pull request by ZacBlanco**
## Description

The `iceberg.pushdown_filter_enabled` flag added recently
changed how the iceberg connector metadata generates
table layouts. The previous fork in the logic would cause
layouts to be generated without a partition predicate constraint
even if it existed. This can lead to table stats being incorrect
and hence incorrect statistics and poor query planning when
filtering on partitioned tables or when the config is disabled.

The original logic led to the codepath responsible for
filling in the predicate for tables when filter pushdown was disabled
to be unreachable. This change will now allows the predicates to
show up on partition columns in the layout.

## Motivation and Context

Incorrect stats for planning.

Fixes #22357

## Impact

N/A

## Test Plan

- New test to ensure layouts are pushed into the connector table layout which is propagated to the stats collection code.

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [x] CI passed.

## Release Notes

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

File: presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergAbstractMetadata.java [hunk 1]
```diff
@@ -258,59 +258,52 @@ public ConnectorTableLayout getTableLayout(ConnectorSession session, ConnectorTa
...
         if (!isPushdownFilterEnabled(session)) {
-            return new ConnectorTableLayout(handle);
-        }
-
-        if (!icebergTableLayoutHandle.getPartitions().isPresent()) {
             return new ConnectorTableLayout(
                     icebergTableLayoutHandle,
                     Optional.empty(),
-                    TupleDomain.none(),
+                    icebergTableLayoutHandle.getPartitionColumnPredicate(),
```
Comment (hantangwangd) [inline presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergAbstractMetadata.java:266]: Nice job, it's pretty good to fill partition predicate constraint into layout for shown up. I am investigating and confirming in my local branch about totally discard the predicate in IcebergTableHandle. So that the responsibilities of `IcebergTableHandle`, `IcebergTableLayoutHandle` and `ConnectorTableLayout` could be clarified more clearer, and the behaviors could be more consistent between `filter_push_down` on and off.

**Review by hantangwangd — APPROVED** [review]
LGTM! Only one nit.

File: presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergAbstractMetadata.java (hunk 1 above)
Comment (ZacBlanco) [reply presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergAbstractMetadata.java:266]: I agree with making that change. Having a predicate specified in multiple places currently is quite confusing

File: presto-spi/src/main/java/com/facebook/presto/spi/statistics/ColumnStatistics.java [hunk 2]
```diff
@@ -184,6 +199,11 @@ public Builder setHistogram(Optional<ConnectorHistogram> histogram)
             return this;
         }
 
+        public Optional<DoubleRange> getRange()
+        {
+            return range;
+        }
+
```
[the remark this answers is not in the document]
Comment (ZacBlanco) [reply presto-spi/src/main/java/com/facebook/presto/spi/statistics/ColumnStatistics.java]: Fixed, thanks

**Review by hantangwangd — APPROVED** [review]

**Review by tdcmeehan — APPROVED** [review]
