### PR TITLE
Fix and refactor boolean expression optimization

### LINKED ISSUE #6954: Query optimizer generates incorrect plans for some logical expressions
Reproduce with:
```
select (a=8 or b=2) and (a=8 or c=3) or (b=9) from (values (1, 2, 3)) as t (a, b, c);
```

`(a=8 or b=2) and (a=8 or c=3)` should become `a=8 or (b=2 and c=3)`. The query optimizer turns it into `a=8 and (b=2 and c=3)`

### PR DESCRIPTION
**Pull request by erichwang**
This fixes a correctness issue in the boolean expression optimization that
occurs when a multiple nested boolean expression attempts to factor out some
common sub-expressions.

For Example:
((A AND B) OR (A AND C)) AND D

Fixes #6954

### CODE REVIEW

File: presto-main/src/test/java/com/facebook/presto/sql/planner/optimizations/TestSimplifyExpressions.java [hunk 1]
```diff
@@ -83,9 +83,18 @@ public void testExtractsCommonPredicate()
...
+        assertSimplifies("((X OR V) AND Z) OR ((X OR V) AND V)", "(X OR V) AND (Z OR V)");
         assertSimplifies("X AND ((Y AND Z) OR (Y AND V) OR (Y AND X))", "X AND Y AND (Z OR V OR X)");
         assertSimplifies("(A AND B AND C AND D) OR (A AND B AND E) OR (A AND F)", "A AND ((B AND C AND D) OR (B AND E) OR F)");
+
+        assertSimplifies("((A AND B) OR (A AND C)) AND D", "A AND (B OR C) AND D");
+        assertSimplifies("((A OR B) AND (A OR C)) OR D", "(A OR B OR D) AND (A OR C OR D)");
+        assertSimplifies("(((A AND B) OR (A AND C)) AND D) OR E", "(A OR E) AND (B OR C OR E) AND (D OR E)");
+        assertSimplifies("(((A OR B) AND (A OR C)) OR D) AND E", "(A OR (B AND C) OR D) AND E");
+
+        assertSimplifies("(A AND B) OR (C AND D)", "(A OR C) AND (A OR D) AND (B OR C) AND (B OR D)");
```
Comment (martint) [inline presto-main/src/test/java/com/facebook/presto/sql/planner/optimizations/TestSimplifyExpressions.java]: The simplified form doesn't look better than the original one. All the terms appear twice in the new form, and all conjuncts have two distinct terms in them, so it doesn't help for predicate pushdown into connectors.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java [hunk 2]
```diff
@@ -234,26 +253,63 @@ public Expression rewriteLogicalBinaryExpression(LogicalBinaryExpression node, N
...
+         * ( A & B ) | ( C & D ) => ( A | C ) & ( A | D ) & ( B | C ) & ( B | D )
+         *
+         * Returns the original expression if the expression is non-deterministic or if the distribution will
+         * create more sub-expressions than the original.
+         */
+        private static Expression distributeIfPossible(LogicalBinaryExpression expression)
+        {
+            if (!DeterminismEvaluator.isDeterministic(expression)) {
+                // Do not distribute boolean expressions if there are any non-deterministic elements
+                // This can be optimized further, but let's not deal with it right now.
```
Comment (martint) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java]: make this a TODO

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java [hunk 3]
```diff
@@ -234,26 +253,63 @@ public Expression rewriteLogicalBinaryExpression(LogicalBinaryExpression node, N
...
+                return expression;
+            }
+            List<Set<Expression>> subPredicates = getSubPredicates(expression).stream()
+                    .map(ImmutableSet::copyOf)
+                    .collect(toList());
+
+            int originalSubexpressions = subPredicates.stream()
+                    .mapToInt(Set::size)
+                    .reduce(Math::addExact)
```
Comment (martint) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java]: `.sum()` ?

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java [hunk 4]
```diff
@@ -234,26 +253,63 @@ public Expression rewriteLogicalBinaryExpression(LogicalBinaryExpression node, N
...
+                    .mapToInt(Set::size)
+                    .reduce(Math::multiplyExact)
+                    .getAsInt();
+            if (newSubexpressions > originalSubexpressions) {
+                // Do not distribute boolean expressions if it would create more sub-expressions.
+                // This is just a heuristic to avoid cross product expression explosion.
+                return expression;
+            }
+
+            Set<List<Expression>> crossProduct = Sets.cartesianProduct(subPredicates);
```
Comment (martint) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java]: Does this preserve the relative left-to-right order of terms?

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java [hunk 5]
```diff
@@ -234,26 +253,63 @@ public Expression rewriteLogicalBinaryExpression(LogicalBinaryExpression node, N
...
+        /**
+         * Applies the boolean distributive property.
+         *
+         * For example:
+         * ( A & B ) | ( C & D ) => ( A | C ) & ( A | D ) & ( B | C ) & ( B | D )
+         *
+         * Returns the original expression if the expression is non-deterministic or if the distribution will
+         * create more sub-expressions than the original.
+         */
+        private static Expression distributeIfPossible(LogicalBinaryExpression expression)
```
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java]: call if:
`convertToCNFIfPossible`?

https://en.wikipedia.org/wiki/Conjunctive_normal_form

Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java]: I wonder if CNF conversion shouldn't be a different plan optimizer? It's not expression simplification per se.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java [hunk 6]
```diff
@@ -234,26 +253,63 @@ public Expression rewriteLogicalBinaryExpression(LogicalBinaryExpression node, N
...
+        {
+            if (!DeterminismEvaluator.isDeterministic(expression)) {
+                // Do not distribute boolean expressions if there are any non-deterministic elements
+                // This can be optimized further, but let's not deal with it right now.
+                return expression;
+            }
+            List<Set<Expression>> subPredicates = getSubPredicates(expression).stream()
+                    .map(ImmutableSet::copyOf)
```
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java]: why convert to set? Duplicates should already be removed by previous simplification step.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java [hunk 7]
```diff
@@ -234,26 +253,63 @@ public Expression rewriteLogicalBinaryExpression(LogicalBinaryExpression node, N
...
                     .collect(toImmutableList());
         }
 
+        /**
+         * Applies the boolean distributive property.
+         *
+         * For example:
+         * ( A & B ) | ( C & D ) => ( A | C ) & ( A | D ) & ( B | C ) & ( B | D )
+         *
+         * Returns the original expression if the expression is non-deterministic or if the distribution will
```
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java]: The rewritten expression above has more subexpressions (8, `[A, C]`, `[A, D]`, `[B, C]`, `[B, D]`) than the original one (4, `[A, B]`, `[C, D]`). From the computation below I deduce by subexpressions you mean elementary predicates, e.g: `A, B, C, D`

Please provide some more motivation about this heuristics.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java [hunk 8]
```diff
@@ -234,26 +253,63 @@ public Expression rewriteLogicalBinaryExpression(LogicalBinaryExpression node, N
...
+                    .map(ImmutableSet::copyOf)
+                    .collect(toList());
+
+            int originalSubexpressions = subPredicates.stream()
+                    .mapToInt(Set::size)
+                    .reduce(Math::addExact)
+                    .getAsInt();
+            int newSubexpressions = subPredicates.stream()
+                    .mapToInt(Set::size)
+                    .reduce(Math::multiplyExact)
```
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java]: The number of elementary subpredicates (e.g: `A, B, C, D`) will be larger. You have to multiply additionally by: `subPredicates.size()`.

For instance, for input expression:
`( A & B ) | ( C & D )` this will return 4
while it should be 8:
`( A | C ) & ( A | D ) & ( B | C ) & ( B | D )`

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java [hunk 9]
```diff
@@ -234,26 +253,63 @@ public Expression rewriteLogicalBinaryExpression(LogicalBinaryExpression node, N
...
+                    .getAsInt();
+            if (newSubexpressions > originalSubexpressions) {
```
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java]: When `newSubexpressions` computation is fixed to return actual number of elementary subpredicates,
then maybe this condition should be relaxed a bit, for instance: `newSubexpressions > originalSubexpressions * 2`. Otherwise it will never be met.

It's heuristics, so I don't know which constant would be the best.

File: presto-main/src/test/java/com/facebook/presto/sql/planner/optimizations/TestSimplifyExpressions.java [hunk 10]
```diff
@@ -65,7 +65,7 @@ public void testPushesDownNegations()
     }
 
     @Test
-    public void testExtractsCommonPredicate()
+    public void testExtractCommonPredicates()
     {
         assertSimplifies("X AND X", "X");
```
Comment (sopel39) [inline presto-main/src/test/java/com/facebook/presto/sql/planner/optimizations/TestSimplifyExpressions.java]: please add even more basic tests:
`X OR Y`,
`X AND Y`.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java [hunk 11]
```diff
@@ -212,11 +213,29 @@ public Expression rewriteExpression(Expression node, NodeContext context, Expres
...
+
+            if (!(expression instanceof LogicalBinaryExpression)) {
+                return expression;
+            }
+
+            Expression simplified = extractCommonPredicates((LogicalBinaryExpression) expression);
+
+            // Prefer AND LogicalBinaryExpression at the root if possible
+            if (context.isRootNode() && simplified instanceof LogicalBinaryExpression && ((LogicalBinaryExpression) simplified).getType() == OR) {
+                return distributeIfPossible((LogicalBinaryExpression) simplified);
```
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java]: I think
`distributeIfPossible`
will return wrong result (`X AND Y`) for input expression:
`X OR Y`.

**Comment by sopel39** [comment]
Maybe split this PR into two smaller ones: original bufix and refactor.
Refactor (although short) is non trivial might take longer to land.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java (hunk 5 above)
Comment (erichwang) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java]: This is not intended to produce CNF (which needs to be applied recursively to all sub-expressions). We only replace the top level here as a simple heuristic to make sure we don't mess up our predicate move around too much with this optimization by slightly preferring conjunctions.

The only thing this is trying to do is to apply the boolean distribution property in some cases.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java (hunk 7 above)
Comment (erichwang) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java]: The only thing we are trying to do here is prevent a huge explosion in the expression size that can occur when you do this type of expansion. it doesn't really matter what heuristic in this case, just that we avoid crazy cross products.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java (hunk 8 above)
Comment (erichwang) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java]: Yea, to compare strictly the same thing, you are right to multiply by sub predicates sizes.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java (hunk 9 above)
Comment (erichwang) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java]: I don't think there is a good way to know that right now. Let's just pick something and adjust it if there are issues.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java (hunk 11 above)
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/SimplifyExpressions.java]: Yes, it seems to be handled correctly since first `X` and `Y` are `OR-ed` and then `AND-ed` as only cross product.

**Comment by sopel39** [comment]
Thanks for addressing comments. Would be great though if you waited for approval next time before merging since this code is definitely not trivial and double checking is definitely valuable.
