### PR TITLE
Fix 'integer overflow' in PagesRTreeIndex

### LINKED ISSUE #10169: Spatial join fails with "integer overflow"
```
java.lang.ArithmeticException: integer overflow
	at java.lang.Math.toIntExact(Math.java:1011)
	at com.facebook.presto.operator.PagesRTreeIndex.isJoinAddressEligible(PagesRTreeIndex.java:148)
	at com.facebook.presto.operator.SpatialJoinOperator.processProbe(SpatialJoinOperator.java:238)
	at com.facebook.presto.operator.SpatialJoinOperator.getOutput(SpatialJoinOperator.java:191)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:278)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:645)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:272)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This issue affects spatial joins with additional filters applied to columns from both sides of the join.

Spatial joins without additional filters are not affected.

### PR DESCRIPTION
**Pull request by mbasmanova**
`PagesRTreeIndex#isJoinPositionEligible` threw "integer overflow" from `toIntExact(joinAddress)` conversion performed before invoking `JoinFilterFunction`. `joinAddress` is a `SynteticAddress` that encodes pageIndex and position within the page. `toIntExact(joinAddress)` succeeds only if `pageIndex == 0` and throws "integer overflow" when `pageIndex > 0`.

This issue affects spatial joins with additional filters applied to columns from both sides of the join.

Spatial joins without additional filters are not affected.

Fixes #10169

### CODE REVIEW

File: presto-geospatial/src/test/java/com/facebook/presto/plugin/geospatial/TestSpatialJoinOperator.java [hunk 1]
```diff
@@ -210,6 +210,7 @@ public void testYield()
 
         RowPagesBuilder buildPages = rowPagesBuilder(ImmutableList.of(GEOMETRY, VARCHAR))
                 .row(POLYGON_A, "A")
+                .pageBreak()
```
Comment (findepi) [inline presto-geospatial/src/test/java/com/facebook/presto/plugin/geospatial/TestSpatialJoinOperator.java]: I understand you need 2 pages for any useful test with addresses. Did you manage to craft a test that would exploit the bug within reasonable time?  Maybe 3,000,000,000 identical (shared) geometries would do that?

File: presto-main/src/main/java/com/facebook/presto/operator/PagesRTreeIndex.java [hunk 2]
```diff
@@ -116,28 +118,29 @@ private static Envelope getEnvelope(OGCGeometry ogcGeometry)
...
-        return matchingAddresses.toLongArray(null);
+        return matchingPositions.toIntArray(null);
     }
 
     @Override
-    public boolean isJoinAddressEligible(long joinAddress, int probePosition, Page probe)
+    public boolean isJoinPositionEligible(int joinPosition, int probePosition, Page probe)
     {
-        return filterFunction == null || filterFunction.filter(toIntExact(joinAddress), probePosition, probe);
+        return filterFunction == null || filterFunction.filter(joinPosition, probePosition, probe);
```
Comment (findepi) [inline presto-main/src/main/java/com/facebook/presto/operator/PagesRTreeIndex.java]: why `joinPosition` and not `addresses.getLong(joinPosition)` ? I think this is _the_ place which you're fixing, right?

If i understand this correctly, please add to the commit message:
- what was wrong ("FilterFunction was incorrectly invoked")
- something about the renames, that they are many renames, but little logic changed

I wonder if this could be made more visible but somehow splitting the commits.

Also, maybe the `com.facebook.presto.operator.JoinFilterFunction#filter`'s `leftAddress` argument should be renamed to eg `leftAddressIndex`?

Comment (findepi) [reply presto-main/src/main/java/com/facebook/presto/operator/PagesRTreeIndex.java]: Also, the commit title line could be improved.

File: presto-geospatial/src/test/java/com/facebook/presto/plugin/geospatial/TestSpatialJoinOperator.java (hunk 1 above)
Comment (mbasmanova) [reply presto-geospatial/src/test/java/com/facebook/presto/plugin/geospatial/TestSpatialJoinOperator.java]: This bug happens whenever join has addition function and a record from a build page other then first matches the spatial condition. toIntExact(joinAddress) fails with "integer overflow" whenever joinAddress encodes a record on a page other than first. Hence, this simple change was sufficient to reproduce the issue.

File: presto-main/src/main/java/com/facebook/presto/operator/PagesRTreeIndex.java (hunk 2 above)
Comment (mbasmanova) [reply presto-main/src/main/java/com/facebook/presto/operator/PagesRTreeIndex.java]: @findepi 

> why joinPosition and not addresses.getLong(joinPosition) ?

It turns out that  `leftAddress` in FIlterFunction interface refers not the address, but rather an index in the `addresses` array.

```
    @Override
    public boolean filter(int leftAddress, int rightPosition, Page rightPage)
    {
        long pageAddress = addresses.getLong(leftAddress);
        int blockIndex = decodeSliceIndex(pageAddress);
        int blockPosition = decodePosition(pageAddress);

        return filterFunction.filter(blockPosition, getLeftBlocks(blockIndex), rightPosition, rightPage.getBlocks());
    }
```

**Comment by mbasmanova** [comment]
@findepi Piotr, thank you for review. I updated commit message and added another commit to rename joinAddress argument in JoinFilterFunction to joinPosition.

File: presto-main/src/main/java/com/facebook/presto/operator/PagesRTreeIndex.java (hunk 2 above)
Comment (findepi) [reply presto-main/src/main/java/com/facebook/presto/operator/PagesRTreeIndex.java]: Yea, i figured that out, but wanted to make sure with you that i understand correctly. Thanks.

**Comment by findepi** [comment]
cmt msg `Fix 'integer overflow' in PagesRTreeIndex`

This is a bit misleading, since the bug was not just "integer overflow" (like in `a + b`).
It was more like "wrong type" -- an "address" was being passed where "index of an address" was expected.

Maybe the commit title should be sth like `Fix row addressing in spatial index's filter` ?

**Comment by mbasmanova** [comment]
@findepi 

> This is a bit misleading, since the bug was not just "integer overflow" (like in a + b).

The bug manifested itself as "integer overflow" error message, hence, I used it in the commit message.

```
java.lang.ArithmeticException: integer overflow
	at java.lang.Math.toIntExact(Math.java:1011)
	at com.facebook.presto.operator.PagesRTreeIndex.isJoinAddressEligible(PagesRTreeIndex.java:148)
	at com.facebook.presto.operator.SpatialJoinOperator.processProbe(SpatialJoinOperator.java:238)
	at com.facebook.presto.operator.SpatialJoinOperator.getOutput(SpatialJoinOperator.java:191)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:278)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:645)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:272)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by findepi** [comment]
> The bug manifested itself as "integer overflow" error message, hence, I used it in the commit message.

I know and understand. However, this title doesn't reflect the actual changes.
