### PR TITLE
Disallow partial aggregation pushdown in more cases

### LINKED ISSUE #15157: partial aggregation pushdown fails in TestHivePushdownFilterQueries and TestHivePushdownDistributedQueries
If enable partial aggregation in TestHivePushdownFilterQueries and TestHivePushdownIntegrationSmokeTest:
```
DistributedQueryRunner queryRunner = HiveQueryRunner.createQueryRunner(getTables(),
                ImmutableMap.of("experimental.pushdown-subfields-enabled", "true", "experimental.pushdown-dereference-enabled", "true"),
                "sql-standard",
                ImmutableMap.of("hive.pushdown-filter-enabled", "true", "hive.enable-parquet-dereference-pushdown", "true", "hive.partial_aggregation_pushdown_enabled", "true", "hive.partial_aggregation_pushdown_for_variable_length_datatypes_enabled", "true"),
                Optional.empty());

queryRunner.execute(noPushdownFilter(queryRunner.getDefaultSession()),
```

                    ImmutableList.of(ORDERS, CUSTOMER, LINE_ITEM, PART_SUPPLIER),
                    ImmutableMap.of("experimental.pushdown-subfields-enabled", "true", "experimental.pushdown-dereference-enabled", "true"),
                    "sql-standard",
                    ImmutableMap.of("hive.pushdown-filter-enabled", "true", "hive.enable-parquet-dereference-pushdown", "true"),
                    ImmutableMap.of("hive.pushdown-filter-enabled", "true", "hive.enable-parquet-dereference-pushdown", "true", "hive.partial_aggregation_pushdown_enabled", "true", "hive.partial_aggregation_pushdown_for_variable_length_datatypes_enabled", "true"),
                    Optional.empty()),
                createBucketedSession(Optional.of(new SelectedRole(ROLE, Optional.of("admin")))),
                createMaterializeExchangesSession(Optional.of(new SelectedRole(ROLE, Optional.of("admin")))),
```

will get following error:
[ERROR] testAggregateSingleColumn(com.facebook.presto.hive.TestHivePushdownIntegrationSmokeTest)  Time elapsed: 2.194 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT MAX(comment) FROM orders
	at org.testng.Assert.fail(Assert.java:83)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:150)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:134)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:129)
	at com.facebook.presto.tests.AbstractTestIntegrationSmokeTest.testAggregateSingleColumn(AbstractTestIntegrationSmokeTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: No min/max found for orc file. Set session property pushdown_partial_aggregations_into_scan=false and execute query again
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:115)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:446)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:147)
	... 17 more
Caused by: java.lang.UnsupportedOperationException: No min/max found for orc file. Set session property pushdown_partial_aggregations_into_scan=false and execute query again
	at com.facebook.presto.hive.orc.AggregatedOrcPageSource.writeMinMax(AggregatedOrcPageSource.java:172)
	at com.facebook.presto.hive.orc.AggregatedOrcPageSource.getNextPage(AggregatedOrcPageSource.java:116)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:251)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:382)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:284)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:277)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_0_242_SNAPSHOT_8b1f15d__testversion____20200910_061017_4.run(Unknown Source)
	... 3 more

[ERROR] testNullBucket(com.facebook.presto.hive.TestHivePushdownIntegrationSmokeTest)  Time elapsed: 0.25 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT COUNT() FROM table_with_null_buckets WHERE key IS NULL
	at org.testng.Assert.fail(Assert.java:83)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:150)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:144)
	at com.facebook.presto.hive.TestHiveIntegrationSmokeTest.testNullBucket(TestHiveIntegrationSmokeTest.java:2185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: No value present
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:115)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:446)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:147)
	... 16 more
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.facebook.presto.hive.orc.AggregatedOrcPageSource.getNextPage(AggregatedOrcPageSource.java:100)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:251)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:382)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:284)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:277)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_0_242_SNAPSHOT_8b1f15d__testversion____20200910_061017_4.run(Unknown Source)
	... 3 more

[ERROR] testBooleans(com.facebook.presto.hive.TestHivePushdownFilterQueries)  Time elapsed: 5.629 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT count(*) FROM lineitem_ex WHERE is_returned is not null
	at org.testng.Assert.fail(Assert.java:83)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:150)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:139)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertQueryUsingH2Cte(TestHivePushdownFilterQueries.java:1139)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertQueryUsingH2Cte(TestHivePushdownFilterQueries.java:1134)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.testBooleans(TestHivePushdownFilterQueries.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: No value present
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:115)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:446)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:147)
	... 18 more
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.facebook.presto.hive.orc.AggregatedOrcPageSource.getNextPage(AggregatedOrcPageSource.java:100)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:251)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:382)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:284)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:277)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_0_242_SNAPSHOT_8b1f15d__testversion____20200910_062606_5113.run(Unknown Source)
	... 3 more

[ERROR] testBytes(com.facebook.presto.hive.TestHivePushdownFilterQueries)  Time elapsed: 8.1 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT count(*) FROM lineitem_ex WHERE ship_day > 15
	at org.testng.Assert.fail(Assert.java:83)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:150)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:139)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertQueryUsingH2Cte(TestHivePushdownFilterQueries.java:1139)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertQueryUsingH2Cte(TestHivePushdownFilterQueries.java:1134)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.testBytes(TestHivePushdownFilterQueries.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: No value present
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:115)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:446)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:147)
	... 18 more
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.facebook.presto.hive.orc.AggregatedOrcPageSource.getNextPage(AggregatedOrcPageSource.java:100)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:251)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:382)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:284)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:277)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_0_242_SNAPSHOT_8b1f15d__testversion____20200910_062552_5111.run(Unknown Source)
	... 3 more

[ERROR] testDecimals(com.facebook.presto.hive.TestHivePushdownFilterQueries)  Time elapsed: 53.143 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT count(*) FROM lineitem_ex WHERE discount_long_decimal IS NOT NULL
	at org.testng.Assert.fail(Assert.java:83)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:150)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:139)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertQueryUsingH2Cte(TestHivePushdownFilterQueries.java:1139)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertQueryUsingH2Cte(TestHivePushdownFilterQueries.java:1134)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertFilterProject(TestHivePushdownFilterQueries.java:701)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.testDecimals(TestHivePushdownFilterQueries.java:390)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: No value present
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:115)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:446)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:147)
	... 19 more
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.facebook.presto.hive.orc.AggregatedOrcPageSource.getNextPage(AggregatedOrcPageSource.java:100)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:251)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:382)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:284)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:277)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_0_242_SNAPSHOT_8b1f15d__testversion____20200910_062552_5111.run(Unknown Source)
	... 3 more

[ERROR] testDouble(com.facebook.presto.hive.TestHivePushdownFilterQueries)  Time elapsed: 6.153 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT count(*) FROM lineitem_ex WHERE discount IS NULL
	at org.testng.Assert.fail(Assert.java:83)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:150)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:139)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertQueryUsingH2Cte(TestHivePushdownFilterQueries.java:1139)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertQueryUsingH2Cte(TestHivePushdownFilterQueries.java:1134)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertFilterProject(TestHivePushdownFilterQueries.java:701)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.testDouble(TestHivePushdownFilterQueries.java:292)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: No value present
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:115)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:446)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:147)
	... 19 more
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.facebook.presto.hive.orc.AggregatedOrcPageSource.getNextPage(AggregatedOrcPageSource.java:100)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:251)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:382)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:284)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:277)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_0_242_SNAPSHOT_8b1f15d__testversion____20200910_062606_5113.run(Unknown Source)
	... 3 more

[ERROR] testFloats(com.facebook.presto.hive.TestHivePushdownFilterQueries)  Time elapsed: 37.422 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT count(*) FROM lineitem_ex WHERE tax_real IS NOT NULL
	at org.testng.Assert.fail(Assert.java:83)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:150)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:139)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertQueryUsingH2Cte(TestHivePushdownFilterQueries.java:1139)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertQueryUsingH2Cte(TestHivePushdownFilterQueries.java:1134)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertFilterProject(TestHivePushdownFilterQueries.java:701)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.testFloats(TestHivePushdownFilterQueries.java:320)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: No value present
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:115)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:446)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:147)
	... 19 more
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.facebook.presto.hive.orc.AggregatedOrcPageSource.getNextPage(AggregatedOrcPageSource.java:100)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:251)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:382)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:284)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:277)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_0_242_SNAPSHOT_8b1f15d__testversion____20200910_062552_5111.run(Unknown Source)
	... 3 more

[ERROR] testNumeric(com.facebook.presto.hive.TestHivePushdownFilterQueries)  Time elapsed: 0.726 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT count(*) FROM orders WHERE orderkey BETWEEN 100 AND 1000 AND custkey BETWEEN 500 AND 800
	at org.testng.Assert.fail(Assert.java:83)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:150)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:134)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:129)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.testNumeric(TestHivePushdownFilterQueries.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: No value present
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:115)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:446)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:147)
	... 17 more
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.facebook.presto.hive.orc.AggregatedOrcPageSource.getNextPage(AggregatedOrcPageSource.java:100)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:251)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:382)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:284)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:277)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_0_242_SNAPSHOT_8b1f15d__testversion____20200910_062611_5114.run(Unknown Source)
	... 3 more

[ERROR] testRcAndTextFormats(com.facebook.presto.hive.TestHivePushdownFilterQueries)  Time elapsed: 39.12 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT COUNT(*) FROM test_file_format_orc
	at org.testng.Assert.fail(Assert.java:83)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:150)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:139)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertQueryUsingH2Cte(TestHivePushdownFilterQueries.java:1129)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertQueryUsingH2Cte(TestHivePushdownFilterQueries.java:1124)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertFileFormat(TestHivePushdownFilterQueries.java:1037)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.testRcAndTextFormats(TestHivePushdownFilterQueries.java:970)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Error opening Hive split file:/tmp/PrestoTest7205970413479009931/hive_data/tpch/test_file_format_orc/ds=2019-11-01/20200910_063440_00217_pwbxv_944cfbcb-d6cf-4130-ba2a-8a486a969456 (offset=0, length=645326): -20
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:115)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:446)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:147)
	... 19 more
Caused by: com.facebook.presto.spi.PrestoException: Error opening Hive split file:/tmp/PrestoTest7205970413479009931/hive_data/tpch/test_file_format_orc/ds=2019-11-01/20200910_063440_00217_pwbxv_944cfbcb-d6cf-4130-ba2a-8a486a969456 (offset=0, length=645326): -20
	at com.facebook.presto.hive.rcfile.RcFilePageSourceFactory.createPageSource(RcFilePageSourceFactory.java:177)
	at com.facebook.presto.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:376)
	at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:170)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:63)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:80)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:248)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:382)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:284)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:277)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_0_242_SNAPSHOT_8b1f15d__testversion____20200910_062558_5112.run(Unknown Source)
	... 3 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: -20
	at com.facebook.presto.rcfile.RcFileReader.<init>(RcFileReader.java:216)
	at com.facebook.presto.rcfile.RcFileReader.<init>(RcFileReader.java:118)
	at com.facebook.presto.hive.rcfile.RcFilePageSourceFactory.createPageSource(RcFilePageSourceFactory.java:150)
	... 16 more

[ERROR] testStrings(com.facebook.presto.hive.TestHivePushdownFilterQueries)  Time elapsed: 14.481 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT count(*) FROM lineitem_ex WHERE comment is NULL
	at org.testng.Assert.fail(Assert.java:83)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:150)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:139)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertQueryUsingH2Cte(TestHivePushdownFilterQueries.java:1139)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertQueryUsingH2Cte(TestHivePushdownFilterQueries.java:1134)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertFilterProject(TestHivePushdownFilterQueries.java:701)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.testStrings(TestHivePushdownFilterQueries.java:419)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: No value present
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:115)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:446)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:147)
	... 19 more
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.facebook.presto.hive.orc.AggregatedOrcPageSource.getNextPage(AggregatedOrcPageSource.java:100)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:251)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:382)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:284)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:277)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_0_242_SNAPSHOT_8b1f15d__testversion____20200910_062552_5111.run(Unknown Source)
	... 3 more

[ERROR] testTimestamps(com.facebook.presto.hive.TestHivePushdownFilterQueries)  Time elapsed: 3.316 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT count(*) FROM lineitem_ex WHERE ship_timestamp IS NOT NULL
	at org.testng.Assert.fail(Assert.java:83)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:150)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:139)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertQueryUsingH2Cte(TestHivePushdownFilterQueries.java:1139)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertQueryUsingH2Cte(TestHivePushdownFilterQueries.java:1134)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.testTimestamps(TestHivePushdownFilterQueries.java:267)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: No value present
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:115)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:446)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:147)
	... 18 more
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.facebook.presto.hive.orc.AggregatedOrcPageSource.getNextPage(AggregatedOrcPageSource.java:100)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:251)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:382)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:284)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:277)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_0_242_SNAPSHOT_8b1f15d__testversion____20200910_062558_5112.run(Unknown Source)
	... 3 more

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestHivePushdownFilterQueries.testBooleans:197->assertQueryUsingH2Cte:1134->assertQueryUsingH2Cte:1139->AbstractTestQueryFramework.assertQuery:139 Execution of 'actual' query failed: SELECT count(*) FROM lineitem_ex WHERE is_returned is not null
[ERROR]   TestHivePushdownFilterQueries.testBytes:221->assertQueryUsingH2Cte:1134->assertQueryUsingH2Cte:1139->AbstractTestQueryFramework.assertQuery:139 Execution of 'actual' query failed: SELECT count(*) FROM lineitem_ex WHERE ship_day > 15
[ERROR]   TestHivePushdownFilterQueries.testDecimals:390->assertFilterProject:701->assertQueryUsingH2Cte:1134->assertQueryUsingH2Cte:1139->AbstractTestQueryFramework.assertQuery:139 Execution of 'actual' query failed: SELECT count(*) FROM lineitem_ex WHERE discount_long_decimal IS NOT NULL
[ERROR]   TestHivePushdownFilterQueries.testDouble:292->assertFilterProject:701->assertQueryUsingH2Cte:1134->assertQueryUsingH2Cte:1139->AbstractTestQueryFramework.assertQuery:139 Execution of 'actual' query failed: SELECT count(*) FROM lineitem_ex WHERE discount IS NULL
[ERROR]   TestHivePushdownFilterQueries.testFloats:320->assertFilterProject:701->assertQueryUsingH2Cte:1134->assertQueryUsingH2Cte:1139->AbstractTestQueryFramework.assertQuery:139 Execution of 'actual' query failed: SELECT count(*) FROM lineitem_ex WHERE tax_real IS NOT NULL
[ERROR]   TestHivePushdownFilterQueries.testNumeric:246->AbstractTestQueryFramework.assertQuery:129->AbstractTestQueryFramework.assertQuery:134 Execution of 'actual' query failed: SELECT count(*) FROM orders WHERE orderkey BETWEEN 100 AND 1000 AND custkey BETWEEN 500 AND 800
[ERROR]   TestHivePushdownFilterQueries.testRcAndTextFormats:970->assertFileFormat:1037->assertQueryUsingH2Cte:1124->assertQueryUsingH2Cte:1129->AbstractTestQueryFramework.assertQuery:139 Execution of 'actual' query failed: SELECT COUNT(*) FROM test_file_format_orc
[ERROR]   TestHivePushdownFilterQueries.testStrings:419->assertFilterProject:701->assertQueryUsingH2Cte:1134->assertQueryUsingH2Cte:1139->AbstractTestQueryFramework.assertQuery:139 Execution of 'actual' query failed: SELECT count(*) FROM lineitem_ex WHERE comment is NULL
[ERROR]   TestHivePushdownFilterQueries.testTimestamps:267->assertQueryUsingH2Cte:1134->assertQueryUsingH2Cte:1139->AbstractTestQueryFramework.assertQuery:139 Execution of 'actual' query failed: SELECT count(*) FROM lineitem_ex WHERE ship_timestamp IS NOT NULL
[ERROR]   TestHivePushdownIntegrationSmokeTest>AbstractTestIntegrationSmokeTest.testAggregateSingleColumn:47->AbstractTestQueryFramework.assertQuery:129->AbstractTestQueryFramework.assertQuery:134 Execution of 'actual' query failed: SELECT MAX(comment) FROM orders
[ERROR]   TestHivePushdownIntegrationSmokeTest>TestHiveIntegrationSmokeTest.testNullBucket:2185->AbstractTestQueryFramework.assertQuery:144 Execution of 'actual' query failed: SELECT COUNT() FROM table_with_null_buckets WHERE key IS NULL
[INFO] 
[ERROR] Tests run: 150, Failures: 11, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

### PR DESCRIPTION
**Pull request by ClarenceThreepwood**
Disallow partial aggregation pushdown when
1. Filters are pushed into tableScan
2. Storage format metadata is inconsistent with the file format

Also enable partial aggregation flags in more tests

Fixes #15157 
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

File: presto-hive/src/main/java/com/facebook/presto/hive/HivePageSourceProvider.java [hunk 1]
```diff
@@ -422,6 +422,10 @@ protected static CacheQuota generateCacheQuota(HiveSplit hiveSplit)
             }
         }
 
+        if (!hiveColumns.isEmpty() && hiveColumns.get(0).getColumnType() == AGGREGATED) {
```
Comment (zhenxiao) [inline presto-hive/src/main/java/com/facebook/presto/hive/HivePageSourceProvider.java:425]: get confuse here. if hiveColumns only have one AGGREGATED column, is it valid?

File: presto-hive/src/main/java/com/facebook/presto/hive/HivePartialAggregationPushdown.java [hunk 2]
```diff
@@ -125,8 +122,31 @@ public Visitor(VariableAllocator variableAllocator, ConnectorSession session, Pl
...
+
+            TableScanNode tableScanNode = (TableScanNode) partialAggregationNode.getSource();
+            ConnectorTableMetadata connectorTableMetadata = metadataFactory.get().getTableMetadata(session, tableScanNode.getTable().getConnectorHandle());
+            Optional<Object> rawFormat = Optional.ofNullable(connectorTableMetadata.getProperties().get(HiveTableProperties.STORAGE_FORMAT_PROPERTY));
+            if (!rawFormat.isPresent()) {
+                return false;
+            }
+
+            final HiveStorageFormat hiveStorageFormat = HiveStorageFormat.valueOf(rawFormat.get().toString());
+            if (hiveStorageFormat != HiveStorageFormat.ORC && hiveStorageFormat != HiveStorageFormat.PARQUET) {
```
Comment (zhenxiao) [inline presto-hive/src/main/java/com/facebook/presto/hive/HivePartialAggregationPushdown.java:139]: static import ORC and PARQUET

File: presto-hive/src/main/java/com/facebook/presto/hive/orc/AggregatedOrcPageSource.java [hunk 3]
```diff
@@ -138,13 +138,14 @@ private void writeMinMax(int columnIndex, Type type, HiveType hiveType, BlockBui
             completedBytes += ((FixedWidthType) type).getFixedSize();
         }
 
+        String noMinMaxMessage = "No min/max found for orc file. Set session property hive.pushdown_partial_aggregations_into_scan=false and execute query again";
```
Comment (zhenxiao) [inline presto-hive/src/main/java/com/facebook/presto/hive/orc/AggregatedOrcPageSource.java:141]: s/noMinMaxMessage/OrcNoMinMaxMessage/g

File: presto-hive/src/test/java/com/facebook/presto/hive/TestHivePushdownFilterQueries.java [hunk 4]
```diff
@@ -1034,7 +1039,8 @@ private void assertFileFormat(HiveStorageFormat storageFormat)
             // no filter
             assertQueryUsingH2Cte("SELECT * FROM test_file_format_orc", cte);
             assertQueryUsingH2Cte("SELECT comment FROM test_file_format_orc", cte);
-            assertQueryUsingH2Cte("SELECT COUNT(*) FROM test_file_format_orc", cte);
+            assertQueryFails("SELECT COUNT(*) FROM test_file_format_orc", "Partial aggregation pushdown only supported for ORC/Parquet files. Set session property hive.pushdown_partial_aggregations_into_scan=false and execute query again");
```
Comment (zhenxiao) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestHivePushdownFilterQueries.java:1042]: test_file_format_orc is Orc table, right? why partial aggregation pushdown now supported?

**Review by zhenxiao — CHANGES_REQUESTED** [review]
nice work, @ClarenceThreepwood 
left some comments.
shall we enable partial aggregation pushdown in TestHivePushdownIntegrationSmokeTest and TestParquetDistributedQueries?

File: presto-hive/src/main/java/com/facebook/presto/hive/HivePageSourceProvider.java (hunk 1 above)
Comment (ClarenceThreepwood) [reply presto-hive/src/main/java/com/facebook/presto/hive/HivePageSourceProvider.java:425]: Either all columns are aggregate or none is. So we just check the first

File: presto-hive/src/test/java/com/facebook/presto/hive/TestHivePushdownFilterQueries.java (hunk 4 above)
Comment (ClarenceThreepwood) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestHivePushdownFilterQueries.java:1042]: The table is defined as orc - but the files are in RC or text. Surprisingly Presto supports this use case - but we cannot perform partial agg pushdown on all formats so we throw an error here

File: presto-hive/src/main/java/com/facebook/presto/hive/HivePageSourceProvider.java (hunk 1 above)
Comment (zhenxiao) [reply presto-hive/src/main/java/com/facebook/presto/hive/HivePageSourceProvider.java:425]: get it. shall we use allMatch to make sure all are AGGREGATED?
I think we also need to update the message

File: presto-hive/src/main/java/com/facebook/presto/hive/rcfile/RcFilePageSourceFactory.java [hunk 5]
```diff
@@ -110,6 +111,10 @@ public RcFilePageSourceFactory(TypeManager typeManager, HdfsEnvironment hdfsEnvi
             HiveFileContext hiveFileContext,
             Optional<EncryptionInformation> encryptionInformation)
     {
+        if (!columns.isEmpty() && columns.get(0).getColumnType() == AGGREGATED) {
```
Comment (zhenxiao) [inline presto-hive/src/main/java/com/facebook/presto/hive/rcfile/RcFilePageSourceFactory.java:114]: same

File: presto-hive/src/test/java/com/facebook/presto/hive/TestHivePushdownFilterQueries.java (hunk 4 above)
Comment (zhenxiao) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestHivePushdownFilterQueries.java:1042]: ah... maybe add a comment, describe the case?

**Review by zhenxiao — CHANGES_REQUESTED** [review]
thank you, @ClarenceThreepwood 
a few more comments :)

File: presto-hive/src/main/java/com/facebook/presto/hive/HivePageSourceProvider.java (hunk 1 above)
Comment (ClarenceThreepwood) [reply presto-hive/src/main/java/com/facebook/presto/hive/HivePageSourceProvider.java]: Converted to allMatch. What is your suggestion for error message? It reads ok to me

File: presto-hive/src/main/java/com/facebook/presto/hive/HivePageSourceProvider.java [hunk 6]
```diff
@@ -422,6 +422,10 @@ protected static CacheQuota generateCacheQuota(HiveSplit hiveSplit)
             }
         }
 
+        if (!hiveColumns.isEmpty() && hiveColumns.stream().allMatch(hiveColumnHandle -> hiveColumnHandle.getColumnType() == AGGREGATED)) {
```
Comment (zhenxiao) [inline presto-hive/src/main/java/com/facebook/presto/hive/HivePageSourceProvider.java:425]: if all column handles are AGGREGATED, we should not enter HivePageSourceProvider, right?
How about use checkState, with error message like:
`Invalid processing state. Partial aggregation should be processed in AggregatedParquetPageSource or AggregatedOrcPageSource`

**Review by zhenxiao — APPROVED** [review]
hi @ClarenceThreepwood mostly good. just one minor thing

File: presto-hive/src/main/java/com/facebook/presto/hive/HivePageSourceProvider.java (hunk 6 above)
Comment (ClarenceThreepwood) [reply presto-hive/src/main/java/com/facebook/presto/hive/HivePageSourceProvider.java:425]: Right - this error can happen when the metadata defines the table as orc/parquet, but there is at least one file that is in text/rc format. This is potentially a user-facing error message and I wouldn't expect a user to know about AggregatedParquetPageSource or AggregatedOrcPageSource. IMO it makes more sense to point out that the file format here is not supported and suggest one way to work around this. Let me know if you disagree

Comment (zhenxiao) [reply presto-hive/src/main/java/com/facebook/presto/hive/HivePageSourceProvider.java:425]: get it. how about some error message like:
`table $table input format is: $inputformat, but this file is: $filetype`

**Review by zhenxiao — APPROVED** [review]
