### PR TITLE
Fix CSE compilation error for duplicate expressions

### LINKED ISSUE #18098: CSE crashes with dupe key errors
Following query gives compile failure looks like somehow it's thinking there are duplicate keys while doing CES:

```
      SELECT
                  FILTER(
                      MAP_VALUES(map1),
                      x -> x >= ELEMENT_AT(
                              MAP(ARRAY['low','medium','high'], ARRAY[40000,40000,40000]),
                              COALESCE(
                                  ELEMENT_AT(
                                     other_map,
                                      name
                                  ),
                                  'low'
                              )
                          )
                  ) AS v1,
                  FILTER(
                      MAP_VALUES(map1),
                      x -> x >= ELEMENT_AT(
                              MAP(ARRAY['low','medium','high'], ARRAY[40000,40000,40000]),
                              COALESCE(
                                  ELEMENT_AT(
                                     other_map,
                                      name
                                  ),
                                  'low'
                              )
                          )
          ) AS v2
      FROM (select map() map1, '' name)
      CROSS JOIN (
          SELECT
              MAP() AS other_map
      ) risk_map
      ```

CC: @rongrong

### PR DESCRIPTION
**Pull request by feilong-liu**
## what does it fix?
fix #18098 

The CSE implementation assumes that there is no duplicate expressions in projection. While this generally holds true, in some corner cases (for example issue #18098) it's not. While we have another PR #18159 fixing the duplicate keys part in the planner side, it's also good to break this dependency in the CSE side.

In this PR, I add an additional check to see if we have duplicate expressions, if yes, just skip this one for CSE optimization. 

For projections with no duplicate expressions, this PR will behave the same. For projections with duplicate expressions, we will hit compilation error in current version and forced to disable CSE optimization, while with this PR, we can still do CSE for other expressions.

## test
Add unit test. Also test e2e locally.

Existing CSE tests in `TestPageFunctionCompiler.java` make sure the trigger and correctness of CSE optimization for cases without duplicates stays the same. I also added an additional test `testCommonSubExpressionDuplicatesInProjection` to make sure with this PR we will not fail due to duplicates.
An end to end test with the SQL query in the issue is added in `AbstractTestQueries.java` to make sure the issue is fixed.

**The failing test native / build-and-test (pull_request) is unrelated to this PR, and is not required from offline discussion. This diff is ready for review.**

```
== RELEASE NOTES ==

General Changes
* Fix compilation error for common sub expression optimization when there are duplicate expressions in projection node
```

### CODE REVIEW

**Comment by kaikalur** [comment]
This looks good! Since a) this is anyway just an optimization and b) it will anyway throw dupe key error further down, it's best to just ignore this case.

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestDistributedQueries.java [hunk 1]
```diff
@@ -1153,4 +1154,19 @@ public void testComplexCast()
                         "SELECT count(DISTINCT a), CAST(max(b) AS VARCHAR) FROM t",
                 "VALUES (1, '0 00:00:01.000')");
     }
+
+    @Test
+    public void testCSECompilation()
```
Comment (rschlussel) [inline presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestDistributedQueries.java:1159]: Is there a reason this is in AbstractTestDistributedQueries rather than AbstractTestQueries?

File: presto-main/src/main/java/com/facebook/presto/sql/gen/PageFunctionCompiler.java [hunk 2]
```diff
@@ -201,13 +203,15 @@ public List<Supplier<PageProjectionWithOutputs>> compileProjections(
         if (isOptimizeCommonSubExpression) {
             ImmutableList.Builder<Supplier<PageProjectionWithOutputs>> pageProjections = ImmutableList.builder();
             ImmutableMap.Builder<RowExpression, Integer> expressionsWithPositionBuilder = ImmutableMap.builder();
+            Set<RowExpression> expressionCandidates = new HashSet<>();
             for (int i = 0; i < projections.size(); i++) {
                 RowExpression projection = projections.get(i);
-                if (projection instanceof ConstantExpression || projection instanceof InputReferenceExpression) {
+                if (projection instanceof ConstantExpression || projection instanceof InputReferenceExpression || expressionCandidates.contains(projection)) {
```
Comment (rschlussel) [inline presto-main/src/main/java/com/facebook/presto/sql/gen/PageFunctionCompiler.java:209]: Can you add a comment about why we exclude duplicate projections?

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestDistributedQueries.java [hunk 3]
```diff
@@ -1153,4 +1154,19 @@ public void testComplexCast()
...
+    {
+        String sql = "SELECT " +
+                "FILTER( MAP_VALUES(map1), x -> x >= ELEMENT_AT( MAP(ARRAY['low','medium','high'], ARRAY[40000,40000,40000]), COALESCE( ELEMENT_AT( other_map, name ), 'low' ) ) ) AS v1, " +
+                "FILTER( MAP_VALUES(map1), x -> x >= ELEMENT_AT( MAP(ARRAY['low','medium','high'], ARRAY[40000,40000,40000]), COALESCE( ELEMENT_AT( other_map, name ), 'low' ) ) ) AS v2 " +
+                "FROM (select map() map1, '' name) CROSS JOIN ( SELECT MAP() AS other_map ) risk_map";
+        try {
+            computeActual(sql);
```
Comment (rschlussel) [inline presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestDistributedQueries.java:1166]: Can you do a query assert instead to also check the results are correct?  No need for try/catch, as the test will fail if it encounters an exception.

File: presto-main/src/test/java/com/facebook/presto/sql/gen/TestPageFunctionCompiler.java [hunk 4]
```diff
@@ -197,6 +197,18 @@ public void testCommonSubExpressionInProjection()
         checkBlockEqual(cseResult.get(1), noCseResult2.get(0));
     }
 
+    @Test
+    public void testCommonSubExpressionDuplicatesInProjection()
+    {
+        PageFunctionCompiler functionCompiler = new PageFunctionCompiler(createTestMetadataManager(), 0);
+        try {
+            functionCompiler.compileProjections(SESSION.getSqlFunctionProperties(), ImmutableList.of(ADD_X_Y, ADD_X_Y), true, Optional.empty());
```
Comment (rschlussel) [inline presto-main/src/test/java/com/facebook/presto/sql/gen/TestPageFunctionCompiler.java:205]: Can we check for specific results as well (correctness)?

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestDistributedQueries.java (hunk 1 above)
Comment (feilong-liu) [reply presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestDistributedQueries.java]: No specific reason, moved it to AbstractTestQueries.

File: presto-main/src/main/java/com/facebook/presto/sql/gen/PageFunctionCompiler.java (hunk 2 above)
Comment (feilong-liu) [reply presto-main/src/main/java/com/facebook/presto/sql/gen/PageFunctionCompiler.java:210]: Done.

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestDistributedQueries.java (hunk 3 above)
Comment (feilong-liu) [reply presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestDistributedQueries.java]: Done.

File: presto-main/src/test/java/com/facebook/presto/sql/gen/TestPageFunctionCompiler.java (hunk 4 above)
Comment (feilong-liu) [reply presto-main/src/test/java/com/facebook/presto/sql/gen/TestPageFunctionCompiler.java]: Done.

**Comment by feilong-liu** [comment]
@rschlussel Addressed comments and added release notes. The PR is ready for review.

File: presto-main/src/main/java/com/facebook/presto/sql/gen/PageFunctionCompiler.java (hunk 2 above)
Comment (pranjalssh) [reply presto-main/src/main/java/com/facebook/presto/sql/gen/PageFunctionCompiler.java:210]: Instead of just commenting what it will do, can you also comment the intent that we don't do CSE for duplicate expressions? How hard it is to do CSE in case of duplicate expressions as well?

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java [hunk 5]
```diff
@@ -6055,4 +6055,17 @@ public void testSourceLocationInPlan()
...
     }
+
+    @Test
+    public void testCSECompilation()
+    {
+        String sql = "SELECT " +
+                "FILTER( MAP_VALUES(map1), x -> x >= ELEMENT_AT( MAP(ARRAY['low','medium','high'], ARRAY[40000,40000,40000]), COALESCE( ELEMENT_AT( other_map, name ), 'low' ) ) ) AS v1, " +
+                "FILTER( MAP_VALUES(map1), x -> x >= ELEMENT_AT( MAP(ARRAY['low','medium','high'], ARRAY[40000,40000,40000]), COALESCE( ELEMENT_AT( other_map, name ), 'low' ) ) ) AS v2 " +
+                "FROM (select MAP(ARRAY['low'], ARRAY[100000]) map1, '' name) CROSS JOIN ( SELECT MAP() AS other_map ) risk_map";
+        MaterializedResult result = computeActual(sql);
```
Comment (rschlussel) [inline presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java:6066]: you should be able to call AbstractTestQueryFramework.assertQuery(sql), and it will run in presto and H2 and compare the results.  Or if it's not supported in H2 you can do assertQuery(testQuery, expectedResultsQuery), and for the expected results Query do a simple SELECT with no from or SELECT FROM values

File: presto-main/src/main/java/com/facebook/presto/sql/gen/PageFunctionCompiler.java (hunk 2 above)
Comment (feilong-liu) [reply presto-main/src/main/java/com/facebook/presto/sql/gen/PageFunctionCompiler.java:210]: > Instead of just commenting what it will do, can you also comment the intent that we don't do CSE for duplicate expressions? 

I'm not sure but my guess is that it's just a rare corner case which is not considered during implementation. There is no particular reason why it's intrinsically hard to implement.

> How hard it is to do CSE in case of duplicate expressions as well?

I think the biggest challenge is that we need to refactor the CSE code a bit. Consider that this case is rare (we hit this single issue until now), refactor the code looks like not a good tradeoff.

File: presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java (hunk 5 above)
Comment (feilong-liu) [reply presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java]: Done, changed the check code to `assertQuery(sql, "VALUES (100000, 100000)");`

File: presto-main/src/main/java/com/facebook/presto/sql/gen/PageFunctionCompiler.java (hunk 2 above)
Comment (pranjalssh) [reply presto-main/src/main/java/com/facebook/presto/sql/gen/PageFunctionCompiler.java:210]: @feilong-liu can you update the comment to: 

`Duplicate expressions are not expected here in general due to <...>, hence we skip CSE for them to allow for a simpler implementation`

**Review by pranjalssh — APPROVED** [review]

File: presto-main/src/main/java/com/facebook/presto/sql/gen/PageFunctionCompiler.java (hunk 2 above)
Comment (feilong-liu) [reply presto-main/src/main/java/com/facebook/presto/sql/gen/PageFunctionCompiler.java:211]: Updated the comments.

**Review by rschlussel — APPROVED** [review]
