### PR TITLE
Fix geometry_to_bing_tiles function for geometry collections

### LINKED ISSUE #10623: geometry_to_bing_tiles on Geometry Collection fails with NullPointerException
```
presto> select geometry_to_bing_tiles(ST_GeometryFromText('GEOMETRYCOLLECTION (POINT (1 1), POINT (2 2))'), 14);
Query 20180517_003111_02066_p8fjg failed: null
java.lang.NullPointerException
        at com.facebook.presto.plugin.geospatial.BingTileFunctions.geometryToBingTiles(BingTileFunctions.java:187)
```

See https://github.com/Esri/geometry-api-java/issues/176 for a similar problem in the underlying library.

### PR DESCRIPTION
**Pull request by mbasmanova**
Fix NPE in geometry_to_bing_tiles function when input is a geometry collection.

Fixes #10623

### CODE REVIEW

File: presto-geospatial/src/test/java/com/facebook/presto/plugin/geospatial/TestBingTileFunctions.java [hunk 1]
```diff
@@ -338,6 +338,11 @@ public void testGeometryToBingTiles()
         assertFunction("cardinality(geometry_to_bing_tiles(ST_GeometryFromText('POLYGON ((0 0, 0 20, 20 20, 0 0))'), 14))", BIGINT, 428787L);
     }
 
+    private void assertGeometryToBingTiles(String wkt, int zoomLevel, List<String> expectedQuadKeys)
+    {
+        assertFunction("transform(geometry_to_bing_tiles(ST_GeometryFromText('"  + wkt +"'), " + zoomLevel + "), x -> bing_tile_quadkey(x))", new ArrayType(VARCHAR), expectedQuadKeys);
```
Comment (arhimondr) [inline presto-geospatial/src/test/java/com/facebook/presto/plugin/geospatial/TestBingTileFunctions.java]: Use `String.format()` for better readability.

File: presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/BingTileFunctions.java [hunk 2]
```diff
@@ -374,21 +419,35 @@ private static void writeTilesToBlockBuilder(
...
+            if (geometry.isEmpty()) {
+                continue;
+            }
 
-        return ((MultiVertexGeometry) geometry).getPointCount();
+            if (geometry instanceof Point) {
+                points++;
+            }
+            else {
+                points += ((MultiVertexGeometry) geometry).getPointCount();
```
Comment (arhimondr) [inline presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/BingTileFunctions.java]: It can also be a `Segment` (`Line`)

File: presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/BingTileFunctions.java [hunk 3]
```diff
@@ -256,13 +255,59 @@ public static Block geometryToBingTiles(@SqlType(GEOMETRY_TYPE_NAME) Slice input
             // tile covered by the geometry.
             BingTile[] tiles = getTilesInBetween(leftUpperTile, rightLowerTile, OPTIMIZED_TILING_MIN_ZOOM_LEVEL);
```
[the remark this answers is not in the document]
Comment (mbasmanova) [reply presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/BingTileFunctions.java]: @arhimondr I like your other suggestion `s/writeTilesToBlockBuilder/appendIntersectingSubtiles/`, but I'm not sure about this one. Here, we are not looking for intersecting tiles, but rather a set of sub-tiles covering some larger tiles. One can think about this function as 2d version of `sequence(start, stop, step)` where start is a tile in one corner, stop is a tile in the opposite corner and step is zoom level. Perhaps, `s/getTilesInBetween/tilesSequence`?

[the remark this answers is not in the document]
Comment (arhimondr) [reply presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/BingTileFunctions.java]: The name of the method is fine. I was talking about the variable name. But even so, i don't have a strong opinion here.

File: presto-geospatial-toolkit/src/main/java/com/facebook/presto/geospatial/GeometryUtils.java [hunk 4]
```diff
@@ -42,4 +58,111 @@ public static boolean isEsriNaN(double d)
...
+            }
+
+            if (GeometryEngine.contains(geometry, envelope, null)) {
+                return true;
+            }
+        }
+    }
+
+    /**
+     * @return true if the geometry is a point or a rectangle
```
Comment (arhimondr) [inline presto-geospatial-toolkit/src/main/java/com/facebook/presto/geospatial/GeometryUtils.java]: Image of Yaktocat

Comment (arhimondr) [inline presto-geospatial-toolkit/src/main/java/com/facebook/presto/geospatial/GeometryUtils.java]: remove this

File: presto-geospatial-toolkit/src/main/java/com/facebook/presto/geospatial/GeometryUtils.java [hunk 5]
```diff
@@ -42,4 +58,111 @@ public static boolean isEsriNaN(double d)
...
+
+            if (geometry.isEmpty()) {
+                continue;
+            }
+
+            if (geometry instanceof Point) {
+                points++;
+            }
+            else {
+                points += ((MultiVertexGeometry) geometry).getPointCount();
```
Comment (arhimondr) [inline presto-geospatial-toolkit/src/main/java/com/facebook/presto/geospatial/GeometryUtils.java]: I checked type hierarchy. It is not always `MultiVertexGeometry` if it is not a `Point`. It could be `Line` for example.
