### PR TITLE
Tighten show stats

### LINKED ISSUE #11551: Tighten SHOW STATS command
As a follow-up to #11496, let's make the following changes:

* Remove SHOW STATS ON syntax
* Disallow anything other than * in the list of columns, e.g. SHOW STATS FOR (SELECT * FROM t) is allowed, but SHOW STATS FOR (SELECT c1, c2, c3 FROM t) is not.
* Fail the command if any of the filters can't be fully pushed down.

CC: @findepi @kokosing

### PR DESCRIPTION
**Pull request by viczhang861**
Fixes #11551

- Deprecate on keyword in SHOW STATS ON table

 - No longer support SELECT columns clause, only SELECT * is allowed, e.g., SHOW STATS FOR (SELECT * FROM t)

 - Columns in WHERE clause must be enforced columns, e.g., Hive partition columns

### CODE REVIEW

File: presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java [hunk 1]
```diff
@@ -169,6 +169,14 @@ private void validateShowStats(ShowStats node)
                 check(query.getQueryBody() instanceof QuerySpecification, node, "Only table and simple table subquery can be passed as argument to SHOW STATS clause");
                 QuerySpecification querySpecification = (QuerySpecification) query.getQueryBody();
 
+                Plan plan = queryExplainer.get().getLogicalPlan(session, new Query(Optional.empty(), querySpecification, Optional.empty(), Optional.empty()), parameters);
```
Comment (mbasmanova) [inline presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java]: This logic is duplicated in `getConstraint`. Consider refactoring this code a bit to avoid that duplication. Specifically, `validateShowStats` is needed only if `node.getRelation() instanceof TableSubquery`. So, you could do something like:

```
if (node.getRelation() instanceof TableSubquery) {

    Plan plan = ...
    validate(...plan);
     ...getConstraint(...plan...)
}
```

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java [hunk 2]
```diff
@@ -106,6 +106,22 @@ public void testShowStats()
                         "   (null, null, null, null, 5.0, null, null))");
     }
 
+    @Test
+    public void testShowStatsNotSelecAllColumns()
```
Comment (mbasmanova) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: typo: `testShowStatsNotSelectAllColumns`, or, perhaps, `testShowStatsNotSelectStarFails`

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java [hunk 3]
```diff
@@ -106,6 +106,22 @@ public void testShowStats()
...
+    {
+        assertQueryFails("SHOW STATS FOR (SELECT nationkey FROM nation_partitioned)", ".*Only SELECT \\* is supported in SHOW STATS SELECT clause");
+    }
+
+    @Test
+    public void testShowStatsWhereClause()
```
Comment (mbasmanova) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: nit: testShowStatsWithNonPushDownFilterFails

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java [hunk 4]
```diff
@@ -106,6 +106,22 @@ public void testShowStats()
                         "   (null, null, null, null, 5.0, null, null))");
     }
 
+    @Test
+    public void testShowStatsNotSelecAllColumns()
+    {
+        assertQueryFails("SHOW STATS FOR (SELECT nationkey FROM nation_partitioned)", ".*Only SELECT \\* is supported in SHOW STATS SELECT clause");
```
Comment (mbasmanova) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: s/nation_partitioned/nation

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java [hunk 5]
```diff
@@ -106,6 +106,22 @@ public void testShowStats()
...
+    }
+
+    @Test
+    public void testShowStatsWhereClause()
+    {
+        assertQueryFails("SHOW STATS FOR (SELECT nationkey FROM nation_partitioned WHERE nationkey > 0)", ".*Only columns that can be pushed down are supported in SHOW STATS WHERE clause");
```
Comment (mbasmanova) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: s/nation_partitioned/nation

File: presto-parser/src/main/antlr4/com/facebook/presto/sql/parser/SqlBase.g4 [hunk 6]
```diff
@@ -79,7 +79,7 @@ statement
         (LIKE pattern=string (ESCAPE escape=string)?)?                 #showSchemas
     | SHOW CATALOGS (LIKE pattern=string)?                             #showCatalogs
     | SHOW COLUMNS (FROM | IN) qualifiedName                           #showColumns
-    | SHOW STATS (FOR | ON) qualifiedName                              #showStats
+    | SHOW STATS FOR qualifiedName                                     #showStats
```
Comment (mbasmanova) [inline presto-parser/src/main/antlr4/com/facebook/presto/sql/parser/SqlBase.g4]: Could you move this into a separate commit?

File: presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java [hunk 7]
```diff
@@ -178,12 +186,7 @@ private void validateShowStats(ShowStats node)
                 check(!querySpecification.getGroupBy().isPresent(), node, "GROUP BY is not supported in SHOW STATS SELECT clause");
                 check(!querySpecification.getSelect().isDistinct(), node, "DISTINCT is not supported by SHOW STATS SELECT clause");
                 for (SelectItem selectItem : querySpecification.getSelect().getSelectItems()) {
-                    if (selectItem instanceof AllColumns) {
-                        continue;
-                    }
-                    check(selectItem instanceof SingleColumn, node, "Only * and column references are supported by SHOW STATS SELECT clause");
-                    SingleColumn columnSelect = (SingleColumn) selectItem;
-                    check(columnSelect.getExpression() instanceof Identifier, node, "Only * and column references are supported by SHOW STATS SELECT clause");
+                    check(selectItem instanceof AllColumns, node, "Only SELECT * is supported in SHOW STATS SELECT clause");
```
Comment (mbasmanova) [inline presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java]: Could you move this into a separate commit?

File: presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java (hunk 1 above)
Comment (picrinite) [reply presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java]: I initially tried this and pass plan around,  but I am not sure it is good to pass plan into validateShowStats, good to know "validateShowStats is needed for subquery".

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java [hunk 8]
```diff
@@ -106,6 +106,22 @@ public void testShowStats()
...
+
+        assertQueryFails("SHOW STATS FOR (SELECT nationkey FROM nation_partitioned WHERE regionkey > 0 and nationkey > 0)", ".*Only columns that can be pushed down are supported in SHOW STATS WHERE clause");
+
+        assertQueryFails("SHOW STATS FOR (SELECT nationkey FROM nation_partitioned WHERE nationkey = 1 and name is not null)", ".*Only columns that can be pushed down are supported in SHOW STATS WHERE clause");
```
Comment (rschlussel) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: what's this query testing that's different from the one above?

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java (hunk 3 above)
Comment (rschlussel) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: can you add a test query that only uses the partitioning key, but the filter still can't be pushed down because it contains some complex expression or an `or` expression?

File: presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java [hunk 9]
```diff
@@ -169,6 +169,14 @@ private void validateShowStats(ShowStats node)
                 check(query.getQueryBody() instanceof QuerySpecification, node, "Only table and simple table subquery can be passed as argument to SHOW STATS clause");
                 QuerySpecification querySpecification = (QuerySpecification) query.getQueryBody();
 
+                Plan plan = queryExplainer.get().getLogicalPlan(session, new Query(Optional.empty(), querySpecification, Optional.empty(), Optional.empty()), parameters);
+
+                Optional<FilterNode> filterNode = searchFrom(plan.getRoot())
+                        .where(FilterNode.class::isInstance)
+                        .findSingle();
+
+                check(!filterNode.isPresent(), node, "Only columns that can be pushed down are supported in SHOW STATS WHERE clause");
```
Comment (rschlussel) [inline presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java]: Change the message to say `Only predicates that can be pushed down are supported in the SHOW STATS WHERE clause`

**Comment by picrinite** [comment]
Resubmit to separate it to two commits
1. Deprecate SHOW STATS ON and support only SELECT * 
2. Only support predicate that can be pushed down

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java (hunk 8 above)
Comment (picrinite) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: This previous test case has one partition column and one non-partition column, this one has two non-partition columns.

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java [hunk 10]
```diff
@@ -27,12 +29,22 @@ public TestShowStats()
...
-    @Test
-    public void testShowStats()
+    @BeforeClass
+    public void setUp()
     {
         assertUpdate("CREATE TABLE nation_partitioned(nationkey BIGINT, name VARCHAR, comment VARCHAR, regionkey BIGINT) WITH (partitioned_by = ARRAY['regionkey'])");
         assertUpdate("INSERT INTO nation_partitioned SELECT nationkey, name, comment, regionkey from tpch.tiny.nation", 25);
+    }
 
+    @AfterClass(alwaysRun = true)
```
Comment (arhimondr) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: I don't think it is needed. The entire query runner will be killed after all the test cases from this class are ran

**Comment by arhimondr** [comment]
@picrinite Did you loose some of the commits? Now there's only a single commit in the PR, the one that limits SELECT clause. Are you going to open a separate PR for the remaining parts?

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java (hunk 10 above)
Comment (picrinite) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: Thanks, Do you mean tearDown() is not needed, or 'alwaysRun = true' is not needed ?

I was working the second diff, it is now pushed.

Comment (arhimondr) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: I think teadDown is not needed

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java [hunk 11]
```diff
@@ -33,15 +33,10 @@ public TestShowStats()
     public void setUp()
     {
         assertUpdate("CREATE TABLE nation_partitioned(nationkey BIGINT, name VARCHAR, comment VARCHAR, regionkey BIGINT) WITH (partitioned_by = ARRAY['regionkey'])");
+        assertUpdate("CREATE TABLE orders(orderkey BIGINT, totalprice BIGINT, categoryid BIGINT) WITH (partitioned_by = ARRAY['categoryid'])");
```
Comment (arhimondr) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: Why do we need this table? Can we use non partitioned nation?

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java [hunk 12]
```diff
@@ -127,25 +122,25 @@ public void testShowStatsWithoutFromFails()
     @Test
     public void testShowStatsWithMultipleFromFails()
     {
-        assertQueryFails("SHOW STATS FOR (SELECT * FROM orders, lineitem)", ".*There must be exactly one table in query passed to SHOW STATS SELECT clause");
+        assertQueryFails("SHOW STATS FOR (SELECT * FROM orders, nation_partitioned)", ".*There must be exactly one table in query passed to SHOW STATS SELECT clause");
```
Comment (arhimondr) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: Why this change?

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java [hunk 13]
```diff
@@ -127,25 +122,25 @@ public void testShowStatsWithoutFromFails()
...
     }
 
     @Test
     public void testShowStatsWithGroupByFails()
     {
-        assertQueryFails("SHOW STATS FOR (SELECT * FROM orders GROUP BY clerk)", ".*GROUP BY is not supported in SHOW STATS SELECT clause");
+        assertQueryFails("SHOW STATS FOR (SELECT * FROM orders GROUP BY orderkey, totalprice, categoryid)", ".*GROUP BY is not supported in SHOW STATS SELECT clause");
```
Comment (arhimondr) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: Why this change?

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java [hunk 14]
```diff
@@ -127,25 +122,25 @@ public void testShowStatsWithoutFromFails()
...
     }
 
     @Test
     public void testShowStatsWithHavingFails()
     {
-        assertQueryFails("SHOW STATS FOR (SELECT * FROM orders HAVING avg(orderkey) < 5)", ".*HAVING is not supported in SHOW STATS SELECT clause");
+        assertQueryFails("SHOW STATS FOR (SELECT categoryid FROM orders GROUP BY categoryid HAVING categoryid < 5)", ".*HAVING is not supported in SHOW STATS SELECT clause");
```
Comment (arhimondr) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: Why this change?

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java [hunk 15]
```diff
@@ -127,25 +122,25 @@ public void testShowStatsWithoutFromFails()
...
     }
 
     @Test
     public void testShowStatsSelectNonStarFails()
     {
-        assertQueryFails("SHOW STATS FOR (SELECT nationkey FROM nation)", ".*Only SELECT \\* is supported in SHOW STATS SELECT clause");
+        assertQueryFails("SHOW STATS FOR (SELECT nationkey FROM nation_partitioned)", ".*Only SELECT \\* is supported in SHOW STATS SELECT clause");
```
Comment (arhimondr) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: Why this change?

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java [hunk 16]
```diff
@@ -166,4 +161,19 @@ public void testShowStatsWithWhereFunctionCallFails()
...
+    @Test
+    public void testShowStatsWithNonPushDownFilterFails()
+    {
+        assertQueryFails("SHOW STATS FOR (SELECT * FROM nation_partitioned WHERE regionkey + 100 < 200)", ".*Only predicates that can be pushed down are supported in the SHOW STATS WHERE clause");
+        assertQueryFails("SHOW STATS FOR (SELECT * FROM nation_partitioned WHERE regionkey > 0 and nationkey > 0)", ".*Only predicates that can be pushed down are supported in the SHOW STATS WHERE clause");
+        assertQueryFails("SHOW STATS FOR (SELECT * FROM nation_partitioned WHERE nationkey = 1 and name is not null)", ".*Only predicates that can be pushed down are supported in the SHOW STATS WHERE clause");
+    }
+
+    @AfterClass(alwaysRun = true)
+    public void tearDown()
```
Comment (arhimondr) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: Remove this method

File: presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java [hunk 17]
```diff
@@ -132,13 +133,14 @@ public Visitor(Metadata metadata, Session session, List<Expression> parameters,
         @Override
         protected Node visitShowStats(ShowStats node, Void context)
         {
-            validateShowStats(node);
             checkState(queryExplainer.isPresent(), "Query explainer must be provided for SHOW STATS SELECT");
 
             if (node.getRelation() instanceof TableSubquery) {
                 QuerySpecification specification = (QuerySpecification) ((TableSubquery) node.getRelation()).getQuery().getQueryBody();
+                Plan plan = queryExplainer.get().getLogicalPlan(session, new Query(Optional.empty(), specification, Optional.empty(), Optional.empty()), parameters);
```
Comment (arhimondr) [inline presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java]: Why did you pull it up here? You can do this check directly in the `getConstraint`, so you don't have to change `validate` and don't need to extract plan here

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java (hunk 12 above)
Comment (picrinite) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: We need two tables to test testShowStatsWithMultipleFromFails()

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java (hunk 16 above)
Comment (picrinite) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: Got it.

File: presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java (hunk 17 above)
Comment (picrinite) [reply presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java]: By pulling it up here,  plan can be reused in both function validateShowStats and getConstraint,  as suggested by @mbasmanova

Comment (picrinite) [reply presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java]: Because of this change,  QuerySpecification is executed before validateShowStats,  which requires a real table 'orders' to parse it successfully.  

Before this diff,  validateShowStats is executed first, thus it is OK to have a non-existing table before hitting an error.

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java (hunk 13 above)
Comment (picrinite) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: Explained below

**Comment by mbasmanova** [comment]
@picrinite Vic, please split this change into multiple commits, so one commit is changing only one thing.

- Drop SHOW STATS ON syntax
- Enforce SELECT *
- Refactor TestShowStats test
- Rejects predicates that cannot be pushed down

**Comment by picrinite** [comment]
@mbasmanova "Refactor TestShowStatsTest" and "Enforce SELECT *" are interleaved,  can I combine these two to a single commit ?

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java (hunk 11 above)
Comment (mbasmanova) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: @picrinite Vic, what's the answer here? Why do you need `orders` table?

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java [hunk 18]
```diff
@@ -120,19 +121,19 @@ public void testShowStatsWithoutFromFails()
...
     {
-        assertQueryFails("SHOW STATS FOR (SELECT * FROM orders, lineitem)", ".*There must be exactly one table in query passed to SHOW STATS SELECT clause");
+        assertQueryFails("SHOW STATS FOR (SELECT * FROM orders, nation_partitioned)", ".*There must be exactly one table in query passed to SHOW STATS SELECT clause");
     }
 
     @Test
     public void testShowStatsWithGroupByFails()
     {
-        assertQueryFails("SHOW STATS FOR (SELECT avg(totalprice) FROM orders GROUP BY clerk)", ".*GROUP BY is not supported in SHOW STATS SELECT clause");
+        assertQueryFails("SHOW STATS FOR (SELECT avg(totalprice) FROM orders GROUP BY orderkey)", ".*GROUP BY is not supported in SHOW STATS SELECT clause");
```
Comment (mbasmanova) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: unrelated change

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java [hunk 19]
```diff
@@ -120,19 +121,19 @@ public void testShowStatsWithoutFromFails()
...
     }
 
     @Test
     public void testShowStatsWithHavingFails()
     {
-        assertQueryFails("SHOW STATS FOR (SELECT avg(orderkey) FROM orders HAVING avg(orderkey) < 5)", ".*HAVING is not supported in SHOW STATS SELECT clause");
+        assertQueryFails("SHOW STATS FOR (SELECT categoryid FROM orders GROUP BY categoryid HAVING categoryid < 5)", ".*HAVING is not supported in SHOW STATS SELECT clause");
```
Comment (mbasmanova) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: unrelated change

File: presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java [hunk 20]
```diff
@@ -150,12 +152,11 @@ else if (node.getRelation() instanceof Table) {
             }
         }
 
-        private void validateShowStats(ShowStats node)
+        private void validateShowStats(ShowStats node, Plan plan)
```
Comment (mbasmanova) [inline presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java]: `if (node.getRelation() instanceof TableSubquery) {` on L167 is redundant as this method is only called if it is true

File: presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java [hunk 21]
```diff
@@ -168,6 +169,11 @@ private void validateShowStats(ShowStats node)
                 check(query.getQueryBody() instanceof QuerySpecification, node, "Only table and simple table subquery can be passed as argument to SHOW STATS clause");
                 QuerySpecification querySpecification = (QuerySpecification) query.getQueryBody();
 
+                Optional<FilterNode> filterNode = searchFrom(plan.getRoot())
+                        .where(FilterNode.class::isInstance)
+                        .findSingle();
+
+                check(!filterNode.isPresent(), node, "Only predicates that can be pushed down are supported in the SHOW STATS WHERE clause");
```
Comment (mbasmanova) [inline presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java]: Would it make sense to inline all these checks? Or pass `Query` and `QuerySpecification` as arguments to avoid recomputing these?

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java (hunk 19 above)
Comment (picrinite) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: It it related to code refactoring, see answer to @arhimondr 's question "Why did you pull it up here?"

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java (hunk 18 above)
Comment (picrinite) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: see explanation below

File: presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java (hunk 21 above)
Comment (picrinite) [reply presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java]: Agree, we can pass QuerySpecification to avoid duplicated cast

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java [hunk 22]
```diff
@@ -144,12 +152,13 @@ public void testShowStatsWithSelectDistinctFails()
...
-        assertQueryFails("SHOW STATS FOR (SELECT sin(orderkey) FROM orders)", ".*Only \\* and column references are supported by SHOW STATS SELECT clause");
+        assertQueryFails("SHOW STATS FOR (SELECT sin(orderkey) FROM orders)", ".*Only SELECT \\* is supported in SHOW STATS SELECT clause");
+        assertQueryFails("SHOW STATS FOR (SELECT count(*) FROM orders)", ".*Only SELECT \\* is supported in SHOW STATS SELECT clause");
     }
 
     @Test
     public void testShowStatsWithWhereFunctionCallFails()
     {
-        assertQueryFails("SHOW STATS FOR (SELECT orderkey FROM orders WHERE sin(orderkey) > 0)", ".*Only literals, column references, comparators, is \\(not\\) null and logical operators are allowed in WHERE of SHOW STATS SELECT clause");
+        assertQueryFails("SHOW STATS FOR (SELECT * FROM orders WHERE sin(orderkey) > 0)", ".*Only literals, column references, comparators, is \\(not\\) null and logical operators are allowed in WHERE of SHOW STATS SELECT clause");
```
Comment (kokosing) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: do you think we are going to support `SELECT <anything other than *>` in foreseeable future? If not why not change the syntax to: 

```
SHOW STATS FOR orders WHERE sin(orderkey) > 0
```

That is much straightforward and easier. `SELECT` suggests that something may work, while it does not (besides `*`).

Maybe it is another story for followup. What do you think?

CC: @mbasmanova @findepi

File: presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java [hunk 23]
```diff
@@ -150,38 +153,33 @@ else if (node.getRelation() instanceof Table) {
...
+            check(!querySpecification.getGroupBy().isPresent(), node, "GROUP BY is not supported in SHOW STATS SELECT clause");
+            check(!querySpecification.getSelect().isDistinct(), node, "DISTINCT is not supported by SHOW STATS SELECT clause");
+
+            List<SelectItem> selectItems = querySpecification.getSelect().getSelectItems();
+            check(selectItems.size() == 1 && selectItems.get(0) instanceof AllColumns, node, "Only SELECT * is supported in SHOW STATS SELECT clause");
+
+            querySpecification.getWhere().ifPresent((expression) -> validateShowStatsWhereExpression(expression, node));
         }
 
         private void validateShowStatsWhereExpression(Expression expression, ShowStats node)
```
Comment (kokosing) [inline presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java]: I think this method is no longer needed

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java (hunk 22 above)
Comment (mbasmanova) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: @kokosing I'd like to add support for arbitrary queries in SHOW STATS at some point. At a minimum, it would be helpful to support a list of columns. Otherwise, the output for wide tables is hard to consume.

Comment (kokosing) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: Sounds good to me. So we need to make sure that error messages we are raising tell that this is not yet supported.

File: presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java (hunk 23 above)
Comment (picrinite) [reply presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java]: One example use of this function is in #11545, it rejects query "SHOW STATS FOR (SELECT * FROM nation_partitioned WHERE regionkey BETWEEN 1 AND 3+3)".   Suppose  expression "3+3" should be supported, the question becomes "Should we get rid of ALLOWED_SHOW_STATS_WHERE_EXPRESSION_TYPES in ShowStatsRewrite.java?"  @mbasmanova

Comment (mbasmanova) [reply presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java]: @kokosing Grzegorz, why do you think this method is not needed?

File: presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java [hunk 24]
```diff
@@ -132,13 +133,15 @@ public Visitor(Metadata metadata, Session session, List<Expression> parameters,
...
         {
-            validateShowStats(node);
             checkState(queryExplainer.isPresent(), "Query explainer must be provided for SHOW STATS SELECT");
 
             if (node.getRelation() instanceof TableSubquery) {
-                QuerySpecification specification = (QuerySpecification) ((TableSubquery) node.getRelation()).getQuery().getQueryBody();
+                Query query = ((TableSubquery) node.getRelation()).getQuery();
+                QuerySpecification specification = (QuerySpecification) query.getQueryBody();
+                Plan plan = queryExplainer.get().getLogicalPlan(session, new Query(Optional.empty(), specification, Optional.empty(), Optional.empty()), parameters);
+                validateShowStats(node, query, specification, plan);
```
Comment (mbasmanova) [inline presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java]: Now that this method is used only for a subquery, perhaps, it makes sense to rename it to `validateShowStatsSubquery`

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java [hunk 25]
```diff
@@ -32,6 +32,7 @@ public TestShowStats()
     public void setUp()
     {
         assertUpdate("CREATE TABLE nation_partitioned(nationkey BIGINT, name VARCHAR, comment VARCHAR, regionkey BIGINT) WITH (partitioned_by = ARRAY['regionkey'])");
+        assertUpdate("CREATE TABLE orders(orderkey BIGINT, totalprice BIGINT, categoryid BIGINT) WITH (partitioned_by = ARRAY['categoryid'])");
```
Comment (mbasmanova) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: I understand that `orders` needs to be a valid table. However, this table is partitioned, but the name doesn't have `_partitioned` suffix. Also, orders table comes from TPC-H schema where it has different set of columns. To avoid confusion, let's create `orders` and `lineitem` tables to match TPC-H: `CREATE TABLE orders (LIKE tpch.tiny.orders)` and `CREATE TABLE lineitem (LIKE tpch.tiny.lineitem)`. Also, let's put these statements after `INSERT INTO nation_partitioned` to avoid splitting logic related to `nation_partitioned` table.

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java [hunk 26]
```diff
@@ -120,19 +121,19 @@ public void testShowStatsWithoutFromFails()
     @Test
     public void testShowStatsWithMultipleFromFails()
     {
-        assertQueryFails("SHOW STATS FOR (SELECT * FROM orders, lineitem)", ".*There must be exactly one table in query passed to SHOW STATS SELECT clause");
+        assertQueryFails("SHOW STATS FOR (SELECT * FROM orders, nation_partitioned)", ".*There must be exactly one table in query passed to SHOW STATS SELECT clause");
```
Comment (mbasmanova) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: keep `lineitem`

File: presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java (hunk 23 above)
Comment (kokosing) [reply presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java]: If whole predicate can be pushed down to connector (and there is no `FilterNode` here https://github.com/prestodb/presto/pull/11641/commits/0ae180b1968dc7568d51d32d8632588101b489c8#diff-bba77bbf14976e225b69bac5aa20c899R169), then in my opinion there is no much sense to validate predicate. In case there is something unsupported then it won't be pushed down.

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java (hunk 25 above)
Comment (picrinite) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: Tried "CREATE TABLE orders_partitioned(LIKE tpch.tiny.nation) WITH (partitioned_by = ARRAY['orderstatus'])" ,    but got error: java.lang.RuntimeException: line 1:1: LIKE table across catalogs is not supported

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java (hunk 26 above)
Comment (picrinite) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: This test case only cares the number of tables not the actual schema,  it is OK to use nation_partitioned to avoid creating a new lineitem table only for this single test case.

File: presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java (hunk 23 above)
Comment (mbasmanova) [reply presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java]: @kokosing That's a valid point. Thanks for explaining.

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java (hunk 26 above)
Comment (mbasmanova) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: @picrinite It works to use `orders` and `nation_partitioned`, but it is confusing to a reader. orders goes together with customers and lineitem; nation goes together with region. Let's make sure the queries make sense to a casual reader.

Comment (picrinite) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: Updated to lineitem

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java [hunk 27]
```diff
@@ -27,12 +28,18 @@ public TestShowStats()
...
     }
 
-    @Test
-    public void testShowStats()
+    @BeforeClass
+    public void setUp()
     {
         assertUpdate("CREATE TABLE nation_partitioned(nationkey BIGINT, name VARCHAR, comment VARCHAR, regionkey BIGINT) WITH (partitioned_by = ARRAY['regionkey'])");
         assertUpdate("INSERT INTO nation_partitioned SELECT nationkey, name, comment, regionkey from tpch.tiny.nation", 25);
+        assertUpdate("CREATE TABLE orders_partitioned(orderkey BIGINT, totalprice BIGINT, orderstatus BIGINT) WITH (partitioned_by = ARRAY['orderstatus'])");
```
Comment (mbasmanova) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: The schema of `orders` and `lineitem` tables in TPC-H is different.

```
presto:tiny> desc orders;
desc orders;
    Column     |    Type     | Extra | Comment 
---------------+-------------+-------+---------
 orderkey      | bigint      |       |         
 custkey       | bigint      |       |         
 orderstatus   | varchar(1)  |       |         
 totalprice    | double      |       |         
 orderdate     | date        |       |         
 orderpriority | varchar(15) |       |         
 clerk         | varchar(15) |       |         
 shippriority  | integer     |       |         
 comment       | varchar(79) |       |         
(9 rows)

Query 20181017_181406_00002_cjp6j, FINISHED, 4 nodes
Splits: 22 total, 22 done (100.00%)
0:00 [9 rows, 595B] [25 rows/s, 1.61KB/s]

presto:tiny> desc lineitem;
desc lineitem;
    Column     |    Type     | Extra | Comment 
---------------+-------------+-------+---------
 orderkey      | bigint      |       |         
 partkey       | bigint      |       |         
 suppkey       | bigint      |       |         
 linenumber    | integer     |       |         
 quantity      | double      |       |         
 extendedprice | double      |       |         
 discount      | double      |       |         
 tax           | double      |       |         
 returnflag    | varchar(1)  |       |         
 linestatus    | varchar(1)  |       |         
 shipdate      | date        |       |         
 commitdate    | date        |       |         
 receiptdate   | date        |       |         
 shipinstruct  | varchar(25) |       |         
 shipmode      | varchar(10) |       |         
 comment       | varchar(44) |       |         
(16 rows)

Query 20181017_181412_00003_cjp6j, FINISHED, 4 nodes
Splits: 22 total, 22 done (100.00%)
0:00 [16 rows, 1.04KB] [61 rows/s, 4KB/s]

presto:tiny> desc region;
desc region;
  Column   |     Type     | Extra | Comment 
-----------+--------------+-------+---------
 regionkey | bigint       |       |         
 name      | varchar(25)  |       |         
 comment   | varchar(152) |       |         
(3 rows)

Query 20181017_181425_00004_cjp6j, FINISHED, 4 nodes
Splits: 22 total, 22 done (100.00%)
0:00 [3 rows, 196B] [13 rows/s, 896B/s]

presto:tiny> desc nation;
desc nation;
  Column   |     Type     | Extra | Comment 
-----------+--------------+-------+---------
 nationkey | bigint       |       |         
 name      | varchar(25)  |       |         
 regionkey | bigint       |       |         
 comment   | varchar(152) |       |         
(4 rows)

Query 20181017_181429_00005_cjp6j, FINISHED, 4 nodes
Splits: 22 total, 22 done (100.00%)
0:00 [4 rows, 260B] [20 rows/s, 1.27KB/s]
```

Comment (picrinite) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: Thanks, which namespace has tiny schema? (how to activate presto:tiny> )

File: presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java [hunk 28]
```diff
@@ -252,14 +250,12 @@ protected Node visitNode(Node node, Void context)
             return node;
         }
 
-        private Constraint<ColumnHandle> getConstraint(QuerySpecification specification)
+        private Constraint<ColumnHandle> getConstraint(QuerySpecification specification, Plan plan)
         {
             if (!specification.getWhere().isPresent()) {
```
Comment (arhimondr) [inline presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java]: Is this still needed? Remove this check, so you can remove the `specification` parameter.

**Comment by picrinite** [comment]
@arhimondr Thanks for comment, unnecessary getWhere() check in getConstraint() is removed
@kokosing @mbasmanova  WHERE clause operator restriction is removed,  test case is refactored to address this change. Test table is named XX_partitioned only if partition is required in a test, otherwise, don't use table XX_partitioned to make test case simple.

File: presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java [hunk 29]
```diff
@@ -104,6 +112,22 @@ public void testShowStats()
                         "   ('name', 37.0, 5.0, 0.0, null, null, null), " +
                         "   ('comment', 310.0, 5.0, 0.0, null, null, null), " +
                         "   (null, null, null, null, 5.0, null, null))");
+
+        assertQuery("SHOW STATS FOR (SELECT * FROM nation_partitioned WHERE sin(regionkey) > 1)",
```
Comment (mbasmanova) [inline presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: How does this work? Is there some clever logic that detects that `sin` is never `> 1`?

Comment (picrinite) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: I didn't find anything special for sin(), my best guess it that pushing down may have some CBO to evaluate expressions.

Comment (picrinite) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: @mbasmanova It turns out that sin(regionkey) is calculated and this predicate is evaluated for each partition key in test dataset. For the case of "sin(regionkey) > 1",  no partition satisfy the condition. Note that sin() function use radian as unit.  Thanks for tip from @rschlussel

Comment (mbasmanova) [reply presto-hive/src/test/java/com/facebook/presto/hive/TestShowStats.java]: @picrinite Vic, that makes sense, but doesn't explain why `SHOW STATS FOR (SELECT * FROM nation_partitioned WHERE sin(regionkey) > 0)` fails with `Only predicates that can be pushed down are supported in the SHOW STATS WHERE clause`.
