### PR TITLE
Fix flaky test TestQueryManager.testQueryCpuLimit

### LINKED ISSUE #9856: Flaky test TestQueryManager.testQueryCpuLimit
```
[ERROR] Tests run: 2122, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2,134.583 s <<< FAILURE! - in TestSuite
[ERROR] testQueryCpuLimit(com.facebook.presto.tests.TestQueryManager)  Time elapsed: 0.571 s  <<< FAILURE!
org.testng.TestException: 

Method TestQueryManager.testQueryCpuLimit()[pri:0, instance:com.facebook.presto.tests.TestQueryManager@f9d87b] should have thrown an exception of type class java.lang.RuntimeException
```

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
We now run a query that will run for a longer time to give more time to the
SqlQueryManager thread to kill it. We also explicitly wait for the final
query state after running the query instead of waiting for the SqlQueryManager
thread implicitly.

Fixes #9856.

### CODE REVIEW

**Comment by nezihyigitbasi** [comment]
Failure is unrelated: https://github.com/prestodb/presto/issues/9846

File: presto-tests/src/test/java/com/facebook/presto/tests/TestQueryManager.java [hunk 1]
```diff
@@ -76,21 +76,24 @@ public void testFailQuery()
...
+    @Test(timeOut = 60_000L)
     public void testQueryCpuLimit()
             throws Exception
     {
-        Map<String, String> properties = ImmutableMap.<String, String>builder()
-                .put("query.max-cpu-time", "1ms")
-                .build();
-        try (QueryRunner queryRunner = createQueryRunner(properties)) {
-            queryRunner.execute(TEST_SESSION, "SELECT COUNT(*), repeat(orderstatus, 1000) FROM orders GROUP BY 2");
+        ImmutableMap<String, String> properties = ImmutableMap.of("query.max-cpu-time", "1ms");
```
Comment (findepi) [inline presto-tests/src/test/java/com/facebook/presto/tests/TestQueryManager.java]: nit: just `Map`

**Comment by nezihyigitbasi** [comment]
>  Is it no longer flaky?

I was able to repro the flakiness before this change locally with a small invocation count. After this change I cannot repro it with large invocation counts, so this is much better.
