### PR TITLE
Cast constants in SQL function to proper types

### LINKED ISSUE #13786: SQL function with constants mignt not work
The following SQL function throws exception "Compiler failed":
```
CREATE FUNCTION testing.test.divide(x double)
RETURNS double
DETERMINISTIC
RETURNS NULL ON NULL INPUT
RETURN x / 10
```

The reason is that 10 is a `LongLiteral` and x is a double. Function resolution would pick `divide(double, double)` but we cannot assign `long` to `double`. The expression needs to be coerced properly to `x / (cast 10 as double)`.

### PR DESCRIPTION
**Pull request by rongrong**
Fixes #13786.
```
== RELEASE NOTES ==

General Changes
* Fix SQL function byte code compilation error for functions implemented with constants
```

### CODE REVIEW

File: presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java [hunk 1]
```diff
@@ -1574,6 +1575,44 @@ public static ExpressionAnalysis analyzeExpression(
                 analyzer.getWindowFunctions());
     }
 
+    public static ExpressionAnalysis analyzeSqlFunctionExpression(
```
Comment (caithagoras) [inline presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java]: It looks to me that this function should still belong to `SqlFunctionUtils.java`, despite some changes to this method.

Comment (rongrong) [reply presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java]: All function returning `ExpressionAnalysis` are static functions in `ExpressionAnalyzer`. I think `ExpressionAnalysis` is to wrap the data generated by `ExpressionAnalyzer` so the states are not exposed directly. If that's the case, this is the right place for the function, and other methods returning `ExpressionAnalyzer` should be changed to `private`.

**Comment by caithagoras** [comment]
Travis is not green yet.
