### PR TITLE
Use SerdeProperties when adding Hive partition

### LINKED ISSUE #7301: INSERT creating new Hive table partition uses wrong field delimiters for text format
Hi - When running INSERT INTO a hive table as defined below, it seems Presto is writing valid data files. However running subsequent SELECTs on the table will return all NULL values. When running the SELECT in Hive, the same files are read and displayed correctly.  Is this a known/fixed bug or is there an issue with my table definition? I'm running Presto 0.152.3. 

```
CREATE TABLE `test`(
  `d` timestamp,
  `a` string,
  `b` string,
  `c` string
)
PARTITIONED BY (
  `p` string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'field.delim'='\t',
  'line.delim'='\n',
  'serialization.format'='\t')
STORED AS INPUTFORMAT
  'org.apache.hadoop.mapred.TextInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  's3://bucket'
TBLPROPERTIES (
  'serialization.null.format'=''
)

```

Thanks

### PR DESCRIPTION
**Pull request by ebyhr**
Fix #7301

### CODE REVIEW

File: presto-product-tests/src/main/java/com/facebook/presto/tests/hive/TestInsertIntoHiveTable.java [hunk 1]
```diff
@@ -122,4 +124,34 @@ public void testInsertIntoSelectToHiveTableAllHiveSimpleTypes()
                         true,
                         "kot binarny".getBytes()));
     }
+
+    @Test(groups = {HIVE_CONNECTOR, POST_HIVE_1_0_1})
+    public void testInsertIntoPartitionedWithSerdePropety()
+    {
+        String tableName = "target_partitioned_with_serde_property";
+        query(format("DROP TABLE IF EXISTS %s", tableName));
```
Comment (findepi) [inline presto-product-tests/src/main/java/com/facebook/presto/tests/hive/TestInsertIntoHiveTable.java]: Not needed

File: presto-product-tests/src/main/java/com/facebook/presto/tests/hive/TestInsertIntoHiveTable.java [hunk 2]
```diff
@@ -122,4 +124,34 @@ public void testInsertIntoSelectToHiveTableAllHiveSimpleTypes()
...
+                "PARTITIONED BY (dt string)" +
+                "ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'" +
+                "WITH SERDEPROPERTIES (" +
+                "'field.delim'='\\t'," +
+                "'line.delim'='\\n'," +
+                "'serialization.format'='\\t'" +
+                ")", tableName);
+        onHive().executeQuery(query);
+
+        assertThat(query("SELECT * FROM " + tableName)).hasNoRows();
```
Comment (findepi) [inline presto-product-tests/src/main/java/com/facebook/presto/tests/hive/TestInsertIntoHiveTable.java]: not needed, remove

File: presto-product-tests/src/main/java/com/facebook/presto/tests/hive/TestInsertIntoHiveTable.java [hunk 3]
```diff
@@ -122,4 +124,34 @@ public void testInsertIntoSelectToHiveTableAllHiveSimpleTypes()
...
+        assertThat(query("INSERT INTO " + tableName + " SELECT 1, 'presto', '2018-01-01'")).containsExactly(row(1));
+        assertThat(query("SELECT * FROM " + tableName)).containsOnly(
+                row(
+                        1,
```
Comment (findepi) [inline presto-product-tests/src/main/java/com/facebook/presto/tests/hive/TestInsertIntoHiveTable.java]: wrap into single line, this is quite short.

File: presto-product-tests/src/main/java/com/facebook/presto/tests/hive/TestInsertIntoHiveTable.java [hunk 4]
```diff
@@ -122,4 +124,34 @@ public void testInsertIntoSelectToHiveTableAllHiveSimpleTypes()
...
+                "WITH SERDEPROPERTIES (" +
+                "'field.delim'='\\t'," +
+                "'line.delim'='\\n'," +
+                "'serialization.format'='\\t'" +
+                ")", tableName);
+        onHive().executeQuery(query);
+
+        assertThat(query("SELECT * FROM " + tableName)).hasNoRows();
+        assertThat(query("INSERT INTO " + tableName + " SELECT 1, 'presto', '2018-01-01'")).containsExactly(row(1));
+        assertThat(query("SELECT * FROM " + tableName)).containsOnly(
```
Comment (findepi) [inline presto-product-tests/src/main/java/com/facebook/presto/tests/hive/TestInsertIntoHiveTable.java]: `. containsExactly`

File: presto-product-tests/src/main/java/com/facebook/presto/tests/hive/TestInsertIntoHiveTable.java [hunk 5]
```diff
@@ -122,4 +124,34 @@ public void testInsertIntoSelectToHiveTableAllHiveSimpleTypes()
...
                         "kot binarny".getBytes()));
     }
+
+    @Test(groups = {HIVE_CONNECTOR, POST_HIVE_1_0_1})
+    public void testInsertIntoPartitionedWithSerdePropety()
+    {
+        String tableName = "target_partitioned_with_serde_property";
+        query(format("DROP TABLE IF EXISTS %s", tableName));
+        String query = format(
+                "CREATE TABLE %s(" +
```
Comment (findepi) [inline presto-product-tests/src/main/java/com/facebook/presto/tests/hive/TestInsertIntoHiveTable.java]: Convert this into mutable table `Requirement`, see `com.facebook.presto.tests.convention.TestShowPartitions#getRequirements` for example.

**Comment by ebyhr** [comment]
Thanks for your comments. Updated. 
I expanded internal AllSimpleTypesTables into under the TestInsertIntoHiveTable because new test(testInsertIntoPartitionedWithSerdePropety) isn't all-simple-types.

File: presto-product-tests/src/main/java/com/facebook/presto/tests/hive/TestInsertIntoHiveTable.java [hunk 6]
```diff
@@ -39,23 +40,38 @@
...
+                ")" +
+                "PARTITIONED BY (dt string)" +
+                "ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'" +
+                "WITH SERDEPROPERTIES (" +
+                "'field.delim'='\\t'," +
+                "'line.delim'='\\n'," +
+                "'serialization.format'='\\t'" +
+                ")";
+
+        return HiveTableDefinition.builder(PARTITIONED_TABLE).setCreateTableDDLTemplate(createTableDdl).setNoData().build();
```
Comment (findepi) [inline presto-product-tests/src/main/java/com/facebook/presto/tests/hive/TestInsertIntoHiveTable.java]: insert newline before each `.set..` and `.build`

File: presto-product-tests/src/main/java/com/facebook/presto/tests/hive/TestInsertIntoHiveTable.java [hunk 7]
```diff
@@ -39,23 +40,38 @@
 
 public class TestInsertIntoHiveTable
         extends ProductTest
+        implements RequirementsProvider
 {
     private static final String TABLE_NAME = "target_table";
+    private static final String PARTITIONED_TABLE = "target_partitioned_with_serde_property";
```
Comment (findepi) [inline presto-product-tests/src/main/java/com/facebook/presto/tests/hive/TestInsertIntoHiveTable.java]: `s/PARTITIONED_TABLE/PARTITIONED_TABLE_WITH_SERDE`

**Comment by ebyhr** [comment]
Updated.

File: presto-product-tests/src/main/java/com/facebook/presto/tests/hive/TestInsertIntoHiveTable.java [hunk 8]
```diff
@@ -39,23 +40,41 @@
...
+    }
+
+    private static TableDefinition partitionedTableDefinition()
+    {
+        String createTableDdl = "CREATE TABLE %NAME%(" +
+                "id int," +
+                "name string" +
+                ")" +
+                "PARTITIONED BY (dt string)" +
+                "ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'" +
```
Comment (findepi) [inline presto-product-tests/src/main/java/com/facebook/presto/tests/hive/TestInsertIntoHiveTable.java]: i didn't notice this previously, sorry. Add space (` `) at the end of every line. Otherwise this is `...SerDe'WITH SERDEPROPERTIES ( ...`

Comment (ebyhr) [reply presto-product-tests/src/main/java/com/facebook/presto/tests/hive/TestInsertIntoHiveTable.java]: Oh, sorry. Added spaces.

**Comment by findepi** [comment]
Merged, thanks!
