### PR TITLE
Change expected type to be Object instead of Block in Accumulator

### LINKED ISSUE #8559: approx_percentile() with percentages array fails when used as window function
```
presto> select approx_percentile(42, array[0.5]) over ();

Query 20170720_165839_00007_qt844 failed: com.facebook.presto.spi.function.WindowIndex.getObject(II)Lcom/facebook/presto/spi/block/Block;
java.lang.NoSuchMethodError: com.facebook.presto.spi.function.WindowIndex.getObject(II)Lcom/facebook/presto/spi/block/Block;
	at com.facebook.presto.$gen.Array_bigint_BigintArray_double_ApproxPercentileAccumulator_70.addInput(Unknown Source)
	at com.facebook.presto.operator.window.AggregateWindowFunction.accumulate(AggregateWindowFunction.java:81)
	at com.facebook.presto.operator.window.AggregateWindowFunction.processRow(AggregateWindowFunction.java:71)
	at com.facebook.presto.operator.window.WindowPartition.processNextRow(WindowPartition.java:108)
	at com.facebook.presto.operator.WindowOperator.extractOutput(WindowOperator.java:439)
	at com.facebook.presto.operator.WindowOperator.getOutput(WindowOperator.java:395)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:300)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:538)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:229)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:623)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:478)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

### PR DESCRIPTION
**Pull request by maciejgrzybek**
Fixes #8559.

### CODE REVIEW

File: presto-main/src/main/java/com/facebook/presto/operator/aggregation/AccumulatorCompiler.java [hunk 1]
```diff
@@ -360,7 +360,9 @@ else if (parameterType == Slice.class) {
                         expressions.add(index.invoke("getSlice", Slice.class, getChannel, position));
                     }
                     else if (parameterType == Block.class) {
-                        expressions.add(index.invoke("getObject", Block.class, getChannel, position));
+                        // Even though the method signature requires a Block parameter, we can pass an Object here.
+                        // A runtime check will assert that the Object passed as a parameter is actually of type Block.
+                        expressions.add(index.invoke("getObject", Object.class, getChannel, position));
```
Comment (martint) [inline presto-main/src/main/java/com/facebook/presto/operator/aggregation/AccumulatorCompiler.java]: Can you add an explanation to the commit message describing why this is needed? I.e., what causes the query to fail, etc.

**Comment by maciejgrzybek** [comment]
@martint: Changed the description, how does it look now?
