### PR TITLE
Fix incorrect partitioned join after PredicatePushDown

### LINKED ISSUE #12354: failed: Equi criteria are empty, so INNER join should not have PARTITIONED distribution type
Execute join query in presto-cli across different data sources and see this error.

select * from epet.epet_mall.jz_warehouse_list inner join warehouse.epet_warehouse.jz_kingdee_adjust on epet.epet_mall.jz_warehouse_list.wid=warehouse.epet_warehouse.jz_kingdee_adjust.wid where epet.epet_mall.jz_warehouse_list.wid=1 limit 10;

2019-02-19T16:15:10.779+0800	DEBUG	Query-20190219_081506_00017_m793j-405	com.facebook.presto.execution.QueryStateMachineQuery 20190219_081506_00017_m793j failed
java.lang.IllegalArgumentException: Equi criteria are empty, so INNER join should not have PARTITIONED distribution type
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:437)
	at com.facebook.presto.sql.planner.plan.JoinNode.<init>(JoinNode.java:112)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitJoin(PredicatePushDown.java:529)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitJoin(PredicatePushDown.java:129)
	at com.facebook.presto.sql.planner.plan.JoinNode.accept(JoinNode.java:287)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitPlan(PredicatePushDown.java:166)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitPlan(PredicatePushDown.java:129)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitLimit(PlanVisitor.java:54)
	at com.facebook.presto.sql.planner.plan.LimitNode.accept(LimitNode.java:87)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitExchange(PredicatePushDown.java:189)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitExchange(PredicatePushDown.java:129)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:243)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitPlan(PredicatePushDown.java:166)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitPlan(PredicatePushDown.java:129)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitLimit(PlanVisitor.java:54)
	at com.facebook.presto.sql.planner.plan.LimitNode.accept(LimitNode.java:87)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitPlan(PredicatePushDown.java:166)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitPlan(PredicatePushDown.java:129)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:32)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown.optimize(PredicatePushDown.java:123)
	at com.facebook.presto.sql.planner.optimizations.StatsRecordingPlanOptimizer.optimize(StatsRecordingPlanOptimizer.java:51)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:163)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:152)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:418)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:403)
	at com.facebook.presto.execution.SqlQueryExecution.startExecution(SqlQueryExecution.java:347)
	at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:519)
	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:506)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1347)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.ImmediateFuture.addListener(ImmediateFuture.java:39)
	at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1322)
	at io.airlift.concurrent.MoreFutures.addSuccessCallback(MoreFutures.java:512)
	at io.airlift.concurrent.MoreFutures.addSuccessCallback(MoreFutures.java:519)
	at com.facebook.presto.execution.SqlQueryExecution.waitForMinimumWorkers(SqlQueryExecution.java:332)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:325)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### PR DESCRIPTION
**Pull request by rschlussel**
PredicatePushDown used the original join distribution type when it
creates a new join node.  However, if predicate push down removed all
equijoin criteria after DetermineJoinDistributionType already ran, then
the join type could be invalid leading to an assertion failure in the
join node.

Fixes #12354 

I still need to figure out how to test it because none of our test tables have small int types and i'm not sure how to reproduce it with the existing tables. We either need to
1. create a new test table (and not run for tpch?)
2. find another way to reproduce. 
3. just have a product test

### CODE REVIEW

**Comment by BlueStalker** [comment]
Hi, any people can review this? We have multiple queries hitting this problem

**Comment by rschlussel** [comment]
Sorry for the delay, I didn't get a chance to add a proper test yet, so it wasn't ready for review.  I can do that tomorrow.

**Comment by rschlussel** [comment]
Added a unit test.  this is now ready for review :).

File: presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/OptimizerAssert.java [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+
+import static com.facebook.presto.sql.planner.assertions.PlanAssert.assertPlan;
+import static com.facebook.presto.transaction.TransactionBuilder.transaction;
+import static com.google.common.base.Preconditions.checkArgument;
+import static org.testng.Assert.fail;
+
+public class OptimizerAssert
+{
+    private final Metadata metadata;
+    private TestingStatsCalculator statsCalculator;
```
Comment (arhimondr) [inline presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/OptimizerAssert.java]: nit: final

File: presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/OptimizerAssert.java [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+    private Session session;
```
Comment (arhimondr) [inline presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/OptimizerAssert.java]: nit: final

File: presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/OptimizerAssert.java [hunk 3]
```diff
@@ -0,0 +1,118 @@
...
+    private final PlanOptimizer optimizer;
+
+    private final PlanNodeIdAllocator idAllocator = new PlanNodeIdAllocator();
+
+    private TypeProvider types;
+    private PlanNode plan;
+    private final TransactionManager transactionManager;
+    private final AccessControl accessControl;
```
Comment (arhimondr) [inline presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/OptimizerAssert.java]: nit: Group all the finals (assined in the constructor) together

File: presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/OptimizerAssert.java [hunk 4]
```diff
@@ -0,0 +1,118 @@
...
+
+    public OptimizerAssert(Metadata metadata, StatsCalculator statsCalculator, Session session, PlanOptimizer optimizer, TransactionManager transactionManager, AccessControl accessControl)
+    {
+        this.metadata = metadata;
```
Comment (arhimondr) [inline presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/OptimizerAssert.java]: Check everything with `requireNonNull(...)`

File: presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/OptimizerAssert.java [hunk 5]
```diff
@@ -0,0 +1,118 @@
...
+        this.statsCalculator = new TestingStatsCalculator(statsCalculator);
+        this.session = session;
+        this.optimizer = optimizer;
+        this.transactionManager = transactionManager;
+        this.accessControl = accessControl;
+    }
+
+    public OptimizerAssert on(Function<PlanBuilder, PlanNode> planProvider)
+    {
+        checkArgument(plan == null, "plan has already been set");
```
Comment (arhimondr) [inline presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/OptimizerAssert.java]: checkState

File: presto-main/src/main/java/com/facebook/presto/sql/planner/plan/JoinNode.java [hunk 6]
```diff
@@ -132,6 +132,18 @@ public JoinNode flipChildren()
                 distributionType);
     }
 
+    public static boolean mustPartition(JoinNode.Type type)
```
Comment (arhimondr) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/plan/JoinNode.java]: you can make both `mustPartition` and `mustReplicate` non static, so you don't have to pass the parameters

Comment (rschlussel) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/plan/JoinNode.java]: no because it's used in predicate push down to determine if it *can* create that kind a node with those features.
