### PR TITLE
Fix issue while using iceberg table property format_version

### LINKED ISSUE #19778: [Iceberg] Bug in format_version table property when iceberg.catalog.type is hive
When using iceberg.catalog.type as hive in the iceberg connector, the table property `format_version` is not working as expected.

It is always creating a v1 table even if we set format_version to 2.

```
 create table iceberg_customers_v2 WITH (format_version='2') as select * from tpch.tiny.customer limit 5;
```

Screenshot of the metadata file located at `s3://iceberg/iceberg_customers_v2/metadata/00000-4b45f9be-b4cf-41b1-840d-a956001a6cce.metadata.json`

Screenshot 2023-06-02 at 1 38 16 PM

### PR DESCRIPTION
**Pull request by imjalpreet**
Fixes #19778: The value of the table property format_version was not getting passed on to the iceberg library when iceberg.catalog.type was hive

Test plan - 

The bug mentioned in the above Issue is fixed after this change. Example below:
```
 create table iceberg_customers_v2 WITH (format_version='2') as select * from tpch.tiny.customer limit 5;
```

Screenshot of the metadata file located at s3://iceberg/iceberg_customers_v2/metadata/00000-c691f310-d837-4107-8687-21872f5ae5da.metadata.json

Screenshot 2023-06-02 at 1 48 24 PM

```
== RELEASE NOTES ==

General Changes
* Fix issue while using the iceberg table property ``format_version`` when ``iceberg.catalog.type`` is hive (:issue:`19778`)

```

### CODE REVIEW

**Comment by imjalpreet** [comment]
@nmahadevuni Added the tests, please review.

**Comment by nmahadevuni** [comment]
Looks good.

**Review by nmahadevuni — APPROVED** [review]

**Comment by agrawalreetika** [comment]
LGTM as well 👍🏻

**Review by agrawalreetika — APPROVED** [review]

File: presto-iceberg/src/test/java/com/facebook/presto/iceberg/IcebergDistributedSmokeTestBase.java [hunk 1]
```diff
@@ -484,33 +488,83 @@ private void testCreateTableLike()
...
+
+        String createTableSql = format("" +
+                        "CREATE TABLE %s.%s.%s (\n" +
+                        "   \"order_key\" bigint,\n" +
+                        "   \"ship_priority\" integer,\n" +
+                        "   \"order_status\" varchar\n" +
+                        ")\n" +
+                        "WITH (\n" +
+                        "   format = 'PARQUET',\n" +
+                        "   format_version = '" + formatVersion + "'\n" +
```
Comment (yingsu00) [inline presto-iceberg/src/test/java/com/facebook/presto/iceberg/IcebergDistributedSmokeTestBase.java:550]: I know you're referencing `testCreatePartitionedTableAs`, but the formatting doesn't look good in IntelliJ. This statement uses `format()` but for format_version, it's using `+`. Would you please use a unified way? I think the createTable stmt looks better. Also I don't know why this string uses "\n" while the above one doesn't.

File: presto-iceberg/src/test/java/com/facebook/presto/iceberg/IcebergDistributedSmokeTestBase.java [hunk 2]
```diff
@@ -484,33 +488,83 @@ private void testCreateTableLike()
...
+                "format = 'PARQUET', " +
+                "format_version = '" + formatVersion + "'" +
+                ") " +
+                "AS " +
+                "SELECT orderkey AS order_key, shippriority AS ship_priority, orderstatus AS order_status " +
+                "FROM tpch.tiny.orders";
+
+        assertUpdate(session, createTable, "SELECT count(*) from orders");
+
+        String createTableSql = format("" +
```
Comment (yingsu00) [inline presto-iceberg/src/test/java/com/facebook/presto/iceberg/IcebergDistributedSmokeTestBase.java:542]: Add "@Language("SQL")"?

**Review by yingsu00 — APPROVED** [review]
Looks good, just a few nits. Once fixed I'll merge.

File: presto-iceberg/src/test/java/com/facebook/presto/iceberg/IcebergDistributedSmokeTestBase.java (hunk 2 above)
Comment (imjalpreet) [reply presto-iceberg/src/test/java/com/facebook/presto/iceberg/IcebergDistributedSmokeTestBase.java:542]: This annotation was not added here because code editors like IntelliJ are not able to detect the language in the case of format strings. So, even after using this annotation, it doesn't benefit as language injection doesn't take place.

File: presto-iceberg/src/test/java/com/facebook/presto/iceberg/IcebergDistributedSmokeTestBase.java (hunk 1 above)
Comment (imjalpreet) [reply presto-iceberg/src/test/java/com/facebook/presto/iceberg/IcebergDistributedSmokeTestBase.java:550]: I have made the change and used format for all the strings. 

> Also I don't know why this string uses "\n" while the above one doesn't.

The first string is SQL query to run to create the test table and this string is the output for SHOW CREATE TABLE statement in Presto. This is how presto prints the output so to assert the output with expected output we need to add `/n` in the string.

**Review by imjalpreet — COMMENTED** [review]
Thanks @yingsu00 for the review. I have made the changes and added my comments.
