### PR TITLE
Canonicalize ValuesNode as it may contain correlated symbols

### LINKED ISSUE #11047: NPE for lateral join with unnest
```sql
select * from (values array[1]) t(x), lateral (select * from unnest(x))
```

fails with 

```
java.lang.NullPointerException: type cannot be null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.setExpressionType(ExpressionAnalyzer.java:224)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitSymbolReference(ExpressionAnalyzer.java:378)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitSymbolReference(ExpressionAnalyzer.java:302)
	at com.facebook.presto.sql.tree.SymbolReference.accept(SymbolReference.java:41)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:323)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:268)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpressions(ExpressionAnalyzer.java:1524)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpressionsWithSymbols(ExpressionAnalyzer.java:1477)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.getExpressionTypes(ExpressionAnalyzer.java:1443)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitValues(LocalExecutionPlanner.java:1234)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitValues(LocalExecutionPlanner.java:653)
	at com.facebook.presto.sql.planner.plan.ValuesNode.accept(ValuesNode.java:73)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitExchange(LocalExecutionPlanner.java:2196)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitExchange(LocalExecutionPlanner.java:653)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:196)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitUnnest(LocalExecutionPlanner.java:1256)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitUnnest(LocalExecutionPlanner.java:653)
	at com.facebook.presto.sql.planner.plan.UnnestNode.accept(UnnestNode.java:106)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitExchange(LocalExecutionPlanner.java:2196)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitExchange(LocalExecutionPlanner.java:653)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:196)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.createNestedLoopJoin(LocalExecutionPlanner.java:1653)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitJoin(LocalExecutionPlanner.java:1511)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitJoin(LocalExecutionPlanner.java:653)
	at com.facebook.presto.sql.planner.plan.JoinNode.accept(JoinNode.java:279)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitOutput(LocalExecutionPlanner.java:701)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitOutput(LocalExecutionPlanner.java:653)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:432)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:358)
	at com.facebook.presto.execution.SqlTaskExecutionFactory.create(SqlTaskExecutionFactory.java:85)
	at com.facebook.presto.execution.SqlTask.updateTask(SqlTask.java:351)
	at com.facebook.presto.execution.SqlTaskManager.updateTask(SqlTaskManager.java:354)
	at com.facebook.presto.server.TaskResource.createOrUpdateTask(TaskResource.java:129)
```

### PR DESCRIPTION
**Pull request by kokosing**
Canonicalize ValuesNode as it may contain correlated symbols

Fixes #11047

### CODE REVIEW

File: presto-main/src/test/java/com/facebook/presto/sql/query/TestSubqueries.java [hunk 1]
```diff
@@ -181,6 +181,14 @@ public void testCorrelatedLateralWithGroupBy()
                 UNSUPPORTED_CORRELATED_SUBQUERY_ERROR_MSG);
     }
 
+    @Test
+    public void testLateralWithUnnest()
+    {
+        assertions.assertFails(
+                "SELECT * FROM (VALUES ARRAY[1]) t(x), LATERAL (SELECT * FROM UNNEST(x))",
+                UNSUPPORTED_CORRELATED_SUBQUERY_ERROR_MSG);
```
Comment (findepi) [inline presto-main/src/test/java/com/facebook/presto/sql/query/TestSubqueries.java]: Can there be some _positive_ test for this?

Comment (kokosing) [reply presto-main/src/test/java/com/facebook/presto/sql/query/TestSubqueries.java]: I am not sure... Maybe after changes @sopel39 did recently for correlated subqueries we support some subqueries with correlation in values.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/UnaliasSymbolReferences.java [hunk 2]
```diff
@@ -352,7 +352,15 @@ public PlanNode visitSample(SampleNode node, RewriteContext<Void> context)
         @Override
         public PlanNode visitValues(ValuesNode node, RewriteContext<Void> context)
         {
-            return context.defaultRewrite(node);
+            List<List<Expression>> canonicalizedRows = node.getRows().stream()
+                    .map(this::canonicalize)
+                    .collect(toImmutableList());
+            List<Symbol> canonicalizedOutputSymbols = canonicalizeAndDistinct(node.getOutputSymbols());
```
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/UnaliasSymbolReferences.java]: cardinality of output symbols must match cardinality of each row, see:
```
com.facebook.presto.sql.planner.plan.ValuesNode#ValuesNode
```
so `canonicalize` should be used

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/UnaliasSymbolReferences.java [hunk 3]
```diff
@@ -352,7 +352,15 @@ public PlanNode visitSample(SampleNode node, RewriteContext<Void> context)
...
+            checkState(node.getOutputSymbols().size() == canonicalizedOutputSymbols.size(), "Values output symbols were pruned");
```
Comment (sopel39) [inline presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/UnaliasSymbolReferences.java]: just use `canonicalize` (if it exists) instead of `canonicalizeAndDistinct`

File: presto-main/src/test/java/com/facebook/presto/sql/query/TestSubqueries.java (hunk 1 above)
Comment (sopel39) [reply presto-main/src/test/java/com/facebook/presto/sql/query/TestSubqueries.java]: `ValuesNode` can be converted to `ProjectNode` with correlated symbol assignment. If such symbol is not later used with symbols from another table in subquery, then we could just unwind such query, which would be equivalent to:
```
SELECT * FROM (VALUES ARRAY[1]) t(x) CROSS JOIN UNNEST(x)",
```

Comment (kokosing) [reply presto-main/src/test/java/com/facebook/presto/sql/query/TestSubqueries.java]: The query you posted is typical CROSS JOIN UNNEST which has nothing with correlated subqueries (but the fact it can use symbols from left side of join like LATERAL).

Comment (kokosing) [reply presto-main/src/test/java/com/facebook/presto/sql/query/TestSubqueries.java]: > ValuesNode can be converted to ProjectNode

Unless Values have more rows.

File: presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/UnaliasSymbolReferences.java (hunk 3 above)
Comment (kokosing) [reply presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/UnaliasSymbolReferences.java]: No such method. If I use canonicalize then output symbols could silently have duplicates. Even though I use `canonicalizeAndDistinct` I test if none of the symbols were pruned. 

I would prefer to catch this query with the `checkState` to better understand the nature of the query instead of assuming something blindly here.
